// generate I/O
exports.inputs1 = [
  { addr: 'E4.0', label: '' },
  { addr: 'E4.1', label: '' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: '' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: '' },
  { addr: 'E4.6', label: '' },
  { addr: 'E4.7', label: '' },
  { addr: 'E5.0', label: '' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: '' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: '' },
  { addr: 'E6.4', label: '' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: '' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: '' },
  { addr: 'E8.1', label: '' },
  { addr: 'E8.2', label: '' },
  { addr: 'E8.3', label: '' },
  { addr: 'E8.4', label: '' },
  { addr: 'E8.5', label: '' },
  { addr: 'E8.6', label: '' },
  { addr: 'E8.7', label: '' },
  { addr: 'E9.0', label: '' },
  { addr: 'E9.1', label: '' },
  { addr: 'E9.2', label: '' },
  { addr: 'E9.3', label: '' },
  { addr: 'E9.4', label: '' },
  { addr: 'E9.5', label: '' },
  { addr: 'E9.6', label: '' },
  { addr: 'E9.7', label: '' },
  { addr: 'E10.0', label: '' },
  { addr: 'E10.1', label: '' },
  { addr: 'E10.2', label: '' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: '' },
  { addr: 'E10.5', label: '' },
  { addr: 'E10.6', label: '' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: '' },
  { addr: 'E12.1', label: '' },
  { addr: 'E12.2', label: '' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: '' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' },
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: '' },
  { addr: 'E14.2', label: '' },
  { addr: 'E14.3', label: '' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' },
  { addr: 'E16.0', label: '' },
  { addr: 'E16.1', label: '' },
  { addr: 'E16.2', label: '' },
  { addr: 'E16.3', label: '' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A4.0', label: 'SQA' },
  { addr: 'A4.1', label: 'KBA' },
  { addr: 'A4.2', label: 'SBK1' },
  { addr: 'A4.3', label: 'KXPE' },
  { addr: 'A4.4', label: 'SZE' },
  { addr: 'A4.5', label: 'SOE' },
  { addr: 'A4.6', label: 'LA' },
  { addr: 'A4.7', label: 'LC' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'RBE' },
  { addr: 'A6.0', label: 'DYA' },
  { addr: 'A6.1', label: 'DYB' },
  { addr: 'A6.2', label: 'DYC' },
  { addr: 'A6.3', label: 'DYD' },
  { addr: 'A6.4', label: 'AD1' },
  { addr: 'A6.5', label: 'AD2' },
  { addr: 'A6.6', label: 'AD3' },
  { addr: 'A6.7', label: 'STR' },
  { addr: 'A7.0', label: 'LKE' },
  { addr: 'A7.1', label: 'LEE' },
  { addr: 'A7.2', label: 'LBE' },
  { addr: 'A7.3', label: 'RDY' },
  { addr: 'A7.4', label: 'RST' },
  { addr: 'A7.5', label: 'SBK2' },
  { addr: 'A7.6', label: 'TIV' },
  { addr: 'A7.7', label: 'KEM' }
]
exports.outputs2 = [
  { addr: 'A12.0', label: 'LKA' },
  { addr: 'A12.1', label: 'LEA' },
  { addr: 'A12.2', label: 'LBA' },
  { addr: 'A12.3', label: 'RDY' },
  { addr: 'A12.4', label: 'RST' },
  { addr: 'A12.5', label: 'SZA' },
  { addr: 'A12.6', label: 'SOA' },
  { addr: 'A12.7', label: 'SPA' },
  { addr: 'A13.0', label: 'SPE' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: 'RDY' },
  { addr: 'A13.4', label: 'RST' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: 'SMA1' },
  { addr: 'A14.1', label: 'SMB1' },
  { addr: 'A14.2', label: 'SMA2' },
  { addr: 'A14.3', label: 'SMB2' },
  { addr: 'A14.4', label: '' },
  { addr: 'A14.5', label: 'TCR1' },
  { addr: 'A14.6', label: 'LA' },
  { addr: 'A14.7', label: 'LC' },
  { addr: 'A15.0', label: 'T10' },
  { addr: 'A15.1', label: 'T2' },
  { addr: 'A15.2', label: 'TRA' },
  { addr: 'A15.3', label: 'TRB' },
  { addr: 'A15.4', label: 'TCR' },
  { addr: 'A15.5', label: 'SCA' },
  { addr: 'A15.6', label: 'SCB' },
  { addr: 'A15.7', label: '' },
  { addr: 'A16.0', label: 'KCS' },
  { addr: 'A16.1', label: 'KCV' },
  { addr: 'A16.2', label: 'KCH' },
  { addr: 'A16.3', label: '' },
  { addr: 'A16.4', label: '' },
  { addr: 'A16.5', label: '' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' }
]
exports.ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'EU' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
