export const inputs1 = [
  { addr: 'E0.0', label: 'SA1' },
  { addr: 'E0.1', label: 'SA2' },
  { addr: 'E0.2', label: 'SA3' },
  { addr: 'E0.3', label: 'SA4' },
  { addr: 'E0.4', label: 'FE' },
  { addr: 'E0.5', label: 'RSI' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'S2' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: 'UC' },
  { addr: 'E101.1', label: 'RSI' },
  { addr: 'E101.2', label: 'FE1' },
  { addr: 'E101.3', label: 'APB' },
  { addr: 'E101.4', label: 'AP' },
  { addr: 'E101.5', label: 'RTD' },
  { addr: 'E101.6', label: 'ASR' },
  { addr: 'E101.7', label: 'AMC' },
  { addr: 'E102.0', label: 'IV3' },
  { addr: 'E102.1', label: 'IV4' },
  { addr: 'E102.2', label: 'SRL' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: 'ECA' },
  { addr: 'E103.1', label: 'ECB' },
  { addr: 'E103.2', label: 'EZE' },
  { addr: 'E103.3', label: 'EOE' },
  { addr: 'E103.4', label: 'EBZE' },
  { addr: 'E103.5', label: 'EBOE' },
  { addr: 'E103.6', label: 'FREL' },
  { addr: 'E103.7', label: 'FRER' },
  { addr: 'E104.0', label: 'FBE' },
  { addr: 'E104.1', label: 'FBBE' },
  { addr: 'E104.2', label: 'FPE' },
  { addr: 'E104.3', label: 'FDR1' },
  { addr: 'E104.4', label: 'FDL1' },
  { addr: 'E104.5', label: 'FDR2' },
  { addr: 'E104.6', label: 'FDL2' },
  { addr: 'E104.7', label: 'FTA1' },
  { addr: 'E105.0', label: 'FTA2' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: 'FLP' },
  { addr: 'E105.3', label: 'FLA' },
  { addr: 'E105.4', label: 'EXDE' },
  { addr: 'E105.5', label: 'EXHE' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZA' },
  { addr: 'E106.1', label: 'EOA' },
  { addr: 'E106.2', label: 'EBZA' },
  { addr: 'E106.3', label: 'EBOA' },
  { addr: 'E106.4', label: 'FBA' },
  { addr: 'E106.5', label: 'FBBA' },
  { addr: 'E106.6', label: 'FPA' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'EXDA' },
  { addr: 'E107.1', label: 'EXHA' },
  { addr: 'E107.2', label: 'DB32' },
  { addr: 'E107.3', label: 'DBHZ' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: 'RSI' },
  { addr: 'E110.1', label: 'FE1' },
  { addr: 'E110.2', label: 'IV1' },
  { addr: 'E110.3', label: 'RTA' },
  { addr: 'E110.4', label: 'ASBK' },
  { addr: 'E110.5', label: 'FSBK' },
  { addr: 'E110.6', label: 'SA' },
  { addr: 'E110.7', label: 'UC' },
  { addr: 'E111.0', label: 'A' },
  { addr: 'E111.1', label: 'B' },
  { addr: 'E111.2', label: 'C' },
  { addr: 'E111.3', label: 'D' },
  { addr: 'E111.4', label: 'OK' },
  { addr: 'E111.5', label: 'S2' },
  { addr: 'E111.6', label: 'S2' },
  { addr: 'E111.7', label: 'S2' },
  { addr: 'E112.0', label: 'ASH' },
  { addr: 'E112.1', label: 'AMM' },
  { addr: 'E112.2', label: 'FE1' },
  { addr: 'E112.3', label: '' },
  { addr: 'E112.4', label: '' },
  { addr: 'E112.5', label: '' },
  { addr: 'E112.6', label: '' },
  { addr: 'E112.7', label: '' },
  { addr: 'E113.0', label: 'EOM' },
  { addr: 'E113.1', label: 'EZM' },
  { addr: 'E113.2', label: 'EMC' },
  { addr: 'E113.3', label: 'EXV' },
  { addr: 'E113.4', label: '' },
  { addr: 'E113.5', label: '' },
  { addr: 'E113.6', label: '' },
  { addr: 'E113.7', label: '' },
  { addr: 'E114.0', label: 'A' },
  { addr: 'E114.1', label: 'B' },
  { addr: 'E114.2', label: 'C' },
  { addr: 'E114.3', label: 'D' },
  { addr: 'E114.4', label: 'OK' },
  { addr: 'E114.5', label: 'S2' },
  { addr: 'E114.6', label: 'S2' },
  { addr: 'E114.7', label: 'S2' },
  { addr: 'E115.0', label: 'UC' },
  { addr: 'E115.1', label: 'FE2' },
  { addr: 'E115.2', label: 'IV2' },
  { addr: 'E115.3', label: 'RSI' },
  { addr: 'E115.4', label: 'AH' },
  { addr: 'E115.5', label: 'MTC' },
  { addr: 'E115.6', label: 'ATF' },
  { addr: 'E115.7', label: 'SRL' },
  { addr: 'E116.0', label: 'RMV' },
  { addr: 'E116.1', label: 'RMH' },
  { addr: 'E116.2', label: 'RES' },
  { addr: 'E116.3', label: 'REH' },
  { addr: 'E116.4', label: 'RCV' },
  { addr: 'E116.5', label: 'REAV' },
  { addr: 'E116.6', label: 'REAH' },
  { addr: 'E116.7', label: 'RCH' },
  { addr: 'E117.0', label: 'DB32' },
  { addr: 'E117.1', label: 'DBHZ' },
  { addr: 'E117.2', label: 'EM' },
  { addr: 'E117.3', label: 'FTXV' },
  { addr: 'E117.4', label: 'FTXH' },
  { addr: 'E117.5', label: 'FTAC' },
  { addr: 'E117.6', label: '' },
  { addr: 'E117.7', label: '' }
]
export const inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'S2' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: '' },
  { addr: 'E201.0', label: 'UC' },
  { addr: 'E201.1', label: 'RSI' },
  { addr: 'E201.2', label: 'FE1' },
  { addr: 'E201.3', label: 'APB' },
  { addr: 'E201.4', label: 'AP' },
  { addr: 'E201.5', label: 'RTD' },
  { addr: 'E201.6', label: 'ASR' },
  { addr: 'E201.7', label: 'AMC' },
  { addr: 'E202.0', label: 'IV3' },
  { addr: 'E202.1', label: 'IV4' },
  { addr: 'E202.2', label: 'SRL' },
  { addr: 'E202.3', label: '' },
  { addr: 'E202.4', label: '' },
  { addr: 'E202.5', label: '' },
  { addr: 'E202.6', label: '' },
  { addr: 'E202.7', label: '' },
  { addr: 'E203.0', label: 'ECA' },
  { addr: 'E203.1', label: 'ECB' },
  { addr: 'E203.2', label: 'EZE' },
  { addr: 'E203.3', label: 'EOE' },
  { addr: 'E203.4', label: 'EBZE' },
  { addr: 'E203.5', label: 'EBOE' },
  { addr: 'E203.6', label: 'FREL' },
  { addr: 'E203.7', label: 'FRER' },
  { addr: 'E204.0', label: 'FBE' },
  { addr: 'E204.1', label: 'FBBE' },
  { addr: 'E204.2', label: 'FPE' },
  { addr: 'E204.3', label: 'FDR1' },
  { addr: 'E204.4', label: 'FDL1' },
  { addr: 'E204.5', label: 'FDR2' },
  { addr: 'E204.6', label: 'FDL2' },
  { addr: 'E204.7', label: 'FTA1' },
  { addr: 'E205.0', label: 'FTA2' },
  { addr: 'E205.1', label: '' },
  { addr: 'E205.2', label: 'FLP' },
  { addr: 'E205.3', label: 'FLA' },
  { addr: 'E205.4', label: 'EXDE' },
  { addr: 'E205.5', label: 'EXHE' },
  { addr: 'E205.6', label: '' },
  { addr: 'E205.7', label: '' },
  { addr: 'E206.0', label: 'EZA' },
  { addr: 'E206.1', label: 'EOA' },
  { addr: 'E206.2', label: 'EBZA' },
  { addr: 'E206.3', label: 'EBOA' },
  { addr: 'E206.4', label: 'FBA' },
  { addr: 'E206.5', label: 'FBBA' },
  { addr: 'E206.6', label: 'FPA' },
  { addr: 'E206.7', label: '' },
  { addr: 'E207.0', label: 'EXDA' },
  { addr: 'E207.1', label: 'EXHA' },
  { addr: 'E207.2', label: 'DB32' },
  { addr: 'E207.3', label: 'DBHZ' },
  { addr: 'E207.4', label: '' },
  { addr: 'E207.5', label: '' },
  { addr: 'E207.6', label: '' },
  { addr: 'E207.7', label: '' }
]
export const inputs5 = [
  { addr: 'E210.0', label: 'RSI' },
  { addr: 'E210.1', label: 'FE1' },
  { addr: 'E210.2', label: 'IV1' },
  { addr: 'E210.3', label: 'RTA' },
  { addr: 'E210.4', label: 'ASBK' },
  { addr: 'E210.5', label: 'FSBK' },
  { addr: 'E210.6', label: 'SA' },
  { addr: 'E210.7', label: 'UC' },
  { addr: 'E211.0', label: 'A' },
  { addr: 'E211.1', label: 'B' },
  { addr: 'E211.2', label: 'C' },
  { addr: 'E211.3', label: 'D' },
  { addr: 'E211.4', label: 'OK' },
  { addr: 'E211.5', label: 'S2' },
  { addr: 'E211.6', label: 'S2' },
  { addr: 'E211.7', label: 'S2' },
  { addr: 'E212.0', label: 'ASH' },
  { addr: 'E212.1', label: 'AMM' },
  { addr: 'E212.2', label: 'FE1' },
  { addr: 'E212.3', label: '' },
  { addr: 'E212.4', label: '' },
  { addr: 'E212.5', label: '' },
  { addr: 'E212.6', label: '' },
  { addr: 'E212.7', label: '' },
  { addr: 'E213.0', label: 'EOM' },
  { addr: 'E213.1', label: 'EZM' },
  { addr: 'E213.2', label: 'EMC' },
  { addr: 'E213.3', label: 'EXV' },
  { addr: 'E213.4', label: '' },
  { addr: 'E213.5', label: '' },
  { addr: 'E213.6', label: '' },
  { addr: 'E213.7', label: '' },
  { addr: 'E214.0', label: 'A' },
  { addr: 'E214.1', label: 'B' },
  { addr: 'E214.2', label: 'C' },
  { addr: 'E214.3', label: 'D' },
  { addr: 'E214.4', label: 'OK' },
  { addr: 'E214.5', label: 'S2' },
  { addr: 'E214.6', label: 'S2' },
  { addr: 'E214.7', label: 'S2' },
  { addr: 'E215.0', label: 'UC' },
  { addr: 'E215.1', label: 'FE2' },
  { addr: 'E215.2', label: 'IV2' },
  { addr: 'E215.3', label: 'RSI' },
  { addr: 'E215.4', label: 'AH' },
  { addr: 'E215.5', label: 'MTC' },
  { addr: 'E215.6', label: 'ATF' },
  { addr: 'E215.7', label: 'SRL' },
  { addr: 'E216.0', label: 'RMV' },
  { addr: 'E216.1', label: 'RMH' },
  { addr: 'E216.2', label: 'RES' },
  { addr: 'E216.3', label: 'REH' },
  { addr: 'E216.4', label: 'RCV' },
  { addr: 'E216.5', label: 'REAV' },
  { addr: 'E216.6', label: 'REAH' },
  { addr: 'E216.7', label: 'RCH' },
  { addr: 'E217.0', label: 'DB32' },
  { addr: 'E217.1', label: 'DBHZ' },
  { addr: 'E217.2', label: 'EM' },
  { addr: 'E217.3', label: 'FTXV' },
  { addr: 'E217.4', label: 'FTXH' },
  { addr: 'E217.5', label: 'FTAC' },
  { addr: 'E217.6', label: '' },
  { addr: 'E217.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LS1' },
  { addr: 'A0.1', label: 'LS2' },
  { addr: 'A0.2', label: 'LS3' },
  { addr: 'A0.3', label: 'LS4' },
  { addr: 'A0.4', label: 'LA' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'LC' },
  { addr: 'A101.1', label: 'LA' },
  { addr: 'A101.2', label: 'KBA3' },
  { addr: 'A101.3', label: 'KBA4' },
  { addr: 'A101.4', label: 'TRBE' },
  { addr: 'A101.5', label: 'TRBA' },
  { addr: 'A101.6', label: 'SCA' },
  { addr: 'A101.7', label: 'SCB' },
  { addr: 'A102.0', label: 'SPE' },
  { addr: 'A102.1', label: 'SPBE' },
  { addr: 'A102.2', label: 'SPA' },
  { addr: 'A102.3', label: 'SPBA' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'SOE' },
  { addr: 'A103.1', label: 'SZE' },
  { addr: 'A103.2', label: 'SOA' },
  { addr: 'A103.3', label: 'SZA' },
  { addr: 'A103.4', label: 'SBOE' },
  { addr: 'A103.5', label: 'SBZE' },
  { addr: 'A103.6', label: 'SBOA' },
  { addr: 'A103.7', label: 'SBZA' },
  { addr: 'A104.0', label: '' },
  { addr: 'A104.1', label: 'RFE' },
  { addr: 'A104.2', label: 'RFA' },
  { addr: 'A104.3', label: 'L1' },
  { addr: 'A104.4', label: 'L2' },
  { addr: 'A104.5', label: 'L3' },
  { addr: 'A104.6', label: 'L4' },
  { addr: 'A104.7', label: 'L5' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
export const outputs3 = [
  { addr: 'A110.0', label: 'LC' },
  { addr: 'A110.1', label: 'LA' },
  { addr: 'A110.2', label: 'KBA1' },
  { addr: 'A110.3', label: 'SBK1' },
  { addr: 'A110.4', label: 'SBK2' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: 'DYA' },
  { addr: 'A111.1', label: 'DYB' },
  { addr: 'A111.2', label: 'DYC' },
  { addr: 'A111.3', label: 'DYD' },
  { addr: 'A111.4', label: 'AD1' },
  { addr: 'A111.5', label: 'AD2' },
  { addr: 'A111.6', label: 'AD3' },
  { addr: 'A111.7', label: 'STR' },
  { addr: 'A112.0', label: 'SMA' },
  { addr: 'A112.1', label: 'SMB' },
  { addr: 'A112.2', label: 'LA' },
  { addr: 'A112.3', label: '' },
  { addr: 'A112.4', label: '' },
  { addr: 'A112.5', label: '' },
  { addr: 'A112.6', label: '' },
  { addr: 'A112.7', label: '' },
  { addr: 'A113.0', label: '' },
  { addr: 'A113.1', label: '' },
  { addr: 'A113.2', label: '' },
  { addr: 'A113.3', label: '' },
  { addr: 'A113.4', label: '' },
  { addr: 'A113.5', label: '' },
  { addr: 'A113.6', label: '' },
  { addr: 'A113.7', label: '' },
  { addr: 'A114.0', label: 'DYA' },
  { addr: 'A114.1', label: 'DYB' },
  { addr: 'A114.2', label: 'DYC' },
  { addr: 'A114.3', label: 'DYD' },
  { addr: 'A114.4', label: 'AD1' },
  { addr: 'A114.5', label: 'AD2' },
  { addr: 'A114.6', label: 'AD3' },
  { addr: 'A114.7', label: 'STR' },
  { addr: 'A115.0', label: 'LC' },
  { addr: 'A115.1', label: 'LA' },
  { addr: 'A115.2', label: 'KBA2' },
  { addr: 'A115.3', label: 'T101' },
  { addr: 'A115.4', label: 'T102' },
  { addr: 'A115.5', label: 'T2' },
  { addr: 'A115.6', label: 'TRA' },
  { addr: 'A115.7', label: 'TRB' },
  { addr: 'A116.0', label: 'T10F' },
  { addr: 'A116.1', label: 'KCS' },
  { addr: 'A116.2', label: 'KCV' },
  { addr: 'A116.3', label: 'KCH' },
  { addr: 'A116.4', label: '' },
  { addr: 'A116.5', label: '' },
  { addr: 'A116.6', label: '' },
  { addr: 'A116.7', label: '' },
  { addr: 'A117.0', label: '' },
  { addr: 'A117.1', label: '' },
  { addr: 'A117.2', label: '' },
  { addr: 'A117.3', label: '' },
  { addr: 'A117.4', label: '' },
  { addr: 'A117.5', label: '' },
  { addr: 'A117.6', label: '' },
  { addr: 'A117.7', label: '' }
]
export const outputs4 = [
  { addr: 'A200.0', label: 'DYA' },
  { addr: 'A200.1', label: 'DYB' },
  { addr: 'A200.2', label: 'DYC' },
  { addr: 'A200.3', label: 'DYD' },
  { addr: 'A200.4', label: 'AD1' },
  { addr: 'A200.5', label: 'AD2' },
  { addr: 'A200.6', label: 'AD3' },
  { addr: 'A200.7', label: 'STR' },
  { addr: 'A201.0', label: 'LC' },
  { addr: 'A201.1', label: 'LA' },
  { addr: 'A201.2', label: 'KBA3' },
  { addr: 'A201.3', label: 'KBA4' },
  { addr: 'A201.4', label: 'TRBE' },
  { addr: 'A201.5', label: 'TRBA' },
  { addr: 'A201.6', label: 'SCA' },
  { addr: 'A201.7', label: 'SCB' },
  { addr: 'A202.0', label: 'SPE' },
  { addr: 'A202.1', label: 'SPBE' },
  { addr: 'A202.2', label: 'SPA' },
  { addr: 'A202.3', label: 'SPBA' },
  { addr: 'A202.4', label: '' },
  { addr: 'A202.5', label: '' },
  { addr: 'A202.6', label: '' },
  { addr: 'A202.7', label: '' },
  { addr: 'A203.0', label: 'SOE' },
  { addr: 'A203.1', label: 'SZE' },
  { addr: 'A203.2', label: 'SOA' },
  { addr: 'A203.3', label: 'SZA' },
  { addr: 'A203.4', label: 'SBOE' },
  { addr: 'A203.5', label: 'SBZE' },
  { addr: 'A203.6', label: 'SBOA' },
  { addr: 'A203.7', label: 'SBZA' },
  { addr: 'A204.0', label: '' },
  { addr: 'A204.1', label: 'RFE' },
  { addr: 'A204.2', label: 'RFA' },
  { addr: 'A204.3', label: 'L1' },
  { addr: 'A204.4', label: 'L2' },
  { addr: 'A204.5', label: 'L3' },
  { addr: 'A204.6', label: 'L4' },
  { addr: 'A204.7', label: 'L5' },
  { addr: 'A205.0', label: '' },
  { addr: 'A205.1', label: '' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' }
]
export const outputs5 = [
  { addr: 'A210.0', label: 'LC' },
  { addr: 'A210.1', label: 'LA' },
  { addr: 'A210.2', label: 'KBA1' },
  { addr: 'A210.3', label: 'SBK1' },
  { addr: 'A210.4', label: 'SBK2' },
  { addr: 'A210.5', label: '' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' },
  { addr: 'A211.0', label: 'DYA' },
  { addr: 'A211.1', label: 'DYB' },
  { addr: 'A211.2', label: 'DYC' },
  { addr: 'A211.3', label: 'DYD' },
  { addr: 'A211.4', label: 'AD1' },
  { addr: 'A211.5', label: 'AD2' },
  { addr: 'A211.6', label: 'AD3' },
  { addr: 'A211.7', label: 'STR' },
  { addr: 'A212.0', label: 'SMA' },
  { addr: 'A212.1', label: 'SMB' },
  { addr: 'A212.2', label: 'LA' },
  { addr: 'A212.3', label: '' },
  { addr: 'A212.4', label: '' },
  { addr: 'A212.5', label: '' },
  { addr: 'A212.6', label: '' },
  { addr: 'A212.7', label: '' },
  { addr: 'A213.0', label: '' },
  { addr: 'A213.1', label: '' },
  { addr: 'A213.2', label: '' },
  { addr: 'A213.3', label: '' },
  { addr: 'A213.4', label: '' },
  { addr: 'A213.5', label: '' },
  { addr: 'A213.6', label: '' },
  { addr: 'A213.7', label: '' },
  { addr: 'A214.0', label: 'DYA' },
  { addr: 'A214.1', label: 'DYB' },
  { addr: 'A214.2', label: 'DYC' },
  { addr: 'A214.3', label: 'DYD' },
  { addr: 'A214.4', label: 'AD1' },
  { addr: 'A214.5', label: 'AD2' },
  { addr: 'A214.6', label: 'AD3' },
  { addr: 'A214.7', label: 'STR' },
  { addr: 'A215.0', label: 'LC' },
  { addr: 'A215.1', label: 'LA' },
  { addr: 'A215.2', label: 'KBA2' },
  { addr: 'A215.3', label: 'T101' },
  { addr: 'A215.4', label: 'T102' },
  { addr: 'A215.5', label: 'T2' },
  { addr: 'A215.6', label: 'TRA' },
  { addr: 'A215.7', label: 'TRB' },
  { addr: 'A216.0', label: 'T10F' },
  { addr: 'A216.1', label: 'KCS' },
  { addr: 'A216.2', label: 'KCV' },
  { addr: 'A216.3', label: 'KCH' },
  { addr: 'A216.4', label: '' },
  { addr: 'A216.5', label: '' },
  { addr: 'A216.6', label: '' },
  { addr: 'A216.7', label: '' },
  { addr: 'A217.0', label: '' },
  { addr: 'A217.1', label: '' },
  { addr: 'A217.2', label: '' },
  { addr: 'A217.3', label: '' },
  { addr: 'A217.4', label: '' },
  { addr: 'A217.5', label: '' },
  { addr: 'A217.6', label: '' },
  { addr: 'A217.7', label: '' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-h-to', query: {} },
  { id: 24, key: 'al-lh', query: {} },
  { id: 25, key: 'al-lh-diff', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-pn', query: { name: 'SH1' } },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: '', query: {} },
  { id: 51, key: 'al-iv', query: { nr: 1 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'ASBK' } },
  { id: 54, key: 'al-th', query: { name: 'ASH' } },
  { id: 55, key: 'al-th', query: { name: 'AMM' } },
  { id: 56, key: 'al-th', query: { name: 'FE' } },
  { id: 57, key: 'al-th', query: { name: 'FE' } },
  { id: 58, key: 'al-iv', query: { nr: 2 } },
  { id: 59, key: 'al-th', query: { name: 'AH' } },
  { id: 60, key: 'al-th', query: { name: 'MTC' } },
  { id: 61, key: 'al-th', query: { name: 'ATF' } },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-flap-to', query: {} },
  { id: 82, key: 'al-flap-fc', query: {} },
  { id: 83, key: 'al-spe-to', query: {} },
  { id: 84, key: 'al-spe-fc', query: {} },
  { id: 85, key: 'al-spbe-to', query: {} },
  { id: 86, key: 'al-spbe-fc', query: {} },
  { id: 87, key: 'al-r-to', query: {} },
  { id: 88, key: 'al-enr', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-pn', query: { name: 'SH2' } },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE' } },
  { id: 114, key: 'al-th', query: { name: 'APB' } },
  { id: 115, key: 'al-th', query: { name: 'AP' } },
  { id: 116, key: 'al-th', query: { name: 'RTD' } },
  { id: 117, key: 'al-th', query: { name: 'ASR' } },
  { id: 118, key: 'al-th', query: { name: 'AMC' } },
  { id: 119, key: 'al-iv', query: { nr: 2 } },
  { id: 120, key: 'al-iv', query: { nr: 3 } },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} },
  { id: 129, key: '', query: {} },
  { id: 130, key: '', query: {} },
  { id: 131, key: '', query: {} },
  { id: 132, key: '', query: {} },
  { id: 133, key: '', query: {} },
  { id: 134, key: '', query: {} },
  { id: 135, key: '', query: {} },
  { id: 136, key: '', query: {} },
  { id: 137, key: '', query: {} },
  { id: 138, key: '', query: {} },
  { id: 139, key: '', query: {} },
  { id: 140, key: '', query: {} },
  { id: 141, key: '', query: {} },
  { id: 142, key: '', query: {} },
  { id: 143, key: '', query: {} },
  { id: 144, key: '', query: {} },
  { id: 145, key: '', query: {} },
  { id: 146, key: '', query: {} },
  { id: 147, key: 'al-spa-to', query: {} },
  { id: 148, key: 'al-spa-fc', query: {} },
  { id: 149, key: 'al-spba-to', query: {} },
  { id: 150, key: 'al-spba-fc', query: {} },
  { id: 151, key: 'al-r-to', query: {} },
  { id: 152, key: 'al-enr', query: {} },
  { id: 153, key: '', query: {} },
  { id: 154, key: '', query: {} },
  { id: 155, key: '', query: {} },
  { id: 156, key: '', query: {} },
  { id: 157, key: '', query: {} },
  { id: 158, key: '', query: {} },
  { id: 159, key: '', query: {} },
  { id: 160, key: '', query: {} },
  { id: 161, key: '', query: {} },
  { id: 162, key: '', query: {} },
  { id: 163, key: '', query: {} },
  { id: 164, key: '', query: {} },
  { id: 165, key: '', query: {} },
  { id: 166, key: '', query: {} },
  { id: 167, key: '', query: {} },
  { id: 168, key: '', query: {} },
  { id: 169, key: '', query: {} },
  { id: 170, key: '', query: {} },
  { id: 171, key: '', query: {} },
  { id: 172, key: '', query: {} },
  { id: 173, key: '', query: {} },
  { id: 174, key: '', query: {} },
  { id: 175, key: '', query: {} },
  { id: 176, key: '', query: {} },
  { id: 177, key: 'al-th', query: { name: 'FE' } },
  { id: 178, key: 'al-th', query: { name: 'APB' } },
  { id: 179, key: 'al-th', query: { name: 'AP' } },
  { id: 180, key: 'al-th', query: { name: 'RTD' } },
  { id: 181, key: 'al-th', query: { name: 'ASR' } },
  { id: 182, key: 'al-th', query: { name: 'AMC' } },
  { id: 183, key: 'al-iv', query: { nr: 2 } },
  { id: 184, key: 'al-iv', query: { nr: 3 } },
  { id: 185, key: '', query: {} },
  { id: 186, key: '', query: {} },
  { id: 187, key: '', query: {} },
  { id: 188, key: '', query: {} },
  { id: 189, key: '', query: {} },
  { id: 190, key: '', query: {} },
  { id: 191, key: '', query: {} },
  { id: 192, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'E1' },
  { id: 4, key: 'E2' },
  { id: 5, key: 'U1' },
  { id: 6, key: 'U2' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
