export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'OK' },
  { addr: 'E1.5', label: 'S2' },
  { addr: 'E1.6', label: 'S2' },
  { addr: 'E1.7', label: 'S2' },
  { addr: 'E2.0', label: 'UC1' },
  { addr: 'E2.1', label: 'MSK1' },
  { addr: 'E2.2', label: 'DB32' },
  { addr: 'E2.3', label: 'DBHZ' },
  { addr: 'E2.4', label: 'UC2' },
  { addr: 'E2.5', label: 'MSK2' },
  { addr: 'E2.6', label: 'DB32' },
  { addr: 'E2.7', label: 'DBHZ' },
  { addr: 'E3.0', label: 'K12' },
  { addr: 'E3.1', label: 'SA' },
  { addr: 'E3.2', label: 'RTA1' },
  { addr: 'E3.3', label: 'RTA2' },
  { addr: 'E3.4', label: 'RTA3' },
  { addr: 'E3.5', label: 'ASBK1' },
  { addr: 'E3.6', label: 'ASBK2' },
  { addr: 'E3.7', label: 'ASBK3' },
  { addr: 'E4.0', label: 'FSBK1' },
  { addr: 'E4.1', label: 'FSBK2' },
  { addr: 'E4.2', label: 'FSBK3' },
  { addr: 'E4.3', label: 'TJ1' },
  { addr: 'E4.4', label: 'TJ2' },
  { addr: 'E4.5', label: 'TJ3' },
  { addr: 'E4.6', label: 'AMM1' },
  { addr: 'E4.7', label: 'AMM2' },
  { addr: 'E5.0', label: 'AMC' },
  { addr: 'E5.1', label: 'APE' },
  { addr: 'E5.2', label: 'APA' },
  { addr: 'E5.3', label: 'FE1' },
  { addr: 'E5.4', label: 'IV1' },
  { addr: 'E5.5', label: 'IV2' },
  { addr: 'E5.6', label: 'IV3' },
  { addr: 'E5.7', label: 'E5.7' },
  { addr: 'E6.0', label: 'EOM1' },
  { addr: 'E6.1', label: 'EZM1' },
  { addr: 'E6.2', label: 'ECA' },
  { addr: 'E6.3', label: 'ECB' },
  { addr: 'E6.4', label: 'EXPV1' },
  { addr: 'E6.5', label: 'EFB1' },
  { addr: 'E6.6', label: 'FTXV1' },
  { addr: 'E6.7', label: 'FTXH1' },
  { addr: 'E7.0', label: 'FRER' },
  { addr: 'E7.1', label: 'FREL' },
  { addr: 'E7.2', label: 'FTC1' },
  { addr: 'E7.3', label: 'FBE' },
  { addr: 'E7.4', label: 'FPE' },
  { addr: 'E7.5', label: 'FDR1' },
  { addr: 'E7.6', label: 'FDL1' },
  { addr: 'E7.7', label: 'FDR2' },
  { addr: 'E8.0', label: 'FDL2' },
  { addr: 'E8.1', label: 'FLA' },
  { addr: 'E8.2', label: 'FLP' },
  { addr: 'E8.3', label: 'FTA1' },
  { addr: 'E8.4', label: 'EOE' },
  { addr: 'E8.5', label: 'EZE' },
  { addr: 'E8.6', label: '' },
  { addr: 'E8.7', label: 'EOM2' },
  { addr: 'E9.0', label: 'EZM2' },
  { addr: 'E9.1', label: 'EXPV2' },
  { addr: 'E9.2', label: 'EFB2' },
  { addr: 'E9.3', label: 'FTC2' },
  { addr: 'E9.4', label: 'FBA' },
  { addr: 'E9.5', label: 'EOA' },
  { addr: 'E9.6', label: 'EZA' },
  { addr: 'E9.7', label: 'FPA' },
  { addr: 'E10.0', label: 'ET1' },
  { addr: 'E10.1', label: 'ET2' },
  { addr: 'E10.2', label: 'BBA' },
  { addr: 'E10.3', label: 'BBE' },
  { addr: 'E10.4', label: 'BBLE' },
  { addr: 'E10.5', label: '' },
  { addr: 'E10.6', label: 'FTXV2' },
  { addr: 'E10.7', label: 'FTXH2' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: 'ACR1' },
  { addr: 'E12.1', label: 'AMM3' },
  { addr: 'E12.2', label: 'ASH' },
  { addr: 'E12.3', label: 'FTCR1' },
  { addr: 'E12.4', label: 'K12' },
  { addr: 'E12.5', label: 'EMC' },
  { addr: 'E12.6', label: 'EOM3' },
  { addr: 'E12.7', label: 'EZM3' },
  { addr: 'E13.0', label: 'FE3' },
  { addr: 'E13.1', label: 'EXV' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' },
  { addr: 'E14.0', label: 'A' },
  { addr: 'E14.1', label: 'B' },
  { addr: 'E14.2', label: 'C' },
  { addr: 'E14.3', label: 'D' },
  { addr: 'E14.4', label: 'OK' },
  { addr: 'E14.5', label: 'S2' },
  { addr: 'E14.6', label: 'S2' },
  { addr: 'E14.7', label: 'S2' },
  { addr: 'E15.0', label: 'UC' },
  { addr: 'E15.1', label: 'MSK3' },
  { addr: 'E15.2', label: 'EM' },
  { addr: 'E15.3', label: 'FTXV' },
  { addr: 'E15.4', label: 'FTXH' },
  { addr: 'E15.5', label: 'FTMV' },
  { addr: 'E15.6', label: 'FTMH' },
  { addr: 'E15.7', label: 'ASBK4' },
  { addr: 'E16.0', label: 'MTC' },
  { addr: 'E16.1', label: 'ACR2' },
  { addr: 'E16.2', label: 'FTCR2' },
  { addr: 'E16.3', label: 'SA' },
  { addr: 'E16.4', label: 'FT10' },
  { addr: 'E16.5', label: 'DB32' },
  { addr: 'E16.6', label: 'DBHZ' },
  { addr: 'E16.7', label: 'KS12' },
  { addr: 'E17.0', label: 'TS1' },
  { addr: 'E17.1', label: 'IV4' },
  { addr: 'E17.2', label: 'FE2' },
  { addr: 'E17.3', label: 'RMV' },
  { addr: 'E17.4', label: 'RMH' },
  { addr: 'E17.5', label: 'RES' },
  { addr: 'E17.6', label: 'REH' },
  { addr: 'E17.7', label: 'RCV' },
  { addr: 'E18.0', label: 'REAV' },
  { addr: 'E18.1', label: 'REAH' },
  { addr: 'E18.2', label: 'RCH' },
  { addr: 'E18.3', label: '' },
  { addr: 'E18.4', label: '' },
  { addr: 'E18.5', label: '' },
  { addr: 'E18.6', label: '' },
  { addr: 'E18.7', label: '' },
  { addr: 'E19.0', label: '' },
  { addr: 'E19.1', label: '' },
  { addr: 'E19.2', label: '' },
  { addr: 'E19.3', label: '' },
  { addr: 'E19.4', label: '' },
  { addr: 'E19.5', label: '' },
  { addr: 'E19.6', label: '' },
  { addr: 'E19.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'DYA' },
  { addr: 'A1.1', label: 'DYB' },
  { addr: 'A1.2', label: 'DYC' },
  { addr: 'A1.3', label: 'DYD' },
  { addr: 'A1.4', label: 'AD1' },
  { addr: 'A1.5', label: 'AD2' },
  { addr: 'A1.6', label: 'AD3' },
  { addr: 'A1.7', label: 'STR' },
  { addr: 'A2.0', label: 'SBK1-1' },
  { addr: 'A2.1', label: 'SBK2-1' },
  { addr: 'A2.2', label: 'SBK1-2' },
  { addr: 'A2.3', label: 'SBK2-2' },
  { addr: 'A2.4', label: 'SBK1-3' },
  { addr: 'A2.5', label: 'SBK2-3' },
  { addr: 'A2.6', label: 'SMA1' },
  { addr: 'A2.7', label: 'SMB1' },
  { addr: 'A3.0', label: 'SMA2' },
  { addr: 'A3.1', label: 'SMB2' },
  { addr: 'A3.2', label: 'SCA' },
  { addr: 'A3.3', label: 'SCB' },
  { addr: 'A3.4', label: 'KBA1-1' },
  { addr: 'A3.5', label: 'KBA2-1' },
  { addr: 'A3.6', label: 'KBA1-2' },
  { addr: 'A3.7', label: 'KBA2-2' },
  { addr: 'A4.0', label: 'KBA3-1' },
  { addr: 'A4.1', label: 'KBA3-2' },
  { addr: 'A4.2', label: 'SPE' },
  { addr: 'A4.3', label: 'SOE' },
  { addr: 'A4.4', label: 'SZE' },
  { addr: 'A4.5', label: 'SPA' },
  { addr: 'A4.6', label: 'SOA' },
  { addr: 'A4.7', label: 'SZA' },
  { addr: 'A5.0', label: 'RFE' },
  { addr: 'A5.1', label: 'RFA' },
  { addr: 'A5.2', label: '' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' },
  { addr: 'A6.0', label: '' },
  { addr: 'A6.1', label: '' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: '' },
  { addr: 'A7.0', label: '' },
  { addr: 'A7.1', label: '' },
  { addr: 'A7.2', label: '' },
  { addr: 'A7.3', label: '' },
  { addr: 'A7.4', label: '' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: '' },
  { addr: 'A7.7', label: '' }
]
export const outputs2 = [
  { addr: 'A12.0', label: 'SMA3' },
  { addr: 'A12.1', label: 'SMB3' },
  { addr: 'A12.2', label: 'TCR1' },
  { addr: 'A12.3', label: 'LA' },
  { addr: 'A12.4', label: '' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: '' },
  { addr: 'A12.7', label: '' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: 'DYA' },
  { addr: 'A14.1', label: 'DYB' },
  { addr: 'A14.2', label: 'DYC' },
  { addr: 'A14.3', label: 'DYD' },
  { addr: 'A14.4', label: 'AD1' },
  { addr: 'A14.5', label: 'AD2' },
  { addr: 'A14.6', label: 'AD3' },
  { addr: 'A14.7', label: 'STR' },
  { addr: 'A15.0', label: 'LC' },
  { addr: 'A15.1', label: 'T10F' },
  { addr: 'A15.2', label: 'TRA' },
  { addr: 'A15.3', label: 'TRB' },
  { addr: 'A15.4', label: 'TCR2' },
  { addr: 'A15.5', label: 'KCS' },
  { addr: 'A15.6', label: 'KCV' },
  { addr: 'A15.7', label: 'KCH' },
  { addr: 'A16.0', label: 'LA3' },
  { addr: 'A16.1', label: 'T2' },
  { addr: 'A16.2', label: 'T101' },
  { addr: 'A16.3', label: 'T102' },
  { addr: 'A16.4', label: 'KBA1-4' },
  { addr: 'A16.5', label: 'KBA2-4' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' }
]
export const alarms1 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
