export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: 'FLP2A' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'STR' },
  { addr: 'E1.5', label: 'OK' },
  { addr: 'E1.6', label: 'DAT' },
  { addr: 'E1.7', label: 'FLP2B' },
  { addr: 'E2.0', label: 'A' },
  { addr: 'E2.1', label: 'B' },
  { addr: 'E2.2', label: 'C' },
  { addr: 'E2.3', label: 'D' },
  { addr: 'E2.4', label: 'STR' },
  { addr: 'E2.5', label: 'OK' },
  { addr: 'E2.6', label: 'DAT' },
  { addr: 'E2.7', label: 'FLP2C' },
  { addr: 'E3.0', label: 'A' },
  { addr: 'E3.1', label: 'B' },
  { addr: 'E3.2', label: 'C' },
  { addr: 'E3.3', label: 'D' },
  { addr: 'E3.4', label: 'STR' },
  { addr: 'E3.5', label: 'OK' },
  { addr: 'E3.6', label: 'DAT' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S1T1' },
  { addr: 'E4.6', label: 'S1T1' },
  { addr: 'E4.7', label: 'S1T1' },
  { addr: 'E5.0', label: 'ST1' },
  { addr: 'E5.1', label: 'ST1' },
  { addr: 'E5.2', label: 'ST2' },
  { addr: 'E5.3', label: 'ST2' },
  { addr: 'E5.4', label: 'ASKD' },
  { addr: 'E5.5', label: 'S1T2' },
  { addr: 'E5.6', label: 'S1T2' },
  { addr: 'E5.7', label: 'S1T2' },
  { addr: 'E6.0', label: '' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: '' },
  { addr: 'E6.4', label: 'OK-EM' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: 'EM-A' },
  { addr: 'E7.1', label: 'EM-B' },
  { addr: 'E7.2', label: 'EM-C' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'S-ABC' },
  { addr: 'E7.5', label: 'S-ABC' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: 'UC' },
  { addr: 'E8.0', label: 'IV' },
  { addr: 'E8.1', label: 'EPA' },
  { addr: 'E8.2', label: 'RX' },
  { addr: 'E8.3', label: 'SPR' },
  { addr: 'E8.4', label: '' },
  { addr: 'E8.5', label: 'S1' },
  { addr: 'E8.6', label: 'S1' },
  { addr: 'E8.7', label: 'S1' },
  { addr: 'E9.0', label: 'MDR' },
  { addr: 'E9.1', label: 'MDL' },
  { addr: 'E9.2', label: 'EDR' },
  { addr: 'E9.3', label: 'EDL' },
  { addr: 'E9.4', label: 'EPB' },
  { addr: 'E9.5', label: 'ECA' },
  { addr: 'E9.6', label: 'ECB' },
  { addr: 'E9.7', label: 'AMC' },
  { addr: 'E10.0', label: 'EPZV' },
  { addr: 'E10.1', label: 'EPZH' },
  { addr: 'E10.2', label: 'FLP' },
  { addr: 'E10.3', label: 'FPE' },
  { addr: 'E10.4', label: 'FDR' },
  { addr: 'E10.5', label: 'FDL' },
  { addr: 'E10.6', label: 'FTA1' },
  { addr: 'E10.7', label: 'FTA2' },
  { addr: 'E11.0', label: 'EZE' },
  { addr: 'E11.1', label: 'EOE' },
  { addr: 'E11.2', label: 'FBE' },
  { addr: 'E11.3', label: 'APE' },
  { addr: 'E11.4', label: 'EBZE' },
  { addr: 'E11.5', label: 'EBOE' },
  { addr: 'E11.6', label: 'FBBE' },
  { addr: 'E11.7', label: 'APBE' },
  { addr: 'E12.0', label: 'IV' },
  { addr: 'E12.1', label: 'EPA' },
  { addr: 'E12.2', label: 'RX' },
  { addr: 'E12.3', label: 'SPR' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: 'S1' },
  { addr: 'E12.6', label: 'S1' },
  { addr: 'E12.7', label: 'S1' },
  { addr: 'E13.0', label: 'MDR' },
  { addr: 'E13.1', label: 'MDL' },
  { addr: 'E13.2', label: 'EDR' },
  { addr: 'E13.3', label: 'EDL' },
  { addr: 'E13.4', label: 'EPB' },
  { addr: 'E13.5', label: 'ECA' },
  { addr: 'E13.6', label: 'ECB' },
  { addr: 'E13.7', label: 'AMC' },
  { addr: 'E14.0', label: 'EPZV' },
  { addr: 'E14.1', label: 'EPZH' },
  { addr: 'E14.2', label: 'FLP' },
  { addr: 'E14.3', label: 'FPE' },
  { addr: 'E14.4', label: 'FDR' },
  { addr: 'E14.5', label: 'FDL' },
  { addr: 'E14.6', label: 'FTA1' },
  { addr: 'E14.7', label: 'FTA2' },
  { addr: 'E15.0', label: 'EZE' },
  { addr: 'E15.1', label: 'EOE' },
  { addr: 'E15.2', label: 'FBE' },
  { addr: 'E15.3', label: 'APE' },
  { addr: 'E15.4', label: 'EBZE' },
  { addr: 'E15.5', label: 'EBOE' },
  { addr: 'E15.6', label: 'FBBE' },
  { addr: 'E15.7', label: 'APBE' },
  { addr: 'E16.0', label: 'IV' },
  { addr: 'E16.1', label: 'EPA' },
  { addr: 'E16.2', label: 'RX' },
  { addr: 'E16.3', label: 'SPR' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: 'S1' },
  { addr: 'E16.6', label: 'S1' },
  { addr: 'E16.7', label: 'S1' },
  { addr: 'E17.0', label: 'MDR' },
  { addr: 'E17.1', label: 'MDL' },
  { addr: 'E17.2', label: 'EDR' },
  { addr: 'E17.3', label: 'EDL' },
  { addr: 'E17.4', label: 'EPB' },
  { addr: 'E17.5', label: 'ECA' },
  { addr: 'E17.6', label: 'ECB' },
  { addr: 'E17.7', label: 'AMC' },
  { addr: 'E18.0', label: 'EPZV' },
  { addr: 'E18.1', label: 'EPZH' },
  { addr: 'E18.2', label: 'FLP' },
  { addr: 'E18.3', label: 'FPE' },
  { addr: 'E18.4', label: 'FDR' },
  { addr: 'E18.5', label: 'FDL' },
  { addr: 'E18.6', label: 'FTA1' },
  { addr: 'E18.7', label: 'FTA2' },
  { addr: 'E19.0', label: 'EZE' },
  { addr: 'E19.1', label: 'EOE' },
  { addr: 'E19.2', label: 'FBE' },
  { addr: 'E19.3', label: 'APE' },
  { addr: 'E19.4', label: 'EBZE' },
  { addr: 'E19.5', label: 'EBOE' },
  { addr: 'E19.6', label: 'FBBE' },
  { addr: 'E19.7', label: 'APBE' }
]
export const inputs2 = [
  { addr: 'E20.0', label: 'A' },
  { addr: 'E20.1', label: 'B' },
  { addr: 'E20.2', label: 'C' },
  { addr: 'E20.3', label: 'D' },
  { addr: 'E20.4', label: 'OK' },
  { addr: 'E20.5', label: 'S2' },
  { addr: 'E20.6', label: 'S2' },
  { addr: 'E20.7', label: 'S2' },
  { addr: 'E21.0', label: 'FTV' },
  { addr: 'E21.1', label: 'FTH1' },
  { addr: 'E21.2', label: 'EOM' },
  { addr: 'E21.3', label: 'EZM' },
  { addr: 'E21.4', label: 'FEMV' },
  { addr: 'E21.5', label: 'FEMH' },
  { addr: 'E21.6', label: 'FTXV' },
  { addr: 'E21.7', label: 'FTXH' },
  { addr: 'E22.0', label: 'RMV' },
  { addr: 'E22.1', label: 'RMH' },
  { addr: 'E22.2', label: 'RES' },
  { addr: 'E22.3', label: 'REH' },
  { addr: 'E22.4', label: 'RCV' },
  { addr: 'E22.5', label: 'REAV' },
  { addr: 'E22.6', label: 'REAH' },
  { addr: 'E22.7', label: 'RCH' },
  { addr: 'E23.0', label: 'IV1' },
  { addr: 'E23.1', label: 'IV2' },
  { addr: 'E23.2', label: 'S1' },
  { addr: 'E23.3', label: 'RSI' },
  { addr: 'E23.4', label: 'DB32' },
  { addr: 'E23.5', label: 'DBHZ' },
  { addr: 'E23.6', label: 'FTH2' },
  { addr: 'E23.7', label: 'UC' },
  { addr: 'E24.0', label: 'EFR' },
  { addr: 'E24.1', label: 'EFL' },
  { addr: 'E24.2', label: 'EHP' },
  { addr: 'E24.3', label: 'EXPV' },
  { addr: 'E24.4', label: 'ASBK2' },
  { addr: 'E24.5', label: 'FTCR' },
  { addr: 'E24.6', label: 'AH' },
  { addr: 'E24.7', label: 'MTC' },
  { addr: 'E25.0', label: 'EFA' },
  { addr: 'E25.1', label: 'EFB' },
  { addr: 'E25.2', label: 'EXV' },
  { addr: 'E25.3', label: 'FDBK' },
  { addr: 'E25.4', label: 'ASBK' },
  { addr: 'E25.5', label: 'RTA' },
  { addr: 'E25.6', label: 'TJ2' },
  { addr: 'E25.7', label: 'AMM' }
]
export const inputs3 = [
  { addr: 'E26.0', label: 'A' },
  { addr: 'E26.1', label: 'B' },
  { addr: 'E26.2', label: 'C' },
  { addr: 'E26.3', label: 'D' },
  { addr: 'E26.4', label: 'OK' },
  { addr: 'E26.5', label: 'S2' },
  { addr: 'E26.6', label: 'S2' },
  { addr: 'E26.7', label: 'S2' },
  { addr: 'E27.0', label: 'FTV' },
  { addr: 'E27.1', label: 'FTH1' },
  { addr: 'E27.2', label: 'EOM' },
  { addr: 'E27.3', label: 'EZM' },
  { addr: 'E27.4', label: 'FEMV' },
  { addr: 'E27.5', label: 'FEMH' },
  { addr: 'E27.6', label: 'FTXV' },
  { addr: 'E27.7', label: 'FTXH' },
  { addr: 'E28.0', label: 'RMV' },
  { addr: 'E28.1', label: 'RMH' },
  { addr: 'E28.2', label: 'RES' },
  { addr: 'E28.3', label: 'REH' },
  { addr: 'E28.4', label: 'RCV' },
  { addr: 'E28.5', label: 'REAV' },
  { addr: 'E28.6', label: 'REAH' },
  { addr: 'E28.7', label: 'RCH' },
  { addr: 'E29.0', label: 'IV1' },
  { addr: 'E29.1', label: 'IV2' },
  { addr: 'E29.2', label: 'S1' },
  { addr: 'E29.3', label: 'RSI' },
  { addr: 'E29.4', label: 'DB32' },
  { addr: 'E29.5', label: 'DBHZ' },
  { addr: 'E29.6', label: 'FTH2' },
  { addr: 'E29.7', label: 'UC' },
  { addr: 'E30.0', label: 'EFR' },
  { addr: 'E30.1', label: 'EFL' },
  { addr: 'E30.2', label: 'EHP' },
  { addr: 'E30.3', label: 'EXPV' },
  { addr: 'E30.4', label: 'ASBK2' },
  { addr: 'E30.5', label: 'FTCR' },
  { addr: 'E30.6', label: 'AH' },
  { addr: 'E30.7', label: 'MTC' },
  { addr: 'E31.0', label: 'EFA' },
  { addr: 'E31.1', label: 'EFB' },
  { addr: 'E31.2', label: 'EXV' },
  { addr: 'E31.3', label: 'FDBK' },
  { addr: 'E31.4', label: 'ASBK' },
  { addr: 'E31.5', label: 'RTA' },
  { addr: 'E31.6', label: 'TJ2' },
  { addr: 'E31.7', label: 'AMM' }
]
export const inputs4 = [
  { addr: 'E32.0', label: '' },
  { addr: 'E32.1', label: '' },
  { addr: 'E32.2', label: '' },
  { addr: 'E32.3', label: '' },
  { addr: 'E32.4', label: '' },
  { addr: 'E32.5', label: '' },
  { addr: 'E32.6', label: '' },
  { addr: 'E32.7', label: '' },
  { addr: 'E33.0', label: '' },
  { addr: 'E33.1', label: '' },
  { addr: 'E33.2', label: '' },
  { addr: 'E33.3', label: '' },
  { addr: 'E33.4', label: '' },
  { addr: 'E33.5', label: '' },
  { addr: 'E33.6', label: '' },
  { addr: 'E33.7', label: '' },
  { addr: 'E34.0', label: '' },
  { addr: 'E34.1', label: '' },
  { addr: 'E34.2', label: '' },
  { addr: 'E34.3', label: '' },
  { addr: 'E34.4', label: '' },
  { addr: 'E34.5', label: '' },
  { addr: 'E34.6', label: '' },
  { addr: 'E34.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: 'RBE' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'RBE' },
  { addr: 'A2.0', label: 'LK' },
  { addr: 'A2.1', label: 'LE' },
  { addr: 'A2.2', label: 'LB' },
  { addr: 'A2.3', label: 'RDY' },
  { addr: 'A2.4', label: 'RST' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: 'RBE' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: 'LCT1' },
  { addr: 'A3.6', label: 'LCT2' },
  { addr: 'A3.7', label: 'RBE' },
  { addr: 'A4.0', label: 'SCA' },
  { addr: 'A4.1', label: 'SCB' },
  { addr: 'A4.2', label: 'TD' },
  { addr: 'A4.3', label: 'SP' },
  { addr: 'A4.4', label: 'SZ' },
  { addr: 'A4.5', label: 'SO' },
  { addr: 'A4.6', label: 'SBZ' },
  { addr: 'A4.7', label: 'SBO' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'KBA' },
  { addr: 'A6.0', label: 'SCA' },
  { addr: 'A6.1', label: 'SCB' },
  { addr: 'A6.2', label: 'TD' },
  { addr: 'A6.3', label: 'SP' },
  { addr: 'A6.4', label: 'SZ' },
  { addr: 'A6.5', label: 'SO' },
  { addr: 'A6.6', label: 'SBZ' },
  { addr: 'A6.7', label: 'SBO' },
  { addr: 'A7.0', label: 'L1' },
  { addr: 'A7.1', label: 'L2' },
  { addr: 'A7.2', label: 'L3' },
  { addr: 'A7.3', label: 'L4' },
  { addr: 'A7.4', label: 'L5' },
  { addr: 'A7.5', label: 'RFE' },
  { addr: 'A7.6', label: 'RLN' },
  { addr: 'A7.7', label: 'KBA' },
  { addr: 'A8.0', label: 'SCA' },
  { addr: 'A8.1', label: 'SCB' },
  { addr: 'A8.2', label: 'TD' },
  { addr: 'A8.3', label: 'SP' },
  { addr: 'A8.4', label: 'SZ' },
  { addr: 'A8.5', label: 'SO' },
  { addr: 'A8.6', label: 'SBZ' },
  { addr: 'A8.7', label: 'SBO' },
  { addr: 'A9.0', label: 'L1' },
  { addr: 'A9.1', label: 'L2' },
  { addr: 'A9.2', label: 'L3' },
  { addr: 'A9.3', label: 'L4' },
  { addr: 'A9.4', label: 'L5' },
  { addr: 'A9.5', label: 'RFE' },
  { addr: 'A9.6', label: 'RLN' },
  { addr: 'A9.7', label: 'KBA' },
  { addr: 'A10.0', label: 'A' },
  { addr: 'A10.1', label: 'B' },
  { addr: 'A10.2', label: 'C' },
  { addr: 'A10.3', label: 'D' },
  { addr: 'A10.4', label: 'AD1' },
  { addr: 'A10.5', label: 'AD2' },
  { addr: 'A10.6', label: 'AD3' },
  { addr: 'A10.7', label: 'STR' },
  { addr: 'A11.0', label: 'A' },
  { addr: 'A11.1', label: 'B' },
  { addr: 'A11.2', label: 'C' },
  { addr: 'A11.3', label: 'D' },
  { addr: 'A11.4', label: 'AD1' },
  { addr: 'A11.5', label: 'AD2' },
  { addr: 'A11.6', label: 'AD3' },
  { addr: 'A11.7', label: 'STR' }
]
export const outputs2 = [
  { addr: 'A20.0', label: 'KBA1' },
  { addr: 'A20.1', label: 'SBK1' },
  { addr: 'A20.2', label: 'SMA' },
  { addr: 'A20.3', label: 'SMB' },
  { addr: 'A20.4', label: '' },
  { addr: 'A20.5', label: '' },
  { addr: 'A20.6', label: '' },
  { addr: 'A20.7', label: '' },
  { addr: 'A21.0', label: 'KBA2' },
  { addr: 'A21.1', label: 'SBK2' },
  { addr: 'A21.2', label: 'T10F' },
  { addr: 'A21.3', label: '' },
  { addr: 'A21.4', label: '' },
  { addr: 'A21.5', label: '' },
  { addr: 'A21.6', label: '' },
  { addr: 'A21.7', label: 'LC' },
  { addr: 'A22.0', label: 'A' },
  { addr: 'A22.1', label: 'B' },
  { addr: 'A22.2', label: 'C' },
  { addr: 'A22.3', label: 'D' },
  { addr: 'A22.4', label: 'AD1' },
  { addr: 'A22.5', label: 'AD2' },
  { addr: 'A22.6', label: 'AD3' },
  { addr: 'A22.7', label: 'STR' },
  { addr: 'A23.0', label: 'T10' },
  { addr: 'A23.1', label: 'T2' },
  { addr: 'A23.2', label: 'TRA' },
  { addr: 'A23.3', label: 'TRB' },
  { addr: 'A23.4', label: 'KCS' },
  { addr: 'A23.5', label: 'KCV' },
  { addr: 'A23.6', label: 'KCH' },
  { addr: 'A23.7', label: 'TCR' }
]
export const outputs3 = [
  { addr: 'A26.0', label: 'KBA1' },
  { addr: 'A26.1', label: 'SBK1' },
  { addr: 'A26.2', label: 'SMA' },
  { addr: 'A26.3', label: 'SMB' },
  { addr: 'A26.4', label: '' },
  { addr: 'A26.5', label: '' },
  { addr: 'A26.6', label: '' },
  { addr: 'A26.7', label: '' },
  { addr: 'A27.0', label: 'KBA2' },
  { addr: 'A27.1', label: 'SBK2' },
  { addr: 'A27.2', label: 'T10F' },
  { addr: 'A27.3', label: '' },
  { addr: 'A27.4', label: '' },
  { addr: 'A27.5', label: '' },
  { addr: 'A27.6', label: '' },
  { addr: 'A27.7', label: 'LC' },
  { addr: 'A28.0', label: 'A' },
  { addr: 'A28.1', label: 'B' },
  { addr: 'A28.2', label: 'C' },
  { addr: 'A28.3', label: 'D' },
  { addr: 'A28.4', label: 'AD1' },
  { addr: 'A28.5', label: 'AD2' },
  { addr: 'A28.6', label: 'AD3' },
  { addr: 'A28.7', label: 'STR' },
  { addr: 'A29.0', label: 'T10' },
  { addr: 'A29.1', label: 'T2' },
  { addr: 'A29.2', label: 'TRA' },
  { addr: 'A29.3', label: 'TRB' },
  { addr: 'A29.4', label: 'KCS' },
  { addr: 'A29.5', label: 'KCV' },
  { addr: 'A29.6', label: 'KCH' },
  { addr: 'A29.7', label: 'TCR' }
]
export const outputs4 = [
  { addr: 'A32.0', label: '' },
  { addr: 'A32.1', label: '' },
  { addr: 'A32.2', label: '' },
  { addr: 'A32.3', label: '' },
  { addr: 'A32.4', label: '' },
  { addr: 'A32.5', label: '' },
  { addr: 'A32.6', label: '' },
  { addr: 'A32.7', label: '' },
  { addr: 'A33.0', label: '' },
  { addr: 'A33.1', label: '' },
  { addr: 'A33.2', label: '' },
  { addr: 'A33.3', label: '' },
  { addr: 'A33.4', label: '' },
  { addr: 'A33.5', label: '' },
  { addr: 'A33.6', label: '' },
  { addr: 'A33.7', label: '' }
]

export const ALARMS = [
  { id: 1, key: 'al-v-to', query: {} },
  { id: 2, key: 'al-lv', query: {} },
  { id: 3, key: 'al-v-fdbk', query: {} },
  { id: 4, key: 'al-iv', query: { nr: 1 } },
  { id: 5, key: '', query: {} },
  { id: 6, key: 'al-v-fdbk', query: {} },
  { id: 7, key: 'al-th', query: { name: 'LS' } },
  { id: 8, key: 'al-sil-15', query: {} },
  { id: 9, key: 'al-sil-01', query: {} },
  { id: 10, key: 'al-sil-11', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: 'al-iv', query: { nr: 2 } },
  { id: 13, key: 'al-sil-05', query: {} },
  { id: 14, key: 'al-sil-06', query: {} },
  { id: 15, key: 'al-sil-13', query: {} },
  { id: 16, key: 'al-sil-07', query: {} },
  { id: 17, key: 'al-fc', query: { fc1: 'EFA', fc2: 'EFB' } },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: 'al-v-lck-to', query: {} },
  { id: 23, key: 'al-fc', query: { fc1: 'EOM', fc2: 'EZM' } },
  { id: 24, key: '', query: {} },
  { id: 25, key: 'al-h-to', query: {} },
  { id: 26, key: 'al-lh', query: {} },
  { id: 27, key: 'al-fc', query: { fc1: 'EFL', fc2: 'EFR' } },
  { id: 28, key: 'al-iv', query: { nr: 2 } },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-r-to', query: {} },
  { id: 66, key: 'al-fc', query: { fc1: 'EDL', fc2: 'EDR' } },
  { id: 67, key: '', query: {} },
  { id: 68, key: 'al-iv', query: { nr: 3 } },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: 'al-th', query: { name: 'LS' } },
  { id: 72, key: '', query: {} },
  { id: 73, key: 'al-spb-to', query: {} },
  { id: 74, key: 'al-fc', query: { fc1: 'EBOE', fc2: 'EBZE' } },
  { id: 75, key: 'al-flap-to', query: {} },
  { id: 76, key: 'al-fc', query: { fc1: 'ECB', fc2: 'ECB' } },
  { id: 77, key: 'al-sp-to', query: {} },
  { id: 78, key: 'al-fc', query: { fc1: 'EOE', fc2: 'EZE' } },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'T1' },
  { id: 2, key: 'T2' },
  { id: 3, key: 'A' },
  { id: 4, key: 'B' },
  { id: 5, key: 'C' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
