// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'SF1' },
  { addr: 'E0.1', label: 'SF2' },
  { addr: 'E0.2', label: 'SF3' },
  { addr: 'E0.3', label: 'SF4' },
  { addr: 'E0.4', label: 'SF5' },
  { addr: 'E0.5', label: 'SF6' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: 'RS34' },
  { addr: 'E1.0', label: 'TS1' },
  { addr: 'E1.1', label: 'TS2' },
  { addr: 'E1.2', label: 'TS3' },
  { addr: 'E1.3', label: 'FE' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'FE' },
  { addr: 'E101.1', label: 'IV1' },
  { addr: 'E101.2', label: 'TJ1' },
  { addr: 'E101.3', label: 'RSI' },
  { addr: 'E101.4', label: 'SA' },
  { addr: 'E101.5', label: 'FDBK' },
  { addr: 'E101.6', label: 'ASBK' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'RTA' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: 'DB32' },
  { addr: 'E102.3', label: 'DBHZ' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: '' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: '' },
  { addr: 'E103.5', label: '' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: 'A' },
  { addr: 'E110.1', label: 'B' },
  { addr: 'E110.2', label: 'C' },
  { addr: 'E110.3', label: 'D' },
  { addr: 'E110.4', label: 'OK' },
  { addr: 'E110.5', label: 'S2' },
  { addr: 'E110.6', label: 'S2' },
  { addr: 'E110.7', label: 'S2' },
  { addr: 'E111.0', label: 'FE' },
  { addr: 'E111.1', label: 'IV1' },
  { addr: 'E111.2', label: 'IV2' },
  { addr: 'E111.3', label: 'EM' },
  { addr: 'E111.4', label: 'EXE' },
  { addr: 'E111.5', label: 'EXU' },
  { addr: 'E111.6', label: 'FTXV' },
  { addr: 'E111.7', label: 'FTXH' },
  { addr: 'E112.0', label: 'RMV' },
  { addr: 'E112.1', label: 'RMH' },
  { addr: 'E112.2', label: 'RES' },
  { addr: 'E112.3', label: 'REH' },
  { addr: 'E112.4', label: 'RCV' },
  { addr: 'E112.5', label: 'REAV' },
  { addr: 'E112.6', label: 'REAH' },
  { addr: 'E112.7', label: 'RCH' },
  { addr: 'E113.0', label: 'TJ1' },
  { addr: 'E113.1', label: 'TJ2' },
  { addr: 'E113.2', label: 'SA' },
  { addr: 'E113.3', label: 'RSI' },
  { addr: 'E113.4', label: 'DB32' },
  { addr: 'E113.5', label: 'DBHZ' },
  { addr: 'E113.6', label: '' },
  { addr: 'E113.7', label: 'UC' },
  { addr: 'E114.0', label: 'ASBKD' },
  { addr: 'E114.1', label: 'FTMV' },
  { addr: 'E114.2', label: 'FTMH' },
  { addr: 'E114.3', label: '' },
  { addr: 'E114.4', label: 'FTCR' },
  { addr: 'E114.5', label: 'AD' },
  { addr: 'E114.6', label: 'AH' },
  { addr: 'E114.7', label: 'MTC' },
  { addr: 'E115.0', label: '' },
  { addr: 'E115.1', label: '' },
  { addr: 'E115.2', label: '' },
  { addr: 'E115.3', label: '' },
  { addr: 'E115.4', label: '' },
  { addr: 'E115.5', label: '' },
  { addr: 'E115.6', label: '' },
  { addr: 'E115.7', label: '' }
]
export const inputs4 = [
  { addr: 'E120.0', label: 'AMM' },
  { addr: 'E120.1', label: 'EOM' },
  { addr: 'E120.2', label: 'EZM' },
  { addr: 'E120.3', label: 'AMC' },
  { addr: 'E120.4', label: 'ECA' },
  { addr: 'E120.5', label: 'ECB' },
  { addr: 'E120.6', label: 'APE' },
  { addr: 'E120.7', label: '' },
  { addr: 'E121.0', label: 'RX' },
  { addr: 'E121.1', label: 'EXPV' },
  { addr: 'E121.2', label: 'EXV' },
  { addr: 'E121.3', label: 'FREL' },
  { addr: 'E121.4', label: 'FRER' },
  { addr: 'E121.5', label: '' },
  { addr: 'E121.6', label: '' },
  { addr: 'E121.7', label: '' },
  { addr: 'E122.0', label: 'EZE' },
  { addr: 'E122.1', label: 'EOE' },
  { addr: 'E122.2', label: 'FBE' },
  { addr: 'E122.3', label: 'FPE' },
  { addr: 'E122.4', label: 'FDR1' },
  { addr: 'E122.5', label: 'FDL1' },
  { addr: 'E122.6', label: 'FTA1' },
  { addr: 'E122.7', label: 'FTA2' },
  { addr: 'E123.0', label: '' },
  { addr: 'E123.1', label: 'FLP' },
  { addr: 'E123.2', label: 'FLA' },
  { addr: 'E123.3', label: 'FDR2' },
  { addr: 'E123.4', label: 'FDL2' },
  { addr: 'E123.5', label: 'FTXV' },
  { addr: 'E123.6', label: 'FTXH' },
  { addr: 'E123.7', label: 'FTC' },
  { addr: 'E124.0', label: 'FLX' },
  { addr: 'E124.1', label: 'FRX' },
  { addr: 'E124.2', label: '' },
  { addr: 'E124.3', label: '' },
  { addr: 'E124.4', label: '' },
  { addr: 'E124.5', label: '' },
  { addr: 'E124.6', label: '' },
  { addr: 'E124.7', label: '' },
  { addr: 'E125.0', label: '' },
  { addr: 'E125.1', label: '' },
  { addr: 'E125.2', label: '' },
  { addr: 'E125.3', label: '' },
  { addr: 'E125.4', label: '' },
  { addr: 'E125.5', label: '' },
  { addr: 'E125.6', label: '' },
  { addr: 'E125.7', label: '' }
]
// export const inputs5 = [
//   { addr: 'E200.0', label: '' },
//   { addr: 'E200.1', label: '' },
//   { addr: 'E200.2', label: '' },
//   { addr: 'E200.3', label: '' },
//   { addr: 'E200.4', label: '' },
//   { addr: 'E200.5', label: '' },
//   { addr: 'E200.6', label: '' },
//   { addr: 'E200.7', label: '' },
//   { addr: 'E201.0', label: '' },
//   { addr: 'E201.1', label: '' },
//   { addr: 'E201.2', label: '' },
//   { addr: 'E201.3', label: '' },
//   { addr: 'E201.4', label: '' },
//   { addr: 'E201.5', label: '' },
//   { addr: 'E201.6', label: '' },
//   { addr: 'E201.7', label: '' },
//   { addr: 'E202.0', label: '' },
//   { addr: 'E202.1', label: '' },
//   { addr: 'E202.2', label: '' },
//   { addr: 'E202.3', label: '' },
//   { addr: 'E202.4', label: '' },
//   { addr: 'E202.5', label: '' },
//   { addr: 'E202.6', label: '' },
//   { addr: 'E202.7', label: '' },
//   { addr: 'E203.0', label: '' },
//   { addr: 'E203.1', label: '' },
//   { addr: 'E203.2', label: '' },
//   { addr: 'E203.3', label: '' },
//   { addr: 'E203.4', label: '' },
//   { addr: 'E203.5', label: '' },
//   { addr: 'E203.6', label: '' },
//   { addr: 'E203.7', label: '' }
// ]
// export const inputs6 = [
//   { addr: 'E210.0', label: '' },
//   { addr: 'E210.1', label: '' },
//   { addr: 'E210.2', label: '' },
//   { addr: 'E210.3', label: '' },
//   { addr: 'E210.4', label: '' },
//   { addr: 'E210.5', label: '' },
//   { addr: 'E210.6', label: '' },
//   { addr: 'E210.7', label: '' },
//   { addr: 'E211.0', label: '' },
//   { addr: 'E211.1', label: '' },
//   { addr: 'E211.2', label: '' },
//   { addr: 'E211.3', label: '' },
//   { addr: 'E211.4', label: '' },
//   { addr: 'E211.5', label: '' },
//   { addr: 'E211.6', label: '' },
//   { addr: 'E211.7', label: '' },
//   { addr: 'E212.0', label: '' },
//   { addr: 'E212.1', label: '' },
//   { addr: 'E212.2', label: '' },
//   { addr: 'E212.3', label: '' },
//   { addr: 'E212.4', label: '' },
//   { addr: 'E212.5', label: '' },
//   { addr: 'E212.6', label: '' },
//   { addr: 'E212.7', label: '' },
//   { addr: 'E213.0', label: '' },
//   { addr: 'E213.1', label: '' },
//   { addr: 'E213.2', label: '' },
//   { addr: 'E213.3', label: '' },
//   { addr: 'E213.4', label: '' },
//   { addr: 'E213.5', label: '' },
//   { addr: 'E213.6', label: '' },
//   { addr: 'E213.7', label: '' },
//   { addr: 'E214.0', label: '' },
//   { addr: 'E214.1', label: '' },
//   { addr: 'E214.2', label: '' },
//   { addr: 'E214.3', label: '' },
//   { addr: 'E214.4', label: '' },
//   { addr: 'E214.5', label: '' },
//   { addr: 'E214.6', label: '' },
//   { addr: 'E214.7', label: '' },
//   { addr: 'E215.0', label: '' },
//   { addr: 'E215.1', label: '' },
//   { addr: 'E215.2', label: '' },
//   { addr: 'E215.3', label: '' },
//   { addr: 'E215.4', label: '' },
//   { addr: 'E215.5', label: '' },
//   { addr: 'E215.6', label: '' },
//   { addr: 'E215.7', label: '' }
// ]
// export const inputs7 = [
//   { addr: 'E220.0', label: '' },
//   { addr: 'E220.1', label: '' },
//   { addr: 'E220.2', label: '' },
//   { addr: 'E220.3', label: '' },
//   { addr: 'E220.4', label: '' },
//   { addr: 'E220.5', label: '' },
//   { addr: 'E220.6', label: '' },
//   { addr: 'E220.7', label: '' },
//   { addr: 'E221.0', label: '' },
//   { addr: 'E221.1', label: '' },
//   { addr: 'E221.2', label: '' },
//   { addr: 'E221.3', label: '' },
//   { addr: 'E221.4', label: '' },
//   { addr: 'E221.5', label: '' },
//   { addr: 'E221.6', label: '' },
//   { addr: 'E221.7', label: '' },
//   { addr: 'E222.0', label: '' },
//   { addr: 'E222.1', label: '' },
//   { addr: 'E222.2', label: '' },
//   { addr: 'E222.3', label: '' },
//   { addr: 'E222.4', label: '' },
//   { addr: 'E222.5', label: '' },
//   { addr: 'E222.6', label: '' },
//   { addr: 'E222.7', label: '' },
//   { addr: 'E223.0', label: '' },
//   { addr: 'E223.1', label: '' },
//   { addr: 'E223.2', label: '' },
//   { addr: 'E223.3', label: '' },
//   { addr: 'E223.4', label: '' },
//   { addr: 'E223.5', label: '' },
//   { addr: 'E223.6', label: '' },
//   { addr: 'E223.7', label: '' },
//   { addr: 'E224.0', label: '' },
//   { addr: 'E224.1', label: '' },
//   { addr: 'E224.2', label: '' },
//   { addr: 'E224.3', label: '' },
//   { addr: 'E224.4', label: '' },
//   { addr: 'E224.5', label: '' },
//   { addr: 'E224.6', label: '' },
//   { addr: 'E224.7', label: '' },
//   { addr: 'E225.0', label: '' },
//   { addr: 'E225.1', label: '' },
//   { addr: 'E225.2', label: '' },
//   { addr: 'E225.3', label: '' },
//   { addr: 'E225.4', label: '' },
//   { addr: 'E225.5', label: '' },
//   { addr: 'E225.6', label: '' },
//   { addr: 'E225.7', label: '' }
// ]
// export const inputs8 = [
//   { addr: 'E300.0', label: '' },
//   { addr: 'E300.1', label: '' },
//   { addr: 'E300.2', label: '' },
//   { addr: 'E300.3', label: '' },
//   { addr: 'E300.4', label: '' },
//   { addr: 'E300.5', label: '' },
//   { addr: 'E300.6', label: '' },
//   { addr: 'E300.7', label: '' },
//   { addr: 'E301.0', label: '' },
//   { addr: 'E301.1', label: '' },
//   { addr: 'E301.2', label: '' },
//   { addr: 'E301.3', label: '' },
//   { addr: 'E301.4', label: '' },
//   { addr: 'E301.5', label: '' },
//   { addr: 'E301.6', label: '' },
//   { addr: 'E301.7', label: '' },
//   { addr: 'E302.0', label: '' },
//   { addr: 'E302.1', label: '' },
//   { addr: 'E302.2', label: '' },
//   { addr: 'E302.3', label: '' },
//   { addr: 'E302.4', label: '' },
//   { addr: 'E302.5', label: '' },
//   { addr: 'E302.6', label: '' },
//   { addr: 'E302.7', label: '' },
//   { addr: 'E303.0', label: '' },
//   { addr: 'E303.1', label: '' },
//   { addr: 'E303.2', label: '' },
//   { addr: 'E303.3', label: '' },
//   { addr: 'E303.4', label: '' },
//   { addr: 'E303.5', label: '' },
//   { addr: 'E303.6', label: '' },
//   { addr: 'E303.7', label: '' }
// ]
// export const inputs9 = [
//   { addr: 'E310.0', label: '' },
//   { addr: 'E310.1', label: '' },
//   { addr: 'E310.2', label: '' },
//   { addr: 'E310.3', label: '' },
//   { addr: 'E310.4', label: '' },
//   { addr: 'E310.5', label: '' },
//   { addr: 'E310.6', label: '' },
//   { addr: 'E310.7', label: '' },
//   { addr: 'E311.0', label: '' },
//   { addr: 'E311.1', label: '' },
//   { addr: 'E311.2', label: '' },
//   { addr: 'E311.3', label: '' },
//   { addr: 'E311.4', label: '' },
//   { addr: 'E311.5', label: '' },
//   { addr: 'E311.6', label: '' },
//   { addr: 'E311.7', label: '' },
//   { addr: 'E312.0', label: '' },
//   { addr: 'E312.1', label: '' },
//   { addr: 'E312.2', label: '' },
//   { addr: 'E312.3', label: '' },
//   { addr: 'E312.4', label: '' },
//   { addr: 'E312.5', label: '' },
//   { addr: 'E312.6', label: '' },
//   { addr: 'E312.7', label: '' },
//   { addr: 'E313.0', label: '' },
//   { addr: 'E313.1', label: '' },
//   { addr: 'E313.2', label: '' },
//   { addr: 'E313.3', label: '' },
//   { addr: 'E313.4', label: '' },
//   { addr: 'E313.5', label: '' },
//   { addr: 'E313.6', label: '' },
//   { addr: 'E313.7', label: '' },
//   { addr: 'E314.0', label: '' },
//   { addr: 'E314.1', label: '' },
//   { addr: 'E314.2', label: '' },
//   { addr: 'E314.3', label: '' },
//   { addr: 'E314.4', label: '' },
//   { addr: 'E314.5', label: '' },
//   { addr: 'E314.6', label: '' },
//   { addr: 'E314.7', label: '' },
//   { addr: 'E315.0', label: '' },
//   { addr: 'E315.1', label: '' },
//   { addr: 'E315.2', label: '' },
//   { addr: 'E315.3', label: '' },
//   { addr: 'E315.4', label: '' },
//   { addr: 'E315.5', label: '' },
//   { addr: 'E315.6', label: '' },
//   { addr: 'E315.7', label: '' }
// ]
// export const inputs10 = [
//   { addr: 'E320.0', label: '' },
//   { addr: 'E320.1', label: '' },
//   { addr: 'E320.2', label: '' },
//   { addr: 'E320.3', label: '' },
//   { addr: 'E320.4', label: '' },
//   { addr: 'E320.5', label: '' },
//   { addr: 'E320.6', label: '' },
//   { addr: 'E320.7', label: '' },
//   { addr: 'E321.0', label: '' },
//   { addr: 'E321.1', label: '' },
//   { addr: 'E321.2', label: '' },
//   { addr: 'E321.3', label: '' },
//   { addr: 'E321.4', label: '' },
//   { addr: 'E321.5', label: '' },
//   { addr: 'E321.6', label: '' },
//   { addr: 'E321.7', label: '' },
//   { addr: 'E322.0', label: '' },
//   { addr: 'E322.1', label: '' },
//   { addr: 'E322.2', label: '' },
//   { addr: 'E322.3', label: '' },
//   { addr: 'E322.4', label: '' },
//   { addr: 'E322.5', label: '' },
//   { addr: 'E322.6', label: '' },
//   { addr: 'E322.7', label: '' },
//   { addr: 'E323.0', label: '' },
//   { addr: 'E323.1', label: '' },
//   { addr: 'E323.2', label: '' },
//   { addr: 'E323.3', label: '' },
//   { addr: 'E323.4', label: '' },
//   { addr: 'E323.5', label: '' },
//   { addr: 'E323.6', label: '' },
//   { addr: 'E323.7', label: '' },
//   { addr: 'E324.0', label: '' },
//   { addr: 'E324.1', label: '' },
//   { addr: 'E324.2', label: '' },
//   { addr: 'E324.3', label: '' },
//   { addr: 'E324.4', label: '' },
//   { addr: 'E324.5', label: '' },
//   { addr: 'E324.6', label: '' },
//   { addr: 'E324.7', label: '' },
//   { addr: 'E325.0', label: '' },
//   { addr: 'E325.1', label: '' },
//   { addr: 'E325.2', label: '' },
//   { addr: 'E325.3', label: '' },
//   { addr: 'E325.4', label: '' },
//   { addr: 'E325.5', label: '' },
//   { addr: 'E325.6', label: '' },
//   { addr: 'E325.7', label: '' }
// ]
export const outputs1 = [
  { addr: 'A0.0', label: 'LC1' },
  { addr: 'A0.1', label: 'LC2' },
  { addr: 'A0.2', label: 'LC3' },
  { addr: 'A0.3', label: 'LC4' },
  { addr: 'A0.4', label: 'LC5' },
  { addr: 'A0.5', label: 'LC6' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'SBK1' },
  { addr: 'A101.1', label: 'SBK2' },
  { addr: 'A101.2', label: 'KBA1' },
  { addr: 'A101.3', label: 'KBA2' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: 'LA' },
  { addr: 'A101.7', label: 'LC' }
]
export const outputs3 = [
  { addr: 'A110.0', label: 'DYA' },
  { addr: 'A110.1', label: 'DYB' },
  { addr: 'A110.2', label: 'DYC' },
  { addr: 'A110.3', label: 'DYD' },
  { addr: 'A110.4', label: 'AD1' },
  { addr: 'A110.5', label: 'AD2' },
  { addr: 'A110.6', label: 'AD3' },
  { addr: 'A110.7', label: 'STR' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' },
  { addr: 'A112.0', label: 'TCR' },
  { addr: 'A112.1', label: 'T2' },
  { addr: 'A112.2', label: 'TRA' },
  { addr: 'A112.3', label: 'TRB' },
  { addr: 'A112.4', label: 'KCS' },
  { addr: 'A112.5', label: 'KCV' },
  { addr: 'A112.6', label: 'KCH' },
  { addr: 'A112.7', label: 'KBA2' },
  { addr: 'A113.0', label: 'KBA1' },
  { addr: 'A113.1', label: 'KPM1' },
  { addr: 'A113.2', label: 'T101' },
  { addr: 'A113.3', label: 'T102' },
  { addr: 'A113.4', label: 'TD' },
  { addr: 'A113.5', label: 'T10F' },
  { addr: 'A113.6', label: 'LA' },
  { addr: 'A113.7', label: 'LC' }
]
export const outputs4 = [
  { addr: 'A120.0', label: 'SPE' },
  { addr: 'A120.1', label: 'SMA' },
  { addr: 'A120.2', label: 'SMB' },
  { addr: 'A120.3', label: 'SCA' },
  { addr: 'A120.4', label: 'SCB' },
  { addr: 'A120.5', label: '' },
  { addr: 'A120.6', label: 'SZE' },
  { addr: 'A120.7', label: 'SOE' },
  { addr: 'A121.0', label: 'L1' },
  { addr: 'A121.1', label: 'L2' },
  { addr: 'A121.2', label: 'L3' },
  { addr: 'A121.3', label: 'L4' },
  { addr: 'A121.4', label: 'L5' },
  { addr: 'A121.5', label: 'RFE' },
  { addr: 'A121.6', label: 'RLN' },
  { addr: 'A121.7', label: 'RBE' },
  { addr: 'A122.0', label: 'LC2' },
  { addr: 'A122.1', label: 'LA1' },
  { addr: 'A122.2', label: 'LC1' },
  { addr: 'A122.3', label: '' },
  { addr: 'A122.4', label: '' },
  { addr: 'A122.5', label: '' },
  { addr: 'A122.6', label: '' },
  { addr: 'A122.7', label: '' },
  { addr: 'A123.0', label: '' },
  { addr: 'A123.1', label: '' },
  { addr: 'A123.2', label: '' },
  { addr: 'A123.3', label: '' },
  { addr: 'A123.4', label: '' },
  { addr: 'A123.5', label: '' },
  { addr: 'A123.6', label: '' },
  { addr: 'A123.7', label: '' }
]
// export const outputs5 = [
//   { addr: 'A200.0', label: '' },
//   { addr: 'A200.1', label: '' },
//   { addr: 'A200.2', label: '' },
//   { addr: 'A200.3', label: '' },
//   { addr: 'A200.4', label: '' },
//   { addr: 'A200.5', label: '' },
//   { addr: 'A200.6', label: '' },
//   { addr: 'A200.7', label: '' },
//   { addr: 'A201.0', label: '' },
//   { addr: 'A201.1', label: '' },
//   { addr: 'A201.2', label: '' },
//   { addr: 'A201.3', label: '' },
//   { addr: 'A201.4', label: '' },
//   { addr: 'A201.5', label: '' },
//   { addr: 'A201.6', label: '' },
//   { addr: 'A201.7', label: '' }
// ]
// export const outputs6 = [
//   { addr: 'A210.0', label: '' },
//   { addr: 'A210.1', label: '' },
//   { addr: 'A210.2', label: '' },
//   { addr: 'A210.3', label: '' },
//   { addr: 'A210.4', label: '' },
//   { addr: 'A210.5', label: '' },
//   { addr: 'A210.6', label: '' },
//   { addr: 'A210.7', label: '' },
//   { addr: 'A211.0', label: '' },
//   { addr: 'A211.1', label: '' },
//   { addr: 'A211.2', label: '' },
//   { addr: 'A211.3', label: '' },
//   { addr: 'A211.4', label: '' },
//   { addr: 'A211.5', label: '' },
//   { addr: 'A211.6', label: '' },
//   { addr: 'A211.7', label: '' },
//   { addr: 'A212.0', label: '' },
//   { addr: 'A212.1', label: '' },
//   { addr: 'A212.2', label: '' },
//   { addr: 'A212.3', label: '' },
//   { addr: 'A212.4', label: '' },
//   { addr: 'A212.5', label: '' },
//   { addr: 'A212.6', label: '' },
//   { addr: 'A212.7', label: '' },
//   { addr: 'A213.0', label: '' },
//   { addr: 'A213.1', label: '' },
//   { addr: 'A213.2', label: '' },
//   { addr: 'A213.3', label: '' },
//   { addr: 'A213.4', label: '' },
//   { addr: 'A213.5', label: '' },
//   { addr: 'A213.6', label: '' },
//   { addr: 'A213.7', label: '' }
// ]
// export const outputs7 = [
//   { addr: 'A220.0', label: '' },
//   { addr: 'A220.1', label: '' },
//   { addr: 'A220.2', label: '' },
//   { addr: 'A220.3', label: '' },
//   { addr: 'A220.4', label: '' },
//   { addr: 'A220.5', label: '' },
//   { addr: 'A220.6', label: '' },
//   { addr: 'A220.7', label: '' },
//   { addr: 'A221.0', label: '' },
//   { addr: 'A221.1', label: '' },
//   { addr: 'A221.2', label: '' },
//   { addr: 'A221.3', label: '' },
//   { addr: 'A221.4', label: '' },
//   { addr: 'A221.5', label: '' },
//   { addr: 'A221.6', label: '' },
//   { addr: 'A221.7', label: '' },
//   { addr: 'A222.0', label: '' },
//   { addr: 'A222.1', label: '' },
//   { addr: 'A222.2', label: '' },
//   { addr: 'A222.3', label: '' },
//   { addr: 'A222.4', label: '' },
//   { addr: 'A222.5', label: '' },
//   { addr: 'A222.6', label: '' },
//   { addr: 'A222.7', label: '' },
//   { addr: 'A223.0', label: '' },
//   { addr: 'A223.1', label: '' },
//   { addr: 'A223.2', label: '' },
//   { addr: 'A223.3', label: '' },
//   { addr: 'A223.4', label: '' },
//   { addr: 'A223.5', label: '' },
//   { addr: 'A223.6', label: '' },
//   { addr: 'A223.7', label: '' }
// ]
// export const outputs8 = [
//   { addr: 'A300.0', label: '' },
//   { addr: 'A300.1', label: '' },
//   { addr: 'A300.2', label: '' },
//   { addr: 'A300.3', label: '' },
//   { addr: 'A300.4', label: '' },
//   { addr: 'A300.5', label: '' },
//   { addr: 'A300.6', label: '' },
//   { addr: 'A300.7', label: '' },
//   { addr: 'A301.0', label: '' },
//   { addr: 'A301.1', label: '' },
//   { addr: 'A301.2', label: '' },
//   { addr: 'A301.3', label: '' },
//   { addr: 'A301.4', label: '' },
//   { addr: 'A301.5', label: '' },
//   { addr: 'A301.6', label: '' },
//   { addr: 'A301.7', label: '' }
// ]
// export const outputs9 = [
//   { addr: 'A310.0', label: '' },
//   { addr: 'A310.1', label: '' },
//   { addr: 'A310.2', label: '' },
//   { addr: 'A310.3', label: '' },
//   { addr: 'A310.4', label: '' },
//   { addr: 'A310.5', label: '' },
//   { addr: 'A310.6', label: '' },
//   { addr: 'A310.7', label: '' },
//   { addr: 'A311.0', label: '' },
//   { addr: 'A311.1', label: '' },
//   { addr: 'A311.2', label: '' },
//   { addr: 'A311.3', label: '' },
//   { addr: 'A311.4', label: '' },
//   { addr: 'A311.5', label: '' },
//   { addr: 'A311.6', label: '' },
//   { addr: 'A311.7', label: '' },
//   { addr: 'A312.0', label: '' },
//   { addr: 'A312.1', label: '' },
//   { addr: 'A312.2', label: '' },
//   { addr: 'A312.3', label: '' },
//   { addr: 'A312.4', label: '' },
//   { addr: 'A312.5', label: '' },
//   { addr: 'A312.6', label: '' },
//   { addr: 'A312.7', label: '' },
//   { addr: 'A313.0', label: '' },
//   { addr: 'A313.1', label: '' },
//   { addr: 'A313.2', label: '' },
//   { addr: 'A313.3', label: '' },
//   { addr: 'A313.4', label: '' },
//   { addr: 'A313.5', label: '' },
//   { addr: 'A313.6', label: '' },
//   { addr: 'A313.7', label: '' }
// ]
// export const outputs10 = [
//   { addr: 'A320.0', label: '' },
//   { addr: 'A320.1', label: '' },
//   { addr: 'A320.2', label: '' },
//   { addr: 'A320.3', label: '' },
//   { addr: 'A320.4', label: '' },
//   { addr: 'A320.5', label: '' },
//   { addr: 'A320.6', label: '' },
//   { addr: 'A320.7', label: '' },
//   { addr: 'A321.0', label: '' },
//   { addr: 'A321.1', label: '' },
//   { addr: 'A321.2', label: '' },
//   { addr: 'A321.3', label: '' },
//   { addr: 'A321.4', label: '' },
//   { addr: 'A321.5', label: '' },
//   { addr: 'A321.6', label: '' },
//   { addr: 'A321.7', label: '' },
//   { addr: 'A322.0', label: '' },
//   { addr: 'A322.1', label: '' },
//   { addr: 'A322.2', label: '' },
//   { addr: 'A322.3', label: '' },
//   { addr: 'A322.4', label: '' },
//   { addr: 'A322.5', label: '' },
//   { addr: 'A322.6', label: '' },
//   { addr: 'A322.7', label: '' },
//   { addr: 'A323.0', label: '' },
//   { addr: 'A323.1', label: '' },
//   { addr: 'A323.2', label: '' },
//   { addr: 'A323.3', label: '' },
//   { addr: 'A323.4', label: '' },
//   { addr: 'A323.5', label: '' },
//   { addr: 'A323.6', label: '' },
//   { addr: 'A323.7', label: '' }
// ]
export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-flap-to', query: {} },
  { id: 24, key: 'al-flap-fc', query: {} },
  { id: 25, key: 'al-sp-to', query: {} },
  { id: 26, key: 'al-sp-fc', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-th', query: { name: 'ASBK' } },
  { id: 51, key: 'al-iv', query: { nr: 1 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'AMM' } },
  { id: 54, key: 'al-th', query: { name: 'AMC' } },
  { id: 55, key: 'al-th', query: { name: 'ape' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: 'al-r-to', query: {} },
  { id: 91, key: 'al-enr', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE3' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-iv', query: { nr: 1 } },
  { id: 116, key: 'al-th', query: { name: 'ASBKD' } },
  { id: 117, key: 'al-th', query: { name: 'AD' } },
  { id: 118, key: 'al-th', query: { name: 'AH' } },
  { id: 119, key: 'al-th', query: { name: 'MTC' } },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'SH1' },
  { id: 5, key: 'SH2' },
  { id: 6, key: 'SH3' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
