// generate I/O
exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'SFT1' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: 'RS3' },
  { addr: 'E1.4', label: 'RS12' },
  { addr: 'E1.5', label: 'DB32' },
  { addr: 'E1.6', label: 'DBHZ' },
  { addr: 'E1.7', label: 'UC' },
  { addr: 'E2.0', label: 'SFT' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'FE12' },
  { addr: 'E3.0', label: 'IV1' },
  { addr: 'E3.1', label: 'IV2' },
  { addr: 'E3.2', label: 'RTA' },
  { addr: 'E3.3', label: 'AIV' },
  { addr: 'E3.4', label: 'AF8' },
  { addr: 'E3.5', label: 'AKKU' },
  { addr: 'E3.6', label: 'APE1' },
  { addr: 'E3.7', label: 'APE2' },
  { addr: 'E4.0', label: 'EZE-1' },
  { addr: 'E4.1', label: 'EOE-1' },
  { addr: 'E4.2', label: 'FBE-1' },
  { addr: 'E4.3', label: 'FPE-1' },
  { addr: 'E4.4', label: 'FDR1-1' },
  { addr: 'E4.5', label: 'FDL1-1' },
  { addr: 'E4.6', label: 'FDR2-1' },
  { addr: 'E4.7', label: 'FDL2-1' },
  { addr: 'E5.0', label: 'FLP1-1' },
  { addr: 'E5.1', label: 'FLP2' },
  { addr: 'E5.2', label: 'FLA-1' },
  { addr: 'E5.3', label: 'POD-1' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: 'EZE-2' },
  { addr: 'E6.1', label: 'EOE-2' },
  { addr: 'E6.2', label: 'FBE-2' },
  { addr: 'E6.3', label: 'FPE-2' },
  { addr: 'E6.4', label: 'FDR1-2' },
  { addr: 'E6.5', label: 'FDL1-2' },
  { addr: 'E6.6', label: 'FDR2-2' },
  { addr: 'E6.7', label: 'FDL2-2' },
  { addr: 'E7.0', label: 'FLP1-2' },
  { addr: 'E7.1', label: 'FLP2-2' },
  { addr: 'E7.2', label: 'FLA-2' },
  { addr: 'E7.3', label: 'POD-2' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: 'BA' },
  { addr: 'E8.1', label: 'BB' },
  { addr: 'E8.2', label: 'BC' },
  { addr: 'E8.3', label: 'BD' },
  { addr: 'E8.4', label: 'BSTR' },
  { addr: 'E8.5', label: 'BOK' },
  { addr: 'E8.6', label: 'BDAT' },
  { addr: 'E8.7', label: 'EXZE-1' },
  { addr: 'E9.0', label: 'BA' },
  { addr: 'E9.1', label: 'BB' },
  { addr: 'E9.2', label: 'BC' },
  { addr: 'E9.3', label: 'BD' },
  { addr: 'E9.4', label: 'BSTR' },
  { addr: 'E9.5', label: 'BOK' },
  { addr: 'E9.6', label: 'BDAT' },
  { addr: 'E9.7', label: 'EXZE-2' }
]
exports.inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'SFT1' },
  { addr: 'E11.1', label: 'EXD' },
  { addr: 'E11.2', label: 'EHP' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: 'UC' },
  { addr: 'E12.0', label: 'EOM1' },
  { addr: 'E12.1', label: 'EZM1' },
  { addr: 'E12.2', label: 'EOM2' },
  { addr: 'E12.3', label: 'EZM2' },
  { addr: 'E12.4', label: 'ECA' },
  { addr: 'E12.5', label: 'ECB' },
  { addr: 'E12.6', label: 'FRE1' },
  { addr: 'E12.7', label: 'FRE2' },
  { addr: 'E13.0', label: 'EM' },
  { addr: 'E13.1', label: 'FTXV' },
  { addr: 'E13.2', label: 'FTXH' },
  { addr: 'E13.3', label: 'FTA1' },
  { addr: 'E13.4', label: 'FTA2' },
  { addr: 'E13.5', label: 'RX1' },
  { addr: 'E13.6', label: 'RX2' },
  { addr: 'E13.7', label: 'KEXPV1' },
  { addr: 'E14.0', label: 'FE3' },
  { addr: 'E14.1', label: 'FSBK' },
  { addr: 'E14.2', label: 'ASBK1' },
  { addr: 'E14.3', label: 'ASBK2' },
  { addr: 'E14.4', label: 'AH' },
  { addr: 'E14.5', label: 'AD' },
  { addr: 'E14.6', label: 'FTCR' },
  { addr: 'E14.7', label: 'MTC' },
  { addr: 'E15.0', label: 'AMM1' },
  { addr: 'E15.1', label: 'AMM2' },
  { addr: 'E15.2', label: 'AMC' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: 'KEXPV2' },
  { addr: 'E16.0', label: 'RMV' },
  { addr: 'E16.1', label: 'RMH' },
  { addr: 'E16.2', label: 'RES' },
  { addr: 'E16.3', label: 'REH' },
  { addr: 'E16.4', label: 'RCV' },
  { addr: 'E16.5', label: 'REAV' },
  { addr: 'E16.6', label: 'REAH' },
  { addr: 'E16.7', label: 'RCH' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'STO1-1' },
  { addr: 'A1.1', label: 'STO1-2' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: 'LS' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'LC' },
  { addr: 'A2.0', label: 'L1' },
  { addr: 'A2.1', label: 'L2' },
  { addr: 'A2.2', label: 'L3' },
  { addr: 'A2.3', label: 'L4' },
  { addr: 'A2.4', label: 'L5' },
  { addr: 'A2.5', label: 'RFE' },
  { addr: 'A2.6', label: 'RLN' },
  { addr: 'A2.7', label: 'RBE' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: 'L1' },
  { addr: 'A4.1', label: 'L2' },
  { addr: 'A4.2', label: 'L3' },
  { addr: 'A4.3', label: 'L4' },
  { addr: 'A4.4', label: 'L5' },
  { addr: 'A4.5', label: 'RFE' },
  { addr: 'A4.6', label: 'RLN' },
  { addr: 'A4.7', label: 'RBE' },
  { addr: 'A5.0', label: 'LK' },
  { addr: 'A5.1', label: 'LE' },
  { addr: 'A5.2', label: 'LB' },
  { addr: 'A5.3', label: 'RDY' },
  { addr: 'A5.4', label: 'RST' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' },
  { addr: 'A6.0', label: 'STO2-1' },
  { addr: 'A6.1', label: 'STO2-2' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: 'TIV2' },
  { addr: 'A7.0', label: 'SPE-1' },
  { addr: 'A7.1', label: 'SZE-1' },
  { addr: 'A7.2', label: 'SOE-1' },
  { addr: 'A7.3', label: 'KXP-1' },
  { addr: 'A7.4', label: 'SPE-2' },
  { addr: 'A7.5', label: 'SZE-2' },
  { addr: 'A7.6', label: 'SOE-2' },
  { addr: 'A7.7', label: 'KXP-2' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: 'DYA' },
  { addr: 'A10.1', label: 'DYB' },
  { addr: 'A10.2', label: 'DYC' },
  { addr: 'A10.3', label: 'DYD' },
  { addr: 'A10.4', label: 'AD1' },
  { addr: 'A10.5', label: 'AD2' },
  { addr: 'A10.6', label: 'AD3' },
  { addr: 'A10.7', label: 'STR' },
  { addr: 'A11.0', label: 'T10' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: 'TD' },
  { addr: 'A11.3', label: 'TCR' },
  { addr: 'A11.4', label: 'SBK1' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: 'LA' },
  { addr: 'A11.7', label: 'LC' },
  { addr: 'A12.0', label: 'T2' },
  { addr: 'A12.1', label: 'TRA' },
  { addr: 'A12.2', label: 'TRB' },
  { addr: 'A12.3', label: 'KCS' },
  { addr: 'A12.4', label: 'KCV' },
  { addr: 'A12.5', label: 'KCH' },
  { addr: 'A12.6', label: 'SBK2' },
  { addr: 'A12.7', label: 'T10F' },
  { addr: 'A13.0', label: 'SMA1' },
  { addr: 'A13.1', label: 'SMB1' },
  { addr: 'A13.2', label: 'SMA2' },
  { addr: 'A13.3', label: 'SMB2' },
  { addr: 'A13.4', label: 'SCA' },
  { addr: 'A13.5', label: 'SCB' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' }
]
exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-h-to', query: {} },
  { id: 22, key: 'al-lh', query: {} },
  { id: 23, key: 'al-lh-diff', query: {} },
  { id: 24, key: 'al-r-to', query: {} },
  { id: 25, key: 'al-enr', query: {} },
  { id: 26, key: 'al-v-lck-to', query: {} },
  { id: 27, key: 'al-v-lck-fc', query: {} },
  { id: 28, key: 'al-v-lck-to', query: {} },
  { id: 29, key: 'al-v-lck-fc', query: {} },
  { id: 30, key: 'al-flap-to', query: {} },
  { id: 31, key: 'al-flap-fc', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-iv', query: { nr: 2 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'AIV' } },
  { id: 54, key: 'al-th', query: { name: 'AF8' } },
  { id: 55, key: 'al-th', query: { name: 'AKKU' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: 'al-sp-to', query: {} },
  { id: 97, key: 'al-sp-to', query: {} },
  { id: 98, key: 'al-sp-fc', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'APE' } },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'T' },
  { id: 2, key: 'EU1' },
  { id: 3, key: 'EU2' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
