exports.inputs1 = [
  { addr: 'E0.0', label: 'RSI' },
  { addr: 'E0.1', label: 'SA1' },
  { addr: 'E0.2', label: 'SA2' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'IV1' },
  { addr: 'E101.1', label: 'TJ1' },
  { addr: 'E101.2', label: 'TLK' },
  { addr: 'E101.3', label: 'RSI' },
  { addr: 'E101.4', label: 'SA' },
  { addr: 'E101.5', label: 'UC' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: '' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: 'FSBK' },
  { addr: 'E102.5', label: 'ASBK' },
  { addr: 'E102.6', label: 'RTA' },
  { addr: 'E102.7', label: 'AMC' },
  { addr: 'E103.0', label: 'EBZE' },
  { addr: 'E103.1', label: 'EBOE' },
  { addr: 'E103.2', label: 'FBBE' },
  { addr: 'E103.3', label: 'APBE' },
  { addr: 'E103.4', label: 'EZE' },
  { addr: 'E103.5', label: 'EOE' },
  { addr: 'E103.6', label: 'FBE' },
  { addr: 'E103.7', label: 'APE' },
  { addr: 'E104.0', label: 'EBZA' },
  { addr: 'E104.1', label: 'EBOA' },
  { addr: 'E104.2', label: 'FBBA' },
  { addr: 'E104.3', label: 'APBA' },
  { addr: 'E104.4', label: 'EZA' },
  { addr: 'E104.5', label: 'EOA' },
  { addr: 'E104.6', label: 'FBA' },
  { addr: 'E104.7', label: 'APA' },
  { addr: 'E105.0', label: 'FPE' },
  { addr: 'E105.1', label: 'FLP' },
  { addr: 'E105.2', label: 'FDR' },
  { addr: 'E105.3', label: 'FDL' },
  { addr: 'E105.4', label: 'FLA' },
  { addr: 'E105.5', label: 'FTA1' },
  { addr: 'E105.6', label: 'FTA2' },
  { addr: 'E105.7', label: 'RXE' },
  { addr: 'E106.0', label: 'FPA' },
  { addr: 'E106.1', label: 'RXA' },
  { addr: 'E106.2', label: 'FRSX' },
  { addr: 'E106.3', label: 'FRDX' },
  { addr: 'E106.4', label: '' },
  { addr: 'E106.5', label: '' },
  { addr: 'E106.6', label: '' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'ECA' },
  { addr: 'E107.1', label: 'ECB' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: 'EPZV' },
  { addr: 'E107.7', label: 'EPZH' },
  { addr: 'E108.0', label: '' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: '' },
  { addr: 'E108.3', label: '' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'AGK' },
  { addr: 'E110.1', label: 'TL' },
  { addr: 'E110.2', label: 'AMM' },
  { addr: 'E110.3', label: '' },
  { addr: 'E110.4', label: '' },
  { addr: 'E110.5', label: 'EOM' },
  { addr: 'E110.6', label: 'EZM' },
  { addr: 'E110.7', label: 'EMC' },
  { addr: 'E111.0', label: '' },
  { addr: 'E111.1', label: '' },
  { addr: 'E111.2', label: '' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E120.0', label: 'A' },
  { addr: 'E120.1', label: 'B' },
  { addr: 'E120.2', label: 'C' },
  { addr: 'E120.3', label: 'D' },
  { addr: 'E120.4', label: 'OK' },
  { addr: 'E120.5', label: 'S2' },
  { addr: 'E120.6', label: 'S2' },
  { addr: 'E120.7', label: 'S2' },
  { addr: 'E121.0', label: 'EM' },
  { addr: 'E121.1', label: 'FTXV' },
  { addr: 'E121.2', label: 'FTXH' },
  { addr: 'E121.3', label: 'FTAC' },
  { addr: 'E121.4', label: '' },
  { addr: 'E121.5', label: '' },
  { addr: 'E121.6', label: '' },
  { addr: 'E121.7', label: '' },
  { addr: 'E122.0', label: 'RMV' },
  { addr: 'E122.1', label: 'RMH' },
  { addr: 'E122.2', label: 'RES' },
  { addr: 'E122.3', label: 'REH' },
  { addr: 'E122.4', label: 'RCV' },
  { addr: 'E122.5', label: 'REAV' },
  { addr: 'E122.6', label: 'REAH' },
  { addr: 'E122.7', label: 'RCH' },
  { addr: 'E123.0', label: 'IV2' },
  { addr: 'E123.1', label: 'TJ2' },
  { addr: 'E123.2', label: 'SA' },
  { addr: 'E123.3', label: 'RSI' },
  { addr: 'E123.4', label: 'DB32' },
  { addr: 'E123.5', label: 'DBHZ' },
  { addr: 'E123.6', label: '' },
  { addr: 'E123.7', label: 'UC' },
  { addr: 'E124.0', label: 'AH' },
  { addr: 'E124.1', label: 'MTC' },
  { addr: 'E124.2', label: '' },
  { addr: 'E124.3', label: '' },
  { addr: 'E124.4', label: '' },
  { addr: 'E124.5', label: '' },
  { addr: 'E124.6', label: '' },
  { addr: 'E124.7', label: '' },
  { addr: 'E125.0', label: '' },
  { addr: 'E125.1', label: '' },
  { addr: 'E125.2', label: '' },
  { addr: 'E125.3', label: '' },
  { addr: 'E125.4', label: '' },
  { addr: 'E125.5', label: '' },
  { addr: 'E125.6', label: '' },
  { addr: 'E125.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'TRGU' },
  { addr: 'A0.1', label: 'TRG1' },
  { addr: 'A0.2', label: 'TRG2' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'SBK1' },
  { addr: 'A100.1', label: 'SBK2' },
  { addr: 'A100.2', label: '' },
  { addr: 'A100.3', label: '' },
  { addr: 'A100.4', label: 'KBA' },
  { addr: 'A100.5', label: 'KST' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'DYA' },
  { addr: 'A101.1', label: 'DYB' },
  { addr: 'A101.2', label: 'DYC' },
  { addr: 'A101.3', label: 'DYD' },
  { addr: 'A101.4', label: 'AD1' },
  { addr: 'A101.5', label: 'AD2' },
  { addr: 'A101.6', label: 'AD3' },
  { addr: 'A101.7', label: 'STR' },
  { addr: 'A102.0', label: 'SCA' },
  { addr: 'A102.1', label: 'SCB' },
  { addr: 'A102.2', label: 'SPE' },
  { addr: 'A102.3', label: 'SPBE' },
  { addr: 'A102.4', label: 'SPA' },
  { addr: 'A102.5', label: 'SPBA' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'RFA' },
  { addr: 'A103.1', label: 'RFE' },
  { addr: 'A103.2', label: 'L5' },
  { addr: 'A103.3', label: 'L4' },
  { addr: 'A103.4', label: 'L3' },
  { addr: 'A103.5', label: 'L2' },
  { addr: 'A103.6', label: 'L1' },
  { addr: 'A103.7', label: '' },
  { addr: 'A104.0', label: 'SBZE' },
  { addr: 'A104.1', label: 'SBOE' },
  { addr: 'A104.2', label: 'SZE' },
  { addr: 'A104.3', label: 'SOE' },
  { addr: 'A104.4', label: 'SBZA' },
  { addr: 'A104.5', label: 'SBOA' },
  { addr: 'A104.6', label: 'SZA' },
  { addr: 'A104.7', label: 'SOA' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'SMA' },
  { addr: 'A110.1', label: 'SMB' },
  { addr: 'A110.2', label: 'LA' },
  { addr: 'A110.3', label: '' },
  { addr: 'A110.4', label: '' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A120.0', label: 'DYA' },
  { addr: 'A120.1', label: 'DYB' },
  { addr: 'A120.2', label: 'DYC' },
  { addr: 'A120.3', label: 'DYD' },
  { addr: 'A120.4', label: 'AD1' },
  { addr: 'A120.5', label: 'AD2' },
  { addr: 'A120.6', label: 'AD3' },
  { addr: 'A120.7', label: 'STR' },
  { addr: 'A121.0', label: 'T101' },
  { addr: 'A121.1', label: 'T102' },
  { addr: 'A121.2', label: 'T2' },
  { addr: 'A121.3', label: 'T10F' },
  { addr: 'A121.4', label: 'TRA' },
  { addr: 'A121.5', label: 'TRB' },
  { addr: 'A121.6', label: 'LA' },
  { addr: 'A121.7', label: 'LC' },
  { addr: 'A122.0', label: 'KCS' },
  { addr: 'A122.1', label: 'KCV' },
  { addr: 'A122.2', label: 'KCH' },
  { addr: 'A122.3', label: 'KBA' },
  { addr: 'A122.4', label: 'KST' },
  { addr: 'A122.5', label: '' },
  { addr: 'A122.6', label: '' },
  { addr: 'A122.7', label: '' },
  { addr: 'A123.0', label: '' },
  { addr: 'A123.1', label: '' },
  { addr: 'A123.2', label: '' },
  { addr: 'A123.3', label: '' },
  { addr: 'A123.4', label: '' },
  { addr: 'A123.5', label: '' },
  { addr: 'A123.6', label: '' },
  { addr: 'A123.7', label: '' }
]

exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-01', query: {} },
  { id: 3, key: 'al-sil-01', query: {} },
  { id: 4, key: 'al-sil-02', query: {} },
  { id: 5, key: 'al-sil-03', query: {} },
  { id: 6, key: 'al-sil-04', query: {} },
  { id: 7, key: 'al-v-to', query: {} },
  { id: 8, key: 'al-h-to', query: {} },
  { id: 9, key: 'al-flap-to', query: {} },
  { id: 10, key: 'al-v-fdbk', query: {} },
  { id: 11, key: 'al-v-fdbk', query: {} },
  { id: 12, key: 'al-v-lck-to', query: {} },
  { id: 13, key: 'al-spbe-to', query: {} },
  { id: 14, key: 'al-spe-to', query: {} },
  { id: 15, key: 'al-spba-to', query: {} },
  { id: 16, key: 'al-spa-to', query: {} },
  { id: 17, key: 'al-th', query: { name: 'ASBK' } },
  { id: 18, key: 'al-th', query: { name: 'RTA' } },
  { id: 19, key: 'al-th', query: { name: 'AMC' } },
  { id: 20, key: 'al-th', query: { name: 'APBE' } },
  { id: 21, key: 'al-th', query: { name: 'APE' } },
  { id: 22, key: 'al-th', query: { name: 'APBA' } },
  { id: 23, key: 'al-th', query: { name: 'APA' } },
  { id: 24, key: 'al-th', query: { name: 'AGK' } },
  { id: 25, key: 'al-th', query: { name: 'AMM' } },
  { id: 26, key: 'al-tl', query: { name: 'TLK' } },
  { id: 27, key: 'al-tl', query: { name: 'TL' } },
  { id: 28, key: 'al-tl', query: { name: 'TJ1' } },
  { id: 29, key: 'al-tl', query: { name: 'TJ2' } },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-fc', query: { fc1: 'EOM', fc2: 'EZM' } },
  { id: 34, key: 'al-sil-07', query: {} },
  { id: 35, key: 'al-sil-10', query: {} },
  { id: 36, key: 'al-sil-13', query: {} },
  { id: 37, key: 'al-fc', query: { fc1: 'ECA', fc2: 'ECB' } },
  { id: 38, key: 'al-fc', query: { fc1: 'EBZE', fc2: 'EBOE' } },
  { id: 39, key: 'al-fc', query: { fc1: 'EZE', fc2: 'EOE' } },
  { id: 40, key: 'al-fc', query: { fc1: 'EBZA', fc2: 'EBOA' } },
  { id: 41, key: 'al-fc', query: { fc1: 'EZA', fc2: 'EOA' } },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-lv', query: {} },
  { id: 50, key: 'al-lv', query: {} },
  { id: 51, key: 'al-lh', query: {} },
  { id: 52, key: 'al-lh', query: {} },
  { id: 53, key: 'al-lv-diff', query: {} },
  { id: 54, key: 'al-lh-diff', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'E1' },
  { id: 4, key: 'U1' },
  { id: 5, key: 'E2' },
  { id: 6, key: 'U2' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
