exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'SFT1' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: 'RS3' },
  { addr: 'E1.4', label: 'RS12' },
  { addr: 'E1.5', label: 'DB32' },
  { addr: 'E1.6', label: 'DBHZ' },
  { addr: 'E1.7', label: 'UC' },
  { addr: 'E2.0', label: 'IV1' },
  { addr: 'E2.1', label: 'IV2' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'SFT' },
  { addr: 'E3.0', label: 'FE12' },
  { addr: 'E3.1', label: 'FSBK' },
  { addr: 'E3.2', label: 'ASBK1' },
  { addr: 'E3.3', label: 'ALSE' },
  { addr: 'E3.4', label: 'AIV2' },
  { addr: 'E3.5', label: 'AF8' },
  { addr: 'E3.6', label: 'AKKU' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'SFT1' },
  { addr: 'E5.1', label: 'EXD' },
  { addr: 'E5.2', label: 'EXPH' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'FE3' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: 'ASBK2' },
  { addr: 'E6.4', label: 'AH' },
  { addr: 'E6.5', label: 'AD' },
  { addr: 'E6.6', label: 'FTCR' },
  { addr: 'E6.7', label: 'MTC' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: 'EM' },
  { addr: 'E7.2', label: 'EXPV' },
  { addr: 'E7.3', label: 'FTM' },
  { addr: 'E7.4', label: 'FTXV' },
  { addr: 'E7.5', label: 'FTXH' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: 'RMV' },
  { addr: 'E8.1', label: 'RMH' },
  { addr: 'E8.2', label: 'RES' },
  { addr: 'E8.3', label: 'REH' },
  { addr: 'E8.4', label: 'RCV' },
  { addr: 'E8.5', label: 'REAV' },
  { addr: 'E8.6', label: 'REAH' },
  { addr: 'E8.7', label: 'RCH' }
]
exports.inputs2 = [
  { addr: 'E20.0', label: 'A' },
  { addr: 'E20.1', label: 'B' },
  { addr: 'E20.2', label: 'C' },
  { addr: 'E20.3', label: 'D' },
  { addr: 'E20.4', label: 'OK' },
  { addr: 'E20.5', label: 'S2' },
  { addr: 'E20.6', label: 'S2' },
  { addr: 'E20.7', label: 'S2' },
  { addr: 'E21.0', label: 'SFT1' },
  { addr: 'E21.1', label: '' },
  { addr: 'E21.2', label: '' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: 'RS12' },
  { addr: 'E21.5', label: '' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: 'UC' },
  { addr: 'E22.0', label: 'KEM1' },
  { addr: 'E22.1', label: 'RDY1' },
  { addr: 'E22.2', label: 'DF1' },
  { addr: 'E22.3', label: 'TF1' },
  { addr: 'E22.4', label: 'FRE1' },
  { addr: 'E22.5', label: '' },
  { addr: 'E22.6', label: '' },
  { addr: 'E22.7', label: '' },
  { addr: 'E23.0', label: 'KEM2' },
  { addr: 'E23.1', label: 'RDY2' },
  { addr: 'E23.2', label: 'DF2' },
  { addr: 'E23.3', label: 'TF2' },
  { addr: 'E23.4', label: 'FRE2' },
  { addr: 'E23.5', label: '' },
  { addr: 'E23.6', label: '' },
  { addr: 'E23.7', label: '' },
  { addr: 'E24.0', label: 'EZE-1' },
  { addr: 'E24.1', label: 'EOE-1' },
  { addr: 'E24.2', label: 'FBE-1' },
  { addr: 'E24.3', label: 'FPE-1' },
  { addr: 'E24.4', label: 'FDR1-1' },
  { addr: 'E24.5', label: 'FDL1-1' },
  { addr: 'E24.6', label: 'FTA1-1' },
  { addr: 'E24.7', label: 'FTA2-1' },
  { addr: 'E25.0', label: 'FLP1-1' },
  { addr: 'E25.1', label: 'FLP2-1' },
  { addr: 'E25.2', label: 'FLA1-1' },
  { addr: 'E25.3', label: 'FLA2-1' },
  { addr: 'E25.4', label: 'POD-1' },
  { addr: 'E25.5', label: 'RX1-1' },
  { addr: 'E25.6', label: 'RX2-1' },
  { addr: 'E25.7', label: '' },
  { addr: 'E26.0', label: 'EXZE-1' },
  { addr: 'E26.1', label: 'PCD-1' },
  { addr: 'E26.2', label: 'EBZE' },
  { addr: 'E26.3', label: 'EBOE' },
  { addr: 'E26.4', label: '' },
  { addr: 'E26.5', label: 'FDR2-1' },
  { addr: 'E26.6', label: 'FDL2-1' },
  { addr: 'E26.7', label: 'FTA3-1' },
  { addr: 'E27.0', label: '' },
  { addr: 'E27.1', label: '' },
  { addr: 'E27.2', label: 'EXBZE' },
  { addr: 'E27.3', label: 'EXPV-1' },
  { addr: 'E27.4', label: '' },
  { addr: 'E27.5', label: 'APE-1' },
  { addr: 'E27.6', label: 'APBE' },
  { addr: 'E27.7', label: 'FE12' },
  { addr: 'E28.0', label: 'EZE-2' },
  { addr: 'E28.1', label: 'EOE-2' },
  { addr: 'E28.2', label: 'FBE-2' },
  { addr: 'E28.3', label: 'FPE-2' },
  { addr: 'E28.4', label: 'FDR1-2' },
  { addr: 'E28.5', label: 'FDL1-2' },
  { addr: 'E28.6', label: 'FTA1-2' },
  { addr: 'E28.7', label: 'FTA2-2' },
  { addr: 'E29.0', label: 'FLP1-1' },
  { addr: 'E29.1', label: 'FLP2-2' },
  { addr: 'E29.2', label: 'FLA1-2' },
  { addr: 'E29.3', label: 'FLA2-2' },
  { addr: 'E29.4', label: 'POD-2' },
  { addr: 'E29.5', label: 'RX1-2' },
  { addr: 'E29.6', label: 'RX2-2' },
  { addr: 'E29.7', label: '' },
  { addr: 'E30.0', label: 'EXZE-2' },
  { addr: 'E30.1', label: 'PCD-2' },
  { addr: 'E30.2', label: '' },
  { addr: 'E30.3', label: '' },
  { addr: 'E30.4', label: '' },
  { addr: 'E30.5', label: 'FDR2-2' },
  { addr: 'E30.6', label: 'FDL2-2' },
  { addr: 'E30.7', label: 'FTA3-2' },
  { addr: 'E31.0', label: '' },
  { addr: 'E31.1', label: '' },
  { addr: 'E31.2', label: '' },
  { addr: 'E31.3', label: 'EXPV-2' },
  { addr: 'E31.4', label: '' },
  { addr: 'E31.5', label: 'APE-2' },
  { addr: 'E31.6', label: '' },
  { addr: 'E31.7', label: '' },
  { addr: 'E32.0', label: 'EFB1' },
  { addr: 'E32.1', label: 'FDR3-1' },
  { addr: 'E32.2', label: 'FDL3-1' },
  { addr: 'E32.3', label: 'FTA4-1' },
  { addr: 'E32.4', label: 'FTA5-1' },
  { addr: 'E32.5', label: '' },
  { addr: 'E32.6', label: '' },
  { addr: 'E32.7', label: '' },
  { addr: 'E33.0', label: 'EFB2' },
  { addr: 'E33.1', label: 'FDR3-2' },
  { addr: 'E33.2', label: 'FDL3-2' },
  { addr: 'E33.3', label: 'FDL3-2' },
  { addr: 'E33.4', label: 'FTA4-2' },
  { addr: 'E33.5', label: 'FTA5-2' },
  { addr: 'E33.6', label: '' },
  { addr: 'E33.7', label: '' },
  { addr: 'E34.0', label: 'BA' },
  { addr: 'E34.1', label: 'BB' },
  { addr: 'E34.2', label: 'BC' },
  { addr: 'E34.3', label: 'BD' },
  { addr: 'E34.4', label: 'BSTR' },
  { addr: 'E34.5', label: 'BOK' },
  { addr: 'E34.6', label: 'BDAT' },
  { addr: 'E34.7', label: '' },
  { addr: 'E35.0', label: 'BA' },
  { addr: 'E35.1', label: 'BB' },
  { addr: 'E35.2', label: 'BC' },
  { addr: 'E35.3', label: 'BD' },
  { addr: 'E35.4', label: 'BSTR' },
  { addr: 'E35.5', label: 'BOK' },
  { addr: 'E35.6', label: 'BDAT' },
  { addr: 'E35.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'STO1-1' },
  { addr: 'A1.1', label: 'STO1-2' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: 'SBK1' },
  { addr: 'A1.5', label: 'LSE' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'LC' },
  { addr: 'A2.0', label: 'STO2-1' },
  { addr: 'A2.1', label: 'STO2-2' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: 'KQA' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: 'TIV2' },
  { addr: 'A2.6', label: 'SBK2' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: 'DYA' },
  { addr: 'A4.1', label: 'DYB' },
  { addr: 'A4.2', label: 'DYC' },
  { addr: 'A4.3', label: 'DYD' },
  { addr: 'A4.4', label: 'AD1' },
  { addr: 'A4.5', label: 'AD2' },
  { addr: 'A4.6', label: 'AD3' },
  { addr: 'A4.7', label: 'STR' },
  { addr: 'A5.0', label: 'T101' },
  { addr: 'A5.1', label: 'T102' },
  { addr: 'A5.2', label: 'TD' },
  { addr: 'A5.3', label: 'TCR' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: 'LA' },
  { addr: 'A5.7', label: 'LC' },
  { addr: 'A6.0', label: 'T2' },
  { addr: 'A6.1', label: 'TRA' },
  { addr: 'A6.2', label: 'TRB' },
  { addr: 'A6.3', label: 'KCS' },
  { addr: 'A6.4', label: 'KCV' },
  { addr: 'A6.5', label: 'KCH' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: 'T10F' }
]
exports.outputs2 = [
  { addr: 'A20.0', label: 'A' },
  { addr: 'A20.1', label: 'B' },
  { addr: 'A20.2', label: 'C' },
  { addr: 'A20.3', label: 'D' },
  { addr: 'A20.4', label: 'AD1' },
  { addr: 'A20.5', label: 'AD2' },
  { addr: 'A20.6', label: 'AD3' },
  { addr: 'A20.7', label: 'STR' },
  { addr: 'A21.0', label: '' },
  { addr: 'A21.1', label: '' },
  { addr: 'A21.2', label: '' },
  { addr: 'A21.3', label: '' },
  { addr: 'A21.4', label: '' },
  { addr: 'A21.5', label: '' },
  { addr: 'A21.6', label: '' },
  { addr: 'A21.7', label: 'LC' },
  { addr: 'A22.0', label: 'L1' },
  { addr: 'A22.1', label: 'L2' },
  { addr: 'A22.2', label: 'L3' },
  { addr: 'A22.3', label: 'L4' },
  { addr: 'A22.4', label: 'L5' },
  { addr: 'A22.5', label: 'RFE-1' },
  { addr: 'A22.6', label: 'RLN-1' },
  { addr: 'A22.7', label: 'RBE-1' },
  { addr: 'A23.0', label: 'L1' },
  { addr: 'A23.1', label: 'L2' },
  { addr: 'A23.2', label: 'L3' },
  { addr: 'A23.3', label: 'L4' },
  { addr: 'A23.4', label: 'L5' },
  { addr: 'A23.5', label: 'RFE-2' },
  { addr: 'A23.6', label: 'RLN-2' },
  { addr: 'A23.7', label: 'RBE-2' },
  { addr: 'A24.0', label: 'SPE-1' },
  { addr: 'A24.1', label: 'SZE-1' },
  { addr: 'A24.2', label: 'SOE-1' },
  { addr: 'A24.3', label: 'KXPE-1' },
  { addr: 'A24.4', label: 'SBPE' },
  { addr: 'A24.5', label: 'SBZE' },
  { addr: 'A24.6', label: 'SBOE' },
  { addr: 'A24.7', label: 'KXBPE' },
  { addr: 'A25.0', label: 'SPE-2' },
  { addr: 'A25.1', label: 'SZE-2' },
  { addr: 'A25.2', label: 'SOE-2' },
  { addr: 'A25.3', label: 'KXPE-2' },
  { addr: 'A25.4', label: '' },
  { addr: 'A25.5', label: '' },
  { addr: 'A25.6', label: '' },
  { addr: 'A25.7', label: '' },
  { addr: 'A26.0', label: 'UP-1' },
  { addr: 'A26.1', label: 'DOWN-1' },
  { addr: 'A26.2', label: '' },
  { addr: 'A26.3', label: '' },
  { addr: 'A26.4', label: '' },
  { addr: 'A26.5', label: '' },
  { addr: 'A26.6', label: '' },
  { addr: 'A26.7', label: '' },
  { addr: 'A27.0', label: 'UP-2' },
  { addr: 'A27.1', label: 'DOWN-2' },
  { addr: 'A27.2', label: '' },
  { addr: 'A27.3', label: '' },
  { addr: 'A27.4', label: '' },
  { addr: 'A27.5', label: '' },
  { addr: 'A27.6', label: '' },
  { addr: 'A27.7', label: '' },
  { addr: 'A28.0', label: 'LK-1' },
  { addr: 'A28.1', label: 'LE-1' },
  { addr: 'A28.2', label: 'LB-1' },
  { addr: 'A28.3', label: 'RDY-1' },
  { addr: 'A28.4', label: 'RST-1' },
  { addr: 'A28.5', label: '' },
  { addr: 'A28.6', label: '' },
  { addr: 'A28.7', label: '' },
  { addr: 'A29.0', label: 'LK-2' },
  { addr: 'A29.1', label: 'LE-2' },
  { addr: 'A29.2', label: 'LB-2' },
  { addr: 'A29.3', label: 'RDY-2' },
  { addr: 'A29.4', label: 'RST-2' },
  { addr: 'A29.5', label: '' },
  { addr: 'A29.6', label: '' },
  { addr: 'A29.7', label: '' }
]
exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-h-to', query: {} },
  { id: 22, key: 'al-lh', query: {} },
  { id: 23, key: 'al-lh-diff', query: {} },
  { id: 24, key: 'al-r-to', query: {} },
  { id: 25, key: 'al-enr', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE1-2' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-iv', query: { nr: 2 } },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'AIV2' } },
  { id: 54, key: 'al-th', query: { name: 'AF8' } },
  { id: 55, key: 'al-th', query: { name: 'AKKU' } },
  { id: 56, key: 'al-th', query: { name: 'ALSE' } },
  { id: 57, key: 'al-th', query: { name: 'FE3' } },
  { id: 58, key: 'al-th', query: { name: 'AH1-2' } },
  { id: 59, key: 'al-th', query: { name: 'AD' } },
  { id: 60, key: 'al-th', query: { name: 'MTC' } },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-to', query: {} },
  { id: 83, key: 'al-th', query: { name: 'KEM' } },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-sp-to', query: {} },
  { id: 98, key: 'al-sp-to', query: {} },
  { id: 99, key: 'al-sp-fc', query: { name: '' } },
  { id: 100, key: 'al-spb-to', query: {} },
  { id: 101, key: 'al-spb-to', query: {} },
  { id: 102, key: 'al-spb-fc', query: { name: '' } },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'APE' } },
  { id: 114, key: 'al-th', query: { name: 'APBE' } },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'T' },
  { id: 2, key: 'EU1' },
  { id: 3, key: 'EU2' }
]
exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
