export const inputs1 = [
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'BA' },
  { addr: 'E5.1', label: 'BB' },
  { addr: 'E5.2', label: 'BC' },
  { addr: 'E5.3', label: 'BD' },
  { addr: 'E5.4', label: 'BSTR' },
  { addr: 'E5.5', label: 'BOK' },
  { addr: 'E5.6', label: 'BDAT' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'EOM1' },
  { addr: 'E6.1', label: 'EZM1' },
  { addr: 'E6.2', label: 'EOM2' },
  { addr: 'E6.3', label: 'EZM2' },
  { addr: 'E6.4', label: 'EOM3' },
  { addr: 'E6.5', label: 'EZM3' },
  { addr: 'E6.6', label: 'EOM4' },
  { addr: 'E6.7', label: 'EZM4' },
  { addr: 'E7.0', label: 'AMM' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: 'KBA' },
  { addr: 'E8.1', label: 'KXPE' },
  { addr: 'E8.2', label: 'SA' },
  { addr: 'E8.3', label: 'IV1' },
  { addr: 'E8.4', label: 'KEZE' },
  { addr: 'E8.5', label: 'IV2' },
  { addr: 'E8.6', label: 'RTA' },
  { addr: 'E8.7', label: '' },
  { addr: 'E9.0', label: 'FE1' },
  { addr: 'E9.1', label: 'APE' },
  { addr: 'E9.2', label: 'AF9' },
  { addr: 'E9.3', label: 'ASH' },
  { addr: 'E9.4', label: 'AIV' },
  { addr: 'E9.5', label: 'S1' },
  { addr: 'E9.6', label: 'S1' },
  { addr: 'E9.7', label: 'S1' },
  { addr: 'E10.0', label: 'EZE' },
  { addr: 'E10.1', label: 'EOE' },
  { addr: 'E10.2', label: 'FBE' },
  { addr: 'E10.3', label: 'FPE' },
  { addr: 'E10.4', label: 'FDR1' },
  { addr: 'E10.5', label: 'FDL1' },
  { addr: 'E10.6', label: 'FTA1' },
  { addr: 'E10.7', label: 'FTA2' },
  { addr: 'E11.0', label: 'FLP' },
  { addr: 'E11.1', label: 'FLA' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: 'POD' },
  { addr: 'E11.5', label: 'RX' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: 'FAL' },
  { addr: 'E12.0', label: 'BA' },
  { addr: 'E12.1', label: 'BB' },
  { addr: 'E12.2', label: 'BC' },
  { addr: 'E12.3', label: 'BD' },
  { addr: 'E12.4', label: 'BSTR' },
  { addr: 'E12.5', label: 'BOK' },
  { addr: 'E12.6', label: 'BDAT' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: 'BA' },
  { addr: 'E13.1', label: 'BB' },
  { addr: 'E13.2', label: 'BC' },
  { addr: 'E13.3', label: 'BD' },
  { addr: 'E13.4', label: 'BSTR' },
  { addr: 'E13.5', label: 'BOK' },
  { addr: 'E13.6', label: 'BDAT' },
  { addr: 'E13.7', label: '' }
]
export const inputs2 = [
  { addr: 'E14.0', label: 'RMV' },
  { addr: 'E14.1', label: 'RMH' },
  { addr: 'E14.2', label: 'RES' },
  { addr: 'E14.3', label: 'REH' },
  { addr: 'E14.4', label: 'RCV' },
  { addr: 'E14.5', label: 'REAV' },
  { addr: 'E14.6', label: 'REAH' },
  { addr: 'E14.7', label: 'RCH' },
  { addr: 'E15.0', label: 'ASBK' },
  { addr: 'E15.1', label: 'FSBK' },
  { addr: 'E15.2', label: 'MTC' },
  { addr: 'E15.3', label: 'ACR' },
  { addr: 'E15.4', label: 'ASDK' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: 'F24' },
  { addr: 'E15.7', label: 'TCR' },
  { addr: 'E16.0', label: 'FTXV' },
  { addr: 'E16.1', label: 'FTXH' },
  { addr: 'E16.2', label: 'EPZ' },
  { addr: 'E16.3', label: 'EM' },
  { addr: 'E16.4', label: 'ECA' },
  { addr: 'E16.5', label: 'ECB' },
  { addr: 'E16.6', label: 'AMC' },
  { addr: 'E16.7', label: 'AD' },
  { addr: 'E17.0', label: 'EXD' },
  { addr: 'E17.1', label: 'EMC' },
  { addr: 'E17.2', label: 'KEXPV' },
  { addr: 'E17.3', label: 'EXPV' },
  { addr: 'E17.4', label: 'AKKS' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: 'MNR' },
  { addr: 'E17.7', label: 'MNL' }
]
export const outputs1 = [
  { addr: 'A4.0', label: 'KBA1' },
  { addr: 'A4.1', label: 'BLE' },
  { addr: 'A4.2', label: 'BLB' },
  { addr: 'A4.3', label: 'BRDY' },
  { addr: 'A4.4', label: 'BRST' },
  { addr: 'A4.5', label: 'KXPE' },
  { addr: 'A4.6', label: 'LA' },
  { addr: 'A4.7', label: 'LC' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'RBE' },
  { addr: 'A6.0', label: 'DYA' },
  { addr: 'A6.1', label: 'DYB' },
  { addr: 'A6.2', label: 'DYC' },
  { addr: 'A6.3', label: 'DYD' },
  { addr: 'A6.4', label: 'AD1' },
  { addr: 'A6.5', label: 'AD2' },
  { addr: 'A6.6', label: 'AD3' },
  { addr: 'A6.7', label: 'STR' },
  { addr: 'A7.0', label: 'BLK' },
  { addr: 'A7.1', label: 'BLE' },
  { addr: 'A7.2', label: 'BLB' },
  { addr: 'A7.3', label: 'BRDY' },
  { addr: 'A7.4', label: 'BRST' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: 'TLIV' },
  { addr: 'A7.7', label: 'KEM' },
  { addr: 'A8.0', label: 'SMA1' },
  { addr: 'A8.1', label: 'SMB1' },
  { addr: 'A8.2', label: 'SMA2' },
  { addr: 'A8.3', label: 'SMB2' },
  { addr: 'A8.4', label: 'SMA3' },
  { addr: 'A8.5', label: 'SMB3' },
  { addr: 'A8.6', label: 'SMA4' },
  { addr: 'A8.7', label: 'SMB4' },
  { addr: 'A9.0', label: 'BLK' },
  { addr: 'A9.1', label: 'BLE' },
  { addr: 'A9.2', label: 'BLB' },
  { addr: 'A9.3', label: 'BRDY' },
  { addr: 'A9.4', label: 'BRST' },
  { addr: 'A9.5', label: 'KBA2' },
  { addr: 'A9.6', label: '' },
  { addr: 'A9.7', label: '' }
]
export const outputs2 = [
  { addr: 'A14.0', label: 'TD' },
  { addr: 'A14.1', label: 'TCR' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: '' },
  { addr: 'A14.4', label: 'KCS' },
  { addr: 'A14.5', label: 'KCV' },
  { addr: 'A14.6', label: 'KCH' },
  { addr: 'A14.7', label: 'SBK2' },
  { addr: 'A15.0', label: 'T10' },
  { addr: 'A15.1', label: 'T2' },
  { addr: 'A15.2', label: 'TRA' },
  { addr: 'A15.3', label: 'TRB' },
  { addr: 'A15.4', label: 'TCR' },
  { addr: 'A15.5', label: 'SCA' },
  { addr: 'A15.6', label: 'SCB' },
  { addr: 'A15.7', label: 'SBK1' }
]
export const ALARMS = [
  { id: 1, key: 'al-v-to', query: {} },
  { id: 2, key: 'al-h-to', query: {} },
  { id: 3, key: 'al-sil-01', query: {} },
  { id: 4, key: 'al-sil-01', query: {} },
  { id: 5, key: 'al-sil-02', query: {} },
  { id: 6, key: 'al-sil-03', query: {} },
  { id: 7, key: 'al-sil-04', query: {} },
  { id: 8, key: 'al-r-to', query: {} },
  { id: 9, key: 'al-flap-to', query: {} },
  { id: 10, key: 'al-v-lck-to', query: {} },
  { id: 11, key: 'al-v-lck-to', query: {} },
  { id: 12, key: 'al-v-lck-to', query: {} },
  { id: 13, key: 'al-v-lck-to', query: {} },
  { id: 14, key: 'al-sp-to', query: {} },
  { id: 15, key: 'al-sp-to', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: 'al-th', query: { name: 'AMM' } },
  { id: 18, key: 'al-th', query: { name: 'RTA' } },
  { id: 19, key: 'al-th', query: { name: 'FE1' } },
  { id: 20, key: 'al-th', query: { name: 'APE' } },
  { id: 21, key: 'al-th', query: { name: 'AF9' } },
  { id: 22, key: 'al-th', query: { name: 'ASH' } },
  { id: 23, key: 'al-th', query: { name: 'AIV' } },
  { id: 24, key: 'al-th', query: { name: 'ASBK1' } },
  { id: 25, key: 'al-th', query: { name: 'MTC' } },
  { id: 26, key: 'al-th', query: { name: 'ACR' } },
  { id: 27, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 28, key: 'al-th', query: { name: 'F24' } },
  { id: 29, key: 'al-th', query: { name: 'AMC' } },
  { id: 30, key: 'al-th', query: { name: 'AD' } },
  { id: 31, key: 'al-th', query: { name: 'AKKS' } },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-v-lck-fc', query: {} },
  { id: 34, key: 'al-sp-fc', query: {} },
  { id: 35, key: 'al-flap-fc', query: {} },
  { id: 36, key: 'al-sil-11', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
