// generate I/O
export const inputs1 = [
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'BA' },
  { addr: 'E5.1', label: 'BB' },
  { addr: 'E5.2', label: 'BC' },
  { addr: 'E5.3', label: 'BD' },
  { addr: 'E5.4', label: 'BSTR' },
  { addr: 'E5.5', label: 'BOK' },
  { addr: 'E5.6', label: 'BDAT' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'APE' },
  { addr: 'E6.1', label: 'KXPE' },
  { addr: 'E6.2', label: 'KEZE' },
  { addr: 'E6.3', label: 'AF8' },
  { addr: 'E6.4', label: 'AF9' },
  { addr: 'E6.5', label: 'S1' },
  { addr: 'E6.6', label: 'S1' },
  { addr: 'E6.7', label: 'S1' },
  { addr: 'E7.0', label: 'IV1' },
  { addr: 'E7.1', label: 'KBA1' },
  { addr: 'E7.2', label: 'AGF' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: 'FE1' },
  { addr: 'E7.7', label: 'FE2' },
  { addr: 'E8.0', label: 'EXV1L' },
  { addr: 'E8.1', label: 'EXV2L' },
  { addr: 'E8.2', label: 'MNAL' },
  { addr: 'E8.3', label: 'MNBL' },
  { addr: 'E8.4', label: '' },
  { addr: 'E8.5', label: 'MNRL' },
  { addr: 'E8.6', label: 'MNLL' },
  { addr: 'E8.7', label: 'FTXL' },
  { addr: 'E9.0', label: 'EZML' },
  { addr: 'E9.1', label: 'EOML' },
  { addr: 'E9.2', label: 'AMML' },
  { addr: 'E9.3', label: 'ASKM' },
  { addr: 'E9.4', label: 'SQL' },
  { addr: 'E9.5', label: 'ASBKL' },
  { addr: 'E9.6', label: 'IVL' },
  { addr: 'E9.7', label: 'FBKL' },
  { addr: 'E10.0', label: 'EZE' },
  { addr: 'E10.1', label: 'EOE' },
  { addr: 'E10.2', label: 'FBE' },
  { addr: 'E10.3', label: 'FPE' },
  { addr: 'E10.4', label: 'FDR' },
  { addr: 'E10.5', label: 'FDL' },
  { addr: 'E10.6', label: 'FLA' },
  { addr: 'E10.7', label: 'FTA' },
  { addr: 'E11.0', label: 'FLP' },
  { addr: 'E11.1', label: 'EZP' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: 'S3' },
  { addr: 'E11.5', label: 'TCL' },
  { addr: 'E11.6', label: 'POD' },
  { addr: 'E11.7', label: 'RX' },
  { addr: 'E12.0', label: 'EXV1R' },
  { addr: 'E12.1', label: 'EXV2R' },
  { addr: 'E12.2', label: 'MNAR' },
  { addr: 'E12.3', label: 'MNBR' },
  { addr: 'E12.4', label: 'FPR' },
  { addr: 'E12.5', label: 'MNRR' },
  { addr: 'E12.6', label: 'MNLR' },
  { addr: 'E12.7', label: 'FTXR' },
  { addr: 'E13.0', label: 'EZMR' },
  { addr: 'E13.1', label: 'EOMR' },
  { addr: 'E13.2', label: 'AMMR' },
  { addr: 'E13.3', label: 'FTXVR' },
  { addr: 'E13.4', label: 'FTXVL' },
  { addr: 'E13.5', label: 'ASBKR' },
  { addr: 'E13.6', label: 'IVR' },
  { addr: 'E13.7', label: 'FBKR' },
  { addr: 'E14.0', label: 'FTL1' },
  { addr: 'E14.1', label: 'FTR1' },
  { addr: 'E14.2', label: 'FTL2' },
  { addr: 'E14.3', label: 'FTR2' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: 'SQR' },
  { addr: 'E15.1', label: 'AR' },
  { addr: 'E15.2', label: 'AL' },
  { addr: 'E15.3', label: 'AF12' },
  { addr: 'E15.4', label: 'A1LR' },
  { addr: 'E15.5', label: 'T1P' },
  { addr: 'E15.6', label: 'A2LR' },
  { addr: 'E15.7', label: 'T2P' }
]
export const inputs2 = [
  { addr: 'E28.0', label: 'A' },
  { addr: 'E28.1', label: 'B' },
  { addr: 'E28.2', label: 'C' },
  { addr: 'E28.3', label: 'D' },
  { addr: 'E28.4', label: 'OK' },
  { addr: 'E28.5', label: 'S2' },
  { addr: 'E28.6', label: 'S2' },
  { addr: 'E28.7', label: 'S2' },
  { addr: 'E29.0', label: 'AMM1' },
  { addr: 'E29.1', label: 'EOM1' },
  { addr: 'E29.2', label: 'EZM1' },
  { addr: 'E29.3', label: 'AMM2' },
  { addr: 'E29.4', label: 'EOM2' },
  { addr: 'E29.5', label: 'EZM2' },
  { addr: 'E29.6', label: 'KEXPV' },
  { addr: 'E29.7', label: 'UC' },
  { addr: 'E30.0', label: 'RMV' },
  { addr: 'E30.1', label: 'RMH' },
  { addr: 'E30.2', label: 'RES' },
  { addr: 'E30.3', label: 'REH' },
  { addr: 'E30.4', label: 'RCV' },
  { addr: 'E30.5', label: 'REAV' },
  { addr: 'E30.6', label: 'REAH' },
  { addr: 'E30.7', label: 'RCH' },
  { addr: 'E31.0', label: 'MNA' },
  { addr: 'E31.1', label: 'MNB' },
  { addr: 'E31.2', label: 'EXPV' },
  { addr: 'E31.3', label: 'EFB' },
  { addr: 'E31.4', label: 'ASBK' },
  { addr: 'E31.5', label: 'FSBK' },
  { addr: 'E31.6', label: '' },
  { addr: 'E31.7', label: '' }
]
export const inputs3 = [
  { addr: 'E32.0', label: 'FEMV' },
  { addr: 'E32.1', label: 'FEMH' },
  { addr: 'E32.2', label: 'EPZV' },
  { addr: 'E32.3', label: 'EPZH' },
  { addr: 'E32.4', label: 'ACR' },
  { addr: 'E32.5', label: 'TCR' },
  { addr: 'E32.6', label: '' },
  { addr: 'E32.7', label: '' }
]
export const outputs1 = [
  { addr: 'A4.0', label: '' },
  { addr: 'A4.1', label: '' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: 'SBK1L' },
  { addr: 'A4.5', label: 'SBK1R' },
  { addr: 'A4.6', label: 'SZE' },
  { addr: 'A4.7', label: 'SOE' },
  { addr: 'A5.0', label: 'LK' },
  { addr: 'A5.1', label: 'LE' },
  { addr: 'A5.2', label: 'LB' },
  { addr: 'A5.3', label: 'RDY' },
  { addr: 'A5.4', label: 'RST' },
  { addr: 'A5.5', label: 'KSR' },
  { addr: 'A5.6', label: 'LCR' },
  { addr: 'A5.7', label: 'LCL' },
  { addr: 'A6.0', label: 'T2' },
  { addr: 'A6.1', label: '' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: '' },
  { addr: 'A7.0', label: 'L1' },
  { addr: 'A7.1', label: 'L2' },
  { addr: 'A7.2', label: 'L3' },
  { addr: 'A7.3', label: 'L4' },
  { addr: 'A7.4', label: 'L5' },
  { addr: 'A7.5', label: 'RFE' },
  { addr: 'A7.6', label: 'RLN' },
  { addr: 'A7.7', label: 'RBE' },
  { addr: 'A8.0', label: 'KQR' },
  { addr: 'A8.1', label: 'KQL' },
  { addr: 'A8.2', label: 'TL' },
  { addr: 'A8.3', label: 'TR' },
  { addr: 'A8.4', label: 'KBA1' },
  { addr: 'A8.5', label: '' },
  { addr: 'A8.6', label: 'LA' },
  { addr: 'A8.7', label: 'LC' },
  { addr: 'A9.0', label: 'DYA' },
  { addr: 'A9.1', label: 'DYB' },
  { addr: 'A9.2', label: 'DYC' },
  { addr: 'A9.3', label: 'DYD' },
  { addr: 'A9.4', label: 'AD1' },
  { addr: 'A9.5', label: 'AD2' },
  { addr: 'A9.6', label: 'AD3' },
  { addr: 'A9.7', label: 'STR' },
  { addr: 'A10.0', label: 'SMAL' },
  { addr: 'A10.1', label: 'SMBL' },
  { addr: 'A10.2', label: 'SBK2R' },
  { addr: 'A10.3', label: 'KBAR' },
  { addr: 'A10.4', label: 'SBK2L' },
  { addr: 'A10.5', label: 'KBAL' },
  { addr: 'A10.6', label: 'KXPE' },
  { addr: 'A10.7', label: 'KEM' },
  { addr: 'A11.0', label: 'T1P' },
  { addr: 'A11.1', label: 'T1R' },
  { addr: 'A11.2', label: 'T1L' },
  { addr: 'A11.3', label: 'T2P' },
  { addr: 'A11.4', label: 'T2R' },
  { addr: 'A11.5', label: 'T2L' },
  { addr: 'A11.6', label: 'SMAR' },
  { addr: 'A11.7', label: 'SMBL' }
]
export const outputs2 = [
  { addr: 'A28.0', label: 'TCR' },
  { addr: 'A28.1', label: 'T2' },
  { addr: 'A28.2', label: 'TRA' },
  { addr: 'A28.3', label: 'TRB' },
  { addr: 'A28.4', label: 'KCS' },
  { addr: 'A28.5', label: 'KCV' },
  { addr: 'A28.6', label: 'KCH' },
  { addr: 'A28.7', label: 'SBK1' },
  { addr: 'A29.0', label: 'SMA1' },
  { addr: 'A29.1', label: 'SMB1' },
  { addr: 'A29.2', label: 'SMA2' },
  { addr: 'A29.3', label: 'SMB2' },
  { addr: 'A29.4', label: 'SBK2' },
  { addr: 'A29.5', label: '' },
  { addr: 'A29.6', label: 'LA' },
  { addr: 'A29.7', label: 'LC' }
]
export const outputs3 = [
  { addr: 'A32.0', label: 'DYA' },
  { addr: 'A32.1', label: 'DYB' },
  { addr: 'A32.2', label: 'DYC' },
  { addr: 'A32.3', label: 'DYD' },
  { addr: 'A32.4', label: 'AD1' },
  { addr: 'A32.5', label: 'AD2' },
  { addr: 'A32.6', label: 'AD3' },
  { addr: 'A32.7', label: 'STR' }
]
export const ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'EL(L)' },
  { id: 3, key: 'EL(R)' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
