// CPU
export const inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: 'K12' },
  { addr: 'E1.7', label: 'FE' },
  { addr: 'E2.0', label: 'SFL1' },
  { addr: 'E2.1', label: 'SFL2' },
  { addr: 'E2.2', label: 'SFL3' },
  { addr: 'E2.3', label: 'SFL4' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: 'SFS1' },
  { addr: 'E3.1', label: 'SFS2' },
  { addr: 'E3.2', label: 'SFS3' },
  { addr: 'E3.3', label: 'SFS4' },
  { addr: 'E3.4', label: 'SFS5' },
  { addr: 'E3.5', label: 'SFS6' },
  { addr: 'E3.6', label: 'SFS7' },
  { addr: 'E3.7', label: '' }
]
// VT
export const inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: '' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: 'RS3' },
  { addr: 'E101.4', label: 'RS12' },
  { addr: 'E101.5', label: 'DB32' },
  { addr: 'E101.6', label: 'DBHZ' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'IV1' },
  { addr: 'E102.1', label: 'IV2' },
  { addr: 'E102.2', label: 'RTA' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: 'FSBK' },
  { addr: 'E102.7', label: 'ASBK' },
  { addr: 'E103.0', label: 'AMM1' },
  { addr: 'E103.1', label: 'AMM2' },
  { addr: 'E103.2', label: 'AMC' },
  { addr: 'E103.3', label: 'AMD' },
  { addr: 'E103.4', label: 'AMH' },
  { addr: 'E103.5', label: 'ASBK3' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: 'FE12' },
  { addr: 'E104.0', label: 'EOM1' },
  { addr: 'E104.1', label: 'EZM1' },
  { addr: 'E104.2', label: 'EOM2' },
  { addr: 'E104.3', label: 'EZM2' },
  { addr: 'E104.4', label: 'ECA' },
  { addr: 'E104.5', label: 'ECB' },
  { addr: 'E104.6', label: 'FRE1' },
  { addr: 'E104.7', label: 'FRE2' },
  { addr: 'E105.0', label: 'FTC' },
  { addr: 'E105.1', label: 'EXD' },
  { addr: 'E105.2', label: 'FTXV' },
  { addr: 'E105.3', label: 'FTXH' },
  { addr: 'E105.4', label: 'EOMD' },
  { addr: 'E105.5', label: 'EZMD' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: 'KEXPV1' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA1' },
  { addr: 'E107.3', label: 'FLA2' },
  { addr: 'E107.4', label: 'POD' },
  { addr: 'E107.5', label: 'RX1' },
  { addr: 'E107.6', label: 'RX2' },
  { addr: 'E107.7', label: '' },
  { addr: 'E108.0', label: 'EXZE' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: 'EBZE' },
  { addr: 'E108.3', label: 'EBOE' },
  { addr: 'E108.4', label: 'FBBE' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: 'FTA3' },
  { addr: 'E109.0', label: 'FLP3' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: 'KEXPV2' },
  { addr: 'E110.0', label: 'EZA' },
  { addr: 'E110.1', label: 'EOA' },
  { addr: 'E110.2', label: 'FBA' },
  { addr: 'E110.3', label: '' },
  { addr: 'E110.4', label: '' },
  { addr: 'E110.5', label: '' },
  { addr: 'E110.6', label: '' },
  { addr: 'E110.7', label: '' },
  { addr: 'E111.0', label: 'APE' },
  { addr: 'E111.1', label: 'APBE' },
  { addr: 'E111.2', label: 'APA' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: 'SF1' },
  { addr: 'E111.5', label: 'SF2' },
  { addr: 'E111.6', label: 'SF3' },
  { addr: 'E111.7', label: 'SF4' },
  { addr: 'E112.0', label: 'FTX' },
  { addr: 'E112.1', label: 'FIRR' },
  { addr: 'E112.2', label: 'FIRL' },
  { addr: 'E112.3', label: 'EOMH' },
  { addr: 'E112.4', label: 'EZMH' },
  { addr: 'E112.5', label: 'EXH' },
  { addr: 'E112.6', label: 'FCR1' },
  { addr: 'E112.7', label: 'FCL1' },
  { addr: 'E113.0', label: 'FCR2' },
  { addr: 'E113.1', label: 'FCL2' },
  { addr: 'E113.2', label: 'FCR3' },
  { addr: 'E113.3', label: 'FCL3' },
  { addr: 'E113.4', label: '' },
  { addr: 'E113.5', label: '' },
  { addr: 'E113.6', label: '' },
  { addr: 'E113.7', label: '' }
]
// SH
export const inputs3 = [
  { addr: 'E1000.0', label: 'A' },
  { addr: 'E1000.1', label: 'B' },
  { addr: 'E1000.2', label: 'C' },
  { addr: 'E1000.3', label: 'D' },
  { addr: 'E1000.4', label: 'OK' },
  { addr: 'E1000.5', label: 'S2' },
  { addr: 'E1000.6', label: 'S2' },
  { addr: 'E1000.7', label: 'S2' },
  { addr: 'E1001.0', label: 'SFS' },
  { addr: 'E1001.1', label: '' },
  { addr: 'E1001.2', label: '' },
  { addr: 'E1001.3', label: 'RS3' },
  { addr: 'E1001.4', label: 'RS12' },
  { addr: 'E1001.5', label: 'DB32' },
  { addr: 'E1001.6', label: 'DBHZ' },
  { addr: 'E1001.7', label: 'UC' },
  { addr: 'E1002.0', label: '' },
  { addr: 'E1002.1', label: 'EM' },
  { addr: 'E1002.2', label: 'EXPH' },
  { addr: 'E1002.3', label: 'FTAC' },
  { addr: 'E1002.4', label: 'FTXV' },
  { addr: 'E1002.5', label: 'FTXH' },
  { addr: 'E1002.6', label: 'FTMV' },
  { addr: 'E1002.7', label: 'FTMH' },
  { addr: 'E1003.0', label: 'IV1' },
  { addr: 'E1003.1', label: '' },
  { addr: 'E1003.2', label: 'AF7' },
  { addr: 'E1003.3', label: '' },
  { addr: 'E1003.4', label: '' },
  { addr: 'E1003.5', label: '' },
  { addr: 'E1003.6', label: '' },
  { addr: 'E1003.7', label: '' },
  { addr: 'E1004.0', label: 'FE5' },
  { addr: 'E1004.1', label: '' },
  { addr: 'E1004.2', label: '' },
  { addr: 'E1004.3', label: '' },
  { addr: 'E1004.4', label: 'AH12' },
  { addr: 'E1004.5', label: '' },
  { addr: 'E1004.6', label: 'FTCR' },
  { addr: 'E1004.7', label: 'MTC' },
  { addr: 'E1005.0', label: 'RMV' },
  { addr: 'E1005.1', label: 'RMH' },
  { addr: 'E1005.2', label: 'RES' },
  { addr: 'E1005.3', label: 'REH' },
  { addr: 'E1005.4', label: 'RCV' },
  { addr: 'E1005.5', label: 'REAV' },
  { addr: 'E1005.6', label: 'REAH' },
  { addr: 'E1005.7', label: 'RCH' }
]
// CPU
export const outputs1 = [
  { addr: 'A0.0', label: 'LSE' },
  { addr: 'A0.1', label: 'LSL1' },
  { addr: 'A0.2', label: 'LSL1' },
  { addr: 'A0.3', label: 'LSL1' },
  { addr: 'A0.4', label: 'LSL1' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: 'RBE1' },
  { addr: 'A1.1', label: 'RBE2' },
  { addr: 'A1.2', label: 'RBE3' },
  { addr: 'A1.3', label: 'RBE4' },
  { addr: 'A1.4', label: 'RBU1' },
  { addr: 'A1.5', label: 'RBU2' },
  { addr: 'A1.6', label: 'LAL' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: 'LS1' },
  { addr: 'A2.1', label: 'LS2' },
  { addr: 'A2.2', label: 'LS3' },
  { addr: 'A2.3', label: 'LS4' },
  { addr: 'A2.4', label: 'LS5' },
  { addr: 'A2.5', label: 'LS6' },
  { addr: 'A2.6', label: 'LS7' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: 'A' },
  { addr: 'A100.1', label: 'B' },
  { addr: 'A100.2', label: 'C' },
  { addr: 'A100.3', label: 'D' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'STO1-1' },
  { addr: 'A101.1', label: 'STO1-2' },
  { addr: 'A101.2', label: 'TDF' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: 'LA' },
  { addr: 'A101.7', label: 'LC' },
  { addr: 'A102.0', label: 'L1' },
  { addr: 'A102.1', label: 'L2' },
  { addr: 'A102.2', label: 'L3' },
  { addr: 'A102.3', label: 'L4' },
  { addr: 'A102.4', label: 'L5' },
  { addr: 'A102.5', label: 'RFE' },
  { addr: 'A102.6', label: 'RLN' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'SMA1' },
  { addr: 'A103.1', label: 'SMB1' },
  { addr: 'A103.2', label: 'SMA2' },
  { addr: 'A103.3', label: 'SMB2' },
  { addr: 'A103.4', label: 'SCA' },
  { addr: 'A103.5', label: 'SCB' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: 'SBK2' },
  { addr: 'A104.0', label: 'STO2-1' },
  { addr: 'A104.1', label: 'STO2-2' },
  { addr: 'A104.2', label: '' },
  { addr: 'A104.3', label: '' },
  { addr: 'A104.4', label: '' },
  { addr: 'A104.5', label: '' },
  { addr: 'A104.6', label: '' },
  { addr: 'A104.7', label: 'SBK1' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: 'SPE' },
  { addr: 'A106.1', label: 'SZE' },
  { addr: 'A106.2', label: 'SOE' },
  { addr: 'A106.3', label: 'KXPE' },
  { addr: 'A106.4', label: 'SBPE' },
  { addr: 'A106.5', label: 'SBZE' },
  { addr: 'A106.6', label: 'SBOE' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: 'SPA' },
  { addr: 'A107.1', label: 'SZA' },
  { addr: 'A107.2', label: 'SOA' },
  { addr: 'A107.3', label: 'KXPA' },
  { addr: 'A107.4', label: 'SMAD' },
  { addr: 'A107.5', label: 'SMBD' },
  { addr: 'A107.6', label: 'SMAH' },
  { addr: 'A107.7', label: 'SMBH' }
]
export const outputs3 = [
  { addr: 'A1000.0', label: 'A' },
  { addr: 'A1000.1', label: 'B' },
  { addr: 'A1000.2', label: 'C' },
  { addr: 'A1000.3', label: 'D' },
  { addr: 'A1000.4', label: 'AD1' },
  { addr: 'A1000.5', label: 'AD2' },
  { addr: 'A1000.6', label: 'AD3' },
  { addr: 'A1000.7', label: 'STR' },
  { addr: 'A1001.0', label: 'T101' },
  { addr: 'A1001.1', label: 'T102' },
  { addr: 'A1001.2', label: '' },
  { addr: 'A1001.3', label: 'TCR' },
  { addr: 'A1001.4', label: 'STO1-1' },
  { addr: 'A1001.5', label: '' },
  { addr: 'A1001.6', label: 'LA' },
  { addr: 'A1001.7', label: 'LC' },
  { addr: 'A1002.0', label: 'T2' },
  { addr: 'A1002.1', label: 'TRA' },
  { addr: 'A1002.2', label: 'TRB' },
  { addr: 'A1002.3', label: 'KCS' },
  { addr: 'A1002.4', label: 'KCV' },
  { addr: 'A1002.5', label: 'KCH' },
  { addr: 'A1002.6', label: '' },
  { addr: 'A1002.7', label: 'T10F' },
  { addr: 'A1003.0', label: 'STO2-1' },
  { addr: 'A1003.1', label: '' },
  { addr: 'A1003.2', label: '' },
  { addr: 'A1003.3', label: '' },
  { addr: 'A1003.4', label: '' },
  { addr: 'A1003.5', label: '' },
  { addr: 'A1003.6', label: '' },
  { addr: 'A1003.7', label: '' }
]
export const ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-v-lck-to', query: {} },
  { id: 24, key: 'al-v-lck-fc', query: {} },
  { id: 25, key: 'al-r-to', query: {} },
  { id: 26, key: 'al-enr', query: {} },
  { id: 27, key: 'al-r-to', query: {} },
  { id: 28, key: 'al-r-fc', query: {} },
  { id: 29, key: 'al-r-to', query: {} },
  { id: 30, key: 'al-r-fc', query: {} },
  { id: 31, key: 'al-flap-to', query: {} },
  { id: 32, key: 'al-flap-fc', query: {} },
  { id: 33, key: 'al-sp-to', query: {} },
  { id: 34, key: 'al-sp-to', query: {} },
  { id: 35, key: 'al-sp-fc', query: {} },
  { id: 36, key: 'al-spb-to', query: {} },
  { id: 37, key: 'al-spb-to', query: {} },
  { id: 38, key: 'al-spb-fc', query: {} },
  { id: 39, key: 'al-sp-to', query: {} },
  { id: 40, key: 'al-sp-to', query: {} },
  { id: 41, key: 'al-sp-fc', query: {} },
  { id: 42, key: 'al-pn', query: { name: 'IM' } },
  { id: 43, key: 'al-pn', query: { name: 'IV1' } },
  { id: 44, key: 'al-pn', query: { name: 'IV2' } },
  { id: 45, key: 'al-pn', query: { name: 'LV1' } },
  { id: 46, key: 'al-pn', query: { name: 'LV2' } },
  { id: 47, key: 'al-pn', query: { name: 'ENR' } },
  { id: 48, key: 'al-pn', query: { name: 'RFID' } },
  { id: 49, key: 'al-th', query: { name: 'FE12' } },
  { id: 50, key: 'al-th', query: { name: 'IV1' } },
  { id: 51, key: 'al-th', query: { name: 'IV2' } },
  { id: 52, key: 'al-th', query: { name: 'ASBK1' } },
  { id: 53, key: 'al-th', query: { name: 'ASBK3' } },
  { id: 54, key: 'al-th', query: { name: 'RTA' } },
  { id: 55, key: 'al-th', query: { name: 'AMM1' } },
  { id: 56, key: 'al-th', query: { name: 'AMM2' } },
  { id: 57, key: 'al-th', query: { name: 'AMD' } },
  { id: 58, key: 'al-th', query: { name: 'AMH' } },
  { id: 59, key: 'al-th', query: { name: 'AMC' } },
  { id: 60, key: 'al-th', query: { name: 'APE' } },
  { id: 61, key: 'al-th', query: { name: 'APBE' } },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: 'al-h-to', query: {} },
  { id: 86, key: 'al-lh', query: {} },
  { id: 87, key: 'al-lh-diff', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: 'al-pn', query: { name: 'IM' } },
  { id: 107, key: 'al-pn', query: { name: 'IV1' } },
  { id: 108, key: '', query: {} },
  { id: 109, key: 'al-pn', query: { name: 'LH1' } },
  { id: 110, key: 'al-pn', query: { name: 'LH2' } },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE5' } },
  { id: 114, key: 'al-th', query: { name: 'IV1' } },
  { id: 115, key: '', query: {} },
  { id: 116, key: 'al-th', query: { name: 'AF7' } },
  { id: 117, key: '', query: {} },
  { id: 118, key: 'al-th', query: { name: 'AH12' } },
  { id: 119, key: '', query: {} },
  { id: 120, key: 'al-th', query: { name: 'MTC' } },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'VT1' },
  { id: 2, key: 'VT2' },
  { id: 3, key: 'VT3' },
  { id: 4, key: 'VT4' },
  { id: 5, key: 'SH1' },
  { id: 5, key: 'SH2' },
  { id: 5, key: 'SH3' },
  { id: 5, key: 'SH4' },
  { id: 5, key: 'SH5' },
  { id: 5, key: 'SH6' },
  { id: 5, key: 'SH7' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
