export const inputs1 = [
  { addr: 'E0.0', label: 'A', info: 'A' },
  { addr: 'E0.1', label: 'B', info: 'B' },
  { addr: 'E0.2', label: 'C', info: 'C' },
  { addr: 'E0.3', label: 'D', info: 'D' },
  { addr: 'E0.4', label: 'OK', info: 'OK' },
  { addr: 'E0.5', label: 'S2', info: 'S2' },
  { addr: 'E0.6', label: 'S2', info: 'S2' },
  { addr: 'E0.7', label: 'S2', info: 'S2' },
  { addr: 'E1.0', label: 'IV1', info: 'IV1' },
  { addr: 'E1.1', label: 'TJ1', info: 'TJ1' },
  { addr: 'E1.2', label: 'TLK', info: 'TLK' },
  { addr: 'E1.3', label: 'RSI', info: '' },
  { addr: 'E1.4', label: 'SA', info: 'Man / Aut' },
  { addr: 'E1.5', label: 'UC', info: '' },
  { addr: 'E1.6', label: 'FE1', info: '' },
  { addr: 'E1.7', label: '', info: '' },
  { addr: 'E2.0', label: 'ECA', info: '' },
  { addr: 'E2.1', label: 'ECB', info: '' },
  { addr: 'E2.2', label: 'AMC', info: '' },
  { addr: 'E2.3', label: '', info: '' },
  { addr: 'E2.4', label: 'FDBK', info: '' },
  { addr: 'E2.5', label: 'ASBK', info: '' },
  { addr: 'E2.6', label: 'RTA', info: '' },
  { addr: 'E2.7', label: '', info: '' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: '', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' },
  { addr: 'E4.0', label: 'EBZE', info: '' },
  { addr: 'E4.1', label: 'EBOE', info: '' },
  { addr: 'E4.2', label: 'FBBE', info: '' },
  { addr: 'E4.3', label: 'APBE', info: '' },
  { addr: 'E4.4', label: 'EZE', info: '' },
  { addr: 'E4.5', label: 'EOE', info: '' },
  { addr: 'E4.6', label: 'FBE', info: '' },
  { addr: 'E4.7', label: 'APE', info: '' },
  { addr: 'E5.0', label: 'EBZA', info: '' },
  { addr: 'E5.1', label: 'EBOA', info: '' },
  { addr: 'E5.2', label: 'FBBA', info: '' },
  { addr: 'E5.3', label: 'APBA', info: '' },
  { addr: 'E5.4', label: 'EZA', info: '' },
  { addr: 'E5.5', label: 'EOA', info: '' },
  { addr: 'E5.6', label: 'FBA', info: '' },
  { addr: 'E5.7', label: 'APA', info: '' },
  { addr: 'E6.0', label: 'FPE', info: '' },
  { addr: 'E6.1', label: 'FLP', info: '' },
  { addr: 'E6.2', label: 'FDR', info: '' },
  { addr: 'E6.3', label: 'FDL', info: '' },
  { addr: 'E6.4', label: 'FLA', info: '' },
  { addr: 'E6.5', label: 'FTA1', info: '' },
  { addr: 'E6.6', label: 'FTA2', info: '' },
  { addr: 'E6.7', label: 'RXE', info: '' },
  { addr: 'E7.0', label: 'FPA', info: '' },
  { addr: 'E7.1', label: 'RXA', info: '' },
  { addr: 'E7.2', label: 'FTA2', info: '' },
  { addr: 'E7.3', label: '', info: '' },
  { addr: 'E7.4', label: '', info: '' },
  { addr: 'E7.5', label: '', info: '' },
  { addr: 'E7.6', label: 'EPZV', info: '' },
  { addr: 'E7.7', label: 'EPZH', info: '' }
]
export const inputs2 = [
  { addr: 'E8.0', label: 'AGK', info: '' },
  { addr: 'E8.1', label: 'TL', info: '' },
  { addr: 'E8.2', label: 'AMM', info: '' },
  { addr: 'E8.3', label: 'AS2', info: '' },
  { addr: 'E8.4', label: 'EOM', info: '' },
  { addr: 'E8.5', label: 'EZM', info: '' },
  { addr: 'E8.6', label: 'EMC', info: '' },
  { addr: 'E8.7', label: 'FE1', info: '' },
  { addr: 'E9.0', label: '', info: '' },
  { addr: 'E9.1', label: '', info: '' },
  { addr: 'E9.2', label: '', info: '' },
  { addr: 'E9.3', label: '', info: '' },
  { addr: 'E9.4', label: '', info: '' },
  { addr: 'E9.5', label: '', info: '' },
  { addr: 'E9.6', label: '', info: '' },
  { addr: 'E9.7', label: '', info: '' }
]
export const inputs3 = [
  { addr: 'E10.0', label: 'A', info: '' },
  { addr: 'E10.1', label: 'B', info: '' },
  { addr: 'E10.2', label: 'C', info: '' },
  { addr: 'E10.3', label: 'D', info: '' },
  { addr: 'E10.4', label: 'OK', info: '' },
  { addr: 'E10.5', label: 'S2', info: '' },
  { addr: 'E10.6', label: 'S2', info: '' },
  { addr: 'E10.7', label: 'S2', info: '' },
  { addr: 'E11.0', label: 'EM', info: '' },
  { addr: 'E11.1', label: 'FTXV', info: '' },
  { addr: 'E11.2', label: 'FTXH', info: '' },
  { addr: 'E11.3', label: '', info: '' },
  { addr: 'E11.4', label: 'FTAC', info: '' },
  { addr: 'E11.5', label: '', info: '' },
  { addr: 'E11.6', label: '', info: '' },
  { addr: 'E11.7', label: '', info: '' },
  { addr: 'E12.0', label: 'RMV', info: '' },
  { addr: 'E12.1', label: 'RMH', info: '' },
  { addr: 'E12.2', label: 'RES', info: '' },
  { addr: 'E12.3', label: 'REH', info: '' },
  { addr: 'E12.4', label: 'RCV', info: '' },
  { addr: 'E12.5', label: 'REAV', info: '' },
  { addr: 'E12.6', label: 'REAH', info: '' },
  { addr: 'E12.7', label: 'RCH', info: '' },
  { addr: 'E13.0', label: 'IV2', info: '' },
  { addr: 'E13.1', label: 'TJ2', info: '' },
  { addr: 'E13.2', label: 'SRL', info: 'Remote / Local' },
  { addr: 'E13.3', label: 'RSI', info: '' },
  { addr: 'E13.4', label: 'DB32', info: '' },
  { addr: 'E13.5', label: 'DBHZ', info: '' },
  { addr: 'E13.6', label: '', info: '' },
  { addr: 'E13.7', label: 'UC', info: '' },
  { addr: 'E14.0', label: 'AH', info: '' },
  { addr: 'E14.1', label: 'MTC', info: '' },
  { addr: 'E14.2', label: 'FE1', info: '' },
  { addr: 'E14.3', label: '', info: '' },
  { addr: 'E14.4', label: '', info: '' },
  { addr: 'E14.5', label: '', info: '' },
  { addr: 'E14.6', label: '', info: '' },
  { addr: 'E14.7', label: '', info: '' },
  { addr: 'E15.0', label: '', info: '' },
  { addr: 'E15.1', label: '', info: '' },
  { addr: 'E15.2', label: '', info: '' },
  { addr: 'E15.3', label: '', info: '' },
  { addr: 'E15.4', label: '', info: '' },
  { addr: 'E15.5', label: '', info: '' },
  { addr: 'E15.6', label: '', info: '' },
  { addr: 'E15.7', label: '', info: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'SBK1', info: '' },
  { addr: 'A0.1', label: 'SBK2', info: '' },
  { addr: 'A0.2', label: '', info: '' },
  { addr: 'A0.3', label: '', info: '' },
  { addr: 'A0.4', label: 'KBA1', info: '' },
  { addr: 'A0.5', label: '', info: '' },
  { addr: 'A0.6', label: 'LA', info: '' },
  { addr: 'A0.7', label: 'LC', info: '' },
  { addr: 'A1.0', label: 'DYA', info: '' },
  { addr: 'A1.1', label: 'DYB', info: '' },
  { addr: 'A1.2', label: 'DYC', info: '' },
  { addr: 'A1.3', label: 'DYD', info: '' },
  { addr: 'A1.4', label: 'AD1', info: '' },
  { addr: 'A1.5', label: 'AD2', info: '' },
  { addr: 'A1.6', label: 'AD3', info: '' },
  { addr: 'A1.7', label: 'STR', info: '' },
  { addr: 'A2.0', label: 'SCA', info: '' },
  { addr: 'A2.1', label: 'SCB', info: '' },
  { addr: 'A2.2', label: 'SPBE', info: '' },
  { addr: 'A2.3', label: 'SPE', info: '' },
  { addr: 'A2.4', label: 'SPBA', info: '' },
  { addr: 'A2.5', label: 'SPA', info: '' },
  { addr: 'A2.6', label: '', info: '' },
  { addr: 'A2.7', label: '', info: '' },
  { addr: 'A3.0', label: 'L1', info: '' },
  { addr: 'A3.1', label: 'L2', info: '' },
  { addr: 'A3.2', label: 'L3', info: '' },
  { addr: 'A3.3', label: 'L4', info: '' },
  { addr: 'A3.4', label: 'L5', info: '' },
  { addr: 'A3.5', label: 'RFE', info: '' },
  { addr: 'A3.6', label: 'RFA', info: '' },
  { addr: 'A3.7', label: 'RLN', info: '' },
  { addr: 'A4.0', label: 'SBZE', info: '' },
  { addr: 'A4.1', label: 'SBOE', info: '' },
  { addr: 'A4.2', label: 'SZE', info: '' },
  { addr: 'A4.3', label: 'SOE', info: '' },
  { addr: 'A4.4', label: 'SBZA', info: '' },
  { addr: 'A4.5', label: 'SBOA', info: '' },
  { addr: 'A4.6', label: 'SZA', info: '' },
  { addr: 'A4.7', label: 'SOA', info: '' },
  { addr: 'A5.0', label: '', info: '' },
  { addr: 'A5.1', label: '', info: '' },
  { addr: 'A5.2', label: '', info: '' },
  { addr: 'A5.3', label: '', info: '' },
  { addr: 'A5.4', label: '', info: '' },
  { addr: 'A5.5', label: '', info: '' },
  { addr: 'A5.6', label: '', info: '' },
  { addr: 'A5.7', label: '', info: '' }
]
export const outputs2 = [
  { addr: 'A6.0', label: 'SMA', info: '' },
  { addr: 'A6.1', label: 'SMB', info: '' },
  { addr: 'A6.2', label: 'LA', info: '' },
  { addr: 'A6.3', label: '', info: '' },
  { addr: 'A6.4', label: '', info: '' },
  { addr: 'A6.5', label: '', info: '' },
  { addr: 'A6.6', label: '', info: '' },
  { addr: 'A6.7', label: '', info: '' },
  { addr: 'A7.0', label: '', info: '' },
  { addr: 'A7.1', label: '', info: '' },
  { addr: 'A7.2', label: '', info: '' },
  { addr: 'A7.3', label: '', info: '' },
  { addr: 'A7.4', label: '', info: '' },
  { addr: 'A7.5', label: '', info: '' },
  { addr: 'A7.6', label: '', info: '' },
  { addr: 'A7.7', label: '', info: '' }
]
export const outputs3 = [
  { addr: 'A8.0', label: 'DYA', info: '' },
  { addr: 'A8.1', label: 'DYB', info: '' },
  { addr: 'A8.2', label: 'DYC', info: '' },
  { addr: 'A8.3', label: 'DYD', info: '' },
  { addr: 'A8.4', label: 'AD1', info: '' },
  { addr: 'A8.5', label: 'AD2', info: '' },
  { addr: 'A8.6', label: 'AD3', info: '' },
  { addr: 'A8.7', label: 'STR', info: '' },
  { addr: 'A9.0', label: 'T101', info: '' },
  { addr: 'A9.1', label: 'T102', info: '' },
  { addr: 'A9.2', label: 'TRA', info: '' },
  { addr: 'A9.3', label: 'TRB', info: '' },
  { addr: 'A9.4', label: 'KCS', info: '' },
  { addr: 'A9.5', label: 'KCV', info: '' },
  { addr: 'A9.6', label: 'KCH', info: '' },
  { addr: 'A9.7', label: 'LA', info: '' },
  { addr: 'A10.0', label: 'T2', info: '' },
  { addr: 'A10.1', label: 'T10F', info: '' },
  { addr: 'A10.2', label: 'LC', info: '' },
  { addr: 'A10.3', label: 'KBA2', info: '' },
  { addr: 'A10.4', label: '', info: '' },
  { addr: 'A10.5', label: '', info: '' },
  { addr: 'A10.6', label: '', info: '' },
  { addr: 'A10.7', label: '', info: '' },
  { addr: 'A11.0', label: '', info: '' },
  { addr: 'A11.1', label: '', info: '' },
  { addr: 'A11.2', label: '', info: '' },
  { addr: 'A11.3', label: '', info: '' },
  { addr: 'A11.4', label: '', info: '' },
  { addr: 'A11.5', label: '', info: '' },
  { addr: 'A11.6', label: '', info: '' },
  { addr: 'A11.7', label: '', info: '' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-h-to', query: {} },
  { id: 23, key: 'al-lh', query: {} },
  { id: 24, key: 'al-flap-to', query: {} },
  { id: 25, key: 'al-flap-fc', query: {} },
  { id: 26, key: 'al-spe-to', query: {} },
  { id: 27, key: 'al-spe-fc', query: {} },
  { id: 28, key: 'al-spa-to', query: {} },
  { id: 29, key: 'al-spa-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-iv', query: { nr: 1 } },
  { id: 50, key: 'al-th', query: { name: 'TLK' } },
  { id: 51, key: 'al-th', query: { name: 'FE1' } },
  { id: 52, key: 'al-th', query: { name: 'AMC' } },
  { id: 53, key: 'al-th', query: { name: 'ASBK' } },
  { id: 54, key: 'al-th', query: { name: 'RT' } },
  { id: 55, key: 'al-th', query: { name: 'APBE' } },
  { id: 56, key: 'al-th', query: { name: 'APE' } },
  { id: 57, key: 'al-th', query: { name: 'APBA' } },
  { id: 58, key: 'al-th', query: { name: 'APA' } },
  { id: 59, key: 'al-th', query: { name: 'AGK' } },
  { id: 60, key: 'al-th', query: { name: 'TL' } },
  { id: 61, key: 'al-th', query: { name: 'AMM' } },
  { id: 62, key: 'al-th', query: { name: 'AH' } },
  { id: 63, key: 'al-th', query: { name: 'MTC' } },
  { id: 64, key: 'al-th', query: { name: 'FE2' } }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
