export const inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: '' },
  { addr: 'E100.1', label: '' },
  { addr: 'E100.2', label: '' },
  { addr: 'E100.3', label: '' },
  { addr: 'E100.4', label: '' },
  { addr: 'E100.5', label: '' },
  { addr: 'E100.6', label: '' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: '' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: '' },
  { addr: 'E101.4', label: '' },
  { addr: 'E101.5', label: '' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: '' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: '' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: '' },
  { addr: 'E103.5', label: '' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: '' },
  { addr: 'E104.1', label: '' },
  { addr: 'E104.2', label: '' },
  { addr: 'E104.3', label: '' },
  { addr: 'E104.4', label: '' },
  { addr: 'E104.5', label: '' },
  { addr: 'E104.6', label: '' },
  { addr: 'E104.7', label: '' },
  { addr: 'E105.0', label: '' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: '' },
  { addr: 'E105.3', label: '' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: '' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: '' },
  { addr: 'E106.1', label: '' },
  { addr: 'E106.2', label: '' },
  { addr: 'E106.3', label: '' },
  { addr: 'E106.4', label: '' },
  { addr: 'E106.5', label: '' },
  { addr: 'E106.6', label: '' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: '' },
  { addr: 'E107.1', label: '' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' }
]
export const inputs3 = [
  { addr: 'E500.0', label: '' },
  { addr: 'E500.1', label: '' },
  { addr: 'E500.2', label: '' },
  { addr: 'E500.3', label: '' },
  { addr: 'E500.4', label: '' },
  { addr: 'E500.5', label: '' },
  { addr: 'E500.6', label: '' },
  { addr: 'E500.7', label: '' },
  { addr: 'E501.0', label: '' },
  { addr: 'E501.1', label: '' },
  { addr: 'E501.2', label: '' },
  { addr: 'E501.3', label: '' },
  { addr: 'E501.4', label: '' },
  { addr: 'E501.5', label: '' },
  { addr: 'E501.6', label: '' },
  { addr: 'E501.7', label: '' },
  { addr: 'E502.0', label: '' },
  { addr: 'E502.1', label: '' },
  { addr: 'E502.2', label: '' },
  { addr: 'E502.3', label: '' },
  { addr: 'E502.4', label: '' },
  { addr: 'E502.5', label: '' },
  { addr: 'E502.6', label: '' },
  { addr: 'E502.7', label: '' },
  { addr: 'E503.0', label: '' },
  { addr: 'E503.1', label: '' },
  { addr: 'E503.2', label: '' },
  { addr: 'E503.3', label: '' },
  { addr: 'E503.4', label: '' },
  { addr: 'E503.5', label: '' },
  { addr: 'E503.6', label: '' },
  { addr: 'E503.7', label: '' },
  { addr: 'E504.0', label: '' },
  { addr: 'E504.1', label: '' },
  { addr: 'E504.2', label: '' },
  { addr: 'E504.3', label: '' },
  { addr: 'E504.4', label: '' },
  { addr: 'E504.5', label: '' },
  { addr: 'E504.6', label: '' },
  { addr: 'E504.7', label: '' },
  { addr: 'E505.0', label: '' },
  { addr: 'E505.1', label: '' },
  { addr: 'E505.2', label: '' },
  { addr: 'E505.3', label: '' },
  { addr: 'E505.4', label: '' },
  { addr: 'E505.5', label: '' },
  { addr: 'E505.6', label: '' },
  { addr: 'E505.7', label: '' },
  { addr: 'E506.0', label: '' },
  { addr: 'E506.1', label: '' },
  { addr: 'E506.2', label: '' },
  { addr: 'E506.3', label: '' },
  { addr: 'E506.4', label: '' },
  { addr: 'E506.5', label: '' },
  { addr: 'E506.6', label: '' },
  { addr: 'E506.7', label: '' },
  { addr: 'E507.0', label: '' },
  { addr: 'E507.1', label: '' },
  { addr: 'E507.2', label: '' },
  { addr: 'E507.3', label: '' },
  { addr: 'E507.4', label: '' },
  { addr: 'E507.5', label: '' },
  { addr: 'E507.6', label: '' },
  { addr: 'E507.7', label: '' }
]
export const inputs4 = [
  { addr: 'E600.0', label: '' },
  { addr: 'E600.1', label: '' },
  { addr: 'E600.2', label: '' },
  { addr: 'E600.3', label: '' },
  { addr: 'E600.4', label: '' },
  { addr: 'E600.5', label: '' },
  { addr: 'E600.6', label: '' },
  { addr: 'E600.7', label: '' },
  { addr: 'E601.0', label: '' },
  { addr: 'E601.1', label: '' },
  { addr: 'E601.2', label: '' },
  { addr: 'E601.3', label: '' },
  { addr: 'E601.4', label: '' },
  { addr: 'E601.5', label: '' },
  { addr: 'E601.6', label: '' },
  { addr: 'E601.7', label: '' },
  { addr: 'E602.0', label: '' },
  { addr: 'E602.1', label: '' },
  { addr: 'E602.2', label: '' },
  { addr: 'E602.3', label: '' },
  { addr: 'E602.4', label: '' },
  { addr: 'E602.5', label: '' },
  { addr: 'E602.6', label: '' },
  { addr: 'E602.7', label: '' },
  { addr: 'E603.0', label: '' },
  { addr: 'E603.1', label: '' },
  { addr: 'E603.2', label: '' },
  { addr: 'E603.3', label: '' },
  { addr: 'E603.4', label: '' },
  { addr: 'E603.5', label: '' },
  { addr: 'E603.6', label: '' },
  { addr: 'E603.7', label: '' },
  { addr: 'E604.0', label: '' },
  { addr: 'E604.1', label: '' },
  { addr: 'E604.2', label: '' },
  { addr: 'E604.3', label: '' },
  { addr: 'E604.4', label: '' },
  { addr: 'E604.5', label: '' },
  { addr: 'E604.6', label: '' },
  { addr: 'E604.7', label: '' },
  { addr: 'E605.0', label: '' },
  { addr: 'E605.1', label: '' },
  { addr: 'E605.2', label: '' },
  { addr: 'E605.3', label: '' },
  { addr: 'E605.4', label: '' },
  { addr: 'E605.5', label: '' },
  { addr: 'E605.6', label: '' },
  { addr: 'E605.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: '' },
  { addr: 'A0.1', label: '' },
  { addr: 'A0.2', label: '' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: '' },
  { addr: 'A100.1', label: '' },
  { addr: 'A100.2', label: '' },
  { addr: 'A100.3', label: '' },
  { addr: 'A100.4', label: '' },
  { addr: 'A100.5', label: '' },
  { addr: 'A100.6', label: '' },
  { addr: 'A100.7', label: '' },
  { addr: 'A101.0', label: '' },
  { addr: 'A101.1', label: '' },
  { addr: 'A101.2', label: '' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: '' },
  { addr: 'A101.7', label: '' },
  { addr: 'A102.0', label: '' },
  { addr: 'A102.1', label: '' },
  { addr: 'A102.2', label: '' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: '' },
  { addr: 'A103.1', label: '' },
  { addr: 'A103.2', label: '' },
  { addr: 'A103.3', label: '' },
  { addr: 'A103.4', label: '' },
  { addr: 'A103.5', label: '' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: '' }
]
export const outputs3 = [
  { addr: 'A500.0', label: '' },
  { addr: 'A500.1', label: '' },
  { addr: 'A500.2', label: '' },
  { addr: 'A500.3', label: '' },
  { addr: 'A500.4', label: '' },
  { addr: 'A500.5', label: '' },
  { addr: 'A500.6', label: '' },
  { addr: 'A500.7', label: '' },
  { addr: 'A501.0', label: '' },
  { addr: 'A501.1', label: '' },
  { addr: 'A501.2', label: '' },
  { addr: 'A501.3', label: '' },
  { addr: 'A501.4', label: '' },
  { addr: 'A501.5', label: '' },
  { addr: 'A501.6', label: '' },
  { addr: 'A501.7', label: '' },
  { addr: 'A502.0', label: '' },
  { addr: 'A502.1', label: '' },
  { addr: 'A502.2', label: '' },
  { addr: 'A502.3', label: '' },
  { addr: 'A502.4', label: '' },
  { addr: 'A502.5', label: '' },
  { addr: 'A502.6', label: '' },
  { addr: 'A502.7', label: '' },
  { addr: 'A503.0', label: '' },
  { addr: 'A503.1', label: '' },
  { addr: 'A503.2', label: '' },
  { addr: 'A503.3', label: '' },
  { addr: 'A503.4', label: '' },
  { addr: 'A503.5', label: '' },
  { addr: 'A503.6', label: '' },
  { addr: 'A503.7', label: '' }
]
export const outputs4 = [
  { addr: 'A600.0', label: '' },
  { addr: 'A600.1', label: '' },
  { addr: 'A600.2', label: '' },
  { addr: 'A600.3', label: '' },
  { addr: 'A600.4', label: '' },
  { addr: 'A600.5', label: '' },
  { addr: 'A600.6', label: '' },
  { addr: 'A600.7', label: '' },
  { addr: 'A601.0', label: '' },
  { addr: 'A601.1', label: '' },
  { addr: 'A601.2', label: '' },
  { addr: 'A601.3', label: '' },
  { addr: 'A601.4', label: '' },
  { addr: 'A601.5', label: '' },
  { addr: 'A601.6', label: '' },
  { addr: 'A601.7', label: '' },
  { addr: 'A602.0', label: '' },
  { addr: 'A602.1', label: '' },
  { addr: 'A602.2', label: '' },
  { addr: 'A602.3', label: '' },
  { addr: 'A602.4', label: '' },
  { addr: 'A602.5', label: '' },
  { addr: 'A602.6', label: '' },
  { addr: 'A602.7', label: '' },
  { addr: 'A603.0', label: '' },
  { addr: 'A603.1', label: '' },
  { addr: 'A603.2', label: '' },
  { addr: 'A603.3', label: '' },
  { addr: 'A603.4', label: '' },
  { addr: 'A603.5', label: '' },
  { addr: 'A603.6', label: '' },
  { addr: 'A603.7', label: '' }
]
export const alarms1 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 3, key: 'EL4' },
  { id: 3, key: 'EL5' },
  { id: 3, key: 'EL6' },
  { id: 3, key: 'SH1' },
  { id: 3, key: 'SH2' },
  { id: 3, key: 'SH3' },
  { id: 3, key: 'SH4' },
  { id: 3, key: 'SH5' },
  { id: 3, key: 'SH6' },
  { id: 3, key: 'SH7' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
