// generate I/O
exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'SFT1' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: 'RS3' },
  { addr: 'E1.4', label: 'RS12' },
  { addr: 'E1.5', label: 'DB32' },
  { addr: 'E1.6', label: 'DBHZ' },
  { addr: 'E1.7', label: 'UC' },
  { addr: 'E2.0', label: 'SFT' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'FE12' },
  { addr: 'E3.0', label: 'IV1' },
  { addr: 'E3.1', label: 'IV2' },
  { addr: 'E3.2', label: 'RTA' },
  { addr: 'E3.3', label: 'AIV' },
  { addr: 'E3.4', label: 'AF8' },
  { addr: 'E3.5', label: 'AKKU' },
  { addr: 'E3.6', label: 'APE' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'EZE' },
  { addr: 'E4.1', label: 'EOE' },
  { addr: 'E4.2', label: 'FBE' },
  { addr: 'E4.3', label: 'FPE' },
  { addr: 'E4.4', label: 'FDR1' },
  { addr: 'E4.5', label: 'FDL1' },
  { addr: 'E4.6', label: 'FDR2' },
  { addr: 'E4.7', label: 'FDL2' },
  { addr: 'E5.0', label: 'FLP1' },
  { addr: 'E5.1', label: 'FLP2' },
  { addr: 'E5.2', label: 'FLA' },
  { addr: 'E5.3', label: 'POD' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: 'BA' },
  { addr: 'E6.1', label: 'BB' },
  { addr: 'E6.2', label: 'BC' },
  { addr: 'E6.3', label: 'BD' },
  { addr: 'E6.4', label: 'BSTR' },
  { addr: 'E6.5', label: 'BOK' },
  { addr: 'E6.6', label: 'BDAT' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: 'EXZE' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: '' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'SFT1' },
  { addr: 'E11.1', label: 'EXD' },
  { addr: 'E11.2', label: 'EHP' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: 'UC' },
  { addr: 'E12.0', label: 'EOM1' },
  { addr: 'E12.1', label: 'EZM1' },
  { addr: 'E12.2', label: 'EOM2' },
  { addr: 'E12.3', label: 'EZM2' },
  { addr: 'E12.4', label: 'ECA' },
  { addr: 'E12.5', label: 'ECB' },
  { addr: 'E12.6', label: 'FRE1' },
  { addr: 'E12.7', label: 'FRE2' },
  { addr: 'E13.0', label: 'EM' },
  { addr: 'E13.1', label: 'FTXV' },
  { addr: 'E13.2', label: 'FTXH' },
  { addr: 'E13.3', label: 'FTA1' },
  { addr: 'E13.4', label: 'FTA2' },
  { addr: 'E13.5', label: 'RX1' },
  { addr: 'E13.6', label: 'RX2' },
  { addr: 'E13.7', label: 'KEXPV1' },
  { addr: 'E14.0', label: 'FE3' },
  { addr: 'E14.1', label: 'FSBK' },
  { addr: 'E14.2', label: 'ASBK1' },
  { addr: 'E14.3', label: 'ASBK2' },
  { addr: 'E14.4', label: 'AH' },
  { addr: 'E14.5', label: 'AD' },
  { addr: 'E14.6', label: 'FTCR' },
  { addr: 'E14.7', label: 'MTC' },
  { addr: 'E15.0', label: 'AMM1' },
  { addr: 'E15.1', label: 'AMM2' },
  { addr: 'E15.2', label: 'AMC' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: 'KEXPV2' },
  { addr: 'E16.0', label: 'RMV' },
  { addr: 'E16.1', label: 'RMH' },
  { addr: 'E16.2', label: 'RES' },
  { addr: 'E16.3', label: 'REH' },
  { addr: 'E16.4', label: 'RCV' },
  { addr: 'E16.5', label: 'REAV' },
  { addr: 'E16.6', label: 'REAH' },
  { addr: 'E16.7', label: 'RCH' }
]
exports.inputs3 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'SFT1' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: 'RS3' },
  { addr: 'E101.4', label: 'RS12' },
  { addr: 'E101.5', label: 'DB32' },
  { addr: 'E101.6', label: 'DBHZ' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'SFT' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: 'FE12' },
  { addr: 'E103.0', label: 'IV1' },
  { addr: 'E103.1', label: 'IV2' },
  { addr: 'E103.2', label: 'RTA' },
  { addr: 'E103.3', label: 'AIV' },
  { addr: 'E103.4', label: 'AF8' },
  { addr: 'E103.5', label: 'AKKU' },
  { addr: 'E103.6', label: 'APE' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: 'EZE' },
  { addr: 'E104.1', label: 'EOE' },
  { addr: 'E104.2', label: 'FBE' },
  { addr: 'E104.3', label: 'FPE' },
  { addr: 'E104.4', label: 'FDR1' },
  { addr: 'E104.5', label: 'FDL1' },
  { addr: 'E104.6', label: 'FDR2' },
  { addr: 'E104.7', label: 'FDL2' },
  { addr: 'E105.0', label: 'FLP1' },
  { addr: 'E105.1', label: 'FLP2' },
  { addr: 'E105.2', label: 'FLA' },
  { addr: 'E105.3', label: 'POD' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: '' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'BA' },
  { addr: 'E106.1', label: 'BB' },
  { addr: 'E106.2', label: 'BC' },
  { addr: 'E106.3', label: 'BD' },
  { addr: 'E106.4', label: 'BSTR' },
  { addr: 'E106.5', label: 'BOK' },
  { addr: 'E106.6', label: 'BDAT' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'EXZE' },
  { addr: 'E107.1', label: '' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E110.0', label: 'A' },
  { addr: 'E110.1', label: 'B' },
  { addr: 'E110.2', label: 'C' },
  { addr: 'E110.3', label: 'D' },
  { addr: 'E110.4', label: 'OK' },
  { addr: 'E110.5', label: 'S2' },
  { addr: 'E110.6', label: 'S2' },
  { addr: 'E110.7', label: 'S2' },
  { addr: 'E111.0', label: 'SFT1' },
  { addr: 'E111.1', label: 'EXD' },
  { addr: 'E111.2', label: 'EHP' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: 'UC' },
  { addr: 'E112.0', label: 'EOM1' },
  { addr: 'E112.1', label: 'EZM1' },
  { addr: 'E112.2', label: 'EOM2' },
  { addr: 'E112.3', label: 'EZM2' },
  { addr: 'E112.4', label: 'ECA' },
  { addr: 'E112.5', label: 'ECB' },
  { addr: 'E112.6', label: 'FRE1' },
  { addr: 'E112.7', label: 'FRE2' },
  { addr: 'E113.0', label: 'EM' },
  { addr: 'E113.1', label: 'FTXV' },
  { addr: 'E113.2', label: 'FTXH' },
  { addr: 'E113.3', label: 'FTA1' },
  { addr: 'E113.4', label: 'FTA2' },
  { addr: 'E113.5', label: 'RX1' },
  { addr: 'E113.6', label: 'RX2' },
  { addr: 'E113.7', label: 'KEXPV1' },
  { addr: 'E114.0', label: 'FE3' },
  { addr: 'E114.1', label: 'FSBK' },
  { addr: 'E114.2', label: 'ASBK1' },
  { addr: 'E114.3', label: 'ASBK2' },
  { addr: 'E114.4', label: 'AH' },
  { addr: 'E114.5', label: 'AD' },
  { addr: 'E114.6', label: 'FTCR' },
  { addr: 'E114.7', label: 'MTC' },
  { addr: 'E115.0', label: 'AMM1' },
  { addr: 'E115.1', label: 'AMM2' },
  { addr: 'E115.2', label: 'AMC' },
  { addr: 'E115.3', label: '' },
  { addr: 'E115.4', label: '' },
  { addr: 'E115.5', label: '' },
  { addr: 'E115.6', label: '' },
  { addr: 'E115.7', label: 'KEXPV2' },
  { addr: 'E116.0', label: 'RMV' },
  { addr: 'E116.1', label: 'RMH' },
  { addr: 'E116.2', label: 'RES' },
  { addr: 'E116.3', label: 'REH' },
  { addr: 'E116.4', label: 'RCV' },
  { addr: 'E116.5', label: 'REAV' },
  { addr: 'E116.6', label: 'REAH' },
  { addr: 'E116.7', label: 'RCH' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'STO1-1' },
  { addr: 'A1.1', label: 'STO1-2' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: 'LS' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'LC' },
  { addr: 'A2.0', label: 'L1' },
  { addr: 'A2.1', label: 'L2' },
  { addr: 'A2.2', label: 'L3' },
  { addr: 'A2.3', label: 'L4' },
  { addr: 'A2.4', label: 'L5' },
  { addr: 'A2.5', label: 'RFE' },
  { addr: 'A2.6', label: 'RLN' },
  { addr: 'A2.7', label: 'RBE' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: 'STO2-1' },
  { addr: 'A4.1', label: 'STO2-2' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: '' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: 'TIV2' },
  { addr: 'A5.0', label: 'SPE' },
  { addr: 'A5.1', label: 'SZE' },
  { addr: 'A5.2', label: 'SOE' },
  { addr: 'A5.3', label: 'KXPE' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: 'DYA' },
  { addr: 'A10.1', label: 'DYB' },
  { addr: 'A10.2', label: 'DYC' },
  { addr: 'A10.3', label: 'DYD' },
  { addr: 'A10.4', label: 'AD1' },
  { addr: 'A10.5', label: 'AD2' },
  { addr: 'A10.6', label: 'AD3' },
  { addr: 'A10.7', label: 'STR' },
  { addr: 'A11.0', label: 'T10' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: 'TD' },
  { addr: 'A11.3', label: 'TCR' },
  { addr: 'A11.4', label: 'SBK1' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: 'LA' },
  { addr: 'A11.7', label: 'LC' },
  { addr: 'A12.0', label: 'T2' },
  { addr: 'A12.1', label: 'TRA' },
  { addr: 'A12.2', label: 'TRB' },
  { addr: 'A12.3', label: 'KCS' },
  { addr: 'A12.4', label: 'KCV' },
  { addr: 'A12.5', label: 'KCH' },
  { addr: 'A12.6', label: 'SBK2' },
  { addr: 'A12.7', label: 'T10F' },
  { addr: 'A13.0', label: 'SMA1' },
  { addr: 'A13.1', label: 'SMB1' },
  { addr: 'A13.2', label: 'SMA2' },
  { addr: 'A13.3', label: 'SMB2' },
  { addr: 'A13.4', label: 'SCA' },
  { addr: 'A13.5', label: 'SCB' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'STO1-1' },
  { addr: 'A101.1', label: 'STO1-2' },
  { addr: 'A101.2', label: '' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: 'LS' },
  { addr: 'A101.6', label: 'LA' },
  { addr: 'A101.7', label: 'LC' },
  { addr: 'A102.0', label: 'L1' },
  { addr: 'A102.1', label: 'L2' },
  { addr: 'A102.2', label: 'L3' },
  { addr: 'A102.3', label: 'L4' },
  { addr: 'A102.4', label: 'L5' },
  { addr: 'A102.5', label: 'RFE' },
  { addr: 'A102.6', label: 'RLN' },
  { addr: 'A102.7', label: 'RBE' },
  { addr: 'A103.0', label: 'LK' },
  { addr: 'A103.1', label: 'LE' },
  { addr: 'A103.2', label: 'LB' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: '' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: '' },
  { addr: 'A104.0', label: 'STO2-1' },
  { addr: 'A104.1', label: 'STO2-2' },
  { addr: 'A104.2', label: '' },
  { addr: 'A104.3', label: '' },
  { addr: 'A104.4', label: '' },
  { addr: 'A104.5', label: '' },
  { addr: 'A104.6', label: '' },
  { addr: 'A104.7', label: 'TIV2' },
  { addr: 'A105.0', label: 'SPE' },
  { addr: 'A105.1', label: 'SZE' },
  { addr: 'A105.2', label: 'SOE' },
  { addr: 'A105.3', label: 'KXPE' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A110.0', label: 'DYA' },
  { addr: 'A110.1', label: 'DYB' },
  { addr: 'A110.2', label: 'DYC' },
  { addr: 'A110.3', label: 'DYD' },
  { addr: 'A110.4', label: 'AD1' },
  { addr: 'A110.5', label: 'AD2' },
  { addr: 'A110.6', label: 'AD3' },
  { addr: 'A110.7', label: 'STR' },
  { addr: 'A111.0', label: 'T10' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: 'TD' },
  { addr: 'A111.3', label: 'TCR' },
  { addr: 'A111.4', label: 'SBK1' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: 'LA' },
  { addr: 'A111.7', label: 'LC' },
  { addr: 'A112.0', label: 'T2' },
  { addr: 'A112.1', label: 'TRA' },
  { addr: 'A112.2', label: 'TRB' },
  { addr: 'A112.3', label: 'KCS' },
  { addr: 'A112.4', label: 'KCV' },
  { addr: 'A112.5', label: 'KCH' },
  { addr: 'A112.6', label: 'SBK2' },
  { addr: 'A112.7', label: 'T10F' },
  { addr: 'A113.0', label: 'SMA1' },
  { addr: 'A113.1', label: 'SMB1' },
  { addr: 'A113.2', label: 'SMA2' },
  { addr: 'A113.3', label: 'SMB2' },
  { addr: 'A113.4', label: 'SCA' },
  { addr: 'A113.5', label: 'SCB' },
  { addr: 'A113.6', label: '' },
  { addr: 'A113.7', label: '' }
]
exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-h-to', query: {} },
  { id: 22, key: 'al-lh', query: {} },
  { id: 23, key: 'al-lh-diff', query: {} },
  { id: 24, key: 'al-r-to', query: {} },
  { id: 25, key: 'al-enr', query: {} },
  { id: 26, key: 'al-v-lck-to', query: {} },
  { id: 27, key: 'al-v-lck-fc', query: {} },
  { id: 28, key: 'al-v-lck-to', query: {} },
  { id: 29, key: 'al-v-lck-fc', query: {} },
  { id: 30, key: 'al-flap-to', query: {} },
  { id: 31, key: 'al-flap-fc', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-iv', query: { nr: 2 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'AIV' } },
  { id: 54, key: 'al-th', query: { name: 'AF8' } },
  { id: 55, key: 'al-th', query: { name: 'AKKU' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: 'al-sp-to', query: {} },
  { id: 97, key: 'al-sp-to', query: {} },
  { id: 98, key: 'al-sp-fc', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'APE' } },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'T1' },
  { id: 2, key: 'T2' },
  { id: 3, key: 'EU1' },
  { id: 4, key: 'EU2' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
