// generate I/O
exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'EXDR' },
  { addr: 'E1.1', label: 'EXDM' },
  { addr: 'E1.2', label: 'AMM1' },
  { addr: 'E1.3', label: 'EOM1' },
  { addr: 'E1.4', label: 'EZM1' },
  { addr: 'E1.5', label: 'AMM2' },
  { addr: 'E1.6', label: 'EOM2' },
  { addr: 'E1.7', label: 'EZM2' },
  { addr: 'E2.0', label: 'MDR' },
  { addr: 'E2.1', label: 'MDL' },
  { addr: 'E2.2', label: 'EDR' },
  { addr: 'E2.3', label: 'EDL' },
  { addr: 'E2.4', label: 'AD' },
  { addr: 'E2.5', label: 'APE' },
  { addr: 'E2.6', label: 'FTM' },
  { addr: 'E2.7', label: 'RX' },
  { addr: 'E3.0', label: 'IV1' },
  { addr: 'E3.1', label: 'SA' },
  { addr: 'E3.2', label: 'FSBK' },
  { addr: 'E3.3', label: 'ASBK1' },
  { addr: 'E3.4', label: 'EXPV' },
  { addr: 'E3.5', label: 'EFB' },
  { addr: 'E3.6', label: 'MLE' },
  { addr: 'E3.7', label: 'EXPM' },
  { addr: 'E4.0', label: 'BA' },
  { addr: 'E4.1', label: 'BB' },
  { addr: 'E4.2', label: 'BC' },
  { addr: 'E4.3', label: 'BD' },
  { addr: 'E4.4', label: 'BSTR' },
  { addr: 'E4.5', label: 'BOK' },
  { addr: 'E4.6', label: 'BDAT' },
  { addr: 'E4.7', label: 'FTC' },
  { addr: 'E5.0', label: 'BA' },
  { addr: 'E5.1', label: 'BB' },
  { addr: 'E5.2', label: 'BC' },
  { addr: 'E5.3', label: 'BD' },
  { addr: 'E5.4', label: 'BSTR' },
  { addr: 'E5.5', label: 'BOK' },
  { addr: 'E5.6', label: 'BDAT' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'EZE' },
  { addr: 'E6.1', label: 'EOE' },
  { addr: 'E6.2', label: 'FBE' },
  { addr: 'E6.3', label: 'FPE' },
  { addr: 'E6.4', label: 'FTL1' },
  { addr: 'E6.5', label: 'FTL2' },
  { addr: 'E6.6', label: 'FTA' },
  { addr: 'E6.7', label: 'FRE' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: 'FDR' },
  { addr: 'E7.2', label: 'FDL' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: 'FTL3' },
  { addr: 'E7.7', label: 'FE1' },
  { addr: 'E8.0', label: 'KAB' },
  { addr: 'E8.1', label: 'KXPE' },
  { addr: 'E8.2', label: 'KEZE' },
  { addr: 'E8.3', label: 'KEXPV' },
  { addr: 'E8.4', label: 'FTXV' },
  { addr: 'E8.5', label: 'S1' },
  { addr: 'E8.6', label: 'S1' },
  { addr: 'E8.7', label: 'S1' },
  { addr: 'E9.0', label: 'ASBK2' },
  { addr: 'E9.1', label: 'AMMD' },
  { addr: 'E9.2', label: 'EOMD' },
  { addr: 'E9.3', label: 'EZMD' },
  { addr: 'E9.4', label: 'AMC' },
  { addr: 'E9.5', label: 'ECA' },
  { addr: 'E9.6', label: 'ECB' },
  { addr: 'E9.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'EXV' },
  { addr: 'E11.1', label: 'EHP' },
  { addr: 'E11.2', label: 'EXPV' },
  { addr: 'E11.3', label: 'EFB' },
  { addr: 'E11.4', label: 'IV1' },
  { addr: 'E11.5', label: 'FE1' },
  { addr: 'E11.6', label: 'IV2' },
  { addr: 'E11.7', label: 'UC' },
  { addr: 'E12.0', label: 'FTV1' },
  { addr: 'E12.1', label: 'FTH1' },
  { addr: 'E12.2', label: 'FTV2' },
  { addr: 'E12.3', label: 'FTH2' },
  { addr: 'E12.4', label: 'FEMV' },
  { addr: 'E12.5', label: 'FEMH' },
  { addr: 'E12.6', label: 'FSBK' },
  { addr: 'E12.7', label: 'ASBK1' },
  { addr: 'E13.0', label: 'RMV' },
  { addr: 'E13.1', label: 'RMH' },
  { addr: 'E13.2', label: 'RES' },
  { addr: 'E13.3', label: 'REH' },
  { addr: 'E13.4', label: 'RCV' },
  { addr: 'E13.5', label: 'REAV' },
  { addr: 'E13.6', label: 'REAH' },
  { addr: 'E13.7', label: 'RCH' },
  { addr: 'E14.0', label: 'AH' },
  { addr: 'E14.1', label: 'ASBK2' },
  { addr: 'E14.2', label: 'FTV3' },
  { addr: 'E14.3', label: 'FTCR' },
  { addr: 'E14.4', label: 'EM' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: 'FTXV' },
  { addr: 'E14.7', label: 'FTXH' },
  { addr: 'E15.0', label: 'EFR' },
  { addr: 'E15.1', label: 'EFL' },
  { addr: 'E15.2', label: 'EXH' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: 'AMM' },
  { addr: 'E15.5', label: 'EOM' },
  { addr: 'E15.6', label: 'EZM' },
  { addr: 'E15.7', label: 'MTC' },
  { addr: 'E16.0', label: 'FTC1' },
  { addr: 'E16.1', label: 'FTC2' },
  { addr: 'E16.2', label: 'FTC3' },
  { addr: 'E16.3', label: 'FTM' },
  { addr: 'E16.4', label: 'EXT' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: '' },
  { addr: 'E17.0', label: '' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: '' },
  { addr: 'E17.3', label: '' },
  { addr: 'E17.4', label: '' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'KEM' },
  { addr: 'A0.1', label: 'KBA' },
  { addr: 'A0.2', label: 'KXPE' },
  { addr: 'A0.3', label: 'SQA' },
  { addr: 'A0.4', label: 'TD' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'LC' },
  { addr: 'A1.0', label: 'L1' },
  { addr: 'A1.1', label: 'L2' },
  { addr: 'A1.2', label: 'L3' },
  { addr: 'A1.3', label: 'L4' },
  { addr: 'A1.4', label: 'L5' },
  { addr: 'A1.5', label: 'RFE' },
  { addr: 'A1.6', label: 'RLN' },
  { addr: 'A1.7', label: 'RBE' },
  { addr: 'A2.0', label: 'DYA' },
  { addr: 'A2.1', label: 'DYB' },
  { addr: 'A2.2', label: 'DYC' },
  { addr: 'A2.3', label: 'DYD' },
  { addr: 'A2.4', label: 'AD1' },
  { addr: 'A2.5', label: 'AD2' },
  { addr: 'A2.6', label: 'AD3' },
  { addr: 'A2.7', label: 'STR' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: 'SPE' },
  { addr: 'A3.3', label: 'SBK1' },
  { addr: 'A3.4', label: 'SMAD' },
  { addr: 'A3.5', label: 'SMBD' },
  { addr: 'A3.6', label: 'SCA' },
  { addr: 'A3.7', label: 'SCB' },
  { addr: 'A4.0', label: 'LK' },
  { addr: 'A4.1', label: 'LE' },
  { addr: 'A4.2', label: 'LB' },
  { addr: 'A4.3', label: 'RDY' },
  { addr: 'A4.4', label: 'RST' },
  { addr: 'A4.5', label: 'SMA1' },
  { addr: 'A4.6', label: 'SMB1' },
  { addr: 'A4.7', label: '' },
  { addr: 'A5.0', label: 'LK' },
  { addr: 'A5.1', label: 'LE' },
  { addr: 'A5.2', label: 'LB' },
  { addr: 'A5.3', label: 'RDY' },
  { addr: 'A5.4', label: 'RST' },
  { addr: 'A5.5', label: 'SMA2' },
  { addr: 'A5.6', label: 'SMB2' },
  { addr: 'A5.7', label: 'SBK2' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: 'SMA' },
  { addr: 'A10.1', label: 'SMB' },
  { addr: 'A10.2', label: 'KBA1' },
  { addr: 'A10.3', label: '' },
  { addr: 'A10.4', label: 'TCR' },
  { addr: 'A10.5', label: 'KBA2' },
  { addr: 'A10.6', label: 'SBK1' },
  { addr: 'A10.7', label: 'LC' },
  { addr: 'A11.0', label: 'T10' },
  { addr: 'A11.1', label: 'T2' },
  { addr: 'A11.2', label: 'TRA' },
  { addr: 'A11.3', label: 'TRB' },
  { addr: 'A11.4', label: 'KCS' },
  { addr: 'A11.5', label: 'KCV' },
  { addr: 'A11.6', label: 'KCH' },
  { addr: 'A11.7', label: '' },
  { addr: 'A12.0', label: 'DYA' },
  { addr: 'A12.1', label: 'DYB' },
  { addr: 'A12.2', label: 'DYC' },
  { addr: 'A12.3', label: 'DYD' },
  { addr: 'A12.4', label: 'AD1' },
  { addr: 'A12.5', label: 'AD2' },
  { addr: 'A12.6', label: 'AD3' },
  { addr: 'A12.7', label: 'STR' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: 'T10F' },
  { addr: 'A13.7', label: 'SBK2' }
]
// generate Alarms
exports.ALARMS = [
  { id: 1, key: 'al-v-to', query: {} },
  { id: 2, key: 'al-sp-to', query: {} },
  { id: 3, key: 'al-flap-to', query: {} },
  { id: 4, key: 'al-v-lck-to', query: { nr: 1 } },
  { id: 5, key: 'al-v-lck-to', query: { nr: 2 } },
  { id: 6, key: 'al-r-to', query: {} },
  { id: 7, key: 'al-r-lck-to', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: 'al-v-fdbk', query: {} },
  { id: 11, key: 'al-v-fdbk', query: {} },
  { id: 12, key: 'al-sp-to', query: {} },
  { id: 13, key: 'al-sp-to', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: 'al-th', query: { name: 'AMM1' } },
  { id: 18, key: 'al-th', query: { name: 'AMM2' } },
  { id: 19, key: 'al-th', query: { name: 'AD' } },
  { id: 20, key: 'al-th', query: { name: 'APE' } },
  { id: 21, key: 'al-iv', query: { nr: 3 } },
  { id: 22, key: 'al-th', query: { name: 'ASBK1' } },
  { id: 23, key: 'al-th', query: { name: 'FE1' } },
  { id: 24, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 25, key: 'al-th', query: { name: 'AMMD' } },
  { id: 26, key: 'al-th', query: { name: 'RSI' } },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-flap-fc', query: {} },
  { id: 34, key: 'al-fc', query: { fc1: 'EOM1', fc2: 'EZM1' } },
  { id: 35, key: 'al-fc', query: { fc1: 'EOM2', fc2: 'EZM2' } },
  { id: 36, key: 'al-fc', query: { fc1: 'EFB', fc2: 'EXPV' } },
  { id: 37, key: 'al-fc', query: { fc1: 'ETA', fc2: 'ETB' } },
  { id: 38, key: 'al-sp-fc', query: {} },
  { id: 39, key: 'al-r-lck-fc', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-pn', query: { name: 'GENERAL' } },
  { id: 50, key: 'al-pn', query: { name: 'T IM155' } },
  { id: 51, key: 'al-pn', query: { name: 'IV EL' } },
  { id: 52, key: 'al-pn', query: { name: 'IV1 T' } },
  { id: 53, key: 'al-pn', query: { name: 'IV2 T' } },
  { id: 54, key: 'al-pn', query: { name: 'LV T' } },
  { id: 55, key: 'al-pn', query: { name: 'LH T' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-01', query: {} },
  { id: 67, key: 'al-sil-01', query: {} },
  { id: 68, key: 'al-sil-02', query: {} },
  { id: 69, key: 'al-sil-03', query: {} },
  { id: 70, key: 'al-sil-04', query: {} },
  { id: 71, key: 'al-v-to', query: {} },
  { id: 72, key: 'al-h-to', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: 'al-v-fdbk', query: {} },
  { id: 75, key: 'al-v-fdbk', query: {} },
  { id: 76, key: 'al-v-lck-to', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-th', query: { name: 'ASBK1' } },
  { id: 82, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 83, key: 'al-th', query: { name: 'FE1' } },
  { id: 84, key: 'al-th', query: { name: 'AF8' } },
  { id: 85, key: 'al-iv', query: { nr: 1 } },
  { id: 86, key: 'al-iv', query: { nr: 2 } },
  { id: 87, key: 'al-th', query: { name: 'AH' } },
  { id: 88, key: '', query: {} },
  { id: 89, key: 'al-th', query: { name: 'AMM4' } },
  { id: 90, key: 'al-th', query: { name: 'MTC' } },
  { id: 91, key: 'al-th', query: { name: 'RSI' } },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-sil-07', query: {} },
  { id: 98, key: 'al-fc', query: { fc1: 'EFB', fc2: 'EXPV' } },
  { id: 99, key: 'al-sil-12', query: {} },
  { id: 100, key: 'al-sil-13', query: {} },
  { id: 101, key: 'al-fc', query: { fc1: 'EOM4', fc2: 'EZM4' } },
  { id: 102, key: 'al-lv', query: {} },
  { id: 103, key: 'al-lv', query: {} },
  { id: 104, key: 'al-lh', query: {} },
  { id: 105, key: 'al-lh', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EU' },
  { id: 2, key: 'T' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
