// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'UC' },
  { addr: 'E1.1', label: 'FE' },
  { addr: 'E1.2', label: 'IV1' },
  { addr: 'E1.3', label: 'RSI' },
  { addr: 'E1.4', label: 'ASBK' },
  { addr: 'E1.5', label: 'RTA' },
  { addr: 'E1.6', label: 'AMC' },
  { addr: 'E1.7', label: 'APBE' },
  { addr: 'E2.0', label: 'APBA' },
  { addr: 'E2.1', label: 'FSBK' },
  { addr: 'E2.2', label: 'DB32' },
  { addr: 'E2.3', label: 'DBHZ' },
  { addr: 'E2.4', label: 'IV3' },
  { addr: 'E2.5', label: 'IV4' },
  { addr: 'E2.6', label: 'ECA' },
  { addr: 'E2.7', label: 'ECB' },
  { addr: 'E3.0', label: 'EZE' },
  { addr: 'E3.1', label: 'EOE' },
  { addr: 'E3.2', label: 'EBZE' },
  { addr: 'E3.3', label: 'EBOE' },
  { addr: 'E3.4', label: 'EZA' },
  { addr: 'E3.5', label: 'EOA' },
  { addr: 'E3.6', label: 'EBZA' },
  { addr: 'E3.7', label: 'EBOA' },
  { addr: 'E4.0', label: 'FBE' },
  { addr: 'E4.1', label: 'FBBE' },
  { addr: 'E4.2', label: 'FBA' },
  { addr: 'E4.3', label: 'FBBA' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: 'FPE' },
  { addr: 'E4.6', label: 'FPA' },
  { addr: 'E4.7', label: 'FDR1' },
  { addr: 'E5.0', label: 'FDL1' },
  { addr: 'E5.1', label: 'FDR2' },
  { addr: 'E5.2', label: 'FDL2' },
  { addr: 'E5.3', label: 'FTA1' },
  { addr: 'E5.4', label: 'FTA2' },
  { addr: 'E5.5', label: 'FTA3' },
  { addr: 'E5.6', label: 'FLP1' },
  { addr: 'E5.7', label: 'FLA1' },
  { addr: 'E6.0', label: 'EXDE' },
  { addr: 'E6.1', label: 'EXHE' },
  { addr: 'E6.2', label: 'EXDA' },
  { addr: 'E6.3', label: 'EXHA' },
  { addr: 'E6.4', label: 'ATD' },
  { addr: 'E6.5', label: 'ASKD' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: 'SA' },
  { addr: 'E7.0', label: 'TJ1' },
  { addr: 'E7.1', label: 'TJ3' },
  { addr: 'E7.2', label: 'TJ4' },
  { addr: 'E7.3', label: 'FRER' },
  { addr: 'E7.4', label: 'FREL' },
  { addr: 'E7.5', label: 'FTA3-1' },
  { addr: 'E7.6', label: 'FTA2-1' },
  { addr: 'E7.7', label: '' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'UC' },
  { addr: 'E11.1', label: 'IV2' },
  { addr: 'E11.2', label: 'FE' },
  { addr: 'E11.3', label: 'EM' },
  { addr: 'E11.4', label: 'DB32' },
  { addr: 'E11.5', label: 'DBHZ' },
  { addr: 'E11.6', label: 'FTXV' },
  { addr: 'E11.7', label: 'FTXH' },
  { addr: 'E12.0', label: 'RMV' },
  { addr: 'E12.1', label: 'RMH' },
  { addr: 'E12.2', label: 'RES' },
  { addr: 'E12.3', label: 'REH' },
  { addr: 'E12.4', label: 'RCV' },
  { addr: 'E12.5', label: 'REAV' },
  { addr: 'E12.6', label: 'REAH' },
  { addr: 'E12.7', label: 'RCH' },
  { addr: 'E13.0', label: 'TJ2' },
  { addr: 'E13.1', label: 'SRL' },
  { addr: 'E13.2', label: 'RSI' },
  { addr: 'E13.3', label: 'EOM1' },
  { addr: 'E13.4', label: 'EZM1' },
  { addr: 'E13.5', label: 'EMC' },
  { addr: 'E13.6', label: 'EXV' },
  { addr: 'E13.7', label: 'EXPV' },
  { addr: 'E14.0', label: 'ASH' },
  { addr: 'E14.1', label: 'FTCR' },
  { addr: 'E14.2', label: 'AH12' },
  { addr: 'E14.3', label: 'MTC' },
  { addr: 'E14.4', label: 'AMM' },
  { addr: 'E14.5', label: 'FSMA' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'KBA1' },
  { addr: 'A1.1', label: 'LA' },
  { addr: 'A1.2', label: 'LC' },
  { addr: 'A1.3', label: 'SCA' },
  { addr: 'A1.4', label: 'SCB' },
  { addr: 'A1.5', label: 'SBK1' },
  { addr: 'A1.6', label: 'SBK2' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: 'L1' },
  { addr: 'A2.1', label: 'L2' },
  { addr: 'A2.2', label: 'L3' },
  { addr: 'A2.3', label: 'L4' },
  { addr: 'A2.4', label: 'L5' },
  { addr: 'A2.5', label: 'RFE' },
  { addr: 'A2.6', label: 'SPE' },
  { addr: 'A2.7', label: 'SPA' },
  { addr: 'A3.0', label: 'SOE' },
  { addr: 'A3.1', label: 'SZE' },
  { addr: 'A3.2', label: 'SBOE' },
  { addr: 'A3.3', label: 'SBZE' },
  { addr: 'A3.4', label: 'SOA' },
  { addr: 'A3.5', label: 'SZA' },
  { addr: 'A3.6', label: 'SBOA' },
  { addr: 'A3.7', label: 'SBZA' },
  { addr: 'A4.0', label: 'KBA3' },
  { addr: 'A4.1', label: 'KBA4' },
  { addr: 'A4.2', label: 'SKDE' },
  { addr: 'A4.3', label: 'SKDA' },
  { addr: 'A4.4', label: 'LRDY' },
  { addr: 'A4.5', label: 'SPBE' },
  { addr: 'A4.6', label: 'SPBA' },
  { addr: 'A4.7', label: 'RFA' },
  { addr: 'A5.0', label: '' },
  { addr: 'A5.1', label: '' },
  { addr: 'A5.2', label: '' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'DYA' },
  { addr: 'A10.1', label: 'DYB' },
  { addr: 'A10.2', label: 'DYC' },
  { addr: 'A10.3', label: 'DYD' },
  { addr: 'A10.4', label: 'AD1' },
  { addr: 'A10.5', label: 'AD2' },
  { addr: 'A10.6', label: 'AD3' },
  { addr: 'A10.7', label: 'STR' },
  { addr: 'A11.0', label: 'T101' },
  { addr: 'A11.1', label: 'T102' },
  { addr: 'A11.2', label: 'TRA' },
  { addr: 'A11.3', label: 'TRB' },
  { addr: 'A11.4', label: 'KCS' },
  { addr: 'A11.5', label: 'KCV' },
  { addr: 'A11.6', label: 'KCH' },
  { addr: 'A11.7', label: 'TCR' },
  { addr: 'A12.0', label: 'KBA2' },
  { addr: 'A12.1', label: 'T2' },
  { addr: 'A12.2', label: 'TSH' },
  { addr: 'A12.3', label: 'SMA' },
  { addr: 'A12.4', label: 'SMB' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: 'LA' },
  { addr: 'A12.7', label: 'LC' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-h-to', query: {} },
  { id: 24, key: 'al-lh', query: {} },
  { id: 25, key: 'al-lh-diff', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: '', query: {} },
  { id: 51, key: 'al-iv', query: { nr: 1 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'ASBK' } },
  { id: 54, key: 'al-th', query: { name: 'FE1' } },
  { id: 55, key: 'al-iv', query: { nr: 2 } },
  { id: 56, key: 'al-th', query: { name: 'AH12' } },
  { id: 57, key: 'al-th', query: { name: 'MTC' } },
  { id: 58, key: 'al-th', query: { name: 'ASH' } },
  { id: 59, key: 'al-th', query: { name: 'AMM' } },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-flap-to', query: {} },
  { id: 82, key: 'al-flap-fc', query: {} },
  { id: 83, key: 'al-spe-to', query: {} },
  { id: 84, key: 'al-spe-fc', query: {} },
  { id: 85, key: 'al-spbe-to', query: {} },
  { id: 86, key: 'al-spbe-fc', query: {} },
  { id: 87, key: 'al-r-to', query: {} },
  { id: 88, key: 'al-enr', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'AMC' } },
  { id: 114, key: 'al-th', query: { name: 'APBE' } },
  { id: 115, key: 'al-th', query: { name: 'APBA' } },
  { id: 116, key: 'al-iv', query: { nr: 3 } },
  { id: 117, key: 'al-iv', query: { nr: 4 } },
  { id: 118, key: 'al-th', query: { name: 'AID' } },
  { id: 119, key: 'al-th', query: { name: 'ASKD' } },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} },
  { id: 129, key: '', query: {} },
  { id: 130, key: '', query: {} },
  { id: 131, key: '', query: {} },
  { id: 132, key: '', query: {} },
  { id: 133, key: '', query: {} },
  { id: 134, key: '', query: {} },
  { id: 135, key: '', query: {} },
  { id: 136, key: '', query: {} },
  { id: 137, key: '', query: {} },
  { id: 138, key: '', query: {} },
  { id: 139, key: '', query: {} },
  { id: 140, key: '', query: {} },
  { id: 141, key: '', query: {} },
  { id: 142, key: '', query: {} },
  { id: 143, key: '', query: {} },
  { id: 144, key: '', query: {} },
  { id: 145, key: '', query: {} },
  { id: 146, key: '', query: {} },
  { id: 147, key: 'al-spa-to', query: {} },
  { id: 148, key: 'al-spa-fc', query: {} },
  { id: 149, key: 'al-spba-to', query: {} },
  { id: 150, key: 'al-spba-fc', query: {} },
  { id: 151, key: 'al-r-to', query: {} },
  { id: 152, key: 'al-enr', query: {} },
  { id: 153, key: '', query: {} },
  { id: 154, key: '', query: {} },
  { id: 155, key: '', query: {} },
  { id: 156, key: '', query: {} },
  { id: 157, key: '', query: {} },
  { id: 158, key: '', query: {} },
  { id: 159, key: '', query: {} },
  { id: 160, key: '', query: {} },
  { id: 161, key: '', query: {} },
  { id: 162, key: '', query: {} },
  { id: 163, key: '', query: {} },
  { id: 164, key: '', query: {} },
  { id: 165, key: '', query: {} },
  { id: 166, key: '', query: {} },
  { id: 167, key: '', query: {} },
  { id: 168, key: '', query: {} },
  { id: 169, key: '', query: {} },
  { id: 170, key: '', query: {} },
  { id: 171, key: '', query: {} },
  { id: 172, key: '', query: {} },
  { id: 173, key: '', query: {} },
  { id: 174, key: '', query: {} },
  { id: 175, key: '', query: {} },
  { id: 176, key: '', query: {} },
  { id: 177, key: '', query: {} },
  { id: 178, key: 'al-th', query: { name: 'APBE' } },
  { id: 179, key: 'al-th', query: { name: 'APBA' } },
  { id: 180, key: 'al-iv', query: { nr: 3 } },
  { id: 181, key: 'al-iv', query: { nr: 4 } },
  { id: 182, key: 'al-th', query: { name: 'ATD' } },
  { id: 183, key: 'al-th', query: { name: 'ASKD' } },
  { id: 184, key: '', query: {} },
  { id: 185, key: '', query: {} },
  { id: 186, key: '', query: {} },
  { id: 187, key: '', query: {} },
  { id: 188, key: '', query: {} },
  { id: 189, key: '', query: {} },
  { id: 190, key: '', query: {} },
  { id: 191, key: '', query: {} },
  { id: 192, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'E' },
  { id: 3, key: 'U' },
  { id: 100, key: 'HMI' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
