export const inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'RS12' },
  { addr: 'E100.1', label: 'RTJ12' },
  { addr: 'E100.2', label: 'ASBK' },
  { addr: 'E100.3', label: 'FSBK' },
  { addr: 'E100.4', label: 'FTJ1' },
  { addr: 'E100.5', label: 'IV1' },
  { addr: 'E100.6', label: 'FE12' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: '' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: '' },
  { addr: 'E101.4', label: '' },
  { addr: 'E101.5', label: '' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: '' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: '' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: '' },
  { addr: 'E103.5', label: '' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: 'ACR' },
  { addr: 'E110.1', label: 'AMM' },
  { addr: 'E110.2', label: 'ASH' },
  { addr: 'E110.3', label: 'FTCR' },
  { addr: 'E110.4', label: 'RS12' },
  { addr: 'E110.5', label: 'EMC' },
  { addr: 'E110.6', label: 'EOM' },
  { addr: 'E110.7', label: 'EZM' },
  { addr: 'E111.0', label: 'FE' },
  { addr: 'E111.1', label: 'EXV' },
  { addr: 'E111.2', label: 'EXPV' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: '' },
  { addr: 'E112.0', label: 'A' },
  { addr: 'E112.1', label: 'B' },
  { addr: 'E112.2', label: 'C' },
  { addr: 'E112.3', label: 'D' },
  { addr: 'E112.4', label: 'OK' },
  { addr: 'E112.5', label: 'S2' },
  { addr: 'E112.6', label: 'S2' },
  { addr: 'E112.7', label: 'S2' },
  { addr: 'E113.0', label: 'UC' },
  { addr: 'E113.1', label: 'RS3' },
  { addr: 'E113.2', label: 'EM' },
  { addr: 'E113.3', label: 'FTXV' },
  { addr: 'E113.4', label: 'FTXH' },
  { addr: 'E113.5', label: 'FT10' },
  { addr: 'E113.6', label: 'ASBK' },
  { addr: 'E113.7', label: 'IV2' },
  { addr: 'E114.0', label: 'MTC1' },
  { addr: 'E114.1', label: 'MTC2' },
  { addr: 'E114.2', label: 'FTCR' },
  { addr: 'E114.3', label: 'DB32' },
  { addr: 'E114.4', label: 'DBHZ' },
  { addr: 'E114.5', label: 'RS12' },
  { addr: 'E114.6', label: 'FTJ2' },
  { addr: 'E114.7', label: 'FE1' },
  { addr: 'E115.0', label: 'RMV' },
  { addr: 'E115.1', label: 'RMH' },
  { addr: 'E115.2', label: 'RES' },
  { addr: 'E115.3', label: 'REH' },
  { addr: 'E115.4', label: 'RCV' },
  { addr: 'E115.5', label: 'REAV' },
  { addr: 'E115.6', label: 'REAH' },
  { addr: 'E115.7', label: 'RCH' },
  { addr: 'E116.0', label: '' },
  { addr: 'E116.1', label: '' },
  { addr: 'E116.2', label: '' },
  { addr: 'E116.3', label: '' },
  { addr: 'E116.4', label: '' },
  { addr: 'E116.5', label: '' },
  { addr: 'E116.6', label: '' },
  { addr: 'E116.7', label: '' },
  { addr: 'E117.0', label: '' },
  { addr: 'E117.1', label: '' },
  { addr: 'E117.2', label: '' },
  { addr: 'E117.3', label: '' },
  { addr: 'E117.4', label: '' },
  { addr: 'E117.5', label: '' },
  { addr: 'E117.6', label: '' },
  { addr: 'E117.7', label: '' }
]
export const inputs4 = [
  { addr: 'E120.0', label: 'A' },
  { addr: 'E120.1', label: 'B' },
  { addr: 'E120.2', label: 'C' },
  { addr: 'E120.3', label: 'D' },
  { addr: 'E120.4', label: 'OK' },
  { addr: 'E120.5', label: 'S2' },
  { addr: 'E120.6', label: 'S2' },
  { addr: 'E120.7', label: 'S2' },
  { addr: 'E121.0', label: '' },
  { addr: 'E121.1', label: '' },
  { addr: 'E121.2', label: 'RS12' },
  { addr: 'E121.3', label: 'SRL' },
  { addr: 'E121.4', label: 'RTJ3' },
  { addr: 'E121.5', label: 'ASKE' },
  { addr: 'E121.6', label: 'RS3' },
  { addr: 'E121.7', label: 'UC' },
  { addr: 'E122.0', label: 'FSBKE' },
  { addr: 'E122.1', label: 'AMC' },
  { addr: 'E122.2', label: 'TJ3' },
  { addr: 'E122.3', label: 'AP' },
  { addr: 'E122.4', label: 'APB' },
  { addr: 'E122.5', label: 'IV3' },
  { addr: 'E122.6', label: 'FE3' },
  { addr: 'E122.7', label: '' },
  { addr: 'E123.0', label: 'ECA' },
  { addr: 'E123.1', label: 'ECB' },
  { addr: 'E123.2', label: 'FBBE' },
  { addr: 'E123.3', label: 'FBE' },
  { addr: 'E123.4', label: 'FPE' },
  { addr: 'E123.5', label: 'FDR1' },
  { addr: 'E123.6', label: 'FDL1' },
  { addr: 'E123.7', label: 'FDR1-1' },
  { addr: 'E124.0', label: 'FDL1-1' },
  { addr: 'E124.1', label: 'FLP1' },
  { addr: 'E124.2', label: 'FLA1' },
  { addr: 'E124.3', label: 'FTA1' },
  { addr: 'E124.4', label: 'FTA2' },
  { addr: 'E124.5', label: 'FTA2-1' },
  { addr: 'E124.6', label: 'EBZE' },
  { addr: 'E124.7', label: 'EBOE' },
  { addr: 'E125.0', label: 'EZE' },
  { addr: 'E125.1', label: 'EOE' },
  { addr: 'E125.2', label: 'FRER' },
  { addr: 'E125.3', label: 'FREL' },
  { addr: 'E125.4', label: '' },
  { addr: 'E125.5', label: 'FDR2' },
  { addr: 'E125.6', label: 'FDL2' },
  { addr: 'E125.7', label: 'LOOP' },
  { addr: 'E126.0', label: 'FPA' },
  { addr: 'E126.1', label: 'FBA' },
  { addr: 'E126.2', label: 'FBBA' },
  { addr: 'E126.3', label: 'EZA' },
  { addr: 'E126.4', label: 'EOA' },
  { addr: 'E126.5', label: 'EBZA' },
  { addr: 'E126.6', label: 'EBOA' },
  { addr: 'E126.7', label: 'ET1' },
  { addr: 'E127.0', label: 'ET2' },
  { addr: 'E127.1', label: 'FTC' },
  { addr: 'E127.2', label: '' },
  { addr: 'E127.3', label: '' },
  { addr: 'E127.4', label: '' },
  { addr: 'E127.5', label: '' },
  { addr: 'E127.6', label: '' },
  { addr: 'E127.7', label: '' }
]

export const outputs1 = [
  { addr: 'A0.0', label: '' },
  { addr: 'A0.1', label: '' },
  { addr: 'A0.2', label: '' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: 'SBK1' },
  { addr: 'A100.1', label: 'SBK2' },
  { addr: 'A100.2', label: 'STO1-1' },
  { addr: 'A100.3', label: 'STO2-1' },
  { addr: 'A100.4', label: 'LA' },
  { addr: 'A100.5', label: 'LC' },
  { addr: 'A100.6', label: '' },
  { addr: 'A100.7', label: '' },
  { addr: 'A101.0', label: '' },
  { addr: 'A101.1', label: '' },
  { addr: 'A101.2', label: '' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: '' },
  { addr: 'A101.7', label: '' },
  { addr: 'A102.0', label: '' },
  { addr: 'A102.1', label: '' },
  { addr: 'A102.2', label: '' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: '' },
  { addr: 'A103.1', label: '' },
  { addr: 'A103.2', label: '' },
  { addr: 'A103.3', label: '' },
  { addr: 'A103.4', label: '' },
  { addr: 'A103.5', label: '' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: '' }
]
export const outputs3 = [
  { addr: 'A110.0', label: 'SMA' },
  { addr: 'A110.1', label: 'SMB' },
  { addr: 'A110.2', label: 'TCR' },
  { addr: 'A110.3', label: 'LA' },
  { addr: 'A110.4', label: 'LC' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' },
  { addr: 'A112.0', label: 'DYA' },
  { addr: 'A112.1', label: 'DYB' },
  { addr: 'A112.2', label: 'DYC' },
  { addr: 'A112.3', label: 'DYD' },
  { addr: 'A112.4', label: 'AD1' },
  { addr: 'A112.5', label: 'AD2' },
  { addr: 'A112.6', label: 'AD3' },
  { addr: 'A112.7', label: 'STR' },
  { addr: 'A113.0', label: 'LC' },
  { addr: 'A113.1', label: 'T10F' },
  { addr: 'A113.2', label: '' },
  { addr: 'A113.3', label: 'TRA' },
  { addr: 'A113.4', label: 'TRB' },
  { addr: 'A113.5', label: 'TCR' },
  { addr: 'A113.6', label: 'KCS' },
  { addr: 'A113.7', label: 'KCV' },
  { addr: 'A114.0', label: 'KCH' },
  { addr: 'A114.1', label: 'LA' },
  { addr: 'A114.2', label: 'T101' },
  { addr: 'A114.3', label: 'T102' },
  { addr: 'A114.4', label: 'T2' },
  { addr: 'A114.5', label: 'STO1-2' },
  { addr: 'A114.6', label: 'STO2-2' },
  { addr: 'A114.7', label: '' },
  { addr: 'A115.0', label: '' },
  { addr: 'A115.1', label: '' },
  { addr: 'A115.2', label: '' },
  { addr: 'A115.3', label: '' },
  { addr: 'A115.4', label: '' },
  { addr: 'A115.5', label: '' },
  { addr: 'A115.6', label: '' },
  { addr: 'A115.7', label: '' }
]
export const outputs4 = [
  { addr: 'A120.0', label: 'DYA' },
  { addr: 'A120.1', label: 'DYB' },
  { addr: 'A120.2', label: 'DYC' },
  { addr: 'A120.3', label: 'DYD' },
  { addr: 'A120.4', label: 'AD1' },
  { addr: 'A120.5', label: 'AD2' },
  { addr: 'A120.6', label: 'AD3' },
  { addr: 'A120.7', label: 'STR' },
  { addr: 'A121.0', label: 'SBK2' },
  { addr: 'A121.1', label: '' },
  { addr: 'A121.2', label: 'STO1-3' },
  { addr: 'A121.3', label: 'STO2-3' },
  { addr: 'A121.4', label: 'LA' },
  { addr: 'A121.5', label: 'LC' },
  { addr: 'A121.6', label: 'SCA' },
  { addr: 'A121.7', label: 'SCB' },
  { addr: 'A122.0', label: 'SPE' },
  { addr: 'A122.1', label: 'SOE' },
  { addr: 'A122.2', label: 'SZE' },
  { addr: 'A122.3', label: 'SPBE' },
  { addr: 'A122.4', label: 'SBOE' },
  { addr: 'A122.5', label: 'SBZE' },
  { addr: 'A122.6', label: 'SPA' },
  { addr: 'A122.7', label: 'SOA' },
  { addr: 'A123.0', label: 'SZA' },
  { addr: 'A123.1', label: 'SPBA' },
  { addr: 'A123.2', label: 'SBOA' },
  { addr: 'A123.3', label: 'SBZA' },
  { addr: 'A123.4', label: 'RFE' },
  { addr: 'A123.5', label: 'RFA' },
  { addr: 'A123.6', label: '' },
  { addr: 'A123.7', label: '' }
]
export const alarms1 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'E1' },
  { id: 5, key: 'E2' },
  { id: 6, key: 'E3' },
  { id: 7, key: 'U1' },
  { id: 8, key: 'U2' },
  { id: 9, key: 'U3' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
