// generate I/O
exports.inputs1 = [
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'EBZE' },
  { addr: 'E5.1', label: 'EBOE' },
  { addr: 'E5.2', label: 'FBBE' },
  { addr: 'E5.3', label: 'TM1' },
  { addr: 'E5.4', label: 'TM2' },
  { addr: 'E5.5', label: 'SQA' },
  { addr: 'E5.6', label: 'SQB' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'ECA' },
  { addr: 'E6.1', label: 'ECB' },
  { addr: 'E6.2', label: 'AMC' },
  { addr: 'E6.3', label: 'EXD' },
  { addr: 'E6.4', label: 'AD' },
  { addr: 'E6.5', label: 'ASKA' },
  { addr: 'E6.6', label: 'FE' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: 'IV1A' },
  { addr: 'E7.1', label: 'TJ1' },
  { addr: 'E7.2', label: 'SA' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: 'IV2' },
  { addr: 'E7.7', label: 'IV1B' },
  { addr: 'E8.0', label: 'APL' },
  { addr: 'E8.1', label: 'EZEL' },
  { addr: 'E8.2', label: 'EOEL' },
  { addr: 'E8.3', label: 'APBE' },
  { addr: 'E8.4', label: 'FSBK' },
  { addr: 'E8.5', label: 'ASBK' },
  { addr: 'E8.6', label: 'RTA' },
  { addr: 'E8.7', label: 'KBAA' },
  { addr: 'E9.0', label: 'EPZV1' },
  { addr: 'E9.1', label: 'EPZH1' },
  { addr: 'E9.2', label: 'EPZV2' },
  { addr: 'E9.3', label: 'EPZH2' },
  { addr: 'E9.4', label: 'FXR' },
  { addr: 'E9.5', label: 'FXL' },
  { addr: 'E9.6', label: 'POD' },
  { addr: 'E9.7', label: 'KBAB' },
  { addr: 'E10.0', label: 'APR' },
  { addr: 'E10.1', label: 'EZER' },
  { addr: 'E10.2', label: 'EOER' },
  { addr: 'E10.3', label: 'FBE' },
  { addr: 'E10.4', label: 'FPE' },
  { addr: 'E10.5', label: 'FDR1' },
  { addr: 'E10.6', label: 'FDL1' },
  { addr: 'E10.7', label: 'FTA1' },
  { addr: 'E11.0', label: 'FTA2' },
  { addr: 'E11.1', label: 'FLP1' },
  { addr: 'E11.2', label: 'FLA1' },
  { addr: 'E11.3', label: 'FLP2' },
  { addr: 'E11.4', label: 'FLA2' },
  { addr: 'E11.5', label: 'TLC' },
  { addr: 'E11.6', label: 'FTA3' },
  { addr: 'E11.7', label: 'RXE' }
]
exports.inputs2 = [
  { addr: 'E12.0', label: 'EV32' },
  { addr: 'E12.1', label: 'EV33' },
  { addr: 'E12.2', label: 'EV48' },
  { addr: 'E12.3', label: 'EV49' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E24.0', label: 'AGL' },
  { addr: 'E24.1', label: 'ACR1' },
  { addr: 'E24.2', label: 'TCR1' },
  { addr: 'E24.3', label: '' },
  { addr: 'E24.4', label: '' },
  { addr: 'E24.5', label: '' },
  { addr: 'E24.6', label: '' },
  { addr: 'E24.7', label: '' },
  { addr: 'E25.0', label: 'EXPV' },
  { addr: 'E25.1', label: '' },
  { addr: 'E25.2', label: 'AMM' },
  { addr: 'E25.3', label: 'EOM' },
  { addr: 'E25.4', label: 'EZM' },
  { addr: 'E25.5', label: 'EMC' },
  { addr: 'E25.6', label: 'FTXV' },
  { addr: 'E25.7', label: 'FTXH' }
]
exports.inputs4 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'FTV' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: 'FEMV' },
  { addr: 'E1.5', label: 'FEMH' },
  { addr: 'E1.6', label: 'FTXV' },
  { addr: 'E1.7', label: 'FTXH' },
  { addr: 'E2.0', label: 'RMV' },
  { addr: 'E2.1', label: 'RMH' },
  { addr: 'E2.2', label: 'RES' },
  { addr: 'E2.3', label: 'REH' },
  { addr: 'E2.4', label: 'RCV' },
  { addr: 'E2.5', label: 'REAV' },
  { addr: 'E2.6', label: 'REAH' },
  { addr: 'E2.7', label: 'RCH' },
  { addr: 'E3.0', label: 'IV' },
  { addr: 'E3.1', label: 'TJ1' },
  { addr: 'E3.2', label: 'SA' },
  { addr: 'E3.3', label: 'RSI' },
  { addr: 'E3.4', label: 'DB32' },
  { addr: 'E3.5', label: 'DBHZ' },
  { addr: 'E3.6', label: 'FE' },
  { addr: 'E3.7', label: 'UC' },
  { addr: 'E4.0', label: '' },
  { addr: 'E4.1', label: '' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: 'ACRE' },
  { addr: 'E4.4', label: 'TCRE' },
  { addr: 'E4.5', label: 'TCR' },
  { addr: 'E4.6', label: 'AH' },
  { addr: 'E4.7', label: 'MTC' }
]
exports.outputs1 = [
  { addr: 'A4.0', label: 'SBK1' },
  { addr: 'A4.1', label: 'KBAA' },
  { addr: 'A4.2', label: 'SPR' },
  { addr: 'A4.3', label: 'SPL' },
  { addr: 'A4.4', label: 'SBZE' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: 'TD' },
  { addr: 'A4.7', label: 'KBA2' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'KEM' },
  { addr: 'A6.0', label: 'SBK2' },
  { addr: 'A6.1', label: 'SPBE' },
  { addr: 'A6.2', label: 'SCA' },
  { addr: 'A6.3', label: 'SCB' },
  { addr: 'A6.4', label: 'KBAB' },
  { addr: 'A6.5', label: 'LC1' },
  { addr: 'A6.6', label: 'LA' },
  { addr: 'A6.7', label: 'LC' },
  { addr: 'A7.0', label: 'A' },
  { addr: 'A7.1', label: 'B' },
  { addr: 'A7.2', label: 'C' },
  { addr: 'A7.3', label: 'D' },
  { addr: 'A7.4', label: 'AD1' },
  { addr: 'A7.5', label: 'AD2' },
  { addr: 'A7.6', label: 'AD3' },
  { addr: 'A7.7', label: 'STR' }
]
exports.outputs2 = [
  { addr: 'A12.0', label: 'LKE' },
  { addr: 'A12.1', label: 'LEE' },
  { addr: 'A12.2', label: 'LBE' },
  { addr: 'A12.3', label: 'RDY' },
  { addr: 'A12.4', label: 'RST' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: '' },
  { addr: 'A12.7', label: 'RBE' }
]
exports.outputs3 = [
  { addr: 'A24.0', label: 'SMA' },
  { addr: 'A24.1', label: 'SMB' },
  { addr: 'A24.2', label: 'TCR1' },
  { addr: 'A24.3', label: 'TLS2' },
  { addr: 'A24.4', label: '' },
  { addr: 'A24.5', label: '' },
  { addr: 'A24.6', label: '' },
  { addr: 'A24.7', label: 'RL' },
  { addr: 'A25.0', label: '' },
  { addr: 'A25.1', label: '' },
  { addr: 'A25.2', label: '' },
  { addr: 'A25.3', label: '' },
  { addr: 'A25.4', label: '' },
  { addr: 'A25.5', label: '' },
  { addr: 'A25.6', label: '' },
  { addr: 'A25.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A0.0', label: 'KBA' },
  { addr: 'A0.1', label: 'TCRE' },
  { addr: 'A0.2', label: 'TCVE' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: 'T10F' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'LC' },
  { addr: 'A1.0', label: 'A' },
  { addr: 'A1.1', label: 'B' },
  { addr: 'A1.2', label: 'C' },
  { addr: 'A1.3', label: 'D' },
  { addr: 'A1.4', label: 'AD1' },
  { addr: 'A1.5', label: 'AD2' },
  { addr: 'A1.6', label: 'AD3' },
  { addr: 'A1.7', label: 'STR' },
  { addr: 'A2.0', label: 'T10' },
  { addr: 'A2.1', label: 'T2' },
  { addr: 'A2.2', label: 'TRA' },
  { addr: 'A2.3', label: 'TRB' },
  { addr: 'A2.4', label: 'KCS' },
  { addr: 'A2.5', label: 'KCV' },
  { addr: 'A2.6', label: 'KCH' },
  { addr: 'A2.7', label: 'TCR' }
]
exports.ALARMS = [
  { id: 1, key: 'al-v-to', query: {} },
  { id: 2, key: 'al-lv', query: {} },
  { id: 3, key: 'al-fc', query: { fc1: 'EFA', fc2: 'EFB' } },
  { id: 4, key: 'al-iv', query: { nr: 1 } },
  { id: 5, key: '', query: {} },
  { id: 6, key: 'al-v-fdbk', query: {} },
  { id: 7, key: 'al-v-lck-to', query: {} },
  { id: 8, key: 'al-v-lck-fc', query: {} },
  { id: 9, key: 'al-tl', query: { name: 'TCR' } },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: 'al-th', query: { name: '(1)' } },
  { id: 16, key: 'al-th', query: { name: '(2)' } },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-h-to', query: {} },
  { id: 34, key: 'al-lh', query: {} },
  { id: 35, key: 'al-fc', query: { fc1: 'EFL', fc2: 'EFR' } },
  { id: 36, key: 'al-iv', query: { nr: 2 } },
  { id: 37, key: 'al-lh', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: 'al-lh-diff', query: {} },
  { id: 41, key: 'al-sil-01', query: {} },
  { id: 42, key: 'al-sil-11', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: 'al-iv', query: { nr: 2 } },
  { id: 45, key: 'al-sil-05', query: {} },
  { id: 46, key: 'al-sil-06', query: {} },
  { id: 47, key: 'al-sil-13', query: {} },
  { id: 48, key: 'al-sil-07', query: {} },
  { id: 49, key: 'al-sil-15', query: {} },
  { id: 50, key: 'al-tl', query: { name: 'TCRE' } },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: 'al-th', query: { name: 'SHUTTLE' } },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sp-to', query: {} },
  { id: 66, key: 'al-sp-fc', query: {} },
  { id: 67, key: 'al-iv', query: { nr: 3 } },
  { id: 68, key: 'al-flap-to', query: {} },
  { id: 69, key: 'al-flap-fc', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: 'al-spb-to', query: {} },
  { id: 74, key: 'al-spb-fc', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: 'al-th', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: 'al-r-to', query: {} },
  { id: 90, key: 'al-r-fc', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: 'al-iv', query: { nr: 4 } },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'EU' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
