export const inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: '' },
  { addr: 'E4.1', label: '' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: '' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: '' },
  { addr: 'E4.6', label: '' },
  { addr: 'E4.7', label: '' },
  { addr: 'E5.0', label: '' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: '' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: '' },
  { addr: 'E6.4', label: '' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: '' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' }
]
export const inputs2 = [
  { addr: 'E12.0', label: '' },
  { addr: 'E12.1', label: '' },
  { addr: 'E12.2', label: '' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: '' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' },
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: '' },
  { addr: 'E14.2', label: '' },
  { addr: 'E14.3', label: '' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' },
  { addr: 'E16.0', label: '' },
  { addr: 'E16.1', label: '' },
  { addr: 'E16.2', label: '' },
  { addr: 'E16.3', label: '' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: '' },
  { addr: 'E17.0', label: '' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: '' },
  { addr: 'E17.3', label: '' },
  { addr: 'E17.4', label: '' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: '' },
  { addr: 'A0.1', label: '' },
  { addr: 'A0.2', label: '' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: '' },
  { addr: 'A4.1', label: '' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: '' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: '' },
  { addr: 'A5.0', label: '' },
  { addr: 'A5.1', label: '' },
  { addr: 'A5.2', label: '' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' },
  { addr: 'A6.0', label: '' },
  { addr: 'A6.1', label: '' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: '' },
  { addr: 'A7.0', label: '' },
  { addr: 'A7.1', label: '' },
  { addr: 'A7.2', label: '' },
  { addr: 'A7.3', label: '' },
  { addr: 'A7.4', label: '' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: '' },
  { addr: 'A7.7', label: '' }
]
export const outputs2 = [
  { addr: 'A12.0', label: '' },
  { addr: 'A12.1', label: '' },
  { addr: 'A12.2', label: '' },
  { addr: 'A12.3', label: '' },
  { addr: 'A12.4', label: '' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: '' },
  { addr: 'A12.7', label: '' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: '' },
  { addr: 'A14.1', label: '' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: '' },
  { addr: 'A14.4', label: '' },
  { addr: 'A14.5', label: '' },
  { addr: 'A14.6', label: '' },
  { addr: 'A14.7', label: '' },
  { addr: 'A15.0', label: '' },
  { addr: 'A15.1', label: '' },
  { addr: 'A15.2', label: '' },
  { addr: 'A15.3', label: '' },
  { addr: 'A15.4', label: '' },
  { addr: 'A15.5', label: '' },
  { addr: 'A15.6', label: '' },
  { addr: 'A15.7', label: '' },
  { addr: 'A16.0', label: '' },
  { addr: 'A16.1', label: '' },
  { addr: 'A16.2', label: '' },
  { addr: 'A16.3', label: '' },
  { addr: 'A16.4', label: '' },
  { addr: 'A16.5', label: '' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' }
]
export const alarms1 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'E' },
  { id: 2, key: 'U' },
  { id: 3, key: 'EL3' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
