export const inputs1 = [
  { addr: 'E0.0', label: 'BA' },
  { addr: 'E0.1', label: 'BB' },
  { addr: 'E0.2', label: 'BC' },
  { addr: 'E0.3', label: 'BD' },
  { addr: 'E0.4', label: 'BSTR' },
  { addr: 'E0.5', label: 'BOK' },
  { addr: 'E0.6', label: 'BDAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'BA' },
  { addr: 'E1.1', label: 'BB' },
  { addr: 'E1.2', label: 'BC' },
  { addr: 'E1.3', label: 'BD' },
  { addr: 'E1.4', label: 'BSTR' },
  { addr: 'E1.5', label: 'BOK' },
  { addr: 'E1.6', label: 'BDAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'SFA' },
  { addr: 'E2.1', label: 'SFB' },
  { addr: 'E2.2', label: 'SFC' },
  { addr: 'E2.3', label: 'SFT1' },
  { addr: 'E2.4', label: 'SFT2' },
  { addr: 'E2.5', label: 'SFT3' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'RSI' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: 'FE' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'A' },
  { addr: 'E101.1', label: 'B' },
  { addr: 'E101.2', label: 'C' },
  { addr: 'E101.3', label: 'D' },
  { addr: 'E101.4', label: 'STR' },
  { addr: 'E101.5', label: 'OK' },
  { addr: 'E101.6', label: 'DAT' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: 'KEXPV' },
  { addr: 'E102.1', label: 'FTC' },
  { addr: 'E102.2', label: 'EXPV' },
  { addr: 'E102.3', label: 'EFB' },
  { addr: 'E102.4', label: 'ECA' },
  { addr: 'E102.5', label: 'ECB' },
  { addr: 'E102.6', label: 'AMC' },
  { addr: 'E102.7', label: 'APE' },
  { addr: 'E103.0', label: 'FTXV' },
  { addr: 'E103.1', label: 'FTXH' },
  { addr: 'E103.2', label: 'RS3' },
  { addr: 'E103.3', label: 'RS12' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'KXPE' },
  { addr: 'E103.7', label: 'AF7' },
  { addr: 'E104.0', label: 'FKBA' },
  { addr: 'E104.1', label: 'ASBK2' },
  { addr: 'E104.2', label: 'SRL' },
  { addr: 'E104.3', label: 'IV1' },
  { addr: 'E104.4', label: 'FSBK' },
  { addr: 'E104.5', label: 'ASBK1' },
  { addr: 'E104.6', label: 'RTA' },
  { addr: 'E104.7', label: 'SQA' },
  { addr: 'E105.0', label: 'FE12' },
  { addr: 'E105.1', label: 'AD' },
  { addr: 'E105.2', label: 'EXD' },
  { addr: 'E105.3', label: 'EOM' },
  { addr: 'E105.4', label: 'EZM' },
  { addr: 'E105.5', label: 'AMM' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: 'FRE' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' },
  { addr: 'E108.0', label: 'EOMD' },
  { addr: 'E108.1', label: 'EZMD' },
  { addr: 'E108.2', label: 'AMD' },
  { addr: 'E108.3', label: 'SPR' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: 'FDR2' },
  { addr: 'E108.7', label: 'FDL2' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
export const inputs5 = [
  { addr: 'E400.0', label: 'FTACR' },
  { addr: 'E400.1', label: '' },
  { addr: 'E400.2', label: 'FTACL' },
  { addr: 'E400.3', label: '' },
  { addr: 'E400.4', label: '' },
  { addr: 'E400.5', label: '' },
  { addr: 'E400.6', label: 'FE1' },
  { addr: 'E400.7', label: 'AF7' },
  { addr: 'E401.0', label: 'IV1' },
  { addr: 'E401.1', label: 'IV2' },
  { addr: 'E401.2', label: '' },
  { addr: 'E401.3', label: 'RS12' },
  { addr: 'E401.4', label: 'RS3' },
  { addr: 'E401.5', label: 'AH' },
  { addr: 'E401.6', label: 'AGF' },
  { addr: 'E401.7', label: 'AKKP' }
]
export const inputs6 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'EM' },
  { addr: 'E411.1', label: 'EXPV' },
  { addr: 'E411.2', label: 'FSBK' },
  { addr: 'E411.3', label: 'ASBK1' },
  { addr: 'E411.4', label: 'FTCR' },
  { addr: 'E411.5', label: 'AGH' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: '' },
  { addr: 'E413.1', label: '' },
  { addr: 'E413.2', label: 'SRL' },
  { addr: 'E413.3', label: '' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTM' },
  { addr: 'E413.7', label: 'UC' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: 'LSA' },
  { addr: 'A1.6', label: 'LSB' },
  { addr: 'A1.7', label: 'LSC' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: 'LST1' },
  { addr: 'A2.6', label: 'LST2' },
  { addr: 'A2.7', label: 'LST3' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: '' },
  { addr: 'A100.1', label: 'KBA' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RBE' },
  { addr: 'A102.0', label: 'SMA' },
  { addr: 'A102.1', label: 'SMB' },
  { addr: 'A102.2', label: 'KQA' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: 'SCA' },
  { addr: 'A102.5', label: 'SCB' },
  { addr: 'A102.6', label: 'TD' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'LK' },
  { addr: 'A103.1', label: 'LE' },
  { addr: 'A103.2', label: 'LB' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: 'SBK2' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: 'KEM' },
  { addr: 'A104.0', label: 'DYA' },
  { addr: 'A104.1', label: 'DYB' },
  { addr: 'A104.2', label: 'DYC' },
  { addr: 'A104.3', label: 'DYD' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: 'SMAD' },
  { addr: 'A105.1', label: 'SMBD' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' },
  { addr: 'A108.0', label: '' },
  { addr: 'A108.1', label: '' },
  { addr: 'A108.2', label: '' },
  { addr: 'A108.3', label: '' },
  { addr: 'A108.4', label: '' },
  { addr: 'A108.5', label: '' },
  { addr: 'A108.6', label: '' },
  { addr: 'A108.7', label: '' },
  { addr: 'A109.0', label: '' },
  { addr: 'A109.1', label: '' },
  { addr: 'A109.2', label: '' },
  { addr: 'A109.3', label: '' },
  { addr: 'A109.4', label: '' },
  { addr: 'A109.5', label: '' },
  { addr: 'A109.6', label: '' },
  { addr: 'A109.7', label: '' }
]
export const outputs5 = [
  { addr: 'A400.0', label: '' },
  { addr: 'A400.1', label: '' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: '' },
  { addr: 'A400.5', label: '' },
  { addr: 'A400.6', label: '' },
  { addr: 'A400.7', label: '' },
  { addr: 'A401.0', label: 'T101' },
  { addr: 'A401.1', label: 'T2' },
  { addr: 'A401.2', label: 'T10F' },
  { addr: 'A401.3', label: 'T102' },
  { addr: 'A401.4', label: 'KBA1' },
  { addr: 'A401.5', label: 'KBA2' },
  { addr: 'A401.6', label: '' },
  { addr: 'A401.7', label: '' }
]
export const outputs6 = [
  { addr: 'A410.0', label: 'DYA' },
  { addr: 'A410.1', label: 'DYB' },
  { addr: 'A410.2', label: 'DYC' },
  { addr: 'A410.3', label: 'DYD' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'AD3' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'SBK1' },
  { addr: 'A411.1', label: '' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'TCS' },
  { addr: 'A411.5', label: 'TCV' },
  { addr: 'A411.6', label: 'TCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'SBK2' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: '' },
  { addr: 'A412.5', label: '' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' },
  { addr: 'A413.0', label: '' },
  { addr: 'A413.1', label: '' },
  { addr: 'A413.2', label: '' },
  { addr: 'A413.3', label: '' },
  { addr: 'A413.4', label: '' },
  { addr: 'A413.5', label: '' },
  { addr: 'A413.6', label: '' },
  { addr: 'A413.7', label: '' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-r-lck-to', query: {} },
  { id: 25, key: 'al-r-lck-fc', query: {} },
  { id: 26, key: 'al-flap-to', query: {} },
  { id: 27, key: 'al-flap-fc', query: {} },
  { id: 28, key: 'al-sp-to', query: {} },
  { id: 29, key: 'al-sp-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: 'al-fs', query: { name: 'RSI' } },
  { id: 49, key: 'al-th', query: { name: 'AMC' } },
  { id: 50, key: 'al-th', query: { name: 'APE' } },
  { id: 51, key: 'al-th', query: { name: 'AF7' } },
  { id: 52, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 53, key: 'al-th', query: { name: 'ASBK' } },
  { id: 54, key: 'al-th', query: { name: 'RT' } },
  { id: 55, key: 'al-th', query: { name: 'FE1' } },
  { id: 56, key: 'al-th', query: { name: 'AD' } },
  { id: 57, key: 'al-th', query: { name: 'AMM' } },
  { id: 58, key: 'al-th', query: { name: 'AMD' } },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-h-to', query: {} },
  { id: 86, key: 'al-lh', query: {} },
  { id: 87, key: 'al-lh-diff', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: 'al-fs', query: { name: 'RSI' } },
  { id: 113, key: 'al-th', query: { name: 'FE1' } },
  { id: 114, key: 'al-th', query: { name: 'AF7' } },
  { id: 115, key: 'al-th', query: { name: 'AH' } },
  { id: 116, key: 'al-th', query: { name: 'AGF' } },
  { id: 117, key: 'al-th', query: { name: 'AKKP' } },
  { id: 118, key: 'al-th', query: { name: 'ASBK' } },
  { id: 119, key: 'al-th', query: { name: 'MTC' } },
  { id: 120, key: 'al-th', query: { name: 'FE4' } },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'T1' },
  { id: 5, key: 'T2' },
  { id: 6, key: 'T3' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
