// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'SFA' },
  { addr: 'E0.1', label: 'SFB' },
  { addr: 'E0.2', label: 'SF1' },
  { addr: 'E0.3', label: 'SF2' },
  { addr: 'E0.4', label: 'FE' },
  { addr: 'E0.5', label: 'RSI' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'IV1' },
  { addr: 'E10.1', label: 'RSI' },
  { addr: 'E10.2', label: 'FDBK' },
  { addr: 'E10.3', label: 'ASBK' },
  { addr: 'E10.4', label: 'RTA' },
  { addr: 'E10.5', label: 'FE' },
  { addr: 'E10.6', label: 'ASH' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: 'DB32' },
  { addr: 'E11.1', label: 'DBHZ' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: 'A' },
  { addr: 'E12.1', label: 'B' },
  { addr: 'E12.2', label: 'C' },
  { addr: 'E12.3', label: 'D' },
  { addr: 'E12.4', label: 'OK' },
  { addr: 'E12.5', label: 'S2' },
  { addr: 'E12.6', label: 'S2' },
  { addr: 'E12.7', label: 'S2' },
  { addr: 'E13.0', label: 'RSI' },
  { addr: 'E13.1', label: 'FE' },
  { addr: 'E13.2', label: 'APE' },
  { addr: 'E13.3', label: 'ALK' },
  { addr: 'E13.4', label: 'APBE' },
  { addr: 'E13.5', label: 'SRL' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: 'UC' },
  { addr: 'E14.0', label: 'EZE' },
  { addr: 'E14.1', label: 'EOE' },
  { addr: 'E14.2', label: 'FBE' },
  { addr: 'E14.3', label: 'FPE' },
  { addr: 'E14.4', label: 'FDR1' },
  { addr: 'E14.5', label: 'FDL1' },
  { addr: 'E14.6', label: 'FDR2' },
  { addr: 'E14.7', label: 'FDL2' },
  { addr: 'E15.0', label: 'FTA1' },
  { addr: 'E15.1', label: 'FTA2' },
  { addr: 'E15.2', label: 'FTA3' },
  { addr: 'E15.3', label: 'FLP' },
  { addr: 'E15.4', label: 'FLA' },
  { addr: 'E15.5', label: 'RX1' },
  { addr: 'E15.6', label: 'RX2' },
  { addr: 'E15.7', label: 'FTS' },
  { addr: 'E16.0', label: 'AMD' },
  { addr: 'E16.1', label: 'EOMD' },
  { addr: 'E16.2', label: 'EZMD' },
  { addr: 'E16.3', label: '' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: 'HMI' },
  { addr: 'E17.0', label: '' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: '' },
  { addr: 'E17.3', label: '' },
  { addr: 'E17.4', label: '' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' },
  { addr: 'E18.0', label: 'AD' },
  { addr: 'E18.1', label: 'MTC' },
  { addr: 'E18.2', label: 'ECA' },
  { addr: 'E18.3', label: 'ECB' },
  { addr: 'E18.4', label: 'AMC' },
  { addr: 'E18.5', label: 'FE' },
  { addr: 'E18.6', label: 'RSI' },
  { addr: 'E18.7', label: 'IV2' },
  { addr: 'E19.0', label: '' },
  { addr: 'E19.1', label: '' },
  { addr: 'E19.2', label: '' },
  { addr: 'E19.3', label: 'EXD' },
  { addr: 'E19.4', label: 'EM' },
  { addr: 'E19.5', label: 'AMM' },
  { addr: 'E19.6', label: 'EOM' },
  { addr: 'E19.7', label: 'EZM' },
  { addr: 'E20.0', label: 'ASKD' },
  { addr: 'E20.1', label: '' },
  { addr: 'E20.2', label: 'FTXV' },
  { addr: 'E20.3', label: 'FTXH' },
  { addr: 'E20.4', label: 'EXPV' },
  { addr: 'E20.5', label: 'EFB' },
  { addr: 'E20.6', label: 'FRER' },
  { addr: 'E20.7', label: 'FREL' },
  { addr: 'E21.0', label: 'RMV' },
  { addr: 'E21.1', label: 'RMH' },
  { addr: 'E21.2', label: 'RES' },
  { addr: 'E21.3', label: 'REH' },
  { addr: 'E21.4', label: 'RCV' },
  { addr: 'E21.5', label: 'REAV' },
  { addr: 'E21.6', label: 'REAH' },
  { addr: 'E21.7', label: 'RCH' }
]
export const inputs3 = [
  { addr: 'E30.0', label: 'IV1' },
  { addr: 'E30.1', label: 'RSI' },
  { addr: 'E30.2', label: 'FDBK' },
  { addr: 'E30.3', label: 'ASBK' },
  { addr: 'E30.4', label: 'RTA' },
  { addr: 'E30.5', label: 'FE' },
  { addr: 'E30.6', label: 'ASH' },
  { addr: 'E30.7', label: '' },
  { addr: 'E31.0', label: '' },
  { addr: 'E31.1', label: '' },
  { addr: 'E31.2', label: '' },
  { addr: 'E31.3', label: '' },
  { addr: 'E31.4', label: '' },
  { addr: 'E31.5', label: '' },
  { addr: 'E31.6', label: '' },
  { addr: 'E31.7', label: '' },
  { addr: 'E32.0', label: 'ASH' },
  { addr: 'E32.1', label: 'ACR' },
  { addr: 'E32.2', label: 'FTCR' },
  { addr: 'E32.3', label: 'FE' },
  { addr: 'E32.4', label: '' },
  { addr: 'E32.5', label: '' },
  { addr: 'E32.6', label: 'FTSH' },
  { addr: 'E32.7', label: '' },
  { addr: 'E33.0', label: '' },
  { addr: 'E33.1', label: '' },
  { addr: 'E33.2', label: 'AMM' },
  { addr: 'E33.3', label: 'EOM' },
  { addr: 'E33.4', label: 'EZM' },
  { addr: 'E33.5', label: 'EMC' },
  { addr: 'E33.6', label: '' },
  { addr: 'E33.7', label: '' },
  { addr: 'E34.0', label: 'A' },
  { addr: 'E34.1', label: 'B' },
  { addr: 'E34.2', label: 'C' },
  { addr: 'E34.3', label: 'D' },
  { addr: 'E34.4', label: 'OK' },
  { addr: 'E34.5', label: 'S2' },
  { addr: 'E34.6', label: 'S2' },
  { addr: 'E34.7', label: 'S2' },
  { addr: 'E35.0', label: 'FE' },
  { addr: 'E35.1', label: '' },
  { addr: 'E35.2', label: '' },
  { addr: 'E35.3', label: 'EM' },
  { addr: 'E35.4', label: '' },
  { addr: 'E35.5', label: '' },
  { addr: 'E35.6', label: 'FTXV' },
  { addr: 'E35.7', label: 'FTXH' },
  { addr: 'E36.0', label: 'RMV' },
  { addr: 'E36.1', label: 'RMH' },
  { addr: 'E36.2', label: 'RES' },
  { addr: 'E36.3', label: 'REH' },
  { addr: 'E36.4', label: 'RCV' },
  { addr: 'E36.5', label: 'REAV' },
  { addr: 'E36.6', label: 'REAH' },
  { addr: 'E36.7', label: 'RCH' },
  { addr: 'E37.0', label: 'IV2' },
  { addr: 'E37.1', label: 'TJ2' },
  { addr: 'E37.2', label: 'SRL' },
  { addr: 'E37.3', label: 'RSI' },
  { addr: 'E37.4', label: 'DB32' },
  { addr: 'E37.5', label: 'DBHZ' },
  { addr: 'E37.6', label: 'FTAC' },
  { addr: 'E37.7', label: 'UC' },
  { addr: 'E38.0', label: 'ATF' },
  { addr: 'E38.1', label: '' },
  { addr: 'E38.2', label: 'FTM' },
  { addr: 'E38.3', label: '' },
  { addr: 'E38.4', label: '' },
  { addr: 'E38.5', label: 'FTCR' },
  { addr: 'E38.6', label: 'AH' },
  { addr: 'E38.7', label: 'MTC' },
  { addr: 'E39.0', label: '' },
  { addr: 'E39.1', label: '' },
  { addr: 'E39.2', label: '' },
  { addr: 'E39.3', label: '' },
  { addr: 'E39.4', label: '' },
  { addr: 'E39.5', label: '' },
  { addr: 'E39.6', label: '' },
  { addr: 'E39.7', label: '' }
]
export const inputs4 = [
  { addr: 'E40.0', label: 'IV1' },
  { addr: 'E40.1', label: 'RSI' },
  { addr: 'E40.2', label: 'FDBK' },
  { addr: 'E40.3', label: 'ASBK' },
  { addr: 'E40.4', label: 'RTA' },
  { addr: 'E40.5', label: 'FE' },
  { addr: 'E40.6', label: 'ASH' },
  { addr: 'E40.7', label: '' },
  { addr: 'E41.0', label: '' },
  { addr: 'E41.1', label: '' },
  { addr: 'E41.2', label: 'DB32' },
  { addr: 'E41.3', label: 'DBHZ' },
  { addr: 'E41.4', label: '' },
  { addr: 'E41.5', label: '' },
  { addr: 'E41.6', label: '' },
  { addr: 'E41.7', label: '' },
  { addr: 'E42.0', label: 'A' },
  { addr: 'E42.1', label: 'B' },
  { addr: 'E42.2', label: 'C' },
  { addr: 'E42.3', label: 'D' },
  { addr: 'E42.4', label: 'AD1' },
  { addr: 'E42.5', label: 'AD2' },
  { addr: 'E42.6', label: 'AD3' },
  { addr: 'E42.7', label: 'STR' },
  { addr: 'E43.0', label: 'RSI' },
  { addr: 'E43.1', label: 'FE' },
  { addr: 'E43.2', label: 'APE' },
  { addr: 'E43.3', label: 'ALK' },
  { addr: 'E43.4', label: 'APBE' },
  { addr: 'E43.5', label: 'SRL' },
  { addr: 'E43.6', label: '' },
  { addr: 'E43.7', label: 'UC' },
  { addr: 'E44.0', label: 'EZE' },
  { addr: 'E44.1', label: 'EOE' },
  { addr: 'E44.2', label: 'FBE' },
  { addr: 'E44.3', label: 'FPE' },
  { addr: 'E44.4', label: 'FDR1' },
  { addr: 'E44.5', label: 'FDL1' },
  { addr: 'E44.6', label: 'FDR2' },
  { addr: 'E44.7', label: 'FDL2' },
  { addr: 'E45.0', label: 'FTA1' },
  { addr: 'E45.1', label: 'FTA2' },
  { addr: 'E45.2', label: 'FTA2-2' },
  { addr: 'E45.3', label: 'FLP' },
  { addr: 'E45.4', label: 'FLA' },
  { addr: 'E45.5', label: 'RX1' },
  { addr: 'E45.6', label: 'RX2' },
  { addr: 'E45.7', label: 'FTS' },
  { addr: 'E46.0', label: 'AMD' },
  { addr: 'E46.1', label: 'EOMD' },
  { addr: 'E46.2', label: 'EZMD' },
  { addr: 'E46.3', label: '' },
  { addr: 'E46.4', label: '' },
  { addr: 'E46.5', label: '' },
  { addr: 'E46.6', label: '' },
  { addr: 'E46.7', label: 'HMI' },
  { addr: 'E47.0', label: '' },
  { addr: 'E47.1', label: '' },
  { addr: 'E47.2', label: '' },
  { addr: 'E47.3', label: '' },
  { addr: 'E47.4', label: '' },
  { addr: 'E47.5', label: '' },
  { addr: 'E47.6', label: '' },
  { addr: 'E47.7', label: '' },
  { addr: 'E48.0', label: 'AD' },
  { addr: 'E48.1', label: '' },
  { addr: 'E48.2', label: 'ECA' },
  { addr: 'E48.3', label: 'ECB' },
  { addr: 'E48.4', label: 'AMC' },
  { addr: 'E48.5', label: 'FE' },
  { addr: 'E48.6', label: 'RSI' },
  { addr: 'E48.7', label: 'IV2' },
  { addr: 'E49.0', label: '' },
  { addr: 'E49.1', label: '' },
  { addr: 'E49.2', label: '' },
  { addr: 'E49.3', label: 'EXD' },
  { addr: 'E49.4', label: '' },
  { addr: 'E49.5', label: 'AMM' },
  { addr: 'E49.6', label: 'EOM' },
  { addr: 'E49.7', label: 'EZM' },
  { addr: 'E50.0', label: 'ASKD' },
  { addr: 'E50.1', label: 'FTC' },
  { addr: 'E50.2', label: 'FTXV' },
  { addr: 'E50.3', label: 'FTXH' },
  { addr: 'E50.4', label: 'EXPV' },
  { addr: 'E50.5', label: 'EFB' },
  { addr: 'E50.6', label: 'FRER' },
  { addr: 'E50.7', label: 'FREL' },
  { addr: 'E51.0', label: '' },
  { addr: 'E51.1', label: '' },
  { addr: 'E51.2', label: '' },
  { addr: 'E51.3', label: '' },
  { addr: 'E51.4', label: '' },
  { addr: 'E51.5', label: '' },
  { addr: 'E51.6', label: '' },
  { addr: 'E51.7', label: '' }
]
export const inputs5 = [
  { addr: 'E60.0', label: 'IV1' },
  { addr: 'E60.1', label: 'RSI' },
  { addr: 'E60.2', label: 'FDBK' },
  { addr: 'E60.3', label: 'ASBK' },
  { addr: 'E60.4', label: 'RTA' },
  { addr: 'E60.5', label: 'FE' },
  { addr: 'E60.6', label: 'ASH' },
  { addr: 'E60.7', label: '' },
  { addr: 'E61.0', label: '' },
  { addr: 'E61.1', label: '' },
  { addr: 'E61.2', label: '' },
  { addr: 'E61.3', label: '' },
  { addr: 'E61.4', label: '' },
  { addr: 'E61.5', label: '' },
  { addr: 'E61.6', label: '' },
  { addr: 'E61.7', label: '' },
  { addr: 'E62.0', label: 'ASH' },
  { addr: 'E62.1', label: 'ACR' },
  { addr: 'E62.2', label: 'FTCR' },
  { addr: 'E62.3', label: 'FE' },
  { addr: 'E62.4', label: '' },
  { addr: 'E62.5', label: '' },
  { addr: 'E62.6', label: 'FTSH' },
  { addr: 'E62.7', label: '' },
  { addr: 'E63.0', label: '' },
  { addr: 'E63.1', label: '' },
  { addr: 'E63.2', label: 'AMM' },
  { addr: 'E63.3', label: 'EOM' },
  { addr: 'E63.4', label: 'EZM' },
  { addr: 'E63.5', label: 'EMC' },
  { addr: 'E63.6', label: 'EXH' },
  { addr: 'E63.7', label: '' },
  { addr: 'E64.0', label: 'A' },
  { addr: 'E64.1', label: 'B' },
  { addr: 'E64.2', label: 'C' },
  { addr: 'E64.3', label: 'D' },
  { addr: 'E64.4', label: 'OK' },
  { addr: 'E64.5', label: 'S2' },
  { addr: 'E64.6', label: 'S2' },
  { addr: 'E64.7', label: 'S2' },
  { addr: 'E65.0', label: 'FE' },
  { addr: 'E65.1', label: '' },
  { addr: 'E65.2', label: '' },
  { addr: 'E65.3', label: 'EM' },
  { addr: 'E65.4', label: '' },
  { addr: 'E65.5', label: '' },
  { addr: 'E65.6', label: 'FTXV' },
  { addr: 'E65.7', label: 'FTXH' },
  { addr: 'E66.0', label: 'RMV' },
  { addr: 'E66.1', label: 'RMH' },
  { addr: 'E66.2', label: 'RES' },
  { addr: 'E66.3', label: 'REH' },
  { addr: 'E66.4', label: 'RCV' },
  { addr: 'E66.5', label: 'REAV' },
  { addr: 'E66.6', label: 'REAH' },
  { addr: 'E66.7', label: 'RCH' },
  { addr: 'E67.0', label: 'IV2' },
  { addr: 'E67.1', label: 'TJ2' },
  { addr: 'E67.2', label: 'SRL' },
  { addr: 'E67.3', label: 'RSI' },
  { addr: 'E67.4', label: 'DB32' },
  { addr: 'E67.5', label: 'DBHZ' },
  { addr: 'E67.6', label: 'FTAC' },
  { addr: 'E67.7', label: 'UC' },
  { addr: 'E68.0', label: 'ATF' },
  { addr: 'E68.1', label: '' },
  { addr: 'E68.2', label: 'FTM' },
  { addr: 'E68.3', label: '' },
  { addr: 'E68.4', label: '' },
  { addr: 'E68.5', label: 'FTCR' },
  { addr: 'E68.6', label: 'AH' },
  { addr: 'E68.7', label: 'MTC' },
  { addr: 'E69.0', label: '' },
  { addr: 'E69.1', label: '' },
  { addr: 'E69.2', label: '' },
  { addr: 'E69.3', label: '' },
  { addr: 'E69.4', label: '' },
  { addr: 'E69.5', label: '' },
  { addr: 'E69.6', label: '' },
  { addr: 'E69.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LSA' },
  { addr: 'A0.1', label: 'LSB' },
  { addr: 'A0.2', label: 'LS1' },
  { addr: 'A0.3', label: 'LS2' },
  { addr: 'A0.4', label: 'LA' },
  { addr: 'A0.5', label: 'LC' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'SBK1' },
  { addr: 'A10.1', label: 'SBK2' },
  { addr: 'A10.2', label: 'KBA1' },
  { addr: 'A10.3', label: '' },
  { addr: 'A10.4', label: 'LA' },
  { addr: 'A10.5', label: 'LC' },
  { addr: 'A10.6', label: '' },
  { addr: 'A10.7', label: '' },
  { addr: 'A11.0', label: '' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: '' },
  { addr: 'A11.3', label: '' },
  { addr: 'A11.4', label: '' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: '' },
  { addr: 'A11.7', label: '' },
  { addr: 'A12.0', label: 'DYA' },
  { addr: 'A12.1', label: 'DYB' },
  { addr: 'A12.2', label: 'DYC' },
  { addr: 'A12.3', label: 'DYD' },
  { addr: 'A12.4', label: 'AD1' },
  { addr: 'A12.5', label: 'AD2' },
  { addr: 'A12.6', label: 'AD3' },
  { addr: 'A12.7', label: 'STR' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: 'LA' },
  { addr: 'A13.2', label: 'LC' },
  { addr: 'A13.3', label: 'SMAD' },
  { addr: 'A13.4', label: 'SMBD' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: 'L1' },
  { addr: 'A14.1', label: 'L2' },
  { addr: 'A14.2', label: 'L3' },
  { addr: 'A14.3', label: 'L4' },
  { addr: 'A14.4', label: 'L5' },
  { addr: 'A14.5', label: 'SBOE' },
  { addr: 'A14.6', label: 'KXPE' },
  { addr: 'A14.7', label: 'RFE' },
  { addr: 'A15.0', label: 'SBZE' },
  { addr: 'A15.1', label: 'SZE' },
  { addr: 'A15.2', label: 'SOE' },
  { addr: 'A15.3', label: '' },
  { addr: 'A15.4', label: '' },
  { addr: 'A15.5', label: '' },
  { addr: 'A15.6', label: '' },
  { addr: 'A15.7', label: '' },
  { addr: 'A16.0', label: 'SCA' },
  { addr: 'A16.1', label: 'SCB' },
  { addr: 'A16.2', label: 'TDF' },
  { addr: 'A16.3', label: 'LA' },
  { addr: 'A16.4', label: 'LC' },
  { addr: 'A16.5', label: 'SMA' },
  { addr: 'A16.6', label: 'SMB' },
  { addr: 'A16.7', label: 'TD' },
  { addr: 'A17.0', label: 'T2' },
  { addr: 'A17.1', label: 'TRA' },
  { addr: 'A17.2', label: 'TRB' },
  { addr: 'A17.3', label: 'KCS' },
  { addr: 'A17.4', label: 'KCV' },
  { addr: 'A17.5', label: 'KCH' },
  { addr: 'A17.6', label: 'KBA2' },
  { addr: 'A17.7', label: '' }
]
export const outputs3 = [
  { addr: 'A30.0', label: 'SBK1' },
  { addr: 'A30.1', label: 'SBK2' },
  { addr: 'A30.2', label: 'KBA1' },
  { addr: 'A30.3', label: '' },
  { addr: 'A30.4', label: 'LA' },
  { addr: 'A30.5', label: 'LC' },
  { addr: 'A30.6', label: '' },
  { addr: 'A30.7', label: '' },
  { addr: 'A31.0', label: '' },
  { addr: 'A31.1', label: '' },
  { addr: 'A31.2', label: '' },
  { addr: 'A31.3', label: '' },
  { addr: 'A31.4', label: '' },
  { addr: 'A31.5', label: '' },
  { addr: 'A31.6', label: '' },
  { addr: 'A31.7', label: '' },
  { addr: 'A32.0', label: 'SMA' },
  { addr: 'A32.1', label: 'SMB' },
  { addr: 'A32.2', label: 'TCR' },
  { addr: 'A32.3', label: 'LA' },
  { addr: 'A32.4', label: 'LC' },
  { addr: 'A32.5', label: '' },
  { addr: 'A32.6', label: '' },
  { addr: 'A32.7', label: '' },
  { addr: 'A33.0', label: '' },
  { addr: 'A33.1', label: '' },
  { addr: 'A33.2', label: '' },
  { addr: 'A33.3', label: '' },
  { addr: 'A33.4', label: '' },
  { addr: 'A33.5', label: '' },
  { addr: 'A33.6', label: '' },
  { addr: 'A33.7', label: '' },
  { addr: 'A34.0', label: 'DYA' },
  { addr: 'A34.1', label: 'DYB' },
  { addr: 'A34.2', label: 'DYC' },
  { addr: 'A34.3', label: 'DYD' },
  { addr: 'A34.4', label: 'AD1' },
  { addr: 'A34.5', label: 'AD2' },
  { addr: 'A34.6', label: 'AD3' },
  { addr: 'A34.7', label: 'STR' },
  { addr: 'A35.0', label: 'T101' },
  { addr: 'A35.1', label: 'T2' },
  { addr: 'A35.2', label: 'TRA' },
  { addr: 'A35.3', label: 'TRB' },
  { addr: 'A35.4', label: 'KCS' },
  { addr: 'A35.5', label: 'KCV' },
  { addr: 'A35.6', label: 'KCH' },
  { addr: 'A35.7', label: 'TCR' },
  { addr: 'A36.0', label: 'KBA2' },
  { addr: 'A36.1', label: '' },
  { addr: 'A36.2', label: '' },
  { addr: 'A36.3', label: '' },
  { addr: 'A36.4', label: 'T102' },
  { addr: 'A36.5', label: 'T10F' },
  { addr: 'A36.6', label: 'LA' },
  { addr: 'A36.7', label: 'LC' },
  { addr: 'A37.0', label: '' },
  { addr: 'A37.1', label: '' },
  { addr: 'A37.2', label: '' },
  { addr: 'A37.3', label: '' },
  { addr: 'A37.4', label: '' },
  { addr: 'A37.5', label: '' },
  { addr: 'A37.6', label: '' },
  { addr: 'A37.7', label: '' }
]
export const outputs4 = [
  { addr: 'A40.0', label: 'SBK1' },
  { addr: 'A40.1', label: 'SBK2' },
  { addr: 'A40.2', label: 'KBA1' },
  { addr: 'A40.3', label: '' },
  { addr: 'A40.4', label: 'LA' },
  { addr: 'A40.5', label: 'LC' },
  { addr: 'A40.6', label: '' },
  { addr: 'A40.7', label: '' },
  { addr: 'A41.0', label: '' },
  { addr: 'A41.1', label: '' },
  { addr: 'A41.2', label: '' },
  { addr: 'A41.3', label: '' },
  { addr: 'A41.4', label: '' },
  { addr: 'A41.5', label: '' },
  { addr: 'A41.6', label: '' },
  { addr: 'A41.7', label: '' },
  { addr: 'A42.0', label: 'DYA' },
  { addr: 'A42.1', label: 'DYB' },
  { addr: 'A42.2', label: 'DYC' },
  { addr: 'A42.3', label: 'DYD' },
  { addr: 'A42.4', label: 'AD1' },
  { addr: 'A42.5', label: 'AD2' },
  { addr: 'A42.6', label: 'AD3' },
  { addr: 'A42.7', label: 'STR' },
  { addr: 'A43.0', label: '' },
  { addr: 'A43.1', label: 'LA' },
  { addr: 'A43.2', label: 'LC' },
  { addr: 'A43.3', label: 'SMAD' },
  { addr: 'A43.4', label: 'SMBD' },
  { addr: 'A43.5', label: '' },
  { addr: 'A43.6', label: '' },
  { addr: 'A43.7', label: '' },
  { addr: 'A44.0', label: 'L1' },
  { addr: 'A44.1', label: 'L2' },
  { addr: 'A44.2', label: 'L3' },
  { addr: 'A44.3', label: 'L4' },
  { addr: 'A44.4', label: 'L5' },
  { addr: 'A44.5', label: 'SBOE' },
  { addr: 'A44.6', label: 'KXPE' },
  { addr: 'A44.7', label: 'RFE' },
  { addr: 'A45.0', label: 'SBZE' },
  { addr: 'A45.1', label: 'SZE' },
  { addr: 'A45.2', label: 'SOE' },
  { addr: 'A45.3', label: '' },
  { addr: 'A45.4', label: '' },
  { addr: 'A45.5', label: '' },
  { addr: 'A45.6', label: '' },
  { addr: 'A45.7', label: '' },
  { addr: 'A46.0', label: 'SCA' },
  { addr: 'A46.1', label: 'SCB' },
  { addr: 'A46.2', label: 'TDF' },
  { addr: 'A46.3', label: 'LA' },
  { addr: 'A46.4', label: 'LC' },
  { addr: 'A46.5', label: 'SMA' },
  { addr: 'A46.6', label: 'SMB' },
  { addr: 'A46.7', label: 'TD' },
  { addr: 'A47.0', label: '' },
  { addr: 'A47.1', label: '' },
  { addr: 'A47.2', label: '' },
  { addr: 'A47.3', label: '' },
  { addr: 'A47.4', label: '' },
  { addr: 'A47.5', label: '' },
  { addr: 'A47.6', label: 'KBA2' },
  { addr: 'A47.7', label: '' }
]
export const outputs5 = [
  { addr: 'A60.0', label: 'SBK1' },
  { addr: 'A60.1', label: 'SBK2' },
  { addr: 'A60.2', label: 'KBA1' },
  { addr: 'A60.3', label: '' },
  { addr: 'A60.4', label: 'LA' },
  { addr: 'A60.5', label: 'LC' },
  { addr: 'A60.6', label: '' },
  { addr: 'A60.7', label: '' },
  { addr: 'A61.0', label: '' },
  { addr: 'A61.1', label: '' },
  { addr: 'A61.2', label: '' },
  { addr: 'A61.3', label: '' },
  { addr: 'A61.4', label: '' },
  { addr: 'A61.5', label: '' },
  { addr: 'A61.6', label: '' },
  { addr: 'A61.7', label: '' },
  { addr: 'A62.0', label: 'SMA' },
  { addr: 'A62.1', label: 'SMB' },
  { addr: 'A62.2', label: 'TCR' },
  { addr: 'A62.3', label: 'LA' },
  { addr: 'A62.4', label: 'LC' },
  { addr: 'A62.5', label: '' },
  { addr: 'A62.6', label: '' },
  { addr: 'A62.7', label: '' },
  { addr: 'A63.0', label: '' },
  { addr: 'A63.1', label: '' },
  { addr: 'A63.2', label: '' },
  { addr: 'A63.3', label: '' },
  { addr: 'A63.4', label: '' },
  { addr: 'A63.5', label: '' },
  { addr: 'A63.6', label: '' },
  { addr: 'A63.7', label: '' },
  { addr: 'A64.0', label: 'DYA' },
  { addr: 'A64.1', label: 'DYB' },
  { addr: 'A64.2', label: 'DYC' },
  { addr: 'A64.3', label: 'DYD' },
  { addr: 'A64.4', label: 'AD1' },
  { addr: 'A64.5', label: 'AD2' },
  { addr: 'A64.6', label: 'AD3' },
  { addr: 'A64.7', label: 'STR' },
  { addr: 'A65.0', label: 'T101' },
  { addr: 'A65.1', label: 'T2' },
  { addr: 'A65.2', label: 'TRA' },
  { addr: 'A65.3', label: 'TRB' },
  { addr: 'A65.4', label: 'KCS' },
  { addr: 'A65.5', label: 'KCV' },
  { addr: 'A65.6', label: 'KCH' },
  { addr: 'A65.7', label: 'TCR' },
  { addr: 'A66.0', label: 'KBA2' },
  { addr: 'A66.1', label: '' },
  { addr: 'A66.2', label: '' },
  { addr: 'A66.3', label: '' },
  { addr: 'A66.4', label: 'T102' },
  { addr: 'A66.5', label: 'T10F' },
  { addr: 'A66.6', label: 'LA' },
  { addr: 'A66.7', label: 'LC' },
  { addr: 'A67.0', label: '' },
  { addr: 'A67.1', label: '' },
  { addr: 'A67.2', label: '' },
  { addr: 'A67.3', label: '' },
  { addr: 'A67.4', label: '' },
  { addr: 'A67.5', label: '' },
  { addr: 'A67.6', label: '' },
  { addr: 'A67.7', label: '' }
]
export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-r-lck-to', query: {} },
  { id: 25, key: 'al-r-lck-fdbk', query: {} },
  { id: 26, key: 'al-flap-to', query: {} },
  { id: 27, key: 'al-flap-fc', query: {} },
  { id: 28, key: 'al-sp-to', query: {} },
  { id: 29, key: 'al-sp-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-th', query: { name: 'RTA' } },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'ASH' } },
  { id: 54, key: 'al-th', query: { name: 'FE' } },
  { id: 55, key: 'al-th', query: { name: 'APE' } },
  { id: 56, key: 'al-th', query: { name: 'APBE' } },
  { id: 57, key: 'al-th', query: { name: 'ALK' } },
  { id: 58, key: 'al-th', query: { name: 'AMD' } },
  { id: 59, key: 'al-th', query: { name: 'FE' } },
  { id: 60, key: 'al-iv', query: { nr: 2 } },
  { id: 61, key: 'al-th', query: { name: 'AD' } },
  { id: 62, key: 'al-th', query: { name: 'AMC' } },
  { id: 63, key: 'al-th', query: { name: 'AMM' } },
  { id: 64, key: 'al-th', query: { name: 'MTC' } },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-th', query: { name: 'RTA' } },
  { id: 116, key: 'al-th', query: { name: 'ASBK' } },
  { id: 117, key: 'al-th', query: { name: 'ASH' } },
  { id: 118, key: 'al-th', query: { name: 'FE' } },
  { id: 119, key: 'al-th', query: { name: 'AMM' } },
  { id: 120, key: 'al-th', query: { name: 'ACR' } },
  { id: 121, key: 'al-th', query: { name: 'FE' } },
  { id: 122, key: 'al-iv', query: { nr: 2 } },
  { id: 123, key: 'al-th', query: { name: 'AH' } },
  { id: 124, key: 'al-th', query: { name: 'MTC' } },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'ELA' },
  { id: 4, key: 'ELB' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
