export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'RSI' },
  { addr: 'E1.1', label: 'SA' },
  { addr: 'E1.2', label: 'TJ3' },
  { addr: 'E1.3', label: 'ATD' },
  { addr: 'E1.4', label: 'ASKD' },
  { addr: 'E1.5', label: 'FSKD' },
  { addr: 'E1.6', label: 'UC' },
  { addr: 'E1.7', label: 'RS3' },
  { addr: 'E2.0', label: 'AMC' },
  { addr: 'E2.1', label: 'APBE' },
  { addr: 'E2.2', label: 'APE' },
  { addr: 'E2.3', label: 'FE1' },
  { addr: 'E2.4', label: 'IV3' },
  { addr: 'E2.5', label: 'ECA' },
  { addr: 'E2.6', label: 'ECB' },
  { addr: 'E2.7', label: 'FBBE' },
  { addr: 'E3.0', label: 'EBOE' },
  { addr: 'E3.1', label: 'EBZE' },
  { addr: 'E3.2', label: 'FBE' },
  { addr: 'E3.3', label: 'EOE' },
  { addr: 'E3.4', label: 'EZE' },
  { addr: 'E3.5', label: 'FLP1' },
  { addr: 'E3.6', label: 'FTA1' },
  { addr: 'E3.7', label: 'FTA2' },
  { addr: 'E4.0', label: 'FPE' },
  { addr: 'E4.1', label: 'FDR1' },
  { addr: 'E4.2', label: 'FDL1' },
  { addr: 'E4.3', label: 'FDR2' },
  { addr: 'E4.4', label: 'FDL2' },
  { addr: 'E4.5', label: 'FRER' },
  { addr: 'E4.6', label: 'FREL' },
  { addr: 'E4.7', label: 'FLA1' },
  { addr: 'E5.0', label: 'EXDE' },
  { addr: 'E5.1', label: 'EXHE' },
  { addr: 'E5.2', label: 'FTA2-1' },
  { addr: 'E5.3', label: 'FTC' },
  { addr: 'E5.4', label: 'LOOP' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: '' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: '' },
  { addr: 'E6.4', label: '' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: '' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'RSI' },
  { addr: 'E10.1', label: 'RTA' },
  { addr: 'E10.2', label: 'ASBK' },
  { addr: 'E10.3', label: 'FSBK' },
  { addr: 'E10.4', label: 'TJ1' },
  { addr: 'E10.5', label: 'IV1' },
  { addr: 'E10.6', label: 'FE2' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' }
]
export const inputs3 = [
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: 'AMM' },
  { addr: 'E14.2', label: 'ASH' },
  { addr: 'E14.3', label: '' },
  { addr: 'E14.4', label: 'RSI' },
  { addr: 'E14.5', label: 'EMC' },
  { addr: 'E14.6', label: 'EOM' },
  { addr: 'E14.7', label: 'EZM' },
  { addr: 'E15.0', label: 'FE3' },
  { addr: 'E15.1', label: 'EXV' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' },
  { addr: 'E16.0', label: 'A' },
  { addr: 'E16.1', label: 'B' },
  { addr: 'E16.2', label: 'C' },
  { addr: 'E16.3', label: 'D' },
  { addr: 'E16.4', label: 'OK' },
  { addr: 'E16.5', label: 'S2' },
  { addr: 'E16.6', label: 'S2' },
  { addr: 'E16.7', label: 'S2' },
  { addr: 'E17.0', label: 'UC' },
  { addr: 'E17.1', label: 'RS3' },
  { addr: 'E17.2', label: 'EM' },
  { addr: 'E17.3', label: 'FTXV' },
  { addr: 'E17.4', label: 'FTXH' },
  { addr: 'E17.5', label: 'FT10' },
  { addr: 'E17.6', label: 'ASBK2' },
  { addr: 'E17.7', label: 'IV2' },
  { addr: 'E18.0', label: 'MTC1' },
  { addr: 'E18.1', label: 'MTC2' },
  { addr: 'E18.2', label: '' },
  { addr: 'E18.3', label: 'DB32' },
  { addr: 'E18.4', label: 'DBHZ' },
  { addr: 'E18.5', label: 'RSI' },
  { addr: 'E18.6', label: 'TJ2' },
  { addr: 'E18.7', label: 'FE4' },
  { addr: 'E19.0', label: 'RMV' },
  { addr: 'E19.1', label: 'RMH' },
  { addr: 'E19.2', label: 'RES' },
  { addr: 'E19.3', label: 'REH' },
  { addr: 'E19.4', label: 'RCV' },
  { addr: 'E19.5', label: 'REAV' },
  { addr: 'E19.6', label: 'REAH' },
  { addr: 'E19.7', label: 'RCH' },
  { addr: 'E20.0', label: 'SRL' },
  { addr: 'E20.1', label: '' },
  { addr: 'E20.2', label: '' },
  { addr: 'E20.3', label: '' },
  { addr: 'E20.4', label: '' },
  { addr: 'E20.5', label: '' },
  { addr: 'E20.6', label: '' },
  { addr: 'E20.7', label: '' },
  { addr: 'E21.0', label: '' },
  { addr: 'E21.1', label: '' },
  { addr: 'E21.2', label: '' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: '' },
  { addr: 'E21.5', label: '' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'TJ3' },
  { addr: 'A1.1', label: 'TD' },
  { addr: 'A1.2', label: 'SCA' },
  { addr: 'A1.3', label: 'SCB' },
  { addr: 'A1.4', label: 'LC' },
  { addr: 'A1.5', label: 'LA' },
  { addr: 'A1.6', label: 'SPE' },
  { addr: 'A1.7', label: 'SOE' },
  { addr: 'A2.0', label: 'SZE' },
  { addr: 'A2.1', label: 'SPBE' },
  { addr: 'A2.2', label: 'SBOE' },
  { addr: 'A2.3', label: 'SBZE' },
  { addr: 'A2.4', label: 'RFE' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'SBK1' },
  { addr: 'A10.1', label: 'SBK2' },
  { addr: 'A10.2', label: 'KBA1' },
  { addr: 'A10.3', label: 'STO1-1' },
  { addr: 'A10.4', label: 'LA' },
  { addr: 'A10.5', label: 'LC' },
  { addr: 'A10.6', label: 'STO2-1' },
  { addr: 'A10.7', label: '' },
  { addr: 'A11.0', label: '' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: '' },
  { addr: 'A11.3', label: '' },
  { addr: 'A11.4', label: '' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: '' },
  { addr: 'A11.7', label: '' }
]
export const outputs3 = [
  { addr: 'A14.0', label: 'SMA' },
  { addr: 'A14.1', label: 'SMB' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: 'LA' },
  { addr: 'A14.4', label: 'LC' },
  { addr: 'A14.5', label: '' },
  { addr: 'A14.6', label: '' },
  { addr: 'A14.7', label: '' },
  { addr: 'A15.0', label: '' },
  { addr: 'A15.1', label: '' },
  { addr: 'A15.2', label: '' },
  { addr: 'A15.3', label: '' },
  { addr: 'A15.4', label: '' },
  { addr: 'A15.5', label: '' },
  { addr: 'A15.6', label: '' },
  { addr: 'A15.7', label: '' },
  { addr: 'A16.0', label: 'DYA' },
  { addr: 'A16.1', label: 'DYB' },
  { addr: 'A16.2', label: 'DYC' },
  { addr: 'A16.3', label: 'DYD' },
  { addr: 'A16.4', label: 'AD1' },
  { addr: 'A16.5', label: 'AD2' },
  { addr: 'A16.6', label: 'AD3' },
  { addr: 'A16.7', label: 'STR' },
  { addr: 'A17.0', label: 'LC' },
  { addr: 'A17.1', label: 'T10F' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: 'TRA' },
  { addr: 'A17.4', label: 'TRB' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: 'KCS' },
  { addr: 'A17.7', label: 'KCV' },
  { addr: 'A18.0', label: 'KCH' },
  { addr: 'A18.1', label: 'LA' },
  { addr: 'A18.2', label: 'T101' },
  { addr: 'A18.3', label: 'T102' },
  { addr: 'A18.4', label: 'T2' },
  { addr: 'A18.5', label: 'KBA2' },
  { addr: 'A18.6', label: '' },
  { addr: 'A18.7', label: '' },
  { addr: 'A19.0', label: '' },
  { addr: 'A19.1', label: '' },
  { addr: 'A19.2', label: '' },
  { addr: 'A19.3', label: '' },
  { addr: 'A19.4', label: '' },
  { addr: 'A19.5', label: '' },
  { addr: 'A19.6', label: '' },
  { addr: 'A19.7', label: '' }
]
export const alarms1 = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-h-to', query: {} },
  { id: 24, key: 'al-lh', query: {} },
  { id: 25, key: 'al-lh-diff', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-pn', query: { name: 'LS' } },
  { id: 42, key: 'al-pn', query: { name: 'KKP' } },
  { id: 43, key: 'al-pn', query: { name: 'SH' } },
  { id: 44, key: 'al-pn', query: { name: 'IV1' } },
  { id: 45, key: 'al-pn', query: { name: 'IV2' } },
  { id: 46, key: 'al-pn', query: { name: 'LV1' } },
  { id: 47, key: 'al-pn', query: { name: 'LV2' } },
  { id: 48, key: 'al-pn', query: { name: 'LH' } },
  { id: 49, key: 'al-th', query: { name: 'FE2' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: '', query: {} },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'RTJ' } },
  { id: 54, key: 'al-th', query: { name: 'FE3' } },
  { id: 55, key: 'al-th', query: { name: 'AMM' } },
  { id: 56, key: 'al-th', query: { name: 'ASH' } },
  { id: 57, key: '', query: {} },
  { id: 58, key: 'al-th', query: { name: 'FE4' } },
  { id: 59, key: 'al-iv', query: { nr: 2 } },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 63, key: 'al-th', query: { name: 'MTC1' } },
  { id: 64, key: 'al-th', query: { name: 'MTC2' } }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: 'al-r-to', query: {} },
  { id: 26, key: 'al-enr', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: 'al-flap-to', query: {} },
  { id: 32, key: 'al-flap-fc', query: {} },
  { id: 33, key: 'al-sp-to', query: {} },
  { id: 34, key: 'al-sp-to', query: {} },
  { id: 35, key: 'al-sp-fc', query: {} },
  { id: 36, key: 'al-spb-to', query: {} },
  { id: 37, key: 'al-spb-to', query: {} },
  { id: 38, key: 'al-spb-fc', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-pn', query: { name: 'IV3' } },
  { id: 42, key: 'al-pn', query: { name: 'ENR' } },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 3 } },
  { id: 51, key: '', query: {} },
  { id: 52, key: 'al-th', query: { name: 'ASKD' } },
  { id: 53, key: '', query: {} },
  { id: 54, key: 'al-th', query: { name: 'ATD' } },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: 'al-th', query: { name: 'AMC' } },
  { id: 60, key: 'al-th', query: { name: 'APE' } },
  { id: 61, key: 'al-th', query: { name: 'APBE' } },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'EU' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
