exports.inputs1 = [
  { addr: 'E0.0', label: 'SFA' },
  { addr: 'E0.1', label: 'SFB' },
  { addr: 'E0.2', label: 'SF1' },
  { addr: 'E0.3', label: 'SF2' },
  { addr: 'E0.4', label: 'FE' },
  { addr: 'E0.5', label: 'RSI' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E10.0', label: 'IV1' },
  { addr: 'E10.1', label: 'RSI' },
  { addr: 'E10.2', label: 'FDBK' },
  { addr: 'E10.3', label: 'ASBK' },
  { addr: 'E10.4', label: 'RTA' },
  { addr: 'E10.5', label: 'FE' },
  { addr: 'E10.6', label: 'ALK' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: 'DB32' },
  { addr: 'E11.1', label: 'DBHZ' },
  { addr: 'E11.2', label: 'IV2' },
  { addr: 'E11.3', label: 'ATD' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: 'A' },
  { addr: 'E12.1', label: 'B' },
  { addr: 'E12.2', label: 'C' },
  { addr: 'E12.3', label: 'D' },
  { addr: 'E12.4', label: 'OK' },
  { addr: 'E12.5', label: 'S2' },
  { addr: 'E12.6', label: 'S2' },
  { addr: 'E12.7', label: 'S2' },
  { addr: 'E13.0', label: 'RSI' },
  { addr: 'E13.1', label: 'FE' },
  { addr: 'E13.2', label: 'APE' },
  { addr: 'E13.3', label: 'AMM' },
  { addr: 'E13.4', label: 'ECA' },
  { addr: 'E13.5', label: 'ECB' },
  { addr: 'E13.6', label: 'AMC' },
  { addr: 'E13.7', label: 'UC' },
  { addr: 'E14.0', label: 'EZE' },
  { addr: 'E14.1', label: 'EOE' },
  { addr: 'E14.2', label: 'FBE' },
  { addr: 'E14.3', label: 'FPE' },
  { addr: 'E14.4', label: 'FDR1' },
  { addr: 'E14.5', label: 'FDL1' },
  { addr: 'E14.6', label: 'FDR2' },
  { addr: 'E14.7', label: 'FDL2' },
  { addr: 'E15.0', label: 'FTA1' },
  { addr: 'E15.1', label: 'FTA2' },
  { addr: 'E15.2', label: 'FTA3' },
  { addr: 'E15.3', label: 'FLP' },
  { addr: 'E15.4', label: 'FLA' },
  { addr: 'E15.5', label: 'RX1' },
  { addr: 'E15.6', label: 'RX2' },
  { addr: 'E15.7', label: 'SA' },
  { addr: 'E16.0', label: 'AMD' },
  { addr: 'E16.1', label: 'EOMD' },
  { addr: 'E16.2', label: 'EZMD' },
  { addr: 'E16.3', label: 'EXD' },
  { addr: 'E16.4', label: 'EXH' },
  { addr: 'E16.5', label: 'ASKD' },
  { addr: 'E16.6', label: 'EOM' },
  { addr: 'E16.7', label: 'EZM' },
  { addr: 'E17.0', label: 'FTXV' },
  { addr: 'E17.1', label: 'FTXH' },
  { addr: 'E17.2', label: 'FREL' },
  { addr: 'E17.3', label: 'FRER' },
  { addr: 'E17.4', label: 'FTC' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E20.0', label: 'IV1' },
  { addr: 'E20.1', label: 'RSI' },
  { addr: 'E20.2', label: 'FDBK' },
  { addr: 'E20.3', label: 'ASBK' },
  { addr: 'E20.4', label: 'RTA' },
  { addr: 'E20.5', label: 'FE' },
  { addr: 'E20.6', label: 'QLK' },
  { addr: 'E20.7', label: '' },
  { addr: 'E21.0', label: 'DB32' },
  { addr: 'E21.1', label: 'DBHZ' },
  { addr: 'E21.2', label: '' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: '' },
  { addr: 'E21.5', label: '' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: '' },
  { addr: 'E22.0', label: 'A' },
  { addr: 'E22.1', label: 'B' },
  { addr: 'E22.2', label: 'C' },
  { addr: 'E22.3', label: 'D' },
  { addr: 'E22.4', label: 'OK' },
  { addr: 'E22.5', label: 'S2' },
  { addr: 'E22.6', label: 'S2' },
  { addr: 'E22.7', label: 'S2' },
  { addr: 'E23.0', label: 'RSI' },
  { addr: 'E23.1', label: 'FE' },
  { addr: 'E23.2', label: 'APE' },
  { addr: 'E23.3', label: 'AMM' },
  { addr: 'E23.4', label: 'ECA' },
  { addr: 'E23.5', label: 'ECB' },
  { addr: 'E23.6', label: 'AMC' },
  { addr: 'E23.7', label: 'UC' },
  { addr: 'E24.0', label: 'EZE' },
  { addr: 'E24.1', label: 'EOE' },
  { addr: 'E24.2', label: 'FBE' },
  { addr: 'E24.3', label: 'FPE' },
  { addr: 'E24.4', label: 'FDR1' },
  { addr: 'E24.5', label: 'FDL1' },
  { addr: 'E24.6', label: 'FDR2' },
  { addr: 'E24.7', label: 'FDL2' },
  { addr: 'E25.0', label: 'FTA1' },
  { addr: 'E25.1', label: 'FTA2' },
  { addr: 'E25.2', label: 'FTA3' },
  { addr: 'E25.3', label: 'FLP' },
  { addr: 'E25.4', label: 'FLA' },
  { addr: 'E25.5', label: 'RX1' },
  { addr: 'E25.6', label: 'RX2' },
  { addr: 'E25.7', label: 'SA' },
  { addr: 'E26.0', label: '' },
  { addr: 'E26.1', label: 'EOM' },
  { addr: 'E26.2', label: 'EZM' },
  { addr: 'E26.3', label: 'FTXV' },
  { addr: 'E26.4', label: 'FTXH' },
  { addr: 'E26.5', label: 'FREL' },
  { addr: 'E26.6', label: 'FRER' },
  { addr: 'E26.7', label: 'FTC' },
  { addr: 'E27.0', label: '' },
  { addr: 'E27.1', label: '' },
  { addr: 'E27.2', label: '' },
  { addr: 'E27.3', label: '' },
  { addr: 'E27.4', label: '' },
  { addr: 'E27.5', label: '' },
  { addr: 'E27.6', label: '' },
  { addr: 'E27.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E30.0', label: 'A' },
  { addr: 'E30.1', label: 'B' },
  { addr: 'E30.2', label: 'C' },
  { addr: 'E30.3', label: 'D' },
  { addr: 'E30.4', label: 'OK' },
  { addr: 'E30.5', label: 'S2' },
  { addr: 'E30.6', label: 'S2' },
  { addr: 'E30.7', label: 'S2' },
  { addr: 'E31.0', label: 'RSI' },
  { addr: 'E31.1', label: 'MTC' },
  { addr: 'E31.2', label: 'FE' },
  { addr: 'E31.3', label: 'IV1' },
  { addr: 'E31.4', label: 'IV2' },
  { addr: 'E31.5', label: 'ASBK' },
  { addr: 'E31.6', label: 'RTA' },
  { addr: 'E31.7', label: 'AMM' },
  { addr: 'E32.0', label: 'AH' },
  { addr: 'E32.1', label: 'SA' },
  { addr: 'E32.2', label: '' },
  { addr: 'E32.3', label: '' },
  { addr: 'E32.4', label: '' },
  { addr: 'E32.5', label: '' },
  { addr: 'E32.6', label: '' },
  { addr: 'E32.7', label: '' },
  { addr: 'E33.0', label: 'RMV' },
  { addr: 'E33.1', label: 'RMH' },
  { addr: 'E33.2', label: 'RES' },
  { addr: 'E33.3', label: 'REH' },
  { addr: 'E33.4', label: 'RCV' },
  { addr: 'E33.5', label: 'REAV' },
  { addr: 'E33.6', label: 'REAH' },
  { addr: 'E33.7', label: 'RCH' },
  { addr: 'E34.0', label: 'UC' },
  { addr: 'E34.1', label: 'EM' },
  { addr: 'E34.2', label: 'EOM' },
  { addr: 'E34.3', label: 'EZM' },
  { addr: 'E34.4', label: 'FTXV' },
  { addr: 'E34.5', label: 'FTXH' },
  { addr: 'E34.6', label: 'FTM' },
  { addr: 'E34.7', label: 'FTAC' },
  { addr: 'E35.0', label: 'DB32' },
  { addr: 'E35.1', label: 'DBHZ' },
  { addr: 'E35.2', label: '' },
  { addr: 'E35.3', label: '' },
  { addr: 'E35.4', label: '' },
  { addr: 'E35.5', label: '' },
  { addr: 'E35.6', label: '' },
  { addr: 'E35.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LSA' },
  { addr: 'A0.1', label: 'LSB' },
  { addr: 'A0.2', label: 'LS1' },
  { addr: 'A0.3', label: 'LS2' },
  { addr: 'A0.4', label: 'LA' },
  { addr: 'A0.5', label: 'LS' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: 'SBK1' },
  { addr: 'A10.1', label: 'SBK2' },
  { addr: 'A10.2', label: 'KBA1' },
  { addr: 'A10.3', label: '' },
  { addr: 'A10.4', label: 'LA' },
  { addr: 'A10.5', label: 'LC' },
  { addr: 'A10.6', label: 'KBA2' },
  { addr: 'A10.7', label: '' },
  { addr: 'A11.0', label: '' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: '' },
  { addr: 'A11.3', label: '' },
  { addr: 'A11.4', label: '' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: '' },
  { addr: 'A11.7', label: '' },
  { addr: 'A12.0', label: 'DYA' },
  { addr: 'A12.1', label: 'DYB' },
  { addr: 'A12.2', label: 'DYC' },
  { addr: 'A12.3', label: 'DYD' },
  { addr: 'A12.4', label: 'AD1' },
  { addr: 'A12.5', label: 'AD2' },
  { addr: 'A12.6', label: 'AD3' },
  { addr: 'A12.7', label: 'STR' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: 'LA' },
  { addr: 'A13.2', label: 'LC' },
  { addr: 'A13.3', label: 'SMAD' },
  { addr: 'A13.4', label: 'SMBD' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: 'L1' },
  { addr: 'A14.1', label: 'L2' },
  { addr: 'A14.2', label: 'L3' },
  { addr: 'A14.3', label: 'L4' },
  { addr: 'A14.4', label: 'L5' },
  { addr: 'A14.5', label: '' },
  { addr: 'A14.6', label: 'SPE' },
  { addr: 'A14.7', label: 'RFE' },
  { addr: 'A15.0', label: 'SOE' },
  { addr: 'A15.1', label: 'SZE' },
  { addr: 'A15.2', label: '' },
  { addr: 'A15.3', label: 'SCA' },
  { addr: 'A15.4', label: 'SCB' },
  { addr: 'A15.5', label: 'SMA' },
  { addr: 'A15.6', label: 'SMB' },
  { addr: 'A15.7', label: 'TDF' },
  { addr: 'A16.0', label: '' },
  { addr: 'A16.1', label: '' },
  { addr: 'A16.2', label: '' },
  { addr: 'A16.3', label: '' },
  { addr: 'A16.4', label: '' },
  { addr: 'A16.5', label: '' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A20.0', label: 'SBK1' },
  { addr: 'A20.1', label: 'SBK2' },
  { addr: 'A20.2', label: 'KBA1' },
  { addr: 'A20.3', label: '' },
  { addr: 'A20.4', label: 'LA' },
  { addr: 'A20.5', label: 'LC' },
  { addr: 'A20.6', label: '' },
  { addr: 'A20.7', label: '' },
  { addr: 'A21.0', label: '' },
  { addr: 'A21.1', label: '' },
  { addr: 'A21.2', label: '' },
  { addr: 'A21.3', label: '' },
  { addr: 'A21.4', label: '' },
  { addr: 'A21.5', label: '' },
  { addr: 'A21.6', label: '' },
  { addr: 'A21.7', label: '' },
  { addr: 'A22.0', label: 'DYA' },
  { addr: 'A22.1', label: 'DYB' },
  { addr: 'A22.2', label: 'DYC' },
  { addr: 'A22.3', label: 'DYD' },
  { addr: 'A22.4', label: 'AD1' },
  { addr: 'A22.5', label: 'AD2' },
  { addr: 'A22.6', label: 'AD3' },
  { addr: 'A22.7', label: 'STR' },
  { addr: 'A23.0', label: '' },
  { addr: 'A23.1', label: 'LA' },
  { addr: 'A23.2', label: 'LC' },
  { addr: 'A23.3', label: 'SCA' },
  { addr: 'A23.4', label: 'SCB' },
  { addr: 'A23.5', label: 'SMA' },
  { addr: 'A23.6', label: 'SMB' },
  { addr: 'A23.7', label: '' },
  { addr: 'A24.0', label: 'L1' },
  { addr: 'A24.1', label: 'L2' },
  { addr: 'A24.2', label: 'L3' },
  { addr: 'A24.3', label: 'L4' },
  { addr: 'A24.4', label: 'L5' },
  { addr: 'A24.5', label: '' },
  { addr: 'A24.6', label: 'SPE' },
  { addr: 'A24.7', label: 'RFE' },
  { addr: 'A25.0', label: 'SOE' },
  { addr: 'A25.1', label: 'SZE' },
  { addr: 'A25.2', label: '' },
  { addr: 'A25.3', label: '' },
  { addr: 'A25.4', label: '' },
  { addr: 'A25.5', label: '' },
  { addr: 'A25.6', label: '' },
  { addr: 'A25.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A30.0', label: 'DYA' },
  { addr: 'A30.1', label: 'DYB' },
  { addr: 'A30.2', label: 'DYC' },
  { addr: 'A30.3', label: 'DYD' },
  { addr: 'A30.4', label: 'AD1' },
  { addr: 'A30.5', label: 'AD2' },
  { addr: 'A30.6', label: 'AD3' },
  { addr: 'A30.7', label: 'STR' },
  { addr: 'A31.0', label: 'SMA' },
  { addr: 'A31.1', label: 'SMB' },
  { addr: 'A31.2', label: 'SBK1' },
  { addr: 'A31.3', label: 'TSH' },
  { addr: 'A31.4', label: 'KBA1' },
  { addr: 'A31.5', label: 'KBA2' },
  { addr: 'A31.6', label: 'LA' },
  { addr: 'A31.7', label: 'LC' },
  { addr: 'A32.0', label: 'T2' },
  { addr: 'A32.1', label: 'TRA' },
  { addr: 'A32.2', label: 'TRB' },
  { addr: 'A32.3', label: 'KCS' },
  { addr: 'A32.4', label: 'KCV' },
  { addr: 'A32.5', label: 'KCH' },
  { addr: 'A32.6', label: 'T101' },
  { addr: 'A32.7', label: 'T102' },
  { addr: 'A33.0', label: 'SBK2' },
  { addr: 'A33.1', label: '' },
  { addr: 'A33.2', label: '' },
  { addr: 'A33.3', label: '' },
  { addr: 'A33.4', label: '' },
  { addr: 'A33.5', label: '' },
  { addr: 'A33.6', label: '' },
  { addr: 'A33.7', label: '' }
]

exports.ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-r-to', query: {} },
  { id: 24, key: 'al-enr', query: {} },
  { id: 25, key: 'al-r-lck-to', query: {} },
  { id: 26, key: 'al-r-lck-fc', query: {} },
  { id: 27, key: 'al-flap-to', query: {} },
  { id: 28, key: 'al-flap-fc', query: {} },
  { id: 29, key: 'al-sp-to', query: {} },
  { id: 30, key: 'al-sp-fc', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-r-to', query: {} },
  { id: 88, key: 'al-enr', query: {} },
  { id: 89, key: 'al-r-lck-to', query: {} },
  { id: 90, key: 'al-r-lck-fc', query: {} },
  { id: 91, key: 'al-flap-to', query: {} },
  { id: 92, key: 'al-flap-fc', query: {} },
  { id: 93, key: 'al-sp-to', query: {} },
  { id: 94, key: 'al-sp-fc', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} },
  { id: 129, key: 'al-sil-01', query: {} },
  { id: 130, key: 'al-sil-02', query: {} },
  { id: 131, key: 'al-sil-03', query: {} },
  { id: 132, key: 'al-sil-04', query: {} },
  { id: 133, key: 'al-sil-05', query: {} },
  { id: 134, key: 'al-sil-06', query: {} },
  { id: 135, key: 'al-sil-07', query: {} },
  { id: 136, key: 'al-sil-08', query: {} },
  { id: 137, key: 'al-sil-09', query: {} },
  { id: 138, key: 'al-sil-10', query: {} },
  { id: 139, key: 'al-sil-11', query: {} },
  { id: 140, key: 'al-sil-12', query: {} },
  { id: 141, key: 'al-sil-13', query: {} },
  { id: 142, key: 'al-sil-14', query: {} },
  { id: 143, key: 'al-sil-15', query: {} },
  { id: 144, key: 'al-sil-16', query: {} },
  { id: 145, key: 'al-v-to', query: {} },
  { id: 146, key: 'al-v-fdbk', query: {} },
  { id: 147, key: 'al-lv', query: {} },
  { id: 148, key: 'al-lv-diff', query: {} },
  { id: 149, key: 'al-v-lck-to', query: {} },
  { id: 150, key: 'al-v-lck-fc', query: {} },
  { id: 151, key: 'al-h-to', query: {} },
  { id: 152, key: 'al-lh', query: {} },
  { id: 153, key: 'al-lh-diff', query: {} },
  { id: 154, key: '', query: {} },
  { id: 155, key: '', query: {} },
  { id: 156, key: '', query: {} },
  { id: 157, key: '', query: {} },
  { id: 158, key: '', query: {} },
  { id: 159, key: '', query: {} },
  { id: 160, key: '', query: {} },
  { id: 161, key: '', query: {} },
  { id: 162, key: '', query: {} },
  { id: 163, key: '', query: {} },
  { id: 164, key: '', query: {} },
  { id: 165, key: '', query: {} },
  { id: 166, key: '', query: {} },
  { id: 167, key: '', query: {} },
  { id: 168, key: '', query: {} },
  { id: 169, key: '', query: {} },
  { id: 170, key: '', query: {} },
  { id: 171, key: '', query: {} },
  { id: 172, key: '', query: {} },
  { id: 173, key: '', query: {} },
  { id: 174, key: '', query: {} },
  { id: 175, key: '', query: {} },
  { id: 176, key: '', query: {} },
  { id: 177, key: '', query: {} },
  { id: 178, key: '', query: {} },
  { id: 179, key: '', query: {} },
  { id: 180, key: '', query: {} },
  { id: 181, key: '', query: {} },
  { id: 182, key: '', query: {} },
  { id: 183, key: '', query: {} },
  { id: 184, key: '', query: {} },
  { id: 185, key: '', query: {} },
  { id: 186, key: '', query: {} },
  { id: 187, key: '', query: {} },
  { id: 188, key: '', query: {} },
  { id: 189, key: '', query: {} },
  { id: 190, key: '', query: {} },
  { id: 191, key: '', query: {} },
  { id: 192, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'A' },
  { id: 4, key: 'E2' },
  { id: 5, key: 'U1' },
  { id: 6, key: 'U2' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
