exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: 'SPR' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'STR' },
  { addr: 'E1.5', label: 'OK' },
  { addr: 'E1.6', label: 'DAT' },
  { addr: 'E1.7', label: 'SPR' },
  { addr: 'E2.0', label: 'A' },
  { addr: 'E2.1', label: 'B' },
  { addr: 'E2.2', label: 'C' },
  { addr: 'E2.3', label: 'D' },
  { addr: 'E2.4', label: 'STR' },
  { addr: 'E2.5', label: 'OK' },
  { addr: 'E2.6', label: 'DAT' },
  { addr: 'E2.7', label: 'RSI' },
  { addr: 'E3.0', label: 'A' },
  { addr: 'E3.1', label: 'B' },
  { addr: 'E3.2', label: 'C' },
  { addr: 'E3.3', label: 'D' },
  { addr: 'E3.4', label: 'STR' },
  { addr: 'E3.5', label: 'OK' },
  { addr: 'E3.6', label: 'DAT' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'SFA' },
  { addr: 'E4.1', label: 'SFB' },
  { addr: 'E4.2', label: 'SFT1' },
  { addr: 'E4.3', label: 'SFT2' },
  { addr: 'E4.4', label: 'STC' },
  { addr: 'E4.5', label: 'STC' },
  { addr: 'E4.6', label: '' },
  { addr: 'E4.7', label: 'FE3' },
  { addr: 'E5.0', label: '' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'AMM1' },
  { addr: 'E101.1', label: 'EOM1' },
  { addr: 'E101.2', label: 'EZM1' },
  { addr: 'E101.3', label: 'AMM2' },
  { addr: 'E101.4', label: 'EOM2' },
  { addr: 'E101.5', label: 'EZM2' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'AX1' },
  { addr: 'E102.1', label: 'FLDX' },
  { addr: 'E102.2', label: 'FLSX' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: 'FBDX' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: 'SFA0' },
  { addr: 'E102.7', label: 'SFA1' },
  { addr: 'E103.0', label: 'IV1' },
  { addr: 'E103.1', label: 'IV2' },
  { addr: 'E103.2', label: 'KXA' },
  { addr: 'E103.3', label: 'RSI' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'APE' },
  { addr: 'E103.7', label: 'FE1' },
  { addr: 'E104.0', label: 'ASH' },
  { addr: 'E104.1', label: 'AH' },
  { addr: 'E104.2', label: 'KXPE' },
  { addr: 'E104.3', label: '' },
  { addr: 'E104.4', label: 'SBK1' },
  { addr: 'E104.5', label: 'ASBK' },
  { addr: 'E104.6', label: 'RTA' },
  { addr: 'E104.7', label: 'KBA1' },
  { addr: 'E105.0', label: 'AMM3' },
  { addr: 'E105.1', label: 'EOM3' },
  { addr: 'E105.2', label: 'EZM3' },
  { addr: 'E105.3', label: 'AMM4' },
  { addr: 'E105.4', label: 'EOM4' },
  { addr: 'E105.5', label: 'EZM4' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FTA2G0' },
  { addr: 'E107.1', label: 'FLP' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: 'FDRG0' },
  { addr: 'E107.4', label: 'FDLG0' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: 'RXL' },
  { addr: 'E107.7', label: 'RXR' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'ECA' },
  { addr: 'E110.1', label: 'ECB' },
  { addr: 'E110.2', label: 'AMC' },
  { addr: 'E110.3', label: 'EXD' },
  { addr: 'E110.4', label: 'EXH' },
  { addr: 'E110.5', label: 'ASKD' },
  { addr: 'E110.6', label: '' },
  { addr: 'E110.7', label: 'KEXPV' },
  { addr: 'E111.0', label: 'FE3' },
  { addr: 'E111.1', label: '' },
  { addr: 'E111.2', label: 'FTC' },
  { addr: 'E111.3', label: 'EFA' },
  { addr: 'E111.4', label: 'FREL' },
  { addr: 'E111.5', label: 'FRER' },
  { addr: 'E111.6', label: 'FTXV' },
  { addr: 'E111.7', label: 'FTXH' }
]
exports.inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'OK' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: 'S2' },
  { addr: 'E201.0', label: 'AMM1' },
  { addr: 'E201.1', label: 'EOM1' },
  { addr: 'E201.2', label: 'EZM1' },
  { addr: 'E201.3', label: 'AMM2' },
  { addr: 'E201.4', label: 'EOM2' },
  { addr: 'E201.5', label: 'EZM2' },
  { addr: 'E201.6', label: '' },
  { addr: 'E201.7', label: 'UC' },
  { addr: 'E202.0', label: 'AX1' },
  { addr: 'E202.1', label: 'FLDX' },
  { addr: 'E202.2', label: 'FLSX' },
  { addr: 'E202.3', label: '' },
  { addr: 'E202.4', label: 'FBDX' },
  { addr: 'E202.5', label: '' },
  { addr: 'E202.6', label: 'SFA0' },
  { addr: 'E202.7', label: 'SFA1' },
  { addr: 'E203.0', label: 'IV1' },
  { addr: 'E203.1', label: 'IV2' },
  { addr: 'E203.2', label: 'KXA' },
  { addr: 'E203.3', label: 'RSI' },
  { addr: 'E203.4', label: 'DB32' },
  { addr: 'E203.5', label: 'DBHZ' },
  { addr: 'E203.6', label: 'APE' },
  { addr: 'E203.7', label: 'FE1' },
  { addr: 'E204.0', label: 'ASH' },
  { addr: 'E204.1', label: 'AH' },
  { addr: 'E204.2', label: 'KXPE' },
  { addr: 'E204.3', label: '' },
  { addr: 'E204.4', label: 'SBK1' },
  { addr: 'E204.5', label: 'ASBK' },
  { addr: 'E204.6', label: 'RTA' },
  { addr: 'E204.7', label: 'KBA1' },
  { addr: 'E205.0', label: 'AMM3' },
  { addr: 'E205.1', label: 'EOM3' },
  { addr: 'E205.2', label: 'EZM3' },
  { addr: 'E205.3', label: 'AMM4' },
  { addr: 'E205.4', label: 'EOM4' },
  { addr: 'E205.5', label: 'EZM4' },
  { addr: 'E205.6', label: '' },
  { addr: 'E205.7', label: '' },
  { addr: 'E206.0', label: 'EZE' },
  { addr: 'E206.1', label: 'EOE' },
  { addr: 'E206.2', label: 'FBE' },
  { addr: 'E206.3', label: 'FPE' },
  { addr: 'E206.4', label: 'FDR1' },
  { addr: 'E206.5', label: 'FDL1' },
  { addr: 'E206.6', label: 'FTA1' },
  { addr: 'E206.7', label: 'FTA2' },
  { addr: 'E207.0', label: 'FTA2G0' },
  { addr: 'E207.1', label: 'FLP' },
  { addr: 'E207.2', label: 'FLA' },
  { addr: 'E207.3', label: 'FDRG0' },
  { addr: 'E207.4', label: 'FDLG0' },
  { addr: 'E207.5', label: '' },
  { addr: 'E207.6', label: 'RXL' },
  { addr: 'E207.7', label: 'RXR' }
]
exports.inputs5 = [
  { addr: 'E210.0', label: 'ECA' },
  { addr: 'E210.1', label: 'ECB' },
  { addr: 'E210.2', label: 'AMC' },
  { addr: 'E210.3', label: 'EXD' },
  { addr: 'E210.4', label: 'EXH' },
  { addr: 'E210.5', label: 'ASKD' },
  { addr: 'E210.6', label: '' },
  { addr: 'E210.7', label: 'KEXPV' },
  { addr: 'E211.0', label: 'FE3' },
  { addr: 'E211.1', label: '' },
  { addr: 'E211.2', label: 'FTC' },
  { addr: 'E211.3', label: 'EFA' },
  { addr: 'E211.4', label: 'FREL' },
  { addr: 'E211.5', label: 'FRER' },
  { addr: 'E211.6', label: 'FTXV' },
  { addr: 'E211.7', label: 'FTXH' }
]
exports.inputs6 = [
  { addr: 'E300.0', label: 'A' },
  { addr: 'E300.1', label: 'B' },
  { addr: 'E300.2', label: 'C' },
  { addr: 'E300.3', label: 'D' },
  { addr: 'E300.4', label: 'OK' },
  { addr: 'E300.5', label: 'S2' },
  { addr: 'E300.6', label: 'S2' },
  { addr: 'E300.7', label: 'S2' },
  { addr: 'E301.0', label: 'FE1' },
  { addr: 'E301.1', label: 'IV1' },
  { addr: 'E301.2', label: 'TJ1' },
  { addr: 'E301.3', label: 'RSI' },
  { addr: 'E301.4', label: 'SA' },
  { addr: 'E301.5', label: '' },
  { addr: 'E301.6', label: '' },
  { addr: 'E301.7', label: 'UC' },
  { addr: 'E302.0', label: '' },
  { addr: 'E302.1', label: '' },
  { addr: 'E302.2', label: '' },
  { addr: 'E302.3', label: '' },
  { addr: 'E302.4', label: 'FDBK' },
  { addr: 'E302.5', label: 'ASBK' },
  { addr: 'E302.6', label: 'RTA' },
  { addr: 'E302.7', label: '' },
  { addr: 'E303.0', label: '' },
  { addr: 'E303.1', label: '' },
  { addr: 'E303.2', label: '' },
  { addr: 'E303.3', label: '' },
  { addr: 'E303.4', label: '' },
  { addr: 'E303.5', label: '' },
  { addr: 'E303.6', label: '' },
  { addr: 'E303.7', label: '' },
  { addr: 'E304.0', label: 'AGK' },
  { addr: 'E304.1', label: 'ACR' },
  { addr: 'E304.2', label: 'TCR' },
  { addr: 'E304.3', label: 'FE3' },
  { addr: 'E304.4', label: 'DB32' },
  { addr: 'E304.5', label: 'DBHZ' },
  { addr: 'E304.6', label: 'KLK' },
  { addr: 'E304.7', label: '' },
  { addr: 'E305.0', label: '' },
  { addr: 'E305.1', label: '' },
  { addr: 'E305.2', label: 'AMM' },
  { addr: 'E305.3', label: 'EOM' },
  { addr: 'E305.4', label: 'EZM' },
  { addr: 'E305.5', label: 'EMC' },
  { addr: 'E305.6', label: '' },
  { addr: 'E305.7', label: '' }
]
exports.inputs7 = [
  { addr: 'E310.0', label: 'A' },
  { addr: 'E310.1', label: 'B' },
  { addr: 'E310.2', label: 'C' },
  { addr: 'E310.3', label: 'D' },
  { addr: 'E310.4', label: 'OK' },
  { addr: 'E310.5', label: 'S2' },
  { addr: 'E310.6', label: 'S2' },
  { addr: 'E310.7', label: 'S2' },
  { addr: 'E311.0', label: 'FE4' },
  { addr: 'E311.1', label: '' },
  { addr: 'E311.2', label: '' },
  { addr: 'E311.3', label: 'EM' },
  { addr: 'E311.4', label: '' },
  { addr: 'E311.5', label: '' },
  { addr: 'E311.6', label: 'FTXV' },
  { addr: 'E311.7', label: 'FTXH' },
  { addr: 'E312.0', label: 'RMV' },
  { addr: 'E312.1', label: 'RMH' },
  { addr: 'E312.2', label: 'RES' },
  { addr: 'E312.3', label: 'REH' },
  { addr: 'E312.4', label: 'RCV' },
  { addr: 'E312.5', label: 'REAV' },
  { addr: 'E312.6', label: 'REAH' },
  { addr: 'E312.7', label: 'RCH' },
  { addr: 'E313.0', label: 'IV2' },
  { addr: 'E313.1', label: 'TJ2' },
  { addr: 'E313.2', label: 'SA' },
  { addr: 'E313.3', label: 'RSI' },
  { addr: 'E313.4', label: 'DB32' },
  { addr: 'E313.5', label: 'DBHZ' },
  { addr: 'E313.6', label: 'FTAC' },
  { addr: 'E313.7', label: 'UC' },
  { addr: 'E314.0', label: 'AF7' },
  { addr: 'E314.1', label: '' },
  { addr: 'E314.2', label: 'FTM1' },
  { addr: 'E314.3', label: 'FTM2' },
  { addr: 'E314.4', label: '' },
  { addr: 'E314.5', label: 'TCR' },
  { addr: 'E314.6', label: 'AH' },
  { addr: 'E314.7', label: 'MTC' }
]
exports.inputs8 = [
  { addr: 'E400.0', label: 'A' },
  { addr: 'E400.1', label: 'B' },
  { addr: 'E400.2', label: 'C' },
  { addr: 'E400.3', label: 'D' },
  { addr: 'E400.4', label: 'OK' },
  { addr: 'E400.5', label: 'S2' },
  { addr: 'E400.6', label: 'S2' },
  { addr: 'E400.7', label: 'S2' },
  { addr: 'E401.0', label: 'FE1' },
  { addr: 'E401.1', label: 'IV1' },
  { addr: 'E401.2', label: 'TJ1' },
  { addr: 'E401.3', label: 'RSI' },
  { addr: 'E401.4', label: 'SA' },
  { addr: 'E401.5', label: '' },
  { addr: 'E401.6', label: '' },
  { addr: 'E401.7', label: 'UC' },
  { addr: 'E402.0', label: '' },
  { addr: 'E402.1', label: '' },
  { addr: 'E402.2', label: '' },
  { addr: 'E402.3', label: '' },
  { addr: 'E402.4', label: 'FDBK' },
  { addr: 'E402.5', label: 'ASBK' },
  { addr: 'E402.6', label: 'RTA' },
  { addr: 'E402.7', label: '' },
  { addr: 'E403.0', label: '' },
  { addr: 'E403.1', label: '' },
  { addr: 'E403.2', label: '' },
  { addr: 'E403.3', label: '' },
  { addr: 'E403.4', label: '' },
  { addr: 'E403.5', label: '' },
  { addr: 'E403.6', label: '' },
  { addr: 'E403.7', label: '' },
  { addr: 'E404.0', label: 'AGK' },
  { addr: 'E404.1', label: 'ACR' },
  { addr: 'E404.2', label: 'TCR' },
  { addr: 'E404.3', label: 'FE3' },
  { addr: 'E404.4', label: 'DB32' },
  { addr: 'E404.5', label: 'DBHZ' },
  { addr: 'E404.6', label: 'KLK' },
  { addr: 'E404.7', label: '' },
  { addr: 'E405.0', label: '' },
  { addr: 'E405.1', label: '' },
  { addr: 'E405.2', label: 'AMM' },
  { addr: 'E405.3', label: 'EOM' },
  { addr: 'E405.4', label: 'EZM' },
  { addr: 'E405.5', label: 'EMC' },
  { addr: 'E405.6', label: '' },
  { addr: 'E405.7', label: '' }
]
exports.inputs9 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'FE4' },
  { addr: 'E411.1', label: '' },
  { addr: 'E411.2', label: '' },
  { addr: 'E411.3', label: 'EM' },
  { addr: 'E411.4', label: '' },
  { addr: 'E411.5', label: '' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: 'IV2' },
  { addr: 'E413.1', label: 'TJ2' },
  { addr: 'E413.2', label: 'SA' },
  { addr: 'E413.3', label: 'RSI' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTAC' },
  { addr: 'E413.7', label: 'UC' },
  { addr: 'E414.0', label: 'AF7' },
  { addr: 'E414.1', label: '' },
  { addr: 'E414.2', label: 'FTM1' },
  { addr: 'E414.3', label: 'FTM2' },
  { addr: 'E414.4', label: '' },
  { addr: 'E414.5', label: 'TCR' },
  { addr: 'E414.6', label: 'AH' },
  { addr: 'E414.7', label: 'MTC' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RB' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'LB' },
  { addr: 'A2.0', label: 'LK' },
  { addr: 'A2.1', label: 'LE' },
  { addr: 'A2.2', label: 'LB' },
  { addr: 'A2.3', label: 'RDY' },
  { addr: 'A2.4', label: 'RST' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: 'LT1' },
  { addr: 'A2.7', label: 'LT2' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'SBK1' },
  { addr: 'A100.1', label: 'KBA1' },
  { addr: 'A100.2', label: 'KBA2' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'KQA' },
  { addr: 'A100.5', label: 'TD' },
  { addr: 'A100.6', label: 'T10' },
  { addr: 'A100.7', label: 'KEM' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: '' },
  { addr: 'A102.0', label: 'SMA1' },
  { addr: 'A102.1', label: 'SMB1' },
  { addr: 'A102.2', label: 'SMA2' },
  { addr: 'A102.3', label: 'SMB2' },
  { addr: 'A102.4', label: 'SMA3' },
  { addr: 'A102.5', label: 'SMB3' },
  { addr: 'A102.6', label: 'SMA4' },
  { addr: 'A102.7', label: 'SMB4' },
  { addr: 'A103.0', label: 'SXU1' },
  { addr: 'A103.1', label: 'SXD1' },
  { addr: 'A103.2', label: '' },
  { addr: 'A103.3', label: '' },
  { addr: 'A103.4', label: '' },
  { addr: 'A103.5', label: 'LC1' },
  { addr: 'A103.6', label: 'LA' },
  { addr: 'A103.7', label: 'LC' },
  { addr: 'A104.0', label: 'A' },
  { addr: 'A104.1', label: 'B' },
  { addr: 'A104.2', label: 'C' },
  { addr: 'A104.3', label: 'D' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: 'SPE' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: 'SBK2' },
  { addr: 'A105.6', label: 'SZE' },
  { addr: 'A105.7', label: 'SOE' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'SCA' },
  { addr: 'A110.1', label: 'SCB' },
  { addr: 'A110.2', label: 'T10F' },
  { addr: 'A110.3', label: 'TDF' },
  { addr: 'A110.4', label: '' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A200.0', label: 'SBK1' },
  { addr: 'A200.1', label: 'KBA1' },
  { addr: 'A200.2', label: 'KBA2' },
  { addr: 'A200.3', label: 'KXPE' },
  { addr: 'A200.4', label: 'KQA' },
  { addr: 'A200.5', label: 'TD' },
  { addr: 'A200.6', label: 'T10' },
  { addr: 'A200.7', label: 'KEM' },
  { addr: 'A201.0', label: 'L1' },
  { addr: 'A201.1', label: 'L2' },
  { addr: 'A201.2', label: 'L3' },
  { addr: 'A201.3', label: 'L4' },
  { addr: 'A201.4', label: 'L5' },
  { addr: 'A201.5', label: 'RFE' },
  { addr: 'A201.6', label: 'RLN' },
  { addr: 'A201.7', label: '' },
  { addr: 'A202.0', label: 'SMA1' },
  { addr: 'A202.1', label: 'SMB1' },
  { addr: 'A202.2', label: 'SMA2' },
  { addr: 'A202.3', label: 'SMB2' },
  { addr: 'A202.4', label: 'SMA3' },
  { addr: 'A202.5', label: 'SMB3' },
  { addr: 'A202.6', label: 'SMA4' },
  { addr: 'A202.7', label: 'SMB4' },
  { addr: 'A203.0', label: 'SXU1' },
  { addr: 'A203.1', label: 'SXD1' },
  { addr: 'A203.2', label: '' },
  { addr: 'A203.3', label: '' },
  { addr: 'A203.4', label: '' },
  { addr: 'A203.5', label: 'LC1' },
  { addr: 'A203.6', label: 'LA' },
  { addr: 'A203.7', label: 'LC' },
  { addr: 'A204.0', label: 'A' },
  { addr: 'A204.1', label: 'B' },
  { addr: 'A204.2', label: 'C' },
  { addr: 'A204.3', label: 'D' },
  { addr: 'A204.4', label: 'AD1' },
  { addr: 'A204.5', label: 'AD2' },
  { addr: 'A204.6', label: 'AD3' },
  { addr: 'A204.7', label: 'STR' },
  { addr: 'A205.0', label: 'SPE' },
  { addr: 'A205.1', label: '' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: 'SBK2' },
  { addr: 'A205.6', label: 'SZE' },
  { addr: 'A205.7', label: 'SOE' }
]
exports.outputs5 = [
  { addr: 'A210.0', label: 'SCA' },
  { addr: 'A210.1', label: 'SCB' },
  { addr: 'A210.2', label: 'T10F' },
  { addr: 'A210.3', label: 'TDF' },
  { addr: 'A210.4', label: '' },
  { addr: 'A210.5', label: '' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' }
]
exports.outputs6 = [
  { addr: 'A300.0', label: 'SBK1' },
  { addr: 'A300.1', label: 'KBA' },
  { addr: 'A300.2', label: '' },
  { addr: 'A300.3', label: '' },
  { addr: 'A300.4', label: 'SBK2' },
  { addr: 'A300.5', label: 'KBA' },
  { addr: 'A300.6', label: 'LA' },
  { addr: 'A300.7', label: 'LC' },
  { addr: 'A301.0', label: 'A' },
  { addr: 'A301.1', label: 'B' },
  { addr: 'A301.2', label: 'C' },
  { addr: 'A301.3', label: 'D' },
  { addr: 'A301.4', label: 'AD1' },
  { addr: 'A301.5', label: 'AD2' },
  { addr: 'A301.6', label: 'AD3' },
  { addr: 'A301.7', label: 'STR' }
]
exports.outputs7 = [
  { addr: 'A304.0', label: 'SMA' },
  { addr: 'A304.1', label: 'SMB' },
  { addr: 'A304.2', label: 'TCR' },
  { addr: 'A304.3', label: 'KSH' },
  { addr: 'A304.4', label: '' },
  { addr: 'A304.5', label: '' },
  { addr: 'A304.6', label: 'LA' },
  { addr: 'A304.7', label: '' }
]
exports.outputs8 = [
  { addr: 'A310.0', label: 'A' },
  { addr: 'A310.1', label: 'B' },
  { addr: 'A310.2', label: 'C' },
  { addr: 'A310.3', label: 'D' },
  { addr: 'A310.4', label: 'AD1' },
  { addr: 'A310.5', label: 'AD2' },
  { addr: 'A310.6', label: 'AD3' },
  { addr: 'A310.7', label: 'STR' },
  { addr: 'A311.0', label: 'T10-1' },
  { addr: 'A311.1', label: 'T2' },
  { addr: 'A311.2', label: 'TRA' },
  { addr: 'A311.3', label: 'TRB' },
  { addr: 'A311.4', label: 'KCS' },
  { addr: 'A311.5', label: 'KCV' },
  { addr: 'A311.6', label: 'KCH' },
  { addr: 'A311.7', label: 'TCR' },
  { addr: 'A312.0', label: 'KBA' },
  { addr: 'A312.1', label: '' },
  { addr: 'A312.2', label: '' },
  { addr: 'A312.3', label: '' },
  { addr: 'A312.4', label: 'T10-2' },
  { addr: 'A312.5', label: 'T10-F' },
  { addr: 'A312.6', label: 'LA' },
  { addr: 'A312.7', label: 'LC' }
]
exports.outputs9 = [
  { addr: 'A400.0', label: 'SBK1' },
  { addr: 'A400.1', label: 'KBA' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: 'SBK2' },
  { addr: 'A400.5', label: 'KBA' },
  { addr: 'A400.6', label: 'LA' },
  { addr: 'A400.7', label: 'LC' },
  { addr: 'A401.0', label: 'A' },
  { addr: 'A401.1', label: 'B' },
  { addr: 'A401.2', label: 'C' },
  { addr: 'A401.3', label: 'D' },
  { addr: 'A401.4', label: 'AD1' },
  { addr: 'A401.5', label: 'AD2' },
  { addr: 'A401.6', label: 'AD3' },
  { addr: 'A401.7', label: 'STR' }
]
exports.outputs10 = [
  { addr: 'A404.0', label: 'SMA' },
  { addr: 'A404.1', label: 'SMB' },
  { addr: 'A404.2', label: 'TCR' },
  { addr: 'A404.3', label: 'KSH' },
  { addr: 'A404.4', label: '' },
  { addr: 'A404.5', label: '' },
  { addr: 'A404.6', label: 'LA' },
  { addr: 'A404.7', label: '' }
]
exports.outputs11 = [
  { addr: 'A410.0', label: 'A' },
  { addr: 'A410.1', label: 'B' },
  { addr: 'A410.2', label: 'C' },
  { addr: 'A410.3', label: 'D' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'AD3' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'T10-1' },
  { addr: 'A411.1', label: 'T2' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'KCS' },
  { addr: 'A411.5', label: 'KCV' },
  { addr: 'A411.6', label: 'KCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'KBA' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: 'T10-2' },
  { addr: 'A412.5', label: 'T10-F' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' }
]

exports.ALARMS = [
  { id: 1, key: 'al-v-to', query: {} },
  { id: 2, key: 'al-h-to', query: {} },
  { id: 3, key: 'al-r-to', query: {} },
  { id: 4, key: 'al-v-lck-to', query: { nr: 1 } },
  { id: 5, key: 'al-v-lck-to', query: { nr: 2 } },
  { id: 6, key: 'al-v-lck-to', query: { nr: 3 } },
  { id: 7, key: 'al-v-lck-to', query: { nr: 4 } },
  { id: 8, key: 'al-h-lck-to', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: 'al-flap-to', query: {} },
  { id: 11, key: 'al-sp-to', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: 'al-v-fdbk', query: {} },
  { id: 15, key: 'al-v-fdbk', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: 'al-th', query: { name: 'AMM1' } },
  { id: 18, key: 'al-th', query: { name: 'AMM2' } },
  { id: 19, key: 'al-th', query: { name: 'AX1' } },
  { id: 20, key: '', query: {} },
  { id: 21, key: 'al-iv', query: { nr: 1 } },
  { id: 22, key: 'al-iv', query: { nr: 2 } },
  { id: 23, key: 'al-th', query: { name: 'APE' } },
  { id: 24, key: 'al-th', query: { name: 'FE1' } },
  { id: 25, key: 'al-th', query: { name: 'ASH' } },
  { id: 26, key: 'al-th', query: { name: 'AH' } },
  { id: 27, key: 'al-th', query: { name: 'ASBK' } },
  { id: 28, key: 'al-th', query: { name: 'RTA' } },
  { id: 29, key: 'al-th', query: { name: 'AMM3' } },
  { id: 30, key: 'al-th', query: { name: 'AMM4' } },
  { id: 31, key: 'al-th', query: { name: 'AMC' } },
  { id: 32, key: 'al-th', query: { name: 'ASKD' } },
  { id: 33, key: 'al-fc', query: { fc1: 'EOM1', fc2: 'EZM1' } },
  { id: 34, key: 'al-fc', query: { fc1: 'EOM2', fc2: 'EZM2' } },
  { id: 35, key: 'al-fc', query: { fc1: 'EOM3', fc2: 'EZM3' } },
  { id: 36, key: 'al-fc', query: { fc1: 'EOM4', fc2: 'EZM4' } },
  { id: 37, key: 'al-fc', query: { fc1: 'FLDX', fc2: 'FLSX' } },
  { id: 38, key: '', query: {} },
  { id: 39, key: 'al-fc', query: { fc1: 'ECA', fc2: 'ECB' } },
  { id: 40, key: 'al-fc', query: { fc1: 'EXPV', fc2: 'EFA' } },
  { id: 41, key: 'al-fc', query: { fc1: 'EZE', fc2: 'EOE' } },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: 'al-fal', query: {} },
  { id: 49, key: 'al-lv', query: { nr: 1 } },
  { id: 50, key: 'al-lv', query: { nr: 2 } },
  { id: 51, key: 'al-enh', query: {} },
  { id: 52, key: 'al-enr', query: {} },
  { id: 53, key: 'al-lv-diff', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-01', query: {} },
  { id: 67, key: 'al-sil-01', query: {} },
  { id: 68, key: 'al-sil-02', query: {} },
  { id: 69, key: 'al-sil-03', query: {} },
  { id: 70, key: 'al-sil-04', query: {} },
  { id: 71, key: 'al-v-to', query: {} },
  { id: 72, key: 'al-h-to', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: 'al-v-fdbk', query: {} },
  { id: 75, key: 'al-v-fdbk', query: {} },
  { id: 76, key: 'al-v-lck', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-th', query: { name: 'FE1' } },
  { id: 82, key: 'al-iv', query: { nr: 1 } },
  { id: 83, key: 'al-tl', query: { name: 'TJ1' } },
  { id: 84, key: 'al-th', query: { name: 'ASBK' } },
  { id: 85, key: 'al-th', query: { name: 'RTA' } },
  { id: 86, key: 'al-th', query: { name: 'AGK' } },
  { id: 87, key: 'al-th', query: { name: 'ACR' } },
  { id: 88, key: 'al-th', query: { name: 'FE3' } },
  { id: 89, key: 'al-th', query: { name: 'AMM' } },
  { id: 90, key: 'al-th', query: { name: 'FE4' } },
  { id: 91, key: 'al-iv', query: { nr: 2 } },
  { id: 92, key: 'al-tl', query: { name: 'TJ2' } },
  { id: 93, key: 'al-th', query: { name: 'AF7' } },
  { id: 94, key: 'al-th', query: { name: 'AH' } },
  { id: 95, key: 'al-th', query: { name: 'MTC' } },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-fc', query: { fc1: 'EOM', fc2: 'EZM' } },
  { id: 98, key: 'al-sil-07', query: {} },
  { id: 99, key: 'al-sil-12', query: {} },
  { id: 100, key: 'al-sil-13', query: {} },
  { id: 101, key: 'al-fc', query: { fc1: 'FDL', fc2: 'FDR' } },
  { id: 102, key: 'al-sil-11', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: 'al-fal', query: {} },
  { id: 113, key: 'al-lv', query: { nr: 1 } },
  { id: 114, key: 'al-lv', query: { nr: 2 } },
  { id: 115, key: 'al-lh', query: { nr: 1 } },
  { id: 116, key: 'al-lh', query: { nr: 2 } },
  { id: 117, key: 'al-lv-diff', query: {} },
  { id: 118, key: 'al-lh-diff', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'EL4' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
