export const inputs1 = [
  { addr: 'E0.0', label: 'PS' },
  { addr: 'E0.1', label: 'SA1' },
  { addr: 'E0.2', label: 'SA2' },
  { addr: 'E0.3', label: 'SA3' },
  { addr: 'E0.4', label: 'RS12' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }]
export const inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: '' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: 'RS12' },
  { addr: 'E101.3', label: 'SRL' },
  { addr: 'E101.4', label: 'RTJ12' },
  { addr: 'E101.5', label: 'ASBK' },
  { addr: 'E101.6', label: 'UC' },
  { addr: 'E101.7', label: 'RS3' },
  { addr: 'E102.0', label: 'FSBK' },
  { addr: 'E102.1', label: 'AMC' },
  { addr: 'E102.2', label: 'TJ1' },
  { addr: 'E102.3', label: 'AP' },
  { addr: 'E102.4', label: 'APB' },
  { addr: 'E102.5', label: 'IV1' },
  { addr: 'E102.6', label: 'FE' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: 'ECA' },
  { addr: 'E103.1', label: 'ECB' },
  { addr: 'E103.2', label: 'FBBE' },
  { addr: 'E103.3', label: 'FBE' },
  { addr: 'E103.4', label: 'FPE' },
  { addr: 'E103.5', label: 'FDR1' },
  { addr: 'E103.6', label: 'FDL1' },
  { addr: 'E103.7', label: 'FDR2' },
  { addr: 'E104.0', label: 'FDL2' },
  { addr: 'E104.1', label: 'FLP1' },
  { addr: 'E104.2', label: 'FLA1' },
  { addr: 'E104.3', label: 'FTA1' },
  { addr: 'E104.4', label: 'FTA2' },
  { addr: 'E104.5', label: 'FTA2-1' },
  { addr: 'E104.6', label: 'EBZE' },
  { addr: 'E104.7', label: 'EBOE' },
  { addr: 'E105.0', label: 'EZE' },
  { addr: 'E105.1', label: 'EOE' },
  { addr: 'E105.2', label: 'FRE3' },
  { addr: 'E105.3', label: 'FREL' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: 'FDR1-1' },
  { addr: 'E105.6', label: 'FDL1-1' },
  { addr: 'E105.7', label: 'LOOP' },
  { addr: 'E106.0', label: 'FPA' },
  { addr: 'E106.1', label: 'FBA' },
  { addr: 'E106.2', label: 'FBBA' },
  { addr: 'E106.3', label: 'EZA' },
  { addr: 'E106.4', label: 'EOA' },
  { addr: 'E106.5', label: 'EBZA' },
  { addr: 'E106.6', label: 'EBOA' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: '' },
  { addr: 'E107.1', label: '' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' },
  { addr: 'E108.0', label: '' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: '' },
  { addr: 'E108.3', label: '' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' },
  { addr: 'E110.0', label: 'ACR' },
  { addr: 'E110.1', label: 'AMM' },
  { addr: 'E110.2', label: 'ASH' },
  { addr: 'E110.3', label: 'FTCR' },
  { addr: 'E110.4', label: 'RS12' },
  { addr: 'E110.5', label: 'EMC' },
  { addr: 'E110.6', label: 'EOM' },
  { addr: 'E110.7', label: 'EZM' },
  { addr: 'E111.0', label: 'FE' },
  { addr: 'E111.1', label: 'EXV' },
  { addr: 'E111.2', label: 'EXPV' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: '' },
  { addr: 'E112.0', label: 'A' },
  { addr: 'E112.1', label: 'B' },
  { addr: 'E112.2', label: 'C' },
  { addr: 'E112.3', label: 'D' },
  { addr: 'E112.4', label: 'OK' },
  { addr: 'E112.5', label: 'S2' },
  { addr: 'E112.6', label: 'S2' },
  { addr: 'E112.7', label: 'S2' },
  { addr: 'E113.0', label: 'UC' },
  { addr: 'E113.1', label: 'RS3' },
  { addr: 'E113.2', label: 'EM' },
  { addr: 'E113.3', label: 'FTXV' },
  { addr: 'E113.4', label: 'FTXH' },
  { addr: 'E113.5', label: 'FT10' },
  { addr: 'E113.6', label: 'ASBK' },
  { addr: 'E113.7', label: 'IV2' },
  { addr: 'E114.0', label: 'MTC1' },
  { addr: 'E114.1', label: 'MTC2' },
  { addr: 'E114.2', label: 'FTCR' },
  { addr: 'E114.3', label: 'DB32' },
  { addr: 'E114.4', label: 'DBHZ' },
  { addr: 'E114.5', label: 'RS12' },
  { addr: 'E114.6', label: 'FTJ2' },
  { addr: 'E114.7', label: 'FE1' },
  { addr: 'E115.0', label: 'RMV' },
  { addr: 'E115.1', label: 'RMH' },
  { addr: 'E115.2', label: 'RES' },
  { addr: 'E115.3', label: 'REH' },
  { addr: 'E115.4', label: 'RCV' },
  { addr: 'E115.5', label: 'REAV' },
  { addr: 'E115.6', label: 'REAH' },
  { addr: 'E115.7', label: 'RCH' },
  { addr: 'E116.0', label: '' },
  { addr: 'E116.1', label: '' },
  { addr: 'E116.2', label: '' },
  { addr: 'E116.3', label: '' },
  { addr: 'E116.4', label: '' },
  { addr: 'E116.5', label: '' },
  { addr: 'E116.6', label: '' },
  { addr: 'E116.7', label: '' },
  { addr: 'E117.0', label: '' },
  { addr: 'E117.1', label: '' },
  { addr: 'E117.2', label: '' },
  { addr: 'E117.3', label: '' },
  { addr: 'E117.4', label: '' },
  { addr: 'E117.5', label: '' },
  { addr: 'E117.6', label: '' },
  { addr: 'E117.7', label: '' }]
export const outputs1 = [
  { addr: 'A0.0', label: 'LS' },
  { addr: 'A0.1', label: 'LS1' },
  { addr: 'A0.2', label: 'LS2' },
  { addr: 'A0.3', label: 'LS3' },
  { addr: 'A0.4', label: 'LA1' },
  { addr: 'A0.5', label: 'LA2' },
  { addr: 'A0.6', label: 'LA3' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }]
export const outputs2 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'SBK1' },
  { addr: 'A101.1', label: 'SBK2' },
  { addr: 'A101.2', label: 'STO1-1' },
  { addr: 'A101.3', label: 'STO2-1' },
  { addr: 'A101.4', label: 'LA' },
  { addr: 'A101.5', label: 'LC' },
  { addr: 'A101.6', label: 'SCA' },
  { addr: 'A101.7', label: 'SCB' },
  { addr: 'A102.0', label: 'SPE' },
  { addr: 'A102.1', label: 'SOE' },
  { addr: 'A102.2', label: 'SZE' },
  { addr: 'A102.3', label: 'SPBE' },
  { addr: 'A102.4', label: 'SBOE' },
  { addr: 'A102.5', label: 'SBZE' },
  { addr: 'A102.6', label: 'SPA' },
  { addr: 'A102.7', label: 'SOA' },
  { addr: 'A103.0', label: 'SZA' },
  { addr: 'A103.1', label: 'SPBA' },
  { addr: 'A103.2', label: 'SBOA' },
  { addr: 'A103.3', label: 'SBZA' },
  { addr: 'A103.4', label: 'RFE' },
  { addr: 'A103.5', label: 'RFA' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: 'CAR' },
  { addr: 'A104.0', label: '' },
  { addr: 'A104.1', label: '' },
  { addr: 'A104.2', label: '' },
  { addr: 'A104.3', label: '' },
  { addr: 'A104.4', label: '' },
  { addr: 'A104.5', label: '' },
  { addr: 'A104.6', label: '' },
  { addr: 'A104.7', label: '' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }]
export const outputs3 = [
  { addr: 'A110.0', label: 'SMA' },
  { addr: 'A110.1', label: 'SMB' },
  { addr: 'A110.2', label: 'TCR' },
  { addr: 'A110.3', label: 'LA' },
  { addr: 'A110.4', label: 'LC' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' },
  { addr: 'A112.0', label: 'DYA' },
  { addr: 'A112.1', label: 'DYB' },
  { addr: 'A112.2', label: 'DYC' },
  { addr: 'A112.3', label: 'DYD' },
  { addr: 'A112.4', label: 'AD1' },
  { addr: 'A112.5', label: 'AD2' },
  { addr: 'A112.6', label: 'AD3' },
  { addr: 'A112.7', label: 'STR' },
  { addr: 'A113.0', label: 'LC' },
  { addr: 'A113.1', label: 'T10F' },
  { addr: 'A113.2', label: '' },
  { addr: 'A113.3', label: 'TRA' },
  { addr: 'A113.4', label: 'TRB' },
  { addr: 'A113.5', label: 'TCR' },
  { addr: 'A113.6', label: 'KCS' },
  { addr: 'A113.7', label: 'KCV' },
  { addr: 'A114.0', label: 'KCH' },
  { addr: 'A114.1', label: 'LA' },
  { addr: 'A114.2', label: 'T101' },
  { addr: 'A114.3', label: 'T102' },
  { addr: 'A114.4', label: 'T2' },
  { addr: 'A114.5', label: 'STO1-2' },
  { addr: 'A114.6', label: 'STO2-2' },
  { addr: 'A114.7', label: '' },
  { addr: 'A115.0', label: '' },
  { addr: 'A115.1', label: '' },
  { addr: 'A115.2', label: '' },
  { addr: 'A115.3', label: '' },
  { addr: 'A115.4', label: '' },
  { addr: 'A115.5', label: '' },
  { addr: 'A115.6', label: '' },
  { addr: 'A115.7', label: '' }]
export const alarms1 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-h-to', query: {} },
  { id: 24, key: 'al-lh', query: {} },
  { id: 25, key: 'al-lh-diff', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-pn', query: { name: 'LS' } },
  { id: 42, key: 'al-pn', query: { name: 'KKP' } },
  { id: 43, key: 'al-pn', query: { name: 'SH' } },
  { id: 44, key: 'al-pn', query: { name: 'IV1' } },
  { id: 45, key: 'al-pn', query: { name: 'IV2' } },
  { id: 46, key: 'al-pn', query: { name: 'LV1' } },
  { id: 47, key: 'al-pn', query: { name: 'LV2' } },
  { id: 48, key: 'al-pn', query: { name: 'LH' } },
  { id: 49, key: 'al-th', query: { name: 'FE2' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: '', query: {} },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'RTJ' } },
  { id: 54, key: 'al-th', query: { name: 'FE3' } },
  { id: 55, key: 'al-th', query: { name: 'AMM' } },
  { id: 56, key: 'al-th', query: { name: 'ASH' } },
  { id: 57, key: '', query: {} },
  { id: 58, key: 'al-th', query: { name: 'FE4' } },
  { id: 59, key: 'al-iv', query: { nr: 2 } },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 63, key: 'al-th', query: { name: 'MTC1' } },
  { id: 64, key: 'al-th', query: { name: 'MTC2' } }
]
export const alarms2 = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: 'al-flap-to', query: {} },
  { id: 32, key: 'al-flap-fc', query: {} },
  { id: 33, key: 'al-spe-to', query: {} },
  { id: 34, key: 'al-spe-to', query: {} },
  { id: 35, key: 'al-spe-fc', query: {} },
  { id: 36, key: 'al-spe-to', query: {} },
  { id: 37, key: 'al-spe-to', query: {} },
  { id: 38, key: 'al-spe-fc', query: {} },
  { id: 39, key: 'al-spbe-to', query: {} },
  { id: 40, key: 'al-spbe-to', query: {} },
  { id: 41, key: 'al-spa-fc', query: {} },
  { id: 42, key: 'al-spa-to', query: {} },
  { id: 43, key: 'al-spba-to', query: {} },
  { id: 44, key: 'al-spba-fc', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: 'al-th', query: { name: 'AMC' } },
  { id: 60, key: 'al-th', query: { name: 'AP' } },
  { id: 61, key: 'al-th', query: { name: 'APB' } },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} }
]
export const ALARMS = alarms1.concat(alarms2)
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'E1' },
  { id: 5, key: 'E2' },
  { id: 6, key: 'E3' },
  { id: 7, key: 'U1' },
  { id: 8, key: 'U2' },
  { id: 9, key: 'U3' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
