// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'FE' },
  { addr: 'E0.1', label: 'K12' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'FE1' },
  { addr: 'E11.1', label: 'IV1' },
  { addr: 'E11.2', label: 'RSI' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: 'FDBK' },
  { addr: 'E11.5', label: 'ASBK' },
  { addr: 'E11.6', label: 'RTA' },
  { addr: 'E11.7', label: 'UC' },
  { addr: 'E12.0', label: 'FSQA' },
  { addr: 'E12.1', label: 'FSQB' },
  { addr: 'E12.2', label: '' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: '' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: 'DB32' },
  { addr: 'E13.6', label: 'DBHZ' },
  { addr: 'E13.7', label: '' },
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: 'ACR' },
  { addr: 'E14.2', label: 'FTCR' },
  { addr: 'E14.3', label: 'FE' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: 'AMM' },
  { addr: 'E15.3', label: 'EOM' },
  { addr: 'E15.4', label: 'EZM' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' }
]
export const inputs3 = [
  { addr: 'E20.0', label: 'A' },
  { addr: 'E20.1', label: 'B' },
  { addr: 'E20.2', label: 'C' },
  { addr: 'E20.3', label: 'D' },
  { addr: 'E20.4', label: 'OK' },
  { addr: 'E20.5', label: 'S2' },
  { addr: 'E20.6', label: 'S2' },
  { addr: 'E20.7', label: 'S2' },
  { addr: 'E21.0', label: 'FE' },
  { addr: 'E21.1', label: 'FTC' },
  { addr: 'E21.2', label: 'FPE' },
  { addr: 'E21.3', label: 'DB32' },
  { addr: 'E21.4', label: 'DBHZ' },
  { addr: 'E21.5', label: 'AMC' },
  { addr: 'E21.6', label: 'AH12' },
  { addr: 'E21.7', label: 'UC' },
  { addr: 'E22.0', label: 'FTXV' },
  { addr: 'E22.1', label: 'FTXH' },
  { addr: 'E22.2', label: 'ECA' },
  { addr: 'E22.3', label: 'ECB' },
  { addr: 'E22.4', label: 'FREL' },
  { addr: 'E22.5', label: 'FRER' },
  { addr: 'E22.6', label: 'MNR' },
  { addr: 'E22.7', label: 'MNL' },
  { addr: 'E23.0', label: '' },
  { addr: 'E23.1', label: '' },
  { addr: 'E23.2', label: '' },
  { addr: 'E23.3', label: '' },
  { addr: 'E23.4', label: '' },
  { addr: 'E23.5', label: '' },
  { addr: 'E23.6', label: '' },
  { addr: 'E23.7', label: '' }
]
export const inputs4 = [
  { addr: 'E30.0', label: 'FE' },
  { addr: 'E30.1', label: 'APE' },
  { addr: 'E30.2', label: 'APBE' },
  { addr: 'E30.3', label: 'FLA2' },
  { addr: 'E30.4', label: '' },
  { addr: 'E30.5', label: '' },
  { addr: 'E30.6', label: '' },
  { addr: 'E30.7', label: '' },
  { addr: 'E31.0', label: 'FBE' },
  { addr: 'E31.1', label: 'FBBE' },
  { addr: 'E31.2', label: 'FPE' },
  { addr: 'E31.3', label: 'FDR1' },
  { addr: 'E31.4', label: 'FDL1' },
  { addr: 'E31.5', label: 'FDR2' },
  { addr: 'E31.6', label: 'FDL2' },
  { addr: 'E31.7', label: 'FDR11' },
  { addr: 'E32.0', label: 'FDL11' },
  { addr: 'E32.1', label: 'FTA1' },
  { addr: 'E32.2', label: 'FLP1' },
  { addr: 'E32.3', label: 'FLA1' },
  { addr: 'E32.4', label: 'EZE' },
  { addr: 'E32.5', label: 'EOE' },
  { addr: 'E32.6', label: 'EBZE' },
  { addr: 'E32.7', label: 'EBOE' },
  { addr: 'E33.0', label: '' },
  { addr: 'E33.1', label: '' },
  { addr: 'E33.2', label: '' },
  { addr: 'E33.3', label: '' },
  { addr: 'E33.4', label: '' },
  { addr: 'E33.5', label: '' },
  { addr: 'E33.6', label: '' },
  { addr: 'E33.7', label: '' }
]
export const inputs5 = [
  { addr: 'E40.0', label: 'A' },
  { addr: 'E40.1', label: 'B' },
  { addr: 'E40.2', label: 'C' },
  { addr: 'E40.3', label: 'D' },
  { addr: 'E40.4', label: 'OK' },
  { addr: 'E40.5', label: 'S2' },
  { addr: 'E40.6', label: 'S2' },
  { addr: 'E40.7', label: 'S2' },
  { addr: 'E41.0', label: 'FE1' },
  { addr: 'E41.1', label: 'IV1' },
  { addr: 'E41.2', label: 'RSI' },
  { addr: 'E41.3', label: '' },
  { addr: 'E41.4', label: 'FDBK' },
  { addr: 'E41.5', label: 'ASBK' },
  { addr: 'E41.6', label: 'RTA' },
  { addr: 'E41.7', label: 'UC' },
  { addr: 'E42.0', label: '' },
  { addr: 'E42.1', label: '' },
  { addr: 'E42.2', label: '' },
  { addr: 'E42.3', label: '' },
  { addr: 'E42.4', label: '' },
  { addr: 'E42.5', label: '' },
  { addr: 'E42.6', label: '' },
  { addr: 'E42.7', label: '' },
  { addr: 'E43.0', label: '' },
  { addr: 'E43.1', label: '' },
  { addr: 'E43.2', label: '' },
  { addr: 'E43.3', label: '' },
  { addr: 'E43.4', label: '' },
  { addr: 'E43.5', label: 'DB32' },
  { addr: 'E43.6', label: 'DBHZ' },
  { addr: 'E43.7', label: '' },
  { addr: 'E44.0', label: '' },
  { addr: 'E44.1', label: 'ACR' },
  { addr: 'E44.2', label: 'FTCR' },
  { addr: 'E44.3', label: 'FE' },
  { addr: 'E44.4', label: '' },
  { addr: 'E44.5', label: '' },
  { addr: 'E44.6', label: '' },
  { addr: 'E44.7', label: '' },
  { addr: 'E45.0', label: '' },
  { addr: 'E45.1', label: '' },
  { addr: 'E45.2', label: 'AMM' },
  { addr: 'E45.3', label: 'EOM' },
  { addr: 'E45.4', label: 'EZM' },
  { addr: 'E45.5', label: '' },
  { addr: 'E45.6', label: '' },
  { addr: 'E45.7', label: '' }
]
export const inputs6 = [
  { addr: 'E50.0', label: 'A' },
  { addr: 'E50.1', label: 'B' },
  { addr: 'E50.2', label: 'C' },
  { addr: 'E50.3', label: 'D' },
  { addr: 'E50.4', label: 'OK' },
  { addr: 'E50.5', label: 'S2' },
  { addr: 'E50.6', label: 'S2' },
  { addr: 'E50.7', label: 'S2' },
  { addr: 'E51.0', label: 'FE1' },
  { addr: 'E51.1', label: 'AF1' },
  { addr: 'E51.2', label: 'FTCR' },
  { addr: 'E51.3', label: 'EM' },
  { addr: 'E51.4', label: '' },
  { addr: 'E51.5', label: 'FTM' },
  { addr: 'E51.6', label: 'FTXV' },
  { addr: 'E51.7', label: 'FTXH' },
  { addr: 'E52.0', label: 'RMV' },
  { addr: 'E52.1', label: 'RMH' },
  { addr: 'E52.2', label: 'RES' },
  { addr: 'E52.3', label: 'REH' },
  { addr: 'E52.4', label: 'RCV' },
  { addr: 'E52.5', label: 'REAV' },
  { addr: 'E52.6', label: 'REAH' },
  { addr: 'E52.7', label: 'RCH' },
  { addr: 'E53.0', label: 'IV2' },
  { addr: 'E53.1', label: 'AH12' },
  { addr: 'E53.2', label: 'MTC' },
  { addr: 'E53.3', label: '' },
  { addr: 'E53.4', label: 'DB32' },
  { addr: 'E53.5', label: 'DBHZ' },
  { addr: 'E53.6', label: '' },
  { addr: 'E53.7', label: 'UC' },
  { addr: 'E54.0', label: '' },
  { addr: 'E54.1', label: '' },
  { addr: 'E54.2', label: '' },
  { addr: 'E54.3', label: '' },
  { addr: 'E54.4', label: '' },
  { addr: 'E54.5', label: '' },
  { addr: 'E54.6', label: '' },
  { addr: 'E54.7', label: '' }
]
export const inputs7 = [
  { addr: 'E1000.0', label: 'UG-BBL' },
  { addr: 'E1000.1', label: 'BSE' },
  { addr: 'E1000.2', label: 'PS1' },
  { addr: 'E1000.3', label: 'PS2' },
  { addr: 'E1000.4', label: 'SF1' },
  { addr: 'E1000.5', label: 'BBL1' },
  { addr: 'E1000.6', label: 'SF2' },
  { addr: 'E1000.7', label: 'BBL2' },
  { addr: 'E1001.0', label: 'K1' },
  { addr: 'E1001.1', label: 'K2' },
  { addr: 'E1001.2', label: '' },
  { addr: 'E1001.3', label: '' },
  { addr: 'E1001.4', label: '' },
  { addr: 'E1001.5', label: '' },
  { addr: 'E1001.6', label: '' },
  { addr: 'E1001.7', label: '' }
]
export const inputs8 = [
  { addr: 'E1020.0', label: 'UG-BBL' },
  { addr: 'E1020.1', label: 'RS12' },
  { addr: 'E1020.2', label: '' },
  { addr: 'E1020.3', label: 'SF1' },
  { addr: 'E1020.4', label: 'UC' },
  { addr: 'E1020.5', label: 'BBV1' },
  { addr: 'E1020.6', label: 'BBV2' },
  { addr: 'E1020.7', label: 'BPS' },
  { addr: 'E1021.0', label: '' },
  { addr: 'E1021.1', label: 'BBE' },
  { addr: 'E1021.2', label: 'BBA' },
  { addr: 'E1021.3', label: '' },
  { addr: 'E1021.4', label: '' },
  { addr: 'E1021.5', label: '' },
  { addr: 'E1021.6', label: '' },
  { addr: 'E1021.7', label: '' }
]
export const inputs9 = [
  { addr: 'E1040.0', label: 'BBP' },
  { addr: 'E1040.1', label: 'K12' },
  { addr: 'E1040.2', label: 'ETA/B' },
  { addr: 'E1040.3', label: 'EMC' },
  { addr: 'E1040.4', label: '' },
  { addr: 'E1040.5', label: '' },
  { addr: 'E1040.6', label: '' },
  { addr: 'E1040.7', label: '' }
]
export const inputs10 = [
  { addr: 'E1060.0', label: 'BBL' },
  { addr: 'E1060.1', label: 'K12' },
  { addr: 'E1060.2', label: 'SF1' },
  { addr: 'E1060.3', label: 'UC' },
  { addr: 'E1060.4', label: 'BBV1' },
  { addr: 'E1060.5', label: 'BBV2' },
  { addr: 'E1060.6', label: 'BPS' },
  { addr: 'E1060.7', label: 'ETL/R' }
]
export const inputs11 = [
  { addr: 'E1080.0', label: 'UG-BBL' },
  { addr: 'E1080.1', label: 'RS12' },
  { addr: 'E1080.2', label: '' },
  { addr: 'E1080.3', label: 'SF2' },
  { addr: 'E1080.4', label: 'UC' },
  { addr: 'E1080.5', label: 'BBV1' },
  { addr: 'E1080.6', label: 'BBV2' },
  { addr: 'E1080.7', label: 'BPS' },
  { addr: 'E1081.0', label: '' },
  { addr: 'E1081.1', label: '' },
  { addr: 'E1081.2', label: '' },
  { addr: 'E1081.3', label: '' },
  { addr: 'E1081.4', label: '' },
  { addr: 'E1081.5', label: '' },
  { addr: 'E1081.6', label: '' },
  { addr: 'E1081.7', label: '' }
]
export const inputs12 = [
  { addr: 'E1100.0', label: 'BBP' },
  { addr: 'E1100.1', label: 'K12' },
  { addr: 'E1100.2', label: 'ETA/B' },
  { addr: 'E1100.3', label: 'EMC' },
  { addr: 'E1100.4', label: '' },
  { addr: 'E1100.5', label: '' },
  { addr: 'E1100.6', label: '' },
  { addr: 'E1100.7', label: '' }
]
export const inputs13 = [
  { addr: 'E1120.0', label: 'BBL' },
  { addr: 'E1120.1', label: 'K12' },
  { addr: 'E1120.2', label: 'SF2' },
  { addr: 'E1120.3', label: 'UC' },
  { addr: 'E1120.4', label: 'BBV1' },
  { addr: 'E1120.5', label: 'BBV2' },
  { addr: 'E1120.6', label: 'BPS' },
  { addr: 'E1120.7', label: 'ETL/R' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LSK' },
  { addr: 'A0.1', label: 'LA' },
  { addr: 'A0.2', label: 'LS1' },
  { addr: 'A0.3', label: 'LS2' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'SBK1' },
  { addr: 'A10.1', label: 'SBK2' },
  { addr: 'A10.2', label: 'SQA' },
  { addr: 'A10.3', label: 'SQB' },
  { addr: 'A10.4', label: 'KBA1' },
  { addr: 'A10.5', label: '' },
  { addr: 'A10.6', label: 'LA' },
  { addr: 'A10.7', label: 'LC' },
  { addr: 'A11.0', label: 'DYA' },
  { addr: 'A11.1', label: 'DYB' },
  { addr: 'A11.2', label: 'DYC' },
  { addr: 'A11.3', label: 'DYD' },
  { addr: 'A11.4', label: 'AD1' },
  { addr: 'A11.5', label: 'AD2' },
  { addr: 'A11.6', label: 'AD3' },
  { addr: 'A11.7', label: 'STR' },
  { addr: 'A12.0', label: 'SMA' },
  { addr: 'A12.1', label: 'SMB' },
  { addr: 'A12.2', label: 'TCR' },
  { addr: 'A12.3', label: '' },
  { addr: 'A12.4', label: '' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: 'LA' },
  { addr: 'A12.7', label: '' }
]
export const outputs3 = [
  { addr: 'A20.0', label: 'DYA' },
  { addr: 'A20.1', label: 'DYB' },
  { addr: 'A20.2', label: 'DYC' },
  { addr: 'A20.3', label: 'DYD' },
  { addr: 'A20.4', label: 'AD1' },
  { addr: 'A20.5', label: 'AD2' },
  { addr: 'A20.6', label: 'AD3' },
  { addr: 'A20.7', label: 'STR' },
  { addr: 'A21.0', label: 'T101' },
  { addr: 'A21.1', label: 'T102' },
  { addr: 'A21.2', label: 'T10F' },
  { addr: 'A21.3', label: 'LA' },
  { addr: 'A21.4', label: 'LC' },
  { addr: 'A21.5', label: 'SCA' },
  { addr: 'A21.6', label: 'SCB' },
  { addr: 'A21.7', label: 'TCR' }
]
export const outputs4 = [
  { addr: 'A30.0', label: '' },
  { addr: 'A30.1', label: 'RFE' },
  { addr: 'A30.2', label: 'RFA' },
  { addr: 'A30.3', label: 'L1' },
  { addr: 'A30.4', label: 'L2' },
  { addr: 'A30.5', label: 'L3' },
  { addr: 'A30.6', label: 'L4' },
  { addr: 'A30.7', label: 'L5' },
  { addr: 'A31.0', label: 'SPE' },
  { addr: 'A31.1', label: 'SPBE' },
  { addr: 'A31.2', label: 'SOE' },
  { addr: 'A31.3', label: 'SZE' },
  { addr: 'A31.4', label: 'SBOE' },
  { addr: 'A31.5', label: 'SBZE' },
  { addr: 'A31.6', label: '' },
  { addr: 'A31.7', label: '' },
  { addr: 'A32.0', label: 'LA' },
  { addr: 'A32.1', label: '' },
  { addr: 'A32.2', label: '' },
  { addr: 'A32.3', label: '' },
  { addr: 'A32.4', label: '' },
  { addr: 'A32.5', label: '' },
  { addr: 'A32.6', label: '' },
  { addr: 'A32.7', label: '' }
]
export const outputs5 = [
  { addr: 'A40.0', label: 'SBK1' },
  { addr: 'A40.1', label: 'KBA1' },
  { addr: 'A40.2', label: '' },
  { addr: 'A40.3', label: '' },
  { addr: 'A40.4', label: 'SBK2' },
  { addr: 'A40.5', label: '' },
  { addr: 'A40.6', label: 'LA' },
  { addr: 'A40.7', label: 'LC' },
  { addr: 'A41.0', label: 'DYA' },
  { addr: 'A41.1', label: 'DYB' },
  { addr: 'A41.2', label: 'DYC' },
  { addr: 'A41.3', label: 'DYD' },
  { addr: 'A41.4', label: 'AD1' },
  { addr: 'A41.5', label: 'AD2' },
  { addr: 'A41.6', label: 'AD3' },
  { addr: 'A41.7', label: 'STR' },
  { addr: 'A42.0', label: 'SMA' },
  { addr: 'A42.1', label: 'SMB' },
  { addr: 'A42.2', label: 'TCR' },
  { addr: 'A42.3', label: '' },
  { addr: 'A42.4', label: '' },
  { addr: 'A42.5', label: '' },
  { addr: 'A42.6', label: 'LA' },
  { addr: 'A42.7', label: '' }
]
export const outputs6 = [
  { addr: 'A50.0', label: 'DYA' },
  { addr: 'A50.1', label: 'DYB' },
  { addr: 'A50.2', label: 'DYC' },
  { addr: 'A50.3', label: 'DYD' },
  { addr: 'A50.4', label: 'AD1' },
  { addr: 'A50.5', label: 'AD2' },
  { addr: 'A50.6', label: 'AD3' },
  { addr: 'A50.7', label: 'STR' },
  { addr: 'A51.0', label: 'T101' },
  { addr: 'A51.1', label: 'T2' },
  { addr: 'A51.2', label: 'TRA' },
  { addr: 'A51.3', label: 'TRB' },
  { addr: 'A51.4', label: 'KCS' },
  { addr: 'A51.5', label: 'KCV' },
  { addr: 'A51.6', label: 'KCH' },
  { addr: 'A51.7', label: 'TCR' },
  { addr: 'A52.0', label: 'KBA1' },
  { addr: 'A52.1', label: '' },
  { addr: 'A52.2', label: '' },
  { addr: 'A52.3', label: '' },
  { addr: 'A52.4', label: 'T102' },
  { addr: 'A52.5', label: 'T10F' },
  { addr: 'A52.6', label: 'LA' },
  { addr: 'A52.7', label: 'LC' }
]
export const outputs7 = [
  { addr: 'A1010.0', label: 'K1' },
  { addr: 'A1010.1', label: 'K2' },
  { addr: 'A1010.2', label: '' },
  { addr: 'A1010.3', label: '' },
  { addr: 'A1010.4', label: '' },
  { addr: 'A1010.5', label: '' },
  { addr: 'A1010.6', label: '' },
  { addr: 'A1010.7', label: '' }
]
export const outputs8 = [
  { addr: 'A1030.0', label: 'RS1' },
  { addr: 'A1030.1', label: 'RS2' },
  { addr: 'A1030.2', label: 'KBA2' },
  { addr: 'A1030.3', label: 'TKKP' },
  { addr: 'A1030.4', label: 'KE1' },
  { addr: 'A1030.5', label: 'TKKE' },
  { addr: 'A1030.6', label: '' },
  { addr: 'A1030.7', label: '' }
]
export const outputs9 = [
  { addr: 'A1050.0', label: 'K1' },
  { addr: 'A1050.1', label: 'K2' },
  { addr: 'A1050.2', label: '' },
  { addr: 'A1050.3', label: '' },
  { addr: 'A1050.4', label: '' },
  { addr: 'A1050.5', label: '' },
  { addr: 'A1050.6', label: '' },
  { addr: 'A1050.7', label: '' }
]
export const outputs10 = [
  { addr: 'A1070.0', label: 'K1' },
  { addr: 'A1070.1', label: 'K2' },
  { addr: 'A1070.2', label: '' },
  { addr: 'A1070.3', label: '' },
  { addr: 'A1070.4', label: '' },
  { addr: 'A1070.5', label: '' },
  { addr: 'A1070.6', label: '' },
  { addr: 'A1070.7', label: '' }
]
export const outputs11 = [
  { addr: 'A1090.0', label: 'RS1' },
  { addr: 'A1090.1', label: 'RS2' },
  { addr: 'A1090.2', label: 'KBA2' },
  { addr: 'A1090.3', label: 'TKKP' },
  { addr: 'A1090.4', label: '' },
  { addr: 'A1090.5', label: '' },
  { addr: 'A1090.6', label: '' },
  { addr: 'A1090.7', label: '' }
]
export const outputs12 = [
  { addr: 'A1110.0', label: 'K1' },
  { addr: 'A1110.1', label: 'K2' },
  { addr: 'A1110.2', label: '' },
  { addr: 'A1110.3', label: '' },
  { addr: 'A1110.4', label: '' },
  { addr: 'A1110.5', label: '' },
  { addr: 'A1110.6', label: '' },
  { addr: 'A1110.7', label: '' }
]
export const outputs13 = [
  { addr: 'A1130.0', label: 'K1' },
  { addr: 'A1130.1', label: 'K2' },
  { addr: 'A1130.2', label: '' },
  { addr: 'A1130.3', label: '' },
  { addr: 'A1130.4', label: '' },
  { addr: 'A1130.5', label: '' },
  { addr: 'A1130.6', label: '' },
  { addr: 'A1130.7', label: '' }
]
export const ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: 'al-v-lck-to', query: {} },
  { id: 22, key: 'al-v-lck-fc', query: {} },
  { id: 23, key: 'al-h-to', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: 'al-flap-to', query: {} },
  { id: 27, key: 'al-flap-fc', query: {} },
  { id: 28, key: 'al-sp-to', query: {} },
  { id: 29, key: 'al-sp-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-pn', query: { name: 'SH1' } },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-th', query: { name: 'ASBK' } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: 'al-th', query: { name: 'AMM' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: 'al-th', query: { name: 'FE' } },
  { id: 58, key: 'al-th', query: { name: 'AH' } },
  { id: 59, key: 'al-th', query: { name: 'AMC' } },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: 'al-th', query: { name: 'FE' } },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-pn', query: { name: 'SH2' } },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE1' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-th', query: { name: 'ASBK' } },
  { id: 116, key: 'al-th', query: { name: 'RTA' } },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: 'al-th', query: { name: 'AMM' } },
  { id: 120, key: '', query: {} },
  { id: 121, key: 'al-th', query: { name: 'FE2' } },
  { id: 122, key: 'al-th', query: { name: 'AH12' } },
  { id: 123, key: 'al-th', query: { name: 'MTC' } },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
