exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'STR' },
  { addr: 'E1.5', label: 'OK' },
  { addr: 'E1.6', label: 'DAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'A' },
  { addr: 'E2.1', label: 'B' },
  { addr: 'E2.2', label: 'C' },
  { addr: 'E2.3', label: 'D' },
  { addr: 'E2.4', label: 'STR' },
  { addr: 'E2.5', label: 'OK' },
  { addr: 'E2.6', label: 'DAT' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: 'A' },
  { addr: 'E3.1', label: 'B' },
  { addr: 'E3.2', label: 'C' },
  { addr: 'E3.3', label: 'D' },
  { addr: 'E3.4', label: 'STR' },
  { addr: 'E3.5', label: 'OK' },
  { addr: 'E3.6', label: 'DAT' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'STR' },
  { addr: 'E4.5', label: 'OK' },
  { addr: 'E4.6', label: 'DAT' },
  { addr: 'E4.7', label: '' },
  { addr: 'E5.0', label: 'PS1' },
  { addr: 'E5.1', label: 'PS2' },
  { addr: 'E5.2', label: 'PS3' },
  { addr: 'E5.3', label: 'PS4' },
  { addr: 'E5.4', label: 'PS5' },
  { addr: 'E5.5', label: 'PS6' },
  { addr: 'E5.6', label: 'FA1' },
  { addr: 'E5.7', label: 'FE12' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'EZA' },
  { addr: 'E101.1', label: 'EOA' },
  { addr: 'E101.2', label: 'FBA' },
  { addr: 'E101.3', label: 'APA' },
  { addr: 'E101.4', label: 'AGF' },
  { addr: 'E101.5', label: 'AKKM' },
  { addr: 'E101.6', label: 'APE' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'IV2' },
  { addr: 'E102.1', label: 'ASBK2' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: 'IV1' },
  { addr: 'E102.4', label: 'FDBK' },
  { addr: 'E102.5', label: 'ASBK' },
  { addr: 'E102.6', label: 'RT12' },
  { addr: 'E102.7', label: 'FSQA' },
  { addr: 'E103.0', label: 'FE1' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: 'EXD' },
  { addr: 'E103.3', label: 'RS12' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: 'AF7' },
  { addr: 'E104.0', label: 'FTS1' },
  { addr: 'E104.1', label: 'FTS2' },
  { addr: 'E104.2', label: '' },
  { addr: 'E104.3', label: '' },
  { addr: 'E104.4', label: '' },
  { addr: 'E104.5', label: '' },
  { addr: 'E104.6', label: '' },
  { addr: 'E104.7', label: '' },
  { addr: 'E105.0', label: '' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: '' },
  { addr: 'E105.3', label: '' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: '' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: 'FTA1-1' },
  { addr: 'E107.4', label: 'FTA2-1' },
  { addr: 'E107.5', label: 'LOOP' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'ECA' },
  { addr: 'E110.1', label: 'ECB' },
  { addr: 'E110.2', label: 'AMC' },
  { addr: 'E110.3', label: 'EOM' },
  { addr: 'E110.4', label: 'EZM' },
  { addr: 'E110.5', label: 'AMM' },
  { addr: 'E110.6', label: 'FRE' },
  { addr: 'E110.7', label: '' },
  { addr: 'E111.0', label: 'EM' },
  { addr: 'E111.1', label: 'EXPV' },
  { addr: 'E111.2', label: 'EFB' },
  { addr: 'E111.3', label: 'K12' },
  { addr: 'E111.4', label: 'TCR' },
  { addr: 'E111.5', label: 'MTC' },
  { addr: 'E111.6', label: 'FTXV' },
  { addr: 'E111.7', label: 'FTXH' },
  { addr: 'E112.0', label: 'RMV' },
  { addr: 'E112.1', label: 'RMH' },
  { addr: 'E112.2', label: 'RES' },
  { addr: 'E112.3', label: 'REH' },
  { addr: 'E112.4', label: 'RCV' },
  { addr: 'E112.5', label: 'REAV' },
  { addr: 'E112.6', label: 'REAH' },
  { addr: 'E112.7', label: 'RCH' }
]
// ...
exports.inputs8 = [
  { addr: 'E400.0', label: 'A' },
  { addr: 'E400.1', label: 'B' },
  { addr: 'E400.2', label: 'C' },
  { addr: 'E400.3', label: 'D' },
  { addr: 'E400.4', label: 'OK' },
  { addr: 'E400.5', label: 'S2' },
  { addr: 'E400.6', label: 'S2' },
  { addr: 'E400.7', label: 'S2' },
  { addr: 'E401.0', label: 'FE1' },
  { addr: 'E401.1', label: 'IV1' },
  { addr: 'E401.2', label: '' },
  { addr: 'E401.3', label: 'K12' },
  { addr: 'E401.4', label: 'FDBK' },
  { addr: 'E401.5', label: 'ASBK' },
  { addr: 'E401.6', label: 'RT12' },
  { addr: 'E401.7', label: 'UC' },
  { addr: 'E402.0', label: '' },
  { addr: 'E402.1', label: '' },
  { addr: 'E402.2', label: '' },
  { addr: 'E402.3', label: '' },
  { addr: 'E402.4', label: '' },
  { addr: 'E402.5', label: '' },
  { addr: 'E402.6', label: '' },
  { addr: 'E402.7', label: '' },
  { addr: 'E403.0', label: '' },
  { addr: 'E403.1', label: '' },
  { addr: 'E403.2', label: '' },
  { addr: 'E403.3', label: '' },
  { addr: 'E403.4', label: '' },
  { addr: 'E403.5', label: '' },
  { addr: 'E403.6', label: '' },
  { addr: 'E403.7', label: '' }
]
exports.inputs9 = [
  { addr: 'E404.0', label: '' },
  { addr: 'E404.1', label: 'ACR' },
  { addr: 'E404.2', label: 'FTCR' },
  { addr: 'E404.3', label: 'FE3' },
  { addr: 'E404.4', label: '' },
  { addr: 'E404.5', label: '' },
  { addr: 'E404.6', label: 'K12' },
  { addr: 'E404.7', label: '' },
  { addr: 'E405.0', label: '' },
  { addr: 'E405.1', label: '' },
  { addr: 'E405.2', label: 'AMM' },
  { addr: 'E405.3', label: 'EOM' },
  { addr: 'E405.4', label: 'EZM' },
  { addr: 'E405.5', label: 'EMC' },
  { addr: 'E405.6', label: '' },
  { addr: 'E405.7', label: '' }
]
exports.inputs10 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'FE4' },
  { addr: 'E411.1', label: '' },
  { addr: 'E411.2', label: '' },
  { addr: 'E411.3', label: 'EM' },
  { addr: 'E411.4', label: '' },
  { addr: 'E411.5', label: '' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: 'IV2' },
  { addr: 'E413.1', label: '' },
  { addr: 'E413.2', label: '' },
  { addr: 'E413.3', label: 'RS12' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTAC' },
  { addr: 'E413.7', label: 'UC' },
  { addr: 'E414.0', label: 'AF7' },
  { addr: 'E414.1', label: '' },
  { addr: 'E414.2', label: 'FTM1' },
  { addr: 'E414.3', label: 'FTM2' },
  { addr: 'E414.4', label: 'FTM3' },
  { addr: 'E414.5', label: 'FTCR' },
  { addr: 'E414.6', label: 'AH' },
  { addr: 'E414.7', label: 'MTC' }
]
// ...
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: 'LSK' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: 'LS1' },
  { addr: 'A1.6', label: 'LS2' },
  { addr: 'A1.7', label: 'LS3' },
  { addr: 'A2.0', label: 'LK' },
  { addr: 'A2.1', label: 'LE' },
  { addr: 'A2.2', label: 'LB' },
  { addr: 'A2.3', label: 'RDY' },
  { addr: 'A2.4', label: 'RST' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: 'RBE1' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: 'RBE2' },
  { addr: 'A4.0', label: 'LK' },
  { addr: 'A4.1', label: 'LE' },
  { addr: 'A4.2', label: 'LB' },
  { addr: 'A4.3', label: 'RDY' },
  { addr: 'A4.4', label: 'RST' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: 'RBE3' },
  { addr: 'A5.0', label: 'LS4' },
  { addr: 'A5.1', label: 'LS5' },
  { addr: 'A5.2', label: 'LS6' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'T2' },
  { addr: 'A100.1', label: 'KBA1' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KBA2' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RFA' },
  { addr: 'A102.0', label: 'SZA' },
  { addr: 'A102.1', label: 'SOA' },
  { addr: 'A102.2', label: 'KQA' },
  { addr: 'A102.3', label: 'SPA' },
  { addr: 'A102.4', label: 'SBK2' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: 'TD' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'A' },
  { addr: 'A103.1', label: 'B' },
  { addr: 'A103.2', label: 'C' },
  { addr: 'A103.3', label: 'D' },
  { addr: 'A103.4', label: 'AD1' },
  { addr: 'A103.5', label: 'AD2' },
  { addr: 'A103.6', label: 'AD3' },
  { addr: 'A103.7', label: 'STR' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: '' },
  { addr: 'A110.1', label: '' },
  { addr: 'A110.2', label: 'TRA' },
  { addr: 'A110.3', label: 'TRB' },
  { addr: 'A110.4', label: 'KCS' },
  { addr: 'A110.5', label: 'KCV' },
  { addr: 'A110.6', label: 'KCH' },
  { addr: 'A110.7', label: 'TCR' },
  { addr: 'A111.0', label: 'SMA' },
  { addr: 'A111.1', label: 'SMB' },
  { addr: 'A111.2', label: 'SCA' },
  { addr: 'A111.3', label: 'SCB' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
// ...
exports.outputs8 = [
  { addr: 'A400.0', label: 'SBK2' },
  { addr: 'A400.1', label: 'KBA' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: '' },
  { addr: 'A400.5', label: 'RFE1' },
  { addr: 'A400.6', label: 'LA' },
  { addr: 'A400.7', label: 'LC' },
  { addr: 'A401.0', label: 'A' },
  { addr: 'A401.1', label: 'B' },
  { addr: 'A401.2', label: 'C' },
  { addr: 'A401.3', label: 'D' },
  { addr: 'A401.4', label: 'AD1' },
  { addr: 'A401.5', label: 'AD2' },
  { addr: 'A401.6', label: 'AD3' },
  { addr: 'A401.7', label: 'STR' }
]
exports.outputs9 = [
  { addr: 'A404.0', label: 'SMA' },
  { addr: 'A404.1', label: 'SMB' },
  { addr: 'A404.2', label: 'FTCR' },
  { addr: 'A404.3', label: 'KSH' },
  { addr: 'A404.4', label: '' },
  { addr: 'A404.5', label: '' },
  { addr: 'A404.6', label: 'LA' },
  { addr: 'A404.7', label: '' }
]
exports.outputs10 = [
  { addr: 'A410.0', label: 'A' },
  { addr: 'A410.1', label: 'B' },
  { addr: 'A410.2', label: 'C' },
  { addr: 'A410.3', label: 'D' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'ADR' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'T101' },
  { addr: 'A411.1', label: 'T2' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'KCS' },
  { addr: 'A411.5', label: 'KCV' },
  { addr: 'A411.6', label: 'KCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'KBA2' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: 'T102' },
  { addr: 'A412.5', label: 'T10F' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' }
]
// Failsafe I/O
exports.inputs17 = [
  { addr: 'E10.0', label: 'UG_BBL' },
  { addr: 'E10.1', label: 'FDBK' },
  { addr: 'E10.2', label: 'PS' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: 'SF1' },
  { addr: 'E10.5', label: 'BBL1' },
  { addr: 'E10.6', label: 'SF2' },
  { addr: 'E10.7', label: 'BBL2' },
  { addr: 'E11.0', label: 'SF3' },
  { addr: 'E11.1', label: 'BBL3' },
  { addr: 'E11.2', label: 'SF4' },
  { addr: 'E11.3', label: 'BBL4' },
  { addr: 'E11.4', label: 'SF5' },
  { addr: 'E11.5', label: 'BBL5' },
  { addr: 'E11.6', label: 'SF6' },
  { addr: 'E11.7', label: 'BBL6' }
]
exports.inputs18 = [
  { addr: 'E20.0', label: 'WAL' },
  { addr: 'E20.1', label: 'FAL' },
  { addr: 'E20.2', label: 'EZD' },
  { addr: 'E20.3', label: '' },
  { addr: 'E20.4', label: '' },
  { addr: 'E20.5', label: '' },
  { addr: 'E20.6', label: '' },
  { addr: 'E20.7', label: '' },
  { addr: 'E21.0', label: 'BBEL1' },
  { addr: 'E21.1', label: 'BBEL2' },
  { addr: 'E21.2', label: 'BBEL3' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: '' },
  { addr: 'E21.5', label: '' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: '' }
]
// LS1
exports.inputs19 = [
  { addr: 'E1000.0', label: 'UG_BBL' },
  { addr: 'E1000.1', label: 'FDBK' },
  { addr: 'E1000.2', label: 'SA' },
  { addr: 'E1000.3', label: 'US' },
  { addr: 'E1000.4', label: 'BBV1' },
  { addr: 'E1000.5', label: 'BBV2' },
  { addr: 'E1000.6', label: 'BPS' },
  { addr: 'E1000.7', label: 'EXZA' },
  { addr: 'E1001.0', label: 'EXZE' },
  { addr: 'E1001.1', label: 'FKXPE' },
  { addr: 'E1001.2', label: 'FKXPA' },
  { addr: 'E1001.3', label: 'BBE1' },
  { addr: 'E1001.4', label: 'BBE2' },
  { addr: 'E1001.5', label: '' },
  { addr: 'E1001.6', label: '' },
  { addr: 'E1001.7', label: '' }
]
// KKM1
exports.inputs20 = [
  { addr: 'E1020.0', label: 'FDBK' },
  { addr: 'E1020.1', label: 'ETAB' },
  { addr: 'E1020.2', label: 'BBM' },
  { addr: 'E1020.3', label: 'KEXPV' },
  { addr: 'E1020.4', label: '' },
  { addr: 'E1020.5', label: '' },
  { addr: 'E1020.6', label: '' },
  { addr: 'E1020.7', label: '' }
]
// LS4
exports.inputs21 = [
  { addr: 'E4000.0', label: 'UG_BBL' },
  { addr: 'E4000.1', label: 'FDBK' },
  { addr: 'E4000.2', label: 'SA' },
  { addr: 'E4000.3', label: 'US' },
  { addr: 'E4000.4', label: 'BBV1' },
  { addr: 'E4000.5', label: 'BBV2' },
  { addr: 'E4000.6', label: 'BPS' },
  { addr: 'E4000.7', label: '' },
  { addr: 'E4001.0', label: '' },
  { addr: 'E4001.1', label: '' },
  { addr: 'E4001.2', label: '' },
  { addr: 'E4001.3', label: '' },
  { addr: 'E4001.4', label: '' },
  { addr: 'E4001.5', label: '' },
  { addr: 'E4001.6', label: 'FTS1' },
  { addr: 'E4001.7', label: 'FTS2' }
]
// KKP4
exports.inputs22 = [
  { addr: 'E4020.0', label: 'BBP' },
  { addr: 'E4020.1', label: 'FDBK' },
  { addr: 'E4020.2', label: 'ETAB' },
  { addr: 'E4020.3', label: '' },
  { addr: 'E4020.4', label: '' },
  { addr: 'E4020.5', label: '' },
  { addr: 'E4020.6', label: '' },
  { addr: 'E4020.7', label: '' }
]
// SH4
exports.inputs23 = [
  { addr: 'E4040.0', label: 'BBH' },
  { addr: 'E4040.1', label: 'FDBK' },
  { addr: 'E4040.2', label: 'SA' },
  { addr: 'E4040.3', label: 'US' },
  { addr: 'E4040.4', label: 'BBV1' },
  { addr: 'E4040.5', label: 'BBV2' },
  { addr: 'E4040.6', label: 'BPS' },
  { addr: 'E4040.7', label: 'ETLR' }
]
// CPU
exports.outputs17 = [
  { addr: 'A30.0', label: 'K1' },
  { addr: 'A30.1', label: 'K2' },
  { addr: 'A30.2', label: '' },
  { addr: 'A30.3', label: '' },
  { addr: 'A30.4', label: '' },
  { addr: 'A30.5', label: '' },
  { addr: 'A30.6', label: '' },
  { addr: 'A30.7', label: '' }
]
// LS1
exports.outputs18 = [
  { addr: 'A1010.0', label: 'K1' },
  { addr: 'A1010.1', label: 'K2' },
  { addr: 'A1010.2', label: 'KBA1' },
  { addr: 'A1010.3', label: 'KBA2' },
  { addr: 'A1010.4', label: 'TKKM' },
  { addr: 'A1010.5', label: 'KXPE' },
  { addr: 'A1010.6', label: 'KXPA' },
  { addr: 'A1010.7', label: 'SBK1' }
]
// KKM1
exports.outputs19 = [
  { addr: 'A1030.0', label: 'K1' },
  { addr: 'A1030.1', label: 'K2' },
  { addr: 'A1030.2', label: '' },
  { addr: 'A1030.3', label: '' },
  { addr: 'A1030.4', label: '' },
  { addr: 'A1030.5', label: '' },
  { addr: 'A1030.6', label: '' },
  { addr: 'A1030.7', label: '' }
]
// LS4
exports.outputs20 = [
  { addr: 'A4010.0', label: 'UG_BBL' },
  { addr: 'A4010.1', label: 'FDBK' },
  { addr: 'A4010.2', label: 'SA' },
  { addr: 'A4010.3', label: 'US' },
  { addr: 'A4010.4', label: 'BBV1' },
  { addr: 'A4010.5', label: 'BBV2' },
  { addr: 'A4010.6', label: 'BPS' },
  { addr: 'A4010.7', label: 'ETLR' }
]
// KKP4
exports.outputs21 = [
  { addr: 'A4030.0', label: 'K1' },
  { addr: 'A4030.1', label: 'K2' },
  { addr: 'A4030.2', label: '' },
  { addr: 'A4030.3', label: '' },
  { addr: 'A4030.4', label: '' },
  { addr: 'A4030.5', label: '' },
  { addr: 'A4030.6', label: '' },
  { addr: 'A4030.7', label: '' }
]
// SH4
exports.outputs22 = [
  { addr: 'A4050.0', label: 'K1' },
  { addr: 'A4050.1', label: 'K2' },
  { addr: 'A4050.2', label: '' },
  { addr: 'A4050.3', label: '' },
  { addr: 'A4050.4', label: '' },
  { addr: 'A4050.5', label: '' },
  { addr: 'A4050.6', label: '' },
  { addr: 'A4050.7', label: '' }
]

exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-flap-to', query: {} },
  { id: 25, key: 'al-flap-fc', query: {} },
  { id: 26, key: 'al-spe-to', query: {} },
  { id: 27, key: 'al-spe-fc', query: {} },
  { id: 28, key: 'al-spa-to', query: {} },
  { id: 29, key: 'al-spa-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-pn', query: { name: 'LS' } },
  { id: 34, key: 'al-pn', query: { name: 'IV1' } },
  { id: 35, key: 'al-pn', query: { name: 'IV2' } },
  { id: 36, key: 'al-pn', query: { name: 'LV' } },
  { id: 37, key: 'al-pn', query: { name: 'EN' } },
  { id: 38, key: 'al-pn', query: { name: 'KKM' } },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-fs', query: { name: 'BBL' } },
  { id: 42, key: 'al-fs', query: { name: 'BBEL' } },
  { id: 43, key: 'al-fs', query: { name: 'UG/BBL' } },
  { id: 44, key: 'al-fs', query: { name: 'BBE1' } },
  { id: 45, key: 'al-fs', query: { name: 'BBE2' } },
  { id: 46, key: 'al-fs', query: { name: 'ETA/B' } },
  { id: 47, key: 'al-fs', query: { name: 'BBM' } },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'APA' } },
  { id: 50, key: 'al-th', query: { name: 'AGF' } },
  { id: 51, key: 'al-th', query: { name: 'AKKM' } },
  { id: 52, key: 'al-th', query: { name: 'APE' } },
  { id: 53, key: 'al-iv', query: { nr: 2 } },
  { id: 54, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 55, key: 'al-iv', query: { nr: 1 } },
  { id: 56, key: 'al-th', query: { name: 'ASBK' } },
  { id: 57, key: 'al-th', query: { name: 'RTA' } },
  { id: 58, key: 'al-th', query: { name: 'FE1' } },
  { id: 59, key: 'al-th', query: { name: 'AF7' } },
  { id: 60, key: 'al-th', query: { name: 'AMC' } },
  { id: 61, key: 'al-th', query: { name: 'AMM' } },
  { id: 62, key: 'al-th', query: { name: 'MTC' } },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-pn', query: { name: 'LS' } },
  { id: 98, key: 'al-pn', query: { name: 'LV1' } },
  { id: 99, key: 'al-pn', query: { name: 'LV2' } },
  { id: 100, key: 'al-pn', query: { name: 'KKP' } },
  { id: 101, key: 'al-pn', query: { name: 'SH' } },
  { id: 102, key: 'al-pn', query: { name: 'LH1' } },
  { id: 103, key: 'al-pn', query: { name: 'LH2' } },
  { id: 104, key: '', query: {} },
  { id: 105, key: 'al-fs', query: { name: 'BBL' } },
  { id: 106, key: 'al-fs', query: { name: 'UG/BBL' } },
  { id: 107, key: 'al-fs', query: { name: 'BBP' } },
  { id: 108, key: 'al-fs', query: { name: 'ETA/B' } },
  { id: 109, key: 'al-fs', query: { name: 'BBH' } },
  { id: 110, key: 'al-fs', query: { name: 'ETL/R' } },
  { id: 111, key: 'al-fs', query: { name: 'EZD' } },
  { id: 112, key: 'al-fs', query: { name: 'FAL/WAL' } },
  { id: 113, key: 'al-th', query: { name: 'FE1' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-th', query: { name: 'ASBK' } },
  { id: 116, key: 'al-th', query: { name: 'RTA' } },
  { id: 117, key: 'al-th', query: { name: 'ACR' } },
  { id: 118, key: 'al-th', query: { name: 'FE3' } },
  { id: 119, key: 'al-th', query: { name: 'AMM' } },
  { id: 120, key: 'al-th', query: { name: 'FE4' } },
  { id: 121, key: 'al-iv', query: { nr: 2 } },
  { id: 122, key: 'al-th', query: { name: 'AF7' } },
  { id: 123, key: 'al-th', query: { name: 'AH' } },
  { id: 124, key: 'al-th', query: { name: 'MTC' } },
  { id: 125, key: 'al-th', query: { name: 'LS shutdown' } },
  { id: 126, key: 'al-th', query: { name: 'KKP shutdown' } },
  { id: 127, key: 'al-th', query: { name: 'SH shutdown' } },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EVT1' },
  { id: 2, key: 'EVT2' },
  { id: 3, key: 'EVT3' },
  { id: 4, key: 'IVT4' },
  { id: 5, key: 'IVT5' },
  { id: 6, key: 'IVT6' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
