// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'UC' },
  { addr: 'E1.1', label: 'FE' },
  { addr: 'E1.2', label: 'IV1' },
  { addr: 'E1.3', label: 'RSI' },
  { addr: 'E1.4', label: 'ASBK' },
  { addr: 'E1.5', label: 'RTA' },
  { addr: 'E1.6', label: 'AMC' },
  { addr: 'E1.7', label: 'APBE' },
  { addr: 'E2.0', label: 'APBA' },
  { addr: 'E2.1', label: 'FSBK' },
  { addr: 'E2.2', label: 'DB32' },
  { addr: 'E2.3', label: 'DBHZ' },
  { addr: 'E2.4', label: 'IV3' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: 'ECA' },
  { addr: 'E2.7', label: 'ECB' },
  { addr: 'E3.0', label: 'EZE' },
  { addr: 'E3.1', label: 'EOE' },
  { addr: 'E3.2', label: 'EBZE' },
  { addr: 'E3.3', label: 'EBOE' },
  { addr: 'E3.4', label: 'EZA' },
  { addr: 'E3.5', label: 'EOA' },
  { addr: 'E3.6', label: 'EBZA' },
  { addr: 'E3.7', label: 'EBOA' },
  { addr: 'E4.0', label: 'FBE' },
  { addr: 'E4.1', label: 'FBBE' },
  { addr: 'E4.2', label: 'FBA' },
  { addr: 'E4.3', label: 'FBBA' },
  { addr: 'E4.4', label: 'FLP2' },
  { addr: 'E4.5', label: 'FPE' },
  { addr: 'E4.6', label: 'FPA' },
  { addr: 'E4.7', label: 'FDR1' },
  { addr: 'E5.0', label: 'FDL1' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: 'FTA1' },
  { addr: 'E5.4', label: 'FTA2' },
  { addr: 'E5.5', label: 'FTA2-2' },
  { addr: 'E5.6', label: 'FLP1' },
  { addr: 'E5.7', label: 'FLA' },
  { addr: 'E6.0', label: 'EXDE' },
  { addr: 'E6.1', label: 'EXHE' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: 'FTC' },
  { addr: 'E6.4', label: 'ATD' },
  { addr: 'E6.5', label: 'ASBKD' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: 'SA' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: 'EPZV' },
  { addr: 'E7.4', label: 'EPZH' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: '' },
  { addr: 'E8.1', label: '' },
  { addr: 'E8.2', label: '' },
  { addr: 'E8.3', label: '' },
  { addr: 'E8.4', label: '' },
  { addr: 'E8.5', label: '' },
  { addr: 'E8.6', label: '' },
  { addr: 'E8.7', label: '' },
  { addr: 'E9.0', label: '' },
  { addr: 'E9.1', label: '' },
  { addr: 'E9.2', label: '' },
  { addr: 'E9.3', label: '' },
  { addr: 'E9.4', label: '' },
  { addr: 'E9.5', label: '' },
  { addr: 'E9.6', label: '' },
  { addr: 'E9.7', label: '' },
  { addr: 'E10.0', label: '' },
  { addr: 'E10.1', label: '' },
  { addr: 'E10.2', label: '' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: '' },
  { addr: 'E10.5', label: '' },
  { addr: 'E10.6', label: '' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' }
]
export const inputs2 = [
  { addr: 'E12.0', label: 'ASH' },
  { addr: 'E12.1', label: 'AMM' },
  { addr: 'E12.2', label: 'FE2' },
  { addr: 'E12.3', label: 'FTCR' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: 'EOM' },
  { addr: 'E13.1', label: 'EZM' },
  { addr: 'E13.2', label: 'EMC' },
  { addr: 'E13.3', label: 'EXPV' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' }
]
export const inputs3 = [
  { addr: 'E14.0', label: 'A' },
  { addr: 'E14.1', label: 'B' },
  { addr: 'E14.2', label: 'C' },
  { addr: 'E14.3', label: 'D' },
  { addr: 'E14.4', label: 'OK' },
  { addr: 'E14.5', label: 'S2' },
  { addr: 'E14.6', label: 'S2' },
  { addr: 'E14.7', label: 'S2' },
  { addr: 'E15.0', label: 'UC' },
  { addr: 'E15.1', label: 'FE' },
  { addr: 'E15.2', label: 'IV2' },
  { addr: 'E15.3', label: 'RSI' },
  { addr: 'E15.4', label: 'AH' },
  { addr: 'E15.5', label: 'MTC' },
  { addr: 'E15.6', label: 'ATF' },
  { addr: 'E15.7', label: 'SRL' },
  { addr: 'E16.0', label: 'RMV' },
  { addr: 'E16.1', label: 'RMH' },
  { addr: 'E16.2', label: 'RES' },
  { addr: 'E16.3', label: 'REH' },
  { addr: 'E16.4', label: 'RCV' },
  { addr: 'E16.5', label: 'REAV' },
  { addr: 'E16.6', label: 'REAH' },
  { addr: 'E16.7', label: 'RCH' },
  { addr: 'E17.0', label: 'DB32' },
  { addr: 'E17.1', label: 'DBHZ' },
  { addr: 'E17.2', label: 'EM' },
  { addr: 'E17.3', label: 'FTXV' },
  { addr: 'E17.4', label: 'FTXH' },
  { addr: 'E17.5', label: 'FTCR' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' },
  { addr: 'E18.0', label: '' },
  { addr: 'E18.1', label: '' },
  { addr: 'E18.2', label: '' },
  { addr: 'E18.3', label: '' },
  { addr: 'E18.4', label: '' },
  { addr: 'E18.5', label: '' },
  { addr: 'E18.6', label: '' },
  { addr: 'E18.7', label: '' },
  { addr: 'E19.0', label: '' },
  { addr: 'E19.1', label: '' },
  { addr: 'E19.2', label: '' },
  { addr: 'E19.3', label: '' },
  { addr: 'E19.4', label: '' },
  { addr: 'E19.5', label: '' },
  { addr: 'E19.6', label: '' },
  { addr: 'E19.7', label: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'KBA1' },
  { addr: 'A1.1', label: 'LA' },
  { addr: 'A1.2', label: 'LC' },
  { addr: 'A1.3', label: 'SCA' },
  { addr: 'A1.4', label: 'SCB' },
  { addr: 'A1.5', label: 'SBK1' },
  { addr: 'A1.6', label: 'SBK2' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: 'L1' },
  { addr: 'A2.1', label: 'L2' },
  { addr: 'A2.2', label: 'L3' },
  { addr: 'A2.3', label: 'L4' },
  { addr: 'A2.4', label: 'L5' },
  { addr: 'A2.5', label: 'RFE' },
  { addr: 'A2.6', label: 'SPE' },
  { addr: 'A2.7', label: 'SPA' },
  { addr: 'A3.0', label: 'SOE' },
  { addr: 'A3.1', label: 'SZE' },
  { addr: 'A3.2', label: 'SBOE' },
  { addr: 'A3.3', label: 'SBZE' },
  { addr: 'A3.4', label: 'SOA' },
  { addr: 'A3.5', label: 'SZA' },
  { addr: 'A3.6', label: 'SBOA' },
  { addr: 'A3.7', label: 'SBZA' },
  { addr: 'A4.0', label: 'KBA3' },
  { addr: 'A4.1', label: '' },
  { addr: 'A4.2', label: 'SBK3' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: '' },
  { addr: 'A4.5', label: 'RFID' },
  { addr: 'A4.6', label: 'RFA' },
  { addr: 'A4.7', label: '' },
  { addr: 'A5.0', label: '' },
  { addr: 'A5.1', label: '' },
  { addr: 'A5.2', label: '' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' },
  { addr: 'A6.0', label: '' },
  { addr: 'A6.1', label: '' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: '' },
  { addr: 'A7.0', label: '' },
  { addr: 'A7.1', label: '' },
  { addr: 'A7.2', label: '' },
  { addr: 'A7.3', label: '' },
  { addr: 'A7.4', label: '' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: '' },
  { addr: 'A7.7', label: '' }
]
export const outputs2 = [
  { addr: 'A12.0', label: 'SMA' },
  { addr: 'A12.1', label: 'SMB' },
  { addr: 'A12.2', label: 'LA' },
  { addr: 'A12.3', label: 'TCR' },
  { addr: 'A12.4', label: '' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: '' },
  { addr: 'A12.7', label: '' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' }
]
export const outputs3 = [
  { addr: 'A14.0', label: 'DYA' },
  { addr: 'A14.1', label: 'DYB' },
  { addr: 'A14.2', label: 'DYC' },
  { addr: 'A14.3', label: 'DYD' },
  { addr: 'A14.4', label: 'AD1' },
  { addr: 'A14.5', label: 'AD2' },
  { addr: 'A14.6', label: 'AD3' },
  { addr: 'A14.7', label: 'STR' },
  { addr: 'A15.0', label: 'LC' },
  { addr: 'A15.1', label: 'LA' },
  { addr: 'A15.2', label: 'KBA2' },
  { addr: 'A15.3', label: 'T101' },
  { addr: 'A15.4', label: 'T102' },
  { addr: 'A15.5', label: 'T2' },
  { addr: 'A15.6', label: 'TRA' },
  { addr: 'A15.7', label: 'TRB' },
  { addr: 'A16.0', label: 'T10F' },
  { addr: 'A16.1', label: 'KCS' },
  { addr: 'A16.2', label: 'KCV' },
  { addr: 'A16.3', label: 'KCH' },
  { addr: 'A16.4', label: 'TCR' },
  { addr: 'A16.5', label: '' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' }
]
export const ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-sp-to', query: {} },
  { id: 18, key: 'al-sp-to', query: {} },
  { id: 19, key: 'al-sp-fc', query: {} },
  { id: 20, key: 'al-spb-to', query: {} },
  { id: 21, key: 'al-spb-to', query: {} },
  { id: 22, key: 'al-spb-fc', query: {} },
  { id: 23, key: 'al-flap-to', query: {} },
  { id: 24, key: 'al-flap-fc', query: {} },
  { id: 25, key: 'al-r-to', query: {} },
  { id: 26, key: 'al-enr', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-th', query: { name: 'AMC' } },
  { id: 51, key: 'al-th', query: { name: 'APBE' } },
  { id: 52, key: 'al-iv', query: { nr: 3 } },
  { id: 53, key: 'al-th', query: { name: 'ATD' } },
  { id: 54, key: 'al-th', query: { name: 'ASBKD' } },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-pn', query: { name: 'KKP' } },
  { id: 98, key: 'al-pn', query: { name: 'SH' } },
  { id: 99, key: 'al-pn', query: { name: 'IV1' } },
  { id: 100, key: 'al-pn', query: { name: 'IV2' } },
  { id: 101, key: 'al-pn', query: { name: 'LV1' } },
  { id: 102, key: 'al-pn', query: { name: 'LV2' } },
  { id: 103, key: 'al-pn', query: { name: 'LH1' } },
  { id: 104, key: 'al-pn', query: { name: 'LH2' } },
  { id: 105, key: 'al-pn', query: { name: 'ENR' } },
  { id: 106, key: 'al-pn', query: { name: 'IV3' } },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'FE1' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-th', query: { name: 'ASBK' } },
  { id: 116, key: 'al-th', query: { name: 'RTA' } },
  { id: 117, key: 'al-th', query: { name: 'ASH' } },
  { id: 118, key: 'al-th', query: { name: 'AMM' } },
  { id: 119, key: 'al-th', query: { name: 'FE2' } },
  { id: 120, key: 'al-th', query: { name: 'FE3' } },
  { id: 121, key: 'al-iv', query: { nr: 2 } },
  { id: 122, key: 'al-th', query: { name: 'AH' } },
  { id: 123, key: 'al-th', query: { name: 'MTC' } },
  { id: 124, key: 'al-th', query: { name: 'ATF' } },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'E' },
  { id: 2, key: 'U' },
  { id: 3, key: 'EL' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
