exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: 'FE12' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'STR' },
  { addr: 'E1.5', label: 'OK' },
  { addr: 'E1.6', label: 'DAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'AF1' },
  { addr: 'E2.1', label: 'AF2' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: 'RSI' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'A' },
  { addr: 'E101.1', label: 'B' },
  { addr: 'E101.2', label: 'C' },
  { addr: 'E101.3', label: 'D' },
  { addr: 'E101.4', label: 'STR' },
  { addr: 'E101.5', label: 'OK' },
  { addr: 'E101.6', label: 'DAT' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'HEN', info: 'Hoisting Motors' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: 'EZP', info: 'Pedestrian door closed' },
  { addr: 'E102.5', label: 'FDR2' },
  { addr: 'E102.6', label: 'FDL2' },
  { addr: 'E102.7', label: 'APE' },
  { addr: 'E103.0', label: '' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: 'RSI' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'KXPE' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: 'KBA' },
  { addr: 'E104.1', label: '' },
  { addr: 'E104.2', label: 'SA' },
  { addr: 'E104.3', label: 'IV1' },
  { addr: 'E104.4', label: 'SBK1' },
  { addr: 'E104.5', label: 'ASBK' },
  { addr: 'E104.6', label: 'RT12' },
  { addr: 'E104.7', label: 'SQA' },
  { addr: 'E105.0', label: 'FE1' },
  { addr: 'E105.1', label: 'EXHM', info: 'Half-moon position check' },
  { addr: 'E105.2', label: 'AF9' },
  { addr: 'E105.3', label: 'ASH' },
  { addr: 'E105.4', label: 'AHIV' },
  { addr: 'E105.5', label: 'S1' },
  { addr: 'E105.6', label: 'S1' },
  { addr: 'E105.7', label: 'S1' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FTA3' },
  { addr: 'E107.1', label: 'FLP1' },
  { addr: 'E107.2', label: 'FTA4' },
  { addr: 'E107.3', label: 'FLP2' },
  { addr: 'E107.4', label: 'FLA' },
  { addr: 'E107.5', label: 'FLP3' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'RMV' },
  { addr: 'E110.1', label: 'RMH' },
  { addr: 'E110.2', label: 'RES' },
  { addr: 'E110.3', label: 'REH' },
  { addr: 'E110.4', label: 'RCV' },
  { addr: 'E110.5', label: 'REAV' },
  { addr: 'E110.6', label: 'REAH' },
  { addr: 'E110.7', label: 'RCH' },
  { addr: 'E111.0', label: 'EOM1' },
  { addr: 'E111.1', label: 'EZM1' },
  { addr: 'E111.2', label: 'AMM1' },
  { addr: 'E111.3', label: 'EOM2' },
  { addr: 'E111.4', label: 'EZM2' },
  { addr: 'E111.5', label: 'AMM2' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: 'EXD' },
  { addr: 'E112.0', label: 'AD' },
  { addr: 'E112.1', label: 'EOMD' },
  { addr: 'E112.2', label: 'EZMD' },
  { addr: 'E112.3', label: 'AMD' },
  { addr: 'E112.4', label: '' },
  { addr: 'E112.5', label: 'AKKS' },
  { addr: 'E112.6', label: 'ACR1' },
  { addr: 'E112.7', label: 'TCR1' },
  { addr: 'E113.0', label: 'FE1' },
  { addr: 'E113.1', label: 'KEXPV' },
  { addr: 'E113.2', label: 'EXPV' },
  { addr: 'E113.3', label: 'MNR' },
  { addr: 'E113.4', label: 'MNL' },
  { addr: 'E113.5', label: 'FTAC' },
  { addr: 'E113.6', label: 'EMC' },
  { addr: 'E113.7', label: '' },
  { addr: 'E114.0', label: 'FTXV' },
  { addr: 'E114.1', label: 'FTXH' },
  { addr: 'E114.2', label: 'FRE' },
  { addr: 'E114.3', label: 'ECA' },
  { addr: 'E114.4', label: 'ECB' },
  { addr: 'E114.5', label: 'EM' },
  { addr: 'E114.6', label: 'AMC' },
  { addr: 'E114.7', label: 'MTC' }
]
exports.inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'OK' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: 'S2' },
  { addr: 'E201.0', label: 'A' },
  { addr: 'E201.1', label: 'B' },
  { addr: 'E201.2', label: 'C' },
  { addr: 'E201.3', label: 'D' },
  { addr: 'E201.4', label: 'STR' },
  { addr: 'E201.5', label: 'OK' },
  { addr: 'E201.6', label: 'DAT' },
  { addr: 'E201.7', label: 'UC' },
  { addr: 'E202.0', label: 'HEN', info: 'Hoisting Motors' },
  { addr: 'E202.1', label: '' },
  { addr: 'E202.2', label: '' },
  { addr: 'E202.3', label: '' },
  { addr: 'E202.4', label: 'EZP', info: 'Pedestrian door closed' },
  { addr: 'E202.5', label: 'FDR2' },
  { addr: 'E202.6', label: 'FDL2' },
  { addr: 'E202.7', label: 'APE' },
  { addr: 'E203.0', label: '' },
  { addr: 'E203.1', label: '' },
  { addr: 'E203.2', label: '' },
  { addr: 'E203.3', label: 'RSI' },
  { addr: 'E203.4', label: 'DB32' },
  { addr: 'E203.5', label: 'DBHZ' },
  { addr: 'E203.6', label: 'KXPE' },
  { addr: 'E203.7', label: '' },
  { addr: 'E204.0', label: 'KBA' },
  { addr: 'E204.1', label: '' },
  { addr: 'E204.2', label: 'SA' },
  { addr: 'E204.3', label: 'IV1' },
  { addr: 'E204.4', label: 'SBK1' },
  { addr: 'E204.5', label: 'ASBK' },
  { addr: 'E204.6', label: 'RT12' },
  { addr: 'E204.7', label: 'SQA' },
  { addr: 'E205.0', label: 'FE1' },
  { addr: 'E205.1', label: 'EXHM', info: 'Half-moon position check' },
  { addr: 'E205.2', label: 'AF9' },
  { addr: 'E205.3', label: 'ASH' },
  { addr: 'E205.4', label: 'AHIV' },
  { addr: 'E205.5', label: 'S1' },
  { addr: 'E205.6', label: 'S1' },
  { addr: 'E205.7', label: 'S1' },
  { addr: 'E206.0', label: 'EZE' },
  { addr: 'E206.1', label: 'EOE' },
  { addr: 'E206.2', label: 'FBE' },
  { addr: 'E206.3', label: 'FPE' },
  { addr: 'E206.4', label: 'FDR1' },
  { addr: 'E206.5', label: 'FDL1' },
  { addr: 'E206.6', label: 'FTA1' },
  { addr: 'E206.7', label: 'FTA2' },
  { addr: 'E207.0', label: 'FTA3' },
  { addr: 'E207.1', label: 'FLP1' },
  { addr: 'E207.2', label: 'FTA4' },
  { addr: 'E207.3', label: 'FLP2' },
  { addr: 'E207.4', label: 'FLA' },
  { addr: 'E207.5', label: 'FLP3' },
  { addr: 'E207.6', label: 'RX1' },
  { addr: 'E207.7', label: 'RX2' }
]
exports.inputs5 = [
  { addr: 'E210.0', label: 'RMV' },
  { addr: 'E210.1', label: 'RMH' },
  { addr: 'E210.2', label: 'RES' },
  { addr: 'E210.3', label: 'REH' },
  { addr: 'E210.4', label: 'RCV' },
  { addr: 'E210.5', label: 'REAV' },
  { addr: 'E210.6', label: 'REAH' },
  { addr: 'E210.7', label: 'RCH' },
  { addr: 'E211.0', label: 'EOM1' },
  { addr: 'E211.1', label: 'EZM1' },
  { addr: 'E211.2', label: 'AMM1' },
  { addr: 'E211.3', label: 'EOM2' },
  { addr: 'E211.4', label: 'EZM2' },
  { addr: 'E211.5', label: 'AMM2' },
  { addr: 'E211.6', label: '' },
  { addr: 'E211.7', label: 'EXD' },
  { addr: 'E212.0', label: 'AD' },
  { addr: 'E212.1', label: 'EOMD' },
  { addr: 'E212.2', label: 'EZMD' },
  { addr: 'E212.3', label: 'AMD' },
  { addr: 'E212.4', label: '' },
  { addr: 'E212.5', label: 'AKKS' },
  { addr: 'E212.6', label: 'ACR1' },
  { addr: 'E212.7', label: 'TCR1' },
  { addr: 'E213.0', label: 'FE1' },
  { addr: 'E213.1', label: 'KEXPV' },
  { addr: 'E213.2', label: 'EXPV' },
  { addr: 'E213.3', label: 'MNR' },
  { addr: 'E213.4', label: 'MNL' },
  { addr: 'E213.5', label: 'FTAC' },
  { addr: 'E213.6', label: 'EMC' },
  { addr: 'E213.7', label: '' },
  { addr: 'E214.0', label: 'FTXV' },
  { addr: 'E214.1', label: 'FTXH' },
  { addr: 'E214.2', label: 'FRE' },
  { addr: 'E214.3', label: 'ECA' },
  { addr: 'E214.4', label: 'ECB' },
  { addr: 'E214.5', label: 'EM' },
  { addr: 'E214.6', label: 'AMC' },
  { addr: 'E214.7', label: 'MTC' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LKU1' },
  { addr: 'A0.1', label: 'LEU1' },
  { addr: 'A0.2', label: 'LBU1' },
  { addr: 'A0.3', label: 'RDY1' },
  { addr: 'A0.4', label: 'RST1' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LKU2' },
  { addr: 'A1.1', label: 'LEU2' },
  { addr: 'A1.2', label: 'LBU2' },
  { addr: 'A1.3', label: 'RDY2' },
  { addr: 'A1.4', label: 'RST2' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: 'LC-A1' },
  { addr: 'A1.7', label: 'LC-B2' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'SQA' },
  { addr: 'A100.1', label: 'KBA' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RBE' },
  { addr: 'A102.0', label: '' },
  { addr: 'A102.1', label: '' },
  { addr: 'A102.2', label: '' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'LKE' },
  { addr: 'A103.1', label: 'LEE' },
  { addr: 'A103.2', label: 'LBE' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: 'SBK2' },
  { addr: 'A103.6', label: 'TLIV' },
  { addr: 'A103.7', label: 'KEM' },
  { addr: 'A104.0', label: 'A' },
  { addr: 'A104.1', label: 'B' },
  { addr: 'A104.2', label: 'C' },
  { addr: 'A104.3', label: 'D' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'SMA1' },
  { addr: 'A110.1', label: 'SMB1' },
  { addr: 'A110.2', label: 'SMA2' },
  { addr: 'A110.3', label: 'SMB2' },
  { addr: 'A110.4', label: 'SMAD' },
  { addr: 'A110.5', label: 'SMBD' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: 'TD' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: 'KCS' },
  { addr: 'A111.3', label: 'KCV' },
  { addr: 'A111.4', label: 'KCH' },
  { addr: 'A111.5', label: 'TCR1' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' },
  { addr: 'A112.0', label: 'T10' },
  { addr: 'A112.1', label: 'T2' },
  { addr: 'A112.2', label: 'TRA' },
  { addr: 'A112.3', label: 'TRB' },
  { addr: 'A112.4', label: 'TCR' },
  { addr: 'A112.5', label: 'SCA' },
  { addr: 'A112.6', label: 'SCB' },
  { addr: 'A112.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A200.0', label: 'SQA' },
  { addr: 'A200.1', label: 'KBA' },
  { addr: 'A200.2', label: 'SBK1' },
  { addr: 'A200.3', label: 'KXPE' },
  { addr: 'A200.4', label: 'SZE' },
  { addr: 'A200.5', label: 'SOE' },
  { addr: 'A200.6', label: 'LA' },
  { addr: 'A200.7', label: 'LC' },
  { addr: 'A201.0', label: 'L1' },
  { addr: 'A201.1', label: 'L2' },
  { addr: 'A201.2', label: 'L3' },
  { addr: 'A201.3', label: 'L4' },
  { addr: 'A201.4', label: 'L5' },
  { addr: 'A201.5', label: 'RFE' },
  { addr: 'A201.6', label: 'RLN' },
  { addr: 'A201.7', label: 'RBE' },
  { addr: 'A202.0', label: '' },
  { addr: 'A202.1', label: '' },
  { addr: 'A202.2', label: '' },
  { addr: 'A202.3', label: '' },
  { addr: 'A202.4', label: '' },
  { addr: 'A202.5', label: '' },
  { addr: 'A202.6', label: '' },
  { addr: 'A202.7', label: 'SPE' },
  { addr: 'A203.0', label: 'LKE' },
  { addr: 'A203.1', label: 'LEE' },
  { addr: 'A203.2', label: 'LBE' },
  { addr: 'A203.3', label: 'RDY' },
  { addr: 'A203.4', label: 'RST' },
  { addr: 'A203.5', label: 'SBK2' },
  { addr: 'A203.6', label: 'TLIV' },
  { addr: 'A203.7', label: 'KEM' },
  { addr: 'A204.0', label: 'A' },
  { addr: 'A204.1', label: 'B' },
  { addr: 'A204.2', label: 'C' },
  { addr: 'A204.3', label: 'D' },
  { addr: 'A204.4', label: 'AD1' },
  { addr: 'A204.5', label: 'AD2' },
  { addr: 'A204.6', label: 'AD3' },
  { addr: 'A204.7', label: 'STR' },
  { addr: 'A205.0', label: '' },
  { addr: 'A205.1', label: '' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A210.0', label: 'SMA1' },
  { addr: 'A210.1', label: 'SMB1' },
  { addr: 'A210.2', label: 'SMA2' },
  { addr: 'A210.3', label: 'SMB2' },
  { addr: 'A210.4', label: 'SMAD' },
  { addr: 'A210.5', label: 'SMBD' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' },
  { addr: 'A211.0', label: 'TD' },
  { addr: 'A211.1', label: '' },
  { addr: 'A211.2', label: 'KCS' },
  { addr: 'A211.3', label: 'KCV' },
  { addr: 'A211.4', label: 'KCH' },
  { addr: 'A211.5', label: 'TCR1' },
  { addr: 'A211.6', label: '' },
  { addr: 'A211.7', label: '' },
  { addr: 'A212.0', label: 'T10' },
  { addr: 'A212.1', label: 'T2' },
  { addr: 'A212.2', label: 'TRA' },
  { addr: 'A212.3', label: 'TRB' },
  { addr: 'A212.4', label: 'TCR' },
  { addr: 'A212.5', label: 'SCA' },
  { addr: 'A212.6', label: 'SCB' },
  { addr: 'A212.7', label: '' }
]

exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-01', query: {} },
  { id: 3, key: 'al-sil-01', query: {} },
  { id: 4, key: 'al-sil-02', query: {} },
  { id: 5, key: 'al-sil-03', query: {} },
  { id: 6, key: 'al-sil-04', query: {} },
  { id: 7, key: 'al-v-to', query: {} },
  { id: 8, key: 'al-h-to', query: {} },
  { id: 9, key: 'al-flap-to', query: {} },
  { id: 10, key: 'al-v-fdbk', query: {} },
  { id: 11, key: 'al-v-fdbk', query: {} },
  { id: 12, key: 'al-v-lck-to', query: { nr: 1 } },
  { id: 13, key: 'al-v-lck-to', query: { nr: 2 } },
  { id: 14, key: 'al-sp-to', query: {} },
  { id: 15, key: 'al-r-lck-to', query: {} },
  { id: 16, key: 'al-r-to', query: {} },
  { id: 17, key: 'al-th', query: { name: 'ASBK' } },
  { id: 18, key: 'al-th', query: { name: 'RT' } },
  { id: 19, key: '', query: {} },
  { id: 20, key: 'al-th', query: { name: 'APE' } },
  { id: 21, key: 'al-th', query: { name: 'AF8' } },
  { id: 22, key: 'al-th', query: { name: 'ASH' } },
  { id: 23, key: 'al-th', query: { name: 'AIV' } },
  { id: 24, key: 'al-th', query: { name: 'AMM1' } },
  { id: 25, key: 'al-th', query: { name: 'AMM2' } },
  { id: 26, key: 'al-th', query: { name: 'AD' } },
  { id: 27, key: 'al-th', query: { name: 'AMD' } },
  { id: 28, key: 'al-th', query: { name: 'AKKS' } },
  { id: 29, key: 'al-th', query: { name: 'ACR' } },
  { id: 30, key: 'al-th', query: { name: 'AMC' } },
  { id: 31, key: 'al-th', query: { name: 'MTC' } },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-fc', query: { fc1: 'EOM1', fc2: 'EZM1' } },
  { id: 34, key: 'al-sil-07', query: {} },
  { id: 35, key: 'al-sil-12', query: {} },
  { id: 36, key: 'al-sil-13', query: {} },
  { id: 37, key: 'al-fc', query: { fc1: 'ECA', fc2: 'ECB' } },
  { id: 38, key: 'al-sil-11', query: {} },
  { id: 39, key: 'al-fc', query: { fc1: 'EZE', fc2: 'EOE' } },
  { id: 40, key: 'al-fc', query: { fc1: 'EOM2', fc2: 'EZM2' } },
  { id: 41, key: 'al-fc', query: { fc1: 'EOMD', fc2: 'EZMD' } },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-lv', query: { nr: 1 } },
  { id: 50, key: 'al-lv', query: { nr: 2 } },
  { id: 51, key: 'al-lh', query: { nr: 1 } },
  { id: 52, key: 'al-lh', query: { nr: 2 } },
  { id: 53, key: 'al-lv-diff', query: {} },
  { id: 54, key: 'al-lh-diff', query: {} },
  { id: 55, key: 'al-enr', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: 'al-sil-16', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
