exports.inputs1 = [
  { addr: 'E0.0', label: 'A', info: 'A' },
  { addr: 'E0.1', label: 'B', info: 'B' },
  { addr: 'E0.2', label: 'C', info: 'C' },
  { addr: 'E0.3', label: 'D', info: 'D' },
  { addr: 'E0.4', label: 'OK', info: 'OK' },
  { addr: 'E0.5', label: 'S2', info: 'S2' },
  { addr: 'E0.6', label: 'S2', info: 'S2' },
  { addr: 'E0.7', label: 'S2', info: 'S2' },
  { addr: 'E1.0', label: 'A', info: 'A' },
  { addr: 'E1.1', label: 'B', info: 'B' },
  { addr: 'E1.2', label: 'C', info: 'C' },
  { addr: 'E1.3', label: 'D', info: 'D' },
  { addr: 'E1.4', label: 'STR', info: 'STR' },
  { addr: 'E1.5', label: 'OK', info: 'OK' },
  { addr: 'E1.6', label: 'DAT', info: 'DAT' },
  { addr: 'E1.7', label: 'UC', info: 'UC' },
  { addr: 'E2.0', label: 'KEXPV', info: 'KEXPV' },
  { addr: 'E2.1', label: 'FE1', info: 'FE1' },
  { addr: 'E2.2', label: 'K3', info: 'K3' },
  { addr: 'E2.3', label: 'FTC', info: 'FTC' },
  { addr: 'E2.4', label: 'EXPV', info: 'EXPV' },
  { addr: 'E2.5', label: 'S1', info: 'S1' },
  { addr: 'E2.6', label: 'S1', info: 'S1' },
  { addr: 'E2.7', label: 'S1', info: 'S1' },
  { addr: 'E3.0', label: 'ECA', info: '' },
  { addr: 'E3.1', label: 'ECB', info: '' },
  { addr: 'E3.2', label: 'AMC', info: '' },
  { addr: 'E3.3', label: 'K12', info: '' },
  { addr: 'E3.4', label: 'DB32', info: '' },
  { addr: 'E3.5', label: 'DBHZ', info: '' },
  { addr: 'E3.6', label: 'KXPE', info: '' },
  { addr: 'E3.7', label: 'APE', info: '' },
  { addr: 'E4.0', label: 'KBA', info: '' },
  { addr: 'E4.1', label: '', info: '' },
  { addr: 'E4.2', label: 'SFA', info: '' },
  { addr: 'E4.3', label: 'IV1', info: '' },
  { addr: 'E4.4', label: 'SBK1', info: '' },
  { addr: 'E4.5', label: 'ASBK', info: '' },
  { addr: 'E4.6', label: 'RT12', info: '' },
  { addr: 'E4.7', label: '', info: '' },
  { addr: 'E5.0', label: 'EOM1', info: '' },
  { addr: 'E5.1', label: 'EZM1', info: '' },
  { addr: 'E5.2', label: 'AMM1', info: '' },
  { addr: 'E5.3', label: 'EOM2', info: '' },
  { addr: 'E5.4', label: 'EZM2', info: '' },
  { addr: 'E5.5', label: 'AMM2', info: '' },
  { addr: 'E5.6', label: 'FDR1', info: '' },
  { addr: 'E5.7', label: 'FDL1', info: '' },
  { addr: 'E6.0', label: 'EZE', info: '' },
  { addr: 'E6.1', label: 'EOE', info: '' },
  { addr: 'E6.2', label: 'FBE', info: '' },
  { addr: 'E6.3', label: 'FPE', info: '' },
  { addr: 'E6.4', label: 'FDR', info: '' },
  { addr: 'E6.5', label: 'FDL', info: '' },
  { addr: 'E6.6', label: 'FTA', info: '' },
  { addr: 'E6.7', label: '', info: '' },
  { addr: 'E7.0', label: 'FLP', info: '' },
  { addr: 'E7.1', label: 'FLA', info: '' },
  { addr: 'E7.2', label: 'POD', info: '' },
  { addr: 'E7.3', label: 'RX1', info: '' },
  { addr: 'E7.4', label: 'RX2', info: '' },
  { addr: 'E7.5', label: 'FRE', info: '' },
  { addr: 'E7.6', label: 'FTXV', info: '' },
  { addr: 'E7.7', label: 'FTXH', info: '' },
  { addr: 'E8.0', label: 'FTA2', info: '' },
  { addr: 'E8.1', label: 'FDL2', info: '' },
  { addr: 'E8.2', label: 'FDR2', info: '' },
  { addr: 'E8.3', label: 'FTA3', info: '' },
  { addr: 'E8.4', label: 'FDL3', info: '' },
  { addr: 'E8.5', label: 'FDR3', info: '' },
  { addr: 'E8.6', label: '', info: '' },
  { addr: 'E8.7', label: '', info: '' },
  { addr: 'E9.0', label: '', info: '' },
  { addr: 'E9.1', label: '', info: '' },
  { addr: 'E9.2', label: '', info: '' },
  { addr: 'E9.3', label: '', info: '' },
  { addr: 'E9.4', label: '', info: '' },
  { addr: 'E9.5', label: '', info: '' },
  { addr: 'E9.6', label: '', info: '' },
  { addr: 'E9.7', label: '', info: '' },
  { addr: 'E10.0', label: 'A', info: '' },
  { addr: 'E10.1', label: 'B', info: '' },
  { addr: 'E10.2', label: 'C', info: '' },
  { addr: 'E10.3', label: 'D', info: '' },
  { addr: 'E10.4', label: 'OK', info: '' },
  { addr: 'E10.5', label: 'S2', info: '' },
  { addr: 'E10.6', label: 'S2', info: '' },
  { addr: 'E10.7', label: 'S2', info: '' },
  { addr: 'E11.0', label: 'FTXV', info: '' },
  { addr: 'E11.1', label: 'FTXH', info: '' },
  { addr: 'E11.2', label: 'EM', info: '' },
  { addr: 'E11.3', label: 'ASHIV', info: '' },
  { addr: 'E11.4', label: 'AD', info: '' },
  { addr: 'E11.5', label: 'MTC', info: '' },
  { addr: 'E11.6', label: 'AF8', info: '' },
  { addr: 'E11.7', label: 'UC', info: '' },
  { addr: 'E12.0', label: 'RMV', info: '' },
  { addr: 'E12.1', label: 'RMH', info: '' },
  { addr: 'E12.2', label: 'RES', info: '' },
  { addr: 'E12.3', label: 'REH', info: '' },
  { addr: 'E12.4', label: 'RCV', info: '' },
  { addr: 'E12.5', label: 'REAV', info: '' },
  { addr: 'E12.6', label: 'REAH', info: '' },
  { addr: 'E12.7', label: 'RCH', info: '' },
  { addr: 'E13.0', label: 'IV2', info: '' },
  { addr: 'E13.1', label: 'FE2', info: '' },
  { addr: 'E13.2', label: 'SRL', info: '' },
  { addr: 'E13.3', label: 'RS1', info: '' },
  { addr: 'E13.4', label: 'RS3', info: '' },
  { addr: 'E13.5', label: 'FTM', info: '' },
  { addr: 'E13.6', label: 'EHP', info: '' },
  { addr: 'E13.7', label: 'EXD', info: '' }
]
exports.inputs2 = [
  { addr: 'E20.0', label: 'A', info: '' },
  { addr: 'E20.1', label: 'B', info: '' },
  { addr: 'E20.2', label: 'C', info: '' },
  { addr: 'E20.3', label: 'D', info: '' },
  { addr: 'E20.4', label: 'OK', info: '' },
  { addr: 'E20.5', label: 'S2', info: '' },
  { addr: 'E20.6', label: 'S2', info: '' },
  { addr: 'E20.7', label: 'S2', info: '' },
  { addr: 'E21.0', label: 'FTXV', info: '' },
  { addr: 'E21.1', label: 'FTXH', info: '' },
  { addr: 'E21.2', label: 'EM', info: '' },
  { addr: 'E21.3', label: 'ASHIV', info: '' },
  { addr: 'E21.4', label: 'AD', info: '' },
  { addr: 'E21.5', label: 'MTC', info: '' },
  { addr: 'E21.6', label: 'AF8', info: '' },
  { addr: 'E21.7', label: 'UC', info: '' },
  { addr: 'E22.0', label: 'RMV', info: '' },
  { addr: 'E22.1', label: 'RMH', info: '' },
  { addr: 'E22.2', label: 'RES', info: '' },
  { addr: 'E22.3', label: 'REH', info: '' },
  { addr: 'E22.4', label: 'RCV', info: '' },
  { addr: 'E22.5', label: 'REAV', info: '' },
  { addr: 'E22.6', label: 'REAH', info: '' },
  { addr: 'E22.7', label: 'RCH', info: '' },
  { addr: 'E23.0', label: 'IV2', info: '' },
  { addr: 'E23.1', label: 'FE2', info: '' },
  { addr: 'E23.2', label: 'SRL', info: '' },
  { addr: 'E23.3', label: 'RS1', info: '' },
  { addr: 'E23.4', label: 'RS3', info: '' },
  { addr: 'E23.5', label: 'FTM', info: '' },
  { addr: 'E23.6', label: 'EHP', info: '' },
  { addr: 'E23.7', label: 'EXD', info: '' }
]
exports.inputs3 = [
  { addr: 'E30.0', label: 'A', info: '' },
  { addr: 'E30.1', label: 'B', info: '' },
  { addr: 'E30.2', label: 'C', info: '' },
  { addr: 'E30.3', label: 'D', info: '' },
  { addr: 'E30.4', label: 'OK', info: '' },
  { addr: 'E30.5', label: 'S2', info: '' },
  { addr: 'E30.6', label: 'S2', info: '' },
  { addr: 'E30.7', label: 'S2', info: '' },
  { addr: 'E31.0', label: 'FTXV', info: '' },
  { addr: 'E31.1', label: 'FTXH', info: '' },
  { addr: 'E31.2', label: 'EM', info: '' },
  { addr: 'E31.3', label: 'ASHIV', info: '' },
  { addr: 'E31.4', label: 'AD', info: '' },
  { addr: 'E31.5', label: 'MTC', info: '' },
  { addr: 'E31.6', label: 'AF8', info: '' },
  { addr: 'E31.7', label: 'UC', info: '' },
  { addr: 'E32.0', label: 'RMV', info: '' },
  { addr: 'E32.1', label: 'RMH', info: '' },
  { addr: 'E32.2', label: 'RES', info: '' },
  { addr: 'E32.3', label: 'REH', info: '' },
  { addr: 'E32.4', label: 'RCV', info: '' },
  { addr: 'E32.5', label: 'REAV', info: '' },
  { addr: 'E32.6', label: 'REAH', info: '' },
  { addr: 'E32.7', label: 'RCH', info: '' },
  { addr: 'E33.0', label: 'IV2', info: '' },
  { addr: 'E33.1', label: 'FE2', info: '' },
  { addr: 'E33.2', label: 'SRL', info: '' },
  { addr: 'E33.3', label: 'RS1', info: '' },
  { addr: 'E33.4', label: 'RS3', info: '' },
  { addr: 'E33.5', label: 'FTM', info: '' },
  { addr: 'E33.6', label: 'EHP', info: '' },
  { addr: 'E33.7', label: 'EXD', info: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: '', info: '' },
  { addr: 'A0.1', label: 'KBA', info: '' },
  { addr: 'A0.2', label: 'SBK1', info: '' },
  { addr: 'A0.3', label: 'KXPE', info: '' },
  { addr: 'A0.4', label: 'SZE', info: '' },
  { addr: 'A0.5', label: 'SOE', info: '' },
  { addr: 'A0.6', label: 'LA', info: '' },
  { addr: 'A0.7', label: 'LCM', info: '' },
  { addr: 'A1.0', label: 'L1', info: '' },
  { addr: 'A1.1', label: 'L2', info: '' },
  { addr: 'A1.2', label: 'L3', info: '' },
  { addr: 'A1.3', label: 'L4', info: '' },
  { addr: 'A1.4', label: 'L5', info: '' },
  { addr: 'A1.5', label: 'RFE', info: '' },
  { addr: 'A1.6', label: 'RLN', info: '' },
  { addr: 'A1.7', label: 'RBE', info: '' },
  { addr: 'A2.0', label: 'SMA1', info: '' },
  { addr: 'A2.1', label: 'SMB1', info: '' },
  { addr: 'A2.2', label: 'SMA2', info: '' },
  { addr: 'A2.3', label: 'SMB2', info: '' },
  { addr: 'A2.4', label: 'SCA', info: '' },
  { addr: 'A2.5', label: 'SCB', info: '' },
  { addr: 'A2.6', label: '', info: '' },
  { addr: 'A2.7', label: 'SPE', info: '' },
  { addr: 'A3.0', label: 'LKE', info: '' },
  { addr: 'A3.1', label: 'LEE', info: '' },
  { addr: 'A3.2', label: 'LBE', info: '' },
  { addr: 'A3.3', label: 'RDY', info: '' },
  { addr: 'A3.4', label: 'RST', info: '' },
  { addr: 'A3.5', label: 'SBK2', info: '' },
  { addr: 'A3.6', label: '', info: '' },
  { addr: 'A3.7', label: 'KEM', info: '' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: 'KBA2', info: '' },
  { addr: 'A10.1', label: 'TLIV', info: '' },
  { addr: 'A10.2', label: 'KCS', info: '' },
  { addr: 'A10.3', label: 'KCV', info: '' },
  { addr: 'A10.4', label: 'KCH', info: '' },
  { addr: 'A10.5', label: '', info: '' },
  { addr: 'A10.6', label: '', info: '' },
  { addr: 'A10.7', label: '', info: '' },
  { addr: 'A11.0', label: 'T10', info: '' },
  { addr: 'A11.1', label: 'T2', info: '' },
  { addr: 'A11.2', label: 'TRA', info: '' },
  { addr: 'A11.3', label: 'TRB', info: '' },
  { addr: 'A11.4', label: 'TCR', info: '' },
  { addr: 'A11.5', label: 'TD', info: '' },
  { addr: 'A11.6', label: 'LA', info: '' },
  { addr: 'A11.7', label: 'LC', info: '' },
  { addr: 'A12.0', label: 'A', info: '' },
  { addr: 'A12.1', label: 'B', info: '' },
  { addr: 'A12.2', label: 'C', info: '' },
  { addr: 'A12.3', label: 'D', info: '' },
  { addr: 'A12.4', label: 'AD1', info: '' },
  { addr: 'A12.5', label: 'AD2', info: '' },
  { addr: 'A12.6', label: 'AD3', info: '' },
  { addr: 'A12.7', label: 'STR', info: '' },
  { addr: 'A13.0', label: 'LH1', info: '' },
  { addr: 'A13.1', label: 'LH2', info: '' },
  { addr: 'A13.2', label: 'LH3', info: '' },
  { addr: 'A13.3', label: '', info: '' },
  { addr: 'A13.4', label: '', info: '' },
  { addr: 'A13.5', label: '', info: '' },
  { addr: 'A13.6', label: '', info: '' },
  { addr: 'A13.7', label: '', info: '' }
]
exports.outputs3 = [
  { addr: 'A20.0', label: 'KBA2', info: '' },
  { addr: 'A20.1', label: 'TLIV', info: '' },
  { addr: 'A20.2', label: 'KCS', info: '' },
  { addr: 'A20.3', label: 'KCV', info: '' },
  { addr: 'A20.4', label: 'KCH', info: '' },
  { addr: 'A20.5', label: '', info: '' },
  { addr: 'A20.6', label: '', info: '' },
  { addr: 'A20.7', label: '', info: '' },
  { addr: 'A21.0', label: 'T10', info: '' },
  { addr: 'A21.1', label: 'T2', info: '' },
  { addr: 'A21.2', label: 'TRA', info: '' },
  { addr: 'A21.3', label: 'TRB', info: '' },
  { addr: 'A21.4', label: 'TCR', info: '' },
  { addr: 'A21.5', label: 'TD', info: '' },
  { addr: 'A21.6', label: 'LA', info: '' },
  { addr: 'A21.7', label: 'LC', info: '' },
  { addr: 'A22.0', label: 'A', info: '' },
  { addr: 'A22.1', label: 'B', info: '' },
  { addr: 'A22.2', label: 'C', info: '' },
  { addr: 'A22.3', label: 'D', info: '' },
  { addr: 'A22.4', label: 'AD1', info: '' },
  { addr: 'A22.5', label: 'AD2', info: '' },
  { addr: 'A22.6', label: 'AD3', info: '' },
  { addr: 'A22.7', label: 'STR', info: '' },
  { addr: 'A23.0', label: '', info: '' },
  { addr: 'A23.1', label: '', info: '' },
  { addr: 'A23.2', label: '', info: '' },
  { addr: 'A23.3', label: '', info: '' },
  { addr: 'A23.4', label: '', info: '' },
  { addr: 'A23.5', label: '', info: '' },
  { addr: 'A23.6', label: '', info: '' },
  { addr: 'A23.7', label: '', info: '' }
]
exports.outputs4 = [
  { addr: 'A30.0', label: 'KBA2', info: '' },
  { addr: 'A30.1', label: 'TLIV', info: '' },
  { addr: 'A30.2', label: 'KCS', info: '' },
  { addr: 'A30.3', label: 'KCV', info: '' },
  { addr: 'A30.4', label: 'KCH', info: '' },
  { addr: 'A30.5', label: '', info: '' },
  { addr: 'A30.6', label: '', info: '' },
  { addr: 'A30.7', label: '', info: '' },
  { addr: 'A31.0', label: 'T10', info: '' },
  { addr: 'A31.1', label: 'T2', info: '' },
  { addr: 'A31.2', label: 'TRA', info: '' },
  { addr: 'A31.3', label: 'TRB', info: '' },
  { addr: 'A31.4', label: 'TCR', info: '' },
  { addr: 'A31.5', label: 'TD', info: '' },
  { addr: 'A31.6', label: 'LA', info: '' },
  { addr: 'A31.7', label: 'LC', info: '' },
  { addr: 'A32.0', label: 'A', info: '' },
  { addr: 'A32.1', label: 'B', info: '' },
  { addr: 'A32.2', label: 'C', info: '' },
  { addr: 'A32.3', label: 'D', info: '' },
  { addr: 'A32.4', label: 'AD1', info: '' },
  { addr: 'A32.5', label: 'AD2', info: '' },
  { addr: 'A32.6', label: 'AD3', info: '' },
  { addr: 'A32.7', label: 'STR', info: '' },
  { addr: 'A33.0', label: '', info: '' },
  { addr: 'A33.1', label: '', info: '' },
  { addr: 'A33.2', label: '', info: '' },
  { addr: 'A33.3', label: '', info: '' },
  { addr: 'A33.4', label: '', info: '' },
  { addr: 'A33.5', label: '', info: '' },
  { addr: 'A33.6', label: '', info: '' },
  { addr: 'A33.7', label: '', info: '' }
]
exports.ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-flap-to', query: {} },
  { id: 25, key: 'al-flap-fc', query: {} },
  { id: 26, key: 'al-spe-to', query: {} },
  { id: 27, key: 'al-spe-fc', query: {} },
  { id: 28, key: 'al-spa-to', query: {} },
  { id: 29, key: 'al-spa-fc', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: 'al-pn', query: { name: 'LS' } },
  { id: 34, key: 'al-pn', query: { name: 'IV1' } },
  { id: 35, key: 'al-pn', query: { name: 'IV2' } },
  { id: 36, key: 'al-pn', query: { name: 'LV' } },
  { id: 37, key: 'al-pn', query: { name: 'EN' } },
  { id: 38, key: 'al-pn', query: { name: 'KKM' } },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-fs', query: { name: 'BBL' } },
  { id: 42, key: 'al-fs', query: { name: 'BBEL' } },
  { id: 43, key: 'al-fs', query: { name: 'UG/BBL' } },
  { id: 44, key: 'al-fs', query: { name: 'BBE1' } },
  { id: 45, key: 'al-fs', query: { name: 'BBE2' } },
  { id: 46, key: 'al-fs', query: { name: 'ETA/B' } },
  { id: 47, key: 'al-fs', query: { name: 'BBM' } },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'APA' } },
  { id: 50, key: 'al-th', query: { name: 'AGF' } },
  { id: 51, key: 'al-th', query: { name: 'AKKM' } },
  { id: 52, key: 'al-th', query: { name: 'APE' } },
  { id: 53, key: 'al-iv', query: { nr: 2 } },
  { id: 54, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 55, key: 'al-iv', query: { nr: 1 } },
  { id: 56, key: 'al-th', query: { name: 'ASBK' } },
  { id: 57, key: 'al-th', query: { name: 'RTA' } },
  { id: 58, key: 'al-th', query: { name: 'FE1' } },
  { id: 59, key: 'al-th', query: { name: 'AF7' } },
  { id: 60, key: 'al-th', query: { name: 'AMC' } },
  { id: 61, key: 'al-th', query: { name: 'AMM' } },
  { id: 62, key: 'al-th', query: { name: 'MTC' } },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: 'al-lv', query: {} },
  { id: 84, key: 'al-lv-diff', query: {} },
  { id: 85, key: 'al-v-lck-to', query: {} },
  { id: 86, key: 'al-v-lck-fc', query: {} },
  { id: 87, key: 'al-h-to', query: {} },
  { id: 88, key: 'al-lh', query: {} },
  { id: 89, key: 'al-lh-diff', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: 'al-pn', query: { name: 'LS' } },
  { id: 98, key: 'al-pn', query: { name: 'LV1' } },
  { id: 99, key: 'al-pn', query: { name: 'LV2' } },
  { id: 100, key: 'al-pn', query: { name: 'KKP' } },
  { id: 101, key: 'al-pn', query: { name: 'SH' } },
  { id: 102, key: 'al-pn', query: { name: 'LH1' } },
  { id: 103, key: 'al-pn', query: { name: 'LH2' } },
  { id: 104, key: '', query: {} },
  { id: 105, key: 'al-fs', query: { name: 'BBL' } },
  { id: 106, key: 'al-fs', query: { name: 'UG/BBL' } },
  { id: 107, key: 'al-fs', query: { name: 'BBP' } },
  { id: 108, key: 'al-fs', query: { name: 'ETA/B' } },
  { id: 109, key: 'al-fs', query: { name: 'BBH' } },
  { id: 110, key: 'al-fs', query: { name: 'ETL/R' } },
  { id: 111, key: 'al-fs', query: { name: 'EZD' } },
  { id: 112, key: 'al-fs', query: { name: 'FAL/WAL' } },
  { id: 113, key: 'al-th', query: { name: 'FE1' } },
  { id: 114, key: 'al-iv', query: { nr: 1 } },
  { id: 115, key: 'al-th', query: { name: 'ASBK' } },
  { id: 116, key: 'al-th', query: { name: 'RTA' } },
  { id: 117, key: 'al-th', query: { name: 'ACR' } },
  { id: 118, key: 'al-th', query: { name: 'FE3' } },
  { id: 119, key: 'al-th', query: { name: 'AMM' } },
  { id: 120, key: 'al-th', query: { name: 'FE4' } },
  { id: 121, key: 'al-iv', query: { nr: 2 } },
  { id: 122, key: 'al-th', query: { name: 'AF7' } },
  { id: 123, key: 'al-th', query: { name: 'AH' } },
  { id: 124, key: 'al-th', query: { name: 'MTC' } },
  { id: 125, key: 'al-th', query: { name: 'LS shutdown' } },
  { id: 126, key: 'al-th', query: { name: 'KKP shutdown' } },
  { id: 127, key: 'al-th', query: { name: 'SH shutdown' } },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'SH1' },
  { id: 2, key: 'SH2' },
  { id: 3, key: 'SH3' },
  { id: 4, key: 'EL' }
]

exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
