// generate I/O
export const inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'SFT1' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: 'K12' },
  { addr: 'E1.3', label: 'RS3' },
  { addr: 'E1.4', label: 'RS12' },
  { addr: 'E1.5', label: 'DB32' },
  { addr: 'E1.6', label: 'DBHZ' },
  { addr: 'E1.7', label: 'UC' },
  { addr: 'E2.0', label: 'SFT' },
  { addr: 'E2.1', label: 'SF1' },
  { addr: 'E2.2', label: 'SF2' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: 'EXBZE' },
  { addr: 'E2.5', label: 'EBZE' },
  { addr: 'E2.6', label: 'EBOE' },
  { addr: 'E2.7', label: 'FE12' },
  { addr: 'E3.0', label: 'IV1' },
  { addr: 'E3.1', label: 'IV2' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: 'RTA' },
  { addr: 'E3.4', label: 'AIV2' },
  { addr: 'E3.5', label: 'AF8' },
  { addr: 'E3.6', label: 'AKKU' },
  { addr: 'E3.7', label: 'APBE' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'A' },
  { addr: 'E10.1', label: 'B' },
  { addr: 'E10.2', label: 'C' },
  { addr: 'E10.3', label: 'D' },
  { addr: 'E10.4', label: 'OK' },
  { addr: 'E10.5', label: 'S2' },
  { addr: 'E10.6', label: 'S2' },
  { addr: 'E10.7', label: 'S2' },
  { addr: 'E11.0', label: 'SRL' },
  { addr: 'E11.1', label: 'EXD' },
  { addr: 'E11.2', label: 'EHP' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: 'UC' },
  { addr: 'E12.0', label: 'FE3' },
  { addr: 'E12.1', label: 'EM' },
  { addr: 'E12.2', label: 'EXPV' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: 'FTXV' },
  { addr: 'E12.5', label: 'FTXH' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: 'FSBK' },
  { addr: 'E13.2', label: 'ASBK1' },
  { addr: 'E13.3', label: 'ASBK2' },
  { addr: 'E13.4', label: 'AH' },
  { addr: 'E13.5', label: 'AD' },
  { addr: 'E13.6', label: 'FTCR' },
  { addr: 'E13.7', label: 'MTC' },
  { addr: 'E14.0', label: 'RMV' },
  { addr: 'E14.1', label: 'RMH' },
  { addr: 'E14.2', label: 'RES' },
  { addr: 'E14.3', label: 'REH' },
  { addr: 'E14.4', label: 'RCV' },
  { addr: 'E14.5', label: 'REAV' },
  { addr: 'E14.6', label: 'REAH' },
  { addr: 'E14.7', label: 'RCH' }
]
export const inputs3 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'SRL' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: 'RS3' },
  { addr: 'E101.4', label: 'RS12' },
  { addr: 'E101.5', label: '' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'A' },
  { addr: 'E102.1', label: 'B' },
  { addr: 'E102.2', label: 'C' },
  { addr: 'E102.3', label: 'D' },
  { addr: 'E102.4', label: 'STR' },
  { addr: 'E102.5', label: 'OK' },
  { addr: 'E102.6', label: 'DAT' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: 'IV1' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: '' },
  { addr: 'E103.5', label: '' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: 'EOM1' },
  { addr: 'E104.1', label: 'EZM1' },
  { addr: 'E104.2', label: 'EOM2' },
  { addr: 'E104.3', label: 'EZM2' },
  { addr: 'E104.4', label: 'ECA' },
  { addr: 'E104.5', label: 'ECB' },
  { addr: 'E104.6', label: 'FRE1' },
  { addr: 'E104.7', label: 'FRE2' },
  { addr: 'E105.0', label: 'FTC' },
  { addr: 'E105.1', label: 'EFB' },
  { addr: 'E105.2', label: 'FTXV' },
  { addr: 'E105.3', label: 'FTXH' },
  { addr: 'E105.4', label: 'FTM' },
  { addr: 'E105.5', label: 'MNA' },
  { addr: 'E105.6', label: 'MNB' },
  { addr: 'E105.7', label: 'KEXPV1' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR' },
  { addr: 'E106.5', label: 'FDL' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP' },
  { addr: 'E107.1', label: '' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: 'POD' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: 'RX' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' },
  { addr: 'E108.0', label: 'EXZE' },
  { addr: 'E108.1', label: 'FDR1' },
  { addr: 'E108.2', label: 'FDL1' },
  { addr: 'E108.3', label: 'FTA3' },
  { addr: 'E108.4', label: 'FSBK' },
  { addr: 'E108.5', label: 'ASBK' },
  { addr: 'E108.6', label: 'RTA' },
  { addr: 'E108.7', label: 'FE12' },
  { addr: 'E109.0', label: 'AMM1' },
  { addr: 'E109.1', label: 'AMM2' },
  { addr: 'E109.2', label: 'AMC' },
  { addr: 'E109.3', label: 'APE' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: 'KEXPV2' }
]
export const inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'OK' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: 'S2' },
  { addr: 'E201.0', label: 'SRL' },
  { addr: 'E201.1', label: '' },
  { addr: 'E201.2', label: '' },
  { addr: 'E201.3', label: 'RS3' },
  { addr: 'E201.4', label: 'RS12' },
  { addr: 'E201.5', label: '' },
  { addr: 'E201.6', label: '' },
  { addr: 'E201.7', label: 'UC' },
  { addr: 'E202.0', label: 'A' },
  { addr: 'E202.1', label: 'B' },
  { addr: 'E202.2', label: 'C' },
  { addr: 'E202.3', label: 'D' },
  { addr: 'E202.4', label: 'STR' },
  { addr: 'E202.5', label: 'OK' },
  { addr: 'E202.6', label: 'DAT' },
  { addr: 'E202.7', label: '' },
  { addr: 'E203.0', label: 'IV1' },
  { addr: 'E203.1', label: '' },
  { addr: 'E203.2', label: '' },
  { addr: 'E203.3', label: '' },
  { addr: 'E203.4', label: '' },
  { addr: 'E203.5', label: '' },
  { addr: 'E203.6', label: '' },
  { addr: 'E203.7', label: '' },
  { addr: 'E204.0', label: 'EOM1' },
  { addr: 'E204.1', label: 'EZM1' },
  { addr: 'E204.2', label: 'EOM2' },
  { addr: 'E204.3', label: 'EZM2' },
  { addr: 'E204.4', label: 'ECA' },
  { addr: 'E204.5', label: 'ECB' },
  { addr: 'E204.6', label: 'FRE1' },
  { addr: 'E204.7', label: 'FRE2' },
  { addr: 'E205.0', label: 'FTC' },
  { addr: 'E205.1', label: 'EFB' },
  { addr: 'E205.2', label: 'FTXV' },
  { addr: 'E205.3', label: 'FTXH' },
  { addr: 'E205.4', label: 'FTM' },
  { addr: 'E205.5', label: 'MNA' },
  { addr: 'E205.6', label: 'MNB' },
  { addr: 'E205.7', label: 'KEXPV1' },
  { addr: 'E206.0', label: 'EZE' },
  { addr: 'E206.1', label: 'EOE' },
  { addr: 'E206.2', label: 'FBE' },
  { addr: 'E206.3', label: 'FPE' },
  { addr: 'E206.4', label: 'FDR' },
  { addr: 'E206.5', label: 'FDL' },
  { addr: 'E206.6', label: 'FTA1' },
  { addr: 'E206.7', label: 'FTA2' },
  { addr: 'E207.0', label: 'FLP' },
  { addr: 'E207.1', label: '' },
  { addr: 'E207.2', label: 'FLA' },
  { addr: 'E207.3', label: 'POD' },
  { addr: 'E207.4', label: '' },
  { addr: 'E207.5', label: 'RX' },
  { addr: 'E207.6', label: '' },
  { addr: 'E207.7', label: '' },
  { addr: 'E208.0', label: 'EXZE' },
  { addr: 'E208.1', label: 'FDR1' },
  { addr: 'E208.2', label: 'FDL1' },
  { addr: 'E208.3', label: 'FTA3' },
  { addr: 'E208.4', label: 'FSBK' },
  { addr: 'E208.5', label: 'ASBK' },
  { addr: 'E208.6', label: 'RTA' },
  { addr: 'E208.7', label: 'FE12' },
  { addr: 'E209.0', label: 'AMM1' },
  { addr: 'E209.1', label: 'AMM2' },
  { addr: 'E209.2', label: 'AMC' },
  { addr: 'E209.3', label: 'APE' },
  { addr: 'E209.4', label: '' },
  { addr: 'E209.5', label: '' },
  { addr: 'E209.6', label: '' },
  { addr: 'E209.7', label: 'KEXPV2' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'A' },
  { addr: 'A0.1', label: 'B' },
  { addr: 'A0.2', label: 'C' },
  { addr: 'A0.3', label: 'D' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'STO1-1' },
  { addr: 'A1.1', label: 'STO1-2' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: 'LA' },
  { addr: 'A1.7', label: 'LC' },
  { addr: 'A2.0', label: 'STO2-1' },
  { addr: 'A2.1', label: 'STO2-2' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: 'LSE' },
  { addr: 'A2.5', label: 'LST' },
  { addr: 'A2.6', label: 'LS1' },
  { addr: 'A2.7', label: 'LS2' },
  { addr: 'A3.0', label: 'TLIV' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: 'SPBE' },
  { addr: 'A3.5', label: 'SBZE' },
  { addr: 'A3.6', label: 'SBOE' },
  { addr: 'A3.7', label: 'KXPBE' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'A' },
  { addr: 'A10.1', label: 'B' },
  { addr: 'A10.2', label: 'C' },
  { addr: 'A10.3', label: 'D' },
  { addr: 'A10.4', label: 'AD1' },
  { addr: 'A10.5', label: 'AD2' },
  { addr: 'A10.6', label: 'AD3' },
  { addr: 'A10.7', label: 'STR' },
  { addr: 'A11.0', label: 'T10' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: 'TD' },
  { addr: 'A11.3', label: 'TCR' },
  { addr: 'A11.4', label: 'SBK1' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: 'LA' },
  { addr: 'A11.7', label: 'LC' },
  { addr: 'A12.0', label: 'T2' },
  { addr: 'A12.1', label: 'TRA' },
  { addr: 'A12.2', label: 'TRB' },
  { addr: 'A12.3', label: 'KCS' },
  { addr: 'A12.4', label: 'KCV' },
  { addr: 'A12.5', label: 'KCH' },
  { addr: 'A12.6', label: 'SBK2' },
  { addr: 'A12.7', label: 'T10F' }
]
export const outputs3 = [
  { addr: 'A100.0', label: 'A' },
  { addr: 'A100.1', label: 'B' },
  { addr: 'A100.2', label: 'C' },
  { addr: 'A100.3', label: 'D' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'STO1-1' },
  { addr: 'A101.1', label: '' },
  { addr: 'A101.2', label: '' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: 'LA' },
  { addr: 'A101.7', label: 'LC' },
  { addr: 'A102.0', label: '' },
  { addr: 'A102.1', label: '' },
  { addr: 'A102.2', label: '' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: 'SBK1' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'SMA1' },
  { addr: 'A103.1', label: 'SMB1' },
  { addr: 'A103.2', label: 'SMA2' },
  { addr: 'A103.3', label: 'SMB2' },
  { addr: 'A103.4', label: 'SCA' },
  { addr: 'A103.5', label: 'SCB' },
  { addr: 'A103.6', label: 'SBK2' },
  { addr: 'A103.7', label: '' },
  { addr: 'A104.0', label: 'L1' },
  { addr: 'A104.1', label: 'L2' },
  { addr: 'A104.2', label: 'L3' },
  { addr: 'A104.3', label: 'L4' },
  { addr: 'A104.4', label: 'L5' },
  { addr: 'A104.5', label: 'RFE' },
  { addr: 'A104.6', label: 'RLN' },
  { addr: 'A104.7', label: 'RBE' },
  { addr: 'A105.0', label: 'LK' },
  { addr: 'A105.1', label: 'LE' },
  { addr: 'A105.2', label: 'LB' },
  { addr: 'A105.3', label: 'RDY' },
  { addr: 'A105.4', label: 'RST' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: 'STO2-1' },
  { addr: 'A106.0', label: 'SPE' },
  { addr: 'A106.1', label: 'SZE' },
  { addr: 'A106.2', label: 'SOE' },
  { addr: 'A106.3', label: 'KXPE' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' }
]
export const outputs4 = [
  { addr: 'A200.0', label: 'A' },
  { addr: 'A200.1', label: 'B' },
  { addr: 'A200.2', label: 'C' },
  { addr: 'A200.3', label: 'D' },
  { addr: 'A200.4', label: 'AD1' },
  { addr: 'A200.5', label: 'AD2' },
  { addr: 'A200.6', label: 'AD3' },
  { addr: 'A200.7', label: 'STR' },
  { addr: 'A201.0', label: 'STO1-1' },
  { addr: 'A201.1', label: '' },
  { addr: 'A201.2', label: '' },
  { addr: 'A201.3', label: '' },
  { addr: 'A201.4', label: '' },
  { addr: 'A201.5', label: '' },
  { addr: 'A201.6', label: 'LA' },
  { addr: 'A201.7', label: 'LC' },
  { addr: 'A202.0', label: '' },
  { addr: 'A202.1', label: '' },
  { addr: 'A202.2', label: '' },
  { addr: 'A202.3', label: '' },
  { addr: 'A202.4', label: '' },
  { addr: 'A202.5', label: '' },
  { addr: 'A202.6', label: 'SBK1' },
  { addr: 'A202.7', label: '' },
  { addr: 'A203.0', label: 'SMA1' },
  { addr: 'A203.1', label: 'SMB1' },
  { addr: 'A203.2', label: 'SMA2' },
  { addr: 'A203.3', label: 'SMB2' },
  { addr: 'A203.4', label: 'SCA' },
  { addr: 'A203.5', label: 'SCB' },
  { addr: 'A203.6', label: 'SBK2' },
  { addr: 'A203.7', label: '' },
  { addr: 'A204.0', label: 'L1' },
  { addr: 'A204.1', label: 'L2' },
  { addr: 'A204.2', label: 'L3' },
  { addr: 'A204.3', label: 'L4' },
  { addr: 'A204.4', label: 'L5' },
  { addr: 'A204.5', label: 'RFE' },
  { addr: 'A204.6', label: 'RLN' },
  { addr: 'A204.7', label: 'RBE' },
  { addr: 'A205.0', label: 'LK' },
  { addr: 'A205.1', label: 'LE' },
  { addr: 'A205.2', label: 'LB' },
  { addr: 'A205.3', label: 'RDY' },
  { addr: 'A205.4', label: 'RST' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: 'STO2-1' },
  { addr: 'A206.0', label: 'SPE' },
  { addr: 'A206.1', label: 'SZE' },
  { addr: 'A206.2', label: 'SOE' },
  { addr: 'A206.3', label: 'KXPE' },
  { addr: 'A206.4', label: '' },
  { addr: 'A206.5', label: '' },
  { addr: 'A206.6', label: '' },
  { addr: 'A206.7', label: '' },
  { addr: 'A207.0', label: '' },
  { addr: 'A207.1', label: '' },
  { addr: 'A207.2', label: '' },
  { addr: 'A207.3', label: '' },
  { addr: 'A207.4', label: '' },
  { addr: 'A207.5', label: '' },
  { addr: 'A207.6', label: '' },
  { addr: 'A207.7', label: '' }
]
export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-lv-diff', query: {} },
  { id: 21, key: 'al-h-to', query: {} },
  { id: 22, key: 'al-lh', query: {} },
  { id: 23, key: 'al-lh-diff', query: {} },
  { id: 24, key: 'al-r-to', query: {} },
  { id: 25, key: 'al-enr', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'FE' } },
  { id: 50, key: 'al-iv', query: { nr: 1 } },
  { id: 51, key: 'al-iv', query: { nr: 2 } },
  { id: 52, key: 'al-th', query: { name: 'RTA' } },
  { id: 53, key: 'al-th', query: { name: 'AIV' } },
  { id: 54, key: 'al-th', query: { name: 'AF8' } },
  { id: 55, key: 'al-th', query: { name: 'AKKU' } },
  { id: 56, key: 'al-th', query: { name: 'APBE' } },
  { id: 57, key: 'al-th', query: { name: 'ASBK1' } },
  { id: 58, key: 'al-th', query: { name: 'ASBK2' } },
  { id: 59, key: 'al-th', query: { name: 'AD' } },
  { id: 60, key: 'al-th', query: { name: 'MTC' } },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: 'al-v-to', query: {} },
  { id: 82, key: 'al-v-fdbk', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: 'al-v-lck-to', query: {} },
  { id: 85, key: 'al-v-lck-fc', query: {} },
  { id: 86, key: 'al-v-lck-to', query: {} },
  { id: 87, key: 'al-v-lck-fc', query: {} },
  { id: 88, key: 'al-flap-to', query: {} },
  { id: 89, key: 'al-flap-fc', query: {} },
  { id: 90, key: 'al-sp-to', query: {} },
  { id: 91, key: 'al-sp-to', query: {} },
  { id: 92, key: 'al-sp-fc', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'ASBK' } },
  { id: 114, key: 'al-th', query: { name: 'RTA' } },
  { id: 115, key: 'al-th', query: { name: 'FE1' } },
  { id: 116, key: 'al-th', query: { name: 'AMM1' } },
  { id: 117, key: 'al-th', query: { name: 'AMM2' } },
  { id: 118, key: 'al-th', query: { name: 'AMC' } },
  { id: 119, key: 'al-th', query: { name: 'APE' } },
  { id: 120, key: 'al-iv', query: { nr: 1 } },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]
export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'T' },
  { id: 2, key: 'EL1' },
  { id: 3, key: 'EL2' }
]

export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]

export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
