export const inputsEL = [
  { addr: 'E16.0', label: 'BA' },
  { addr: 'E16.1', label: 'BB' },
  { addr: 'E16.2', label: 'BC' },
  { addr: 'E16.3', label: 'BD' },
  { addr: 'E16.4', label: 'BSTR' },
  { addr: 'E16.5', label: 'BOK' },
  { addr: 'E16.6', label: 'BDAT' },
  { addr: 'E16.7', label: 'TCR' },
  { addr: 'E17.0', label: 'EPZ2' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: 'ECA2' },
  { addr: 'E17.3', label: 'ECB2' },
  { addr: 'E17.4', label: 'FEMV' },
  { addr: 'E17.5', label: 'FEMH' },
  { addr: 'E17.6', label: 'FTXV' },
  { addr: 'E17.7', label: 'FTXH' },
  { addr: 'E18.0', label: 'RMV' },
  { addr: 'E18.1', label: 'RMH' },
  { addr: 'E18.2', label: 'RES' },
  { addr: 'E18.3', label: 'REH' },
  { addr: 'E18.4', label: 'RCVH' },
  { addr: 'E18.5', label: 'REAV' },
  { addr: 'E18.6', label: 'REAH' },
  { addr: 'E18.7', label: 'REP' },
  { addr: 'E20.0', label: 'A' },
  { addr: 'E20.1', label: 'B' },
  { addr: 'E20.2', label: 'C' },
  { addr: 'E20.3', label: 'D' },
  { addr: 'E20.4', label: 'OK' },
  { addr: 'E20.5', label: 'S2' },
  { addr: 'E20.6', label: 'S2' },
  { addr: 'E20.7', label: 'S2' },
  { addr: 'E21.0', label: 'EBZE' },
  { addr: 'E21.1', label: 'EBOE' },
  { addr: 'E21.2', label: 'FBBE' },
  { addr: 'E21.3', label: 'APBE' },
  { addr: 'E21.4', label: 'AD' },
  { addr: 'E21.5', label: 'S1' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: '' },
  { addr: 'E22.0', label: 'EFA' },
  { addr: 'E22.1', label: 'EFB' },
  { addr: 'E22.2', label: 'EXPV' },
  { addr: 'E22.3', label: 'EXV' },
  { addr: 'E22.4', label: 'FTC' },
  { addr: 'E22.5', label: 'FPE2' },
  { addr: 'E22.6', label: 'MTC' },
  { addr: 'E22.7', label: 'UC' },
  { addr: 'E23.0', label: 'IV1' },
  { addr: 'E23.1', label: 'IV2' },
  { addr: 'E23.2', label: 'TJ1' },
  { addr: 'E23.3', label: 'RSI' },
  { addr: 'E23.4', label: 'DB32' },
  { addr: 'E23.5', label: 'DBHZ' },
  { addr: 'E23.6', label: 'FDR2' },
  { addr: 'E23.7', label: 'FDL2' },
  { addr: 'E24.0', label: 'MDR' },
  { addr: 'E24.1', label: 'MDL' },
  { addr: 'E24.2', label: 'EDR' },
  { addr: 'E24.3', label: 'EDL' },
  { addr: 'E24.4', label: 'RTA' },
  { addr: 'E24.5', label: 'ASBK' },
  { addr: 'E24.6', label: '>HZ' },
  { addr: 'E24.7', label: 'FDBK' },
  { addr: 'E25.0', label: 'AMM' },
  { addr: 'E25.1', label: 'EOM' },
  { addr: 'E25.2', label: 'EZM' },
  { addr: 'E25.3', label: 'FRDX' },
  { addr: 'E25.4', label: 'FRSX' },
  { addr: 'E25.5', label: 'FDR1' },
  { addr: 'E25.6', label: 'FDL1' },
  { addr: 'E25.7', label: 'APE' },
  { addr: 'E26.0', label: 'EZE' },
  { addr: 'E26.1', label: 'EOE' },
  { addr: 'E26.2', label: 'FBE' },
  { addr: 'E26.3', label: 'FPE' },
  { addr: 'E26.4', label: '' },
  { addr: 'E26.5', label: 'FLP1' },
  { addr: 'E26.6', label: 'RXE' },
  { addr: 'E26.7', label: 'FTA1' },
  { addr: 'E27.0', label: 'FTA2' },
  { addr: 'E27.1', label: 'FLA2' },
  { addr: 'E27.2', label: 'FLP2' },
  { addr: 'E27.3', label: 'EPZV1' },
  { addr: 'E27.4', label: 'EPZH1' },
  { addr: 'E27.5', label: 'AMC' },
  { addr: 'E27.6', label: 'ECA1' },
  { addr: 'E27.7', label: 'ECB1' }
]

export const inputsSH = [
  { addr: 'E16.0', label: 'A' },
  { addr: 'E16.1', label: 'B' },
  { addr: 'E16.2', label: 'C' },
  { addr: 'E16.3', label: 'D' },
  { addr: 'E16.4', label: 'OK' },
  { addr: 'E16.5', label: 'S2' },
  { addr: 'E16.6', label: 'S2' },
  { addr: 'E16.7', label: 'S2' },
  { addr: 'E17.0', label: 'IV1' },
  { addr: 'E17.1', label: 'TJ1' },
  { addr: 'E17.2', label: 'S1' },
  { addr: 'E17.3', label: 'RSI' },
  { addr: 'E17.4', label: 'DB32' },
  { addr: 'E17.5', label: 'DBHZ' },
  { addr: 'E17.6', label: 'FTM' },
  { addr: 'E17.7', label: 'UC' },
  { addr: 'E18.0', label: 'RMV' },
  { addr: 'E18.1', label: 'RMH' },
  { addr: 'E18.2', label: 'RES' },
  { addr: 'E18.3', label: 'REH' },
  { addr: 'E18.4', label: 'RCVH' },
  { addr: 'E18.5', label: 'REAV' },
  { addr: 'E18.6', label: 'REAH' },
  { addr: 'E18.7', label: 'REP' },
  { addr: 'E20.0', label: 'EFR' },
  { addr: 'E20.1', label: 'EFL' },
  { addr: 'E20.2', label: 'EHP1' },
  { addr: 'E20.3', label: 'EHP5' },
  { addr: 'E20.4', label: '' },
  { addr: 'E20.5', label: 'TCR' },
  { addr: 'E20.6', label: 'AH' },
  { addr: 'E20.7', label: 'MTC' },
  { addr: 'E21.0', label: '' },
  { addr: 'E21.1', label: '' },
  { addr: 'E21.2', label: '' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: 'FEMV' },
  { addr: 'E21.5', label: 'FEMH' },
  { addr: 'E21.6', label: 'FTXV' },
  { addr: 'E21.7', label: 'FTXH' }
]

export const outputsEL = [
  { addr: 'A16.0', label: 'DYA' },
  { addr: 'A16.1', label: 'DYB' },
  { addr: 'A16.2', label: 'DYC' },
  { addr: 'A16.3', label: 'DYD' },
  { addr: 'A16.4', label: 'AD1' },
  { addr: 'A16.5', label: 'AD2' },
  { addr: 'A16.6', label: 'AD3' },
  { addr: 'A16.7', label: 'STR' },
  { addr: 'A17.0', label: 'L1' },
  { addr: 'A17.1', label: 'L2' },
  { addr: 'A17.2', label: 'L3' },
  { addr: 'A17.3', label: 'L4' },
  { addr: 'A17.4', label: 'L5' },
  { addr: 'A17.5', label: 'RFE' },
  { addr: 'A17.6', label: 'RLN' },
  { addr: 'A17.7', label: 'RBE' },
  { addr: 'A20.0', label: 'RA1' },
  { addr: 'A20.1', label: 'RB1' },
  { addr: 'A20.2', label: 'RD1' },
  { addr: 'A20.3', label: 'KBA1' },
  { addr: 'A20.4', label: 'KRST1' },
  { addr: 'A20.5', label: 'KBST1' },
  { addr: 'A20.6', label: 'SCA2' },
  { addr: 'A20.7', label: 'SCB2' },
  { addr: 'A21.0', label: 'KQA' },
  { addr: 'A21.1', label: 'SMA' },
  { addr: 'A21.2', label: 'SMB' },
  { addr: 'A21.3', label: 'SCA1' },
  { addr: 'A21.4', label: 'SCB1' },
  { addr: 'A21.5', label: 'SBZE' },
  { addr: 'A21.6', label: 'SBOE' },
  { addr: 'A21.7', label: 'SBK1' },
  { addr: 'A22.0', label: 'RA2' },
  { addr: 'A22.1', label: 'RB2' },
  { addr: 'A22.2', label: 'RD2' },
  { addr: 'A22.3', label: 'KBA2' },
  { addr: 'A22.4', label: 'KRST2' },
  { addr: 'A22.5', label: 'KBST2' },
  { addr: 'A22.6', label: '' },
  { addr: 'A22.7', label: 'SBK2' },
  { addr: 'A23.0', label: 'LK' },
  { addr: 'A23.1', label: 'LE' },
  { addr: 'A23.2', label: 'LB' },
  { addr: 'A23.3', label: 'RDY' },
  { addr: 'A23.4', label: 'RST' },
  { addr: 'A23.5', label: 'LC1' },
  { addr: 'A23.6', label: 'CC2' },
  { addr: 'A23.7', label: '' },
  { addr: 'A24.0', label: '' },
  { addr: 'A24.1', label: '' },
  { addr: 'A24.2', label: 'SC3' },
  { addr: 'A24.3', label: '' },
  { addr: 'A24.4', label: 'SC1' },
  { addr: 'A24.5', label: 'SC2' },
  { addr: 'A24.6', label: 'SPE' },
  { addr: 'A24.7', label: 'TD' },
  { addr: 'A25.0', label: '' },
  { addr: 'A25.1', label: 'T2' },
  { addr: 'A25.2', label: 'TRA' },
  { addr: 'A25.3', label: 'TRB' },
  { addr: 'A25.4', label: 'KCS' },
  { addr: 'A25.5', label: 'KCV' },
  { addr: 'A25.6', label: 'KCH' },
  { addr: 'A25.7', label: 'TCR' }
]

export const outputsSH = [
  { addr: 'A16.0', label: 'DYA' },
  { addr: 'A16.1', label: 'DYB' },
  { addr: 'A16.2', label: 'DYC' },
  { addr: 'A16.3', label: 'DYD' },
  { addr: 'A16.4', label: 'AD1' },
  { addr: 'A16.5', label: 'AD2' },
  { addr: 'A16.6', label: 'ADR' },
  { addr: 'A16.7', label: 'STR' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' },
  { addr: 'A20.0', label: 'RA1' },
  { addr: 'A20.1', label: 'RB1' },
  { addr: 'A20.2', label: 'RD1' },
  { addr: 'A20.3', label: 'KBA1' },
  { addr: 'A20.4', label: 'KRST1' },
  { addr: 'A20.5', label: 'KBST1' },
  { addr: 'A20.6', label: '' },
  { addr: 'A20.7', label: 'LC' },
  { addr: 'A21.0', label: 'T10' },
  { addr: 'A21.1', label: 'T2' },
  { addr: 'A21.2', label: 'TRA' },
  { addr: 'A21.3', label: 'TRB' },
  { addr: 'A21.4', label: 'KCS' },
  { addr: 'A21.5', label: 'KCV' },
  { addr: 'A21.6', label: 'KCH' },
  { addr: 'A21.7', label: 'TCR' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-flap-to', query: {} },
  { id: 25, key: 'al-flap-fc', query: {} },
  { id: 26, key: 'al-flap-to', query: {} },
  { id: 27, key: 'al-flap-fc', query: {} },
  { id: 28, key: 'al-sp-to', query: {} },
  { id: 29, key: 'al-sp-to', query: {} },
  { id: 30, key: 'al-sp-fc', query: {} },
  { id: 31, key: 'al-spb-to', query: {} },
  { id: 32, key: 'al-spb-to', query: {} },
  { id: 33, key: 'al-spb-fc', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-pn', query: { name: 'CPU314' } },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'APBE' } },
  { id: 50, key: 'al-th', query: { name: 'AD' } },
  { id: 51, key: 'al-th', query: { name: 'RTA' } },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'AMM' } },
  { id: 54, key: 'al-th', query: { name: 'APE' } },
  { id: 55, key: 'al-th', query: { name: 'AMC' } },
  { id: 56, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-h-to', query: {} },
  { id: 82, key: 'al-lh', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: 'al-pn', query: { name: 'CPU314' } },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'APBE' } },
  { id: 114, key: 'al-th', query: { name: 'AD' } },
  { id: 115, key: 'al-th', query: { name: 'MTC' } },
  { id: 116, key: 'al-th', query: { name: 'IV1' } },
  { id: 117, key: 'al-th', query: { name: 'IV2' } },
  { id: 118, key: 'al-th', query: { name: 'TJ1' } },
  { id: 119, key: 'al-th', query: { name: 'RTA' } },
  { id: 120, key: 'al-th', query: { name: 'ASBK' } },
  { id: 121, key: 'al-th', query: { name: 'AMM' } },
  { id: 122, key: 'al-th', query: { name: 'APE' } },
  { id: 123, key: 'al-th', query: { name: 'AMC' } },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'EL4' },
  { id: 5, key: 'EL5' },
  { id: 6, key: 'SH1' },
  { id: 7, key: 'SH2' },
  { id: 8, key: 'SH3' },
  { id: 9, key: 'SH4' },
  { id: 10, key: 'SH5' },
  { id: 11, key: 'SH6' },
  { id: 12, key: 'SH7' },
  { id: 13, key: 'SH8' },
  { id: 14, key: 'SH9' },
  { id: 15, key: 'SH10' },
  { id: 16, key: 'SH11' },
  { id: 17, key: 'SH12' },
  { id: 18, key: 'SH13' },
  { id: 19, key: 'SH14' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-eme-3' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
