export const inputsEL = [
  { addr: 'E0.0', label: 'BA' },
  { addr: 'E0.1', label: 'BB' },
  { addr: 'E0.2', label: 'BC' },
  { addr: 'E0.3', label: 'BD' },
  { addr: 'E0.4', label: 'BSTR' },
  { addr: 'E0.5', label: 'BOK' },
  { addr: 'E0.6', label: 'BDAT' },
  { addr: 'E0.7', label: 'TCR' },
  { addr: 'E1.0', label: 'EPZ2' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: 'ECA2' },
  { addr: 'E1.3', label: 'ECB2' },
  { addr: 'E1.4', label: 'FEMV' },
  { addr: 'E1.5', label: 'FEMH' },
  { addr: 'E1.6', label: 'FTXV' },
  { addr: 'E1.7', label: 'FTXH' },
  { addr: 'E2.0', label: 'RMV' },
  { addr: 'E2.1', label: 'RMH' },
  { addr: 'E2.2', label: 'RES' },
  { addr: 'E2.3', label: 'REH' },
  { addr: 'E2.4', label: 'RCVH' },
  { addr: 'E2.5', label: 'REAV' },
  { addr: 'E2.6', label: 'REAH' },
  { addr: 'E2.7', label: 'REP' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'EBZE' },
  { addr: 'E5.1', label: 'EBOE' },
  { addr: 'E5.2', label: 'FBBE' },
  { addr: 'E5.3', label: 'APBE' },
  { addr: 'E5.4', label: 'AD' },
  { addr: 'E5.5', label: 'S1' },
  { addr: 'E5.6', label: 'EZP' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: 'EFA' },
  { addr: 'E6.1', label: 'EFB' },
  { addr: 'E6.2', label: 'EXPV' },
  { addr: 'E6.3', label: 'EXV' },
  { addr: 'E6.4', label: 'FTC' },
  { addr: 'E6.5', label: 'FPE2' },
  { addr: 'E6.6', label: 'MTC' },
  { addr: 'E6.7', label: 'UC' },
  { addr: 'E7.0', label: 'IV1' },
  { addr: 'E7.1', label: 'IV2' },
  { addr: 'E7.2', label: 'TJ1' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: 'FDR2' },
  { addr: 'E7.7', label: 'FDL2' },
  { addr: 'E8.0', label: 'MDR' },
  { addr: 'E8.1', label: 'MDL' },
  { addr: 'E8.2', label: 'EDR' },
  { addr: 'E8.3', label: 'EDL' },
  { addr: 'E8.4', label: 'RTA' },
  { addr: 'E8.5', label: 'ASBK' },
  { addr: 'E8.6', label: '>HZ' },
  { addr: 'E8.7', label: 'FDBK' },
  { addr: 'E9.0', label: 'AMM' },
  { addr: 'E9.1', label: 'EOM' },
  { addr: 'E9.2', label: 'EZM' },
  { addr: 'E9.3', label: 'FRDX' },
  { addr: 'E9.4', label: 'FRSX' },
  { addr: 'E9.5', label: 'FDR1' },
  { addr: 'E9.6', label: 'FDL1' },
  { addr: 'E9.7', label: 'APE' },
  { addr: 'E10.0', label: 'EZE' },
  { addr: 'E10.1', label: 'EOE' },
  { addr: 'E10.2', label: 'FBE' },
  { addr: 'E10.3', label: 'FPE' },
  { addr: 'E10.4', label: '' },
  { addr: 'E10.5', label: 'FLP1' },
  { addr: 'E10.6', label: 'RXE' },
  { addr: 'E10.7', label: 'FTA1' },
  { addr: 'E11.0', label: 'FTA2' },
  { addr: 'E11.1', label: 'FLA2' },
  { addr: 'E11.2', label: 'FLP2' },
  { addr: 'E11.3', label: 'EPZV1' },
  { addr: 'E11.4', label: 'EPZH1' },
  { addr: 'E11.5', label: 'AMC' },
  { addr: 'E11.6', label: 'ECA1' },
  { addr: 'E11.7', label: 'ECB1' }
]

export const inputsSH = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'IV1' },
  { addr: 'E1.1', label: 'TJ1' },
  { addr: 'E1.2', label: 'S1' },
  { addr: 'E1.3', label: 'RSI' },
  { addr: 'E1.4', label: 'DB32' },
  { addr: 'E1.5', label: 'DBHZ' },
  { addr: 'E1.6', label: 'FTM' },
  { addr: 'E1.7', label: 'UC' },
  { addr: 'E2.0', label: 'RMV' },
  { addr: 'E2.1', label: 'RMH' },
  { addr: 'E2.2', label: 'RES' },
  { addr: 'E2.3', label: 'REH' },
  { addr: 'E2.4', label: 'RCVH' },
  { addr: 'E2.5', label: 'REAV' },
  { addr: 'E2.6', label: 'REAH' },
  { addr: 'E2.7', label: 'REP' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'EFR' },
  { addr: 'E4.1', label: 'EFL' },
  { addr: 'E4.2', label: 'EHP1' },
  { addr: 'E4.3', label: 'EHP5' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: 'TCR' },
  { addr: 'E4.6', label: 'AH' },
  { addr: 'E4.7', label: 'MTC' },
  { addr: 'E5.0', label: '' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: 'FEMV' },
  { addr: 'E5.5', label: 'FEMH' },
  { addr: 'E5.6', label: 'FTXV' },
  { addr: 'E5.7', label: 'FTXH' }
]

export const outputsEL = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'L1' },
  { addr: 'A1.1', label: 'L2' },
  { addr: 'A1.2', label: 'L3' },
  { addr: 'A1.3', label: 'L4' },
  { addr: 'A1.4', label: 'L5' },
  { addr: 'A1.5', label: 'RFE' },
  { addr: 'A1.6', label: 'RLN' },
  { addr: 'A1.7', label: 'RBE' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: 'RA1' },
  { addr: 'A4.1', label: 'RB1' },
  { addr: 'A4.2', label: 'RD1' },
  { addr: 'A4.3', label: 'KBA1' },
  { addr: 'A4.4', label: 'KRST1' },
  { addr: 'A4.5', label: 'KBST1' },
  { addr: 'A4.6', label: 'SCA2' },
  { addr: 'A4.7', label: 'SCB2' },
  { addr: 'A5.0', label: 'KQA' },
  { addr: 'A5.1', label: 'SMA' },
  { addr: 'A5.2', label: 'SMB' },
  { addr: 'A5.3', label: 'SCA1' },
  { addr: 'A5.4', label: 'SCB1' },
  { addr: 'A5.5', label: 'SBZE' },
  { addr: 'A5.6', label: 'SBOE' },
  { addr: 'A5.7', label: 'SBK1' },
  { addr: 'A6.0', label: 'RA2' },
  { addr: 'A6.1', label: 'RB2' },
  { addr: 'A6.2', label: 'RD2' },
  { addr: 'A6.3', label: 'KBA2' },
  { addr: 'A6.4', label: 'KRST2' },
  { addr: 'A6.5', label: 'KBST2' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: 'SBK2' },
  { addr: 'A7.0', label: 'LK' },
  { addr: 'A7.1', label: 'LE' },
  { addr: 'A7.2', label: 'LB' },
  { addr: 'A7.3', label: 'RDY' },
  { addr: 'A7.4', label: 'RST' },
  { addr: 'A7.5', label: 'LC1' },
  { addr: 'A7.6', label: 'CC2' },
  { addr: 'A7.7', label: '' },
  { addr: 'A8.0', label: '' },
  { addr: 'A8.1', label: '' },
  { addr: 'A8.2', label: 'SC3' },
  { addr: 'A8.3', label: '' },
  { addr: 'A8.4', label: 'SC1' },
  { addr: 'A8.5', label: 'SC2' },
  { addr: 'A8.6', label: 'SPE' },
  { addr: 'A8.7', label: 'TD' },
  { addr: 'A9.0', label: '' },
  { addr: 'A9.1', label: 'T2' },
  { addr: 'A9.2', label: 'TRA' },
  { addr: 'A9.3', label: 'TRB' },
  { addr: 'A9.4', label: 'KCS' },
  { addr: 'A9.5', label: 'KCV' },
  { addr: 'A9.6', label: 'KCH' },
  { addr: 'A9.7', label: 'TCR' }
]

export const outputsSH = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'ADR' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' },
  { addr: 'A4.0', label: 'RA1' },
  { addr: 'A4.1', label: 'RB1' },
  { addr: 'A4.2', label: 'RD1' },
  { addr: 'A4.3', label: 'KBA1' },
  { addr: 'A4.4', label: 'KRST1' },
  { addr: 'A4.5', label: 'KBST1' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: 'LC' },
  { addr: 'A5.0', label: 'T10' },
  { addr: 'A5.1', label: 'T2' },
  { addr: 'A5.2', label: 'TRA' },
  { addr: 'A5.3', label: 'TRB' },
  { addr: 'A5.4', label: 'KCS' },
  { addr: 'A5.5', label: 'KCV' },
  { addr: 'A5.6', label: 'KCH' },
  { addr: 'A5.7', label: 'TCR' }
]

export const ALARMS = [
  { id: 1, key: 'al-sil-01', query: {} },
  { id: 2, key: 'al-sil-02', query: {} },
  { id: 3, key: 'al-sil-03', query: {} },
  { id: 4, key: 'al-sil-04', query: {} },
  { id: 5, key: 'al-sil-05', query: {} },
  { id: 6, key: 'al-sil-06', query: {} },
  { id: 7, key: 'al-sil-07', query: {} },
  { id: 8, key: 'al-sil-08', query: {} },
  { id: 9, key: 'al-sil-09', query: {} },
  { id: 10, key: 'al-sil-10', query: {} },
  { id: 11, key: 'al-sil-11', query: {} },
  { id: 12, key: 'al-sil-12', query: {} },
  { id: 13, key: 'al-sil-13', query: {} },
  { id: 14, key: 'al-sil-14', query: {} },
  { id: 15, key: 'al-sil-15', query: {} },
  { id: 16, key: 'al-sil-16', query: {} },
  { id: 17, key: 'al-v-to', query: {} },
  { id: 18, key: 'al-v-fdbk', query: {} },
  { id: 19, key: 'al-lv', query: {} },
  { id: 20, key: 'al-v-lck-to', query: {} },
  { id: 21, key: 'al-v-lck-fc', query: {} },
  { id: 22, key: 'al-r-to', query: {} },
  { id: 23, key: 'al-enr', query: {} },
  { id: 24, key: 'al-flap-to', query: {} },
  { id: 25, key: 'al-flap-fc', query: {} },
  { id: 26, key: 'al-flap-to', query: {} },
  { id: 27, key: 'al-flap-fc', query: {} },
  { id: 28, key: 'al-sp-to', query: {} },
  { id: 29, key: 'al-sp-to', query: {} },
  { id: 30, key: 'al-sp-fc', query: {} },
  { id: 31, key: 'al-spb-to', query: {} },
  { id: 32, key: 'al-spb-to', query: {} },
  { id: 33, key: 'al-spb-fc', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: 'al-pn', query: { name: 'CPU314' } },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: 'al-th', query: { name: 'APBE' } },
  { id: 50, key: 'al-th', query: { name: 'AD' } },
  { id: 51, key: 'al-th', query: { name: 'RTA' } },
  { id: 52, key: 'al-th', query: { name: 'ASBK' } },
  { id: 53, key: 'al-th', query: { name: 'AMM' } },
  { id: 54, key: 'al-th', query: { name: 'APE' } },
  { id: 55, key: 'al-th', query: { name: 'AMC' } },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: 'al-sil-01', query: {} },
  { id: 66, key: 'al-sil-02', query: {} },
  { id: 67, key: 'al-sil-03', query: {} },
  { id: 68, key: 'al-sil-04', query: {} },
  { id: 69, key: 'al-sil-05', query: {} },
  { id: 70, key: 'al-sil-06', query: {} },
  { id: 71, key: 'al-sil-07', query: {} },
  { id: 72, key: 'al-sil-08', query: {} },
  { id: 73, key: 'al-sil-09', query: {} },
  { id: 74, key: 'al-sil-10', query: {} },
  { id: 75, key: 'al-sil-11', query: {} },
  { id: 76, key: 'al-sil-12', query: {} },
  { id: 77, key: 'al-sil-13', query: {} },
  { id: 78, key: 'al-sil-14', query: {} },
  { id: 79, key: 'al-sil-15', query: {} },
  { id: 80, key: 'al-sil-16', query: {} },
  { id: 81, key: 'al-h-to', query: {} },
  { id: 82, key: 'al-lh', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: 'al-pn', query: { name: 'CPU314' } },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: 'al-th', query: { name: 'APBE' } },
  { id: 114, key: 'al-th', query: { name: 'AD' } },
  { id: 115, key: 'al-th', query: { name: 'MTC' } },
  { id: 116, key: 'al-th', query: { name: 'IV1' } },
  { id: 117, key: 'al-th', query: { name: 'IV2' } },
  { id: 118, key: 'al-th', query: { name: 'TJ1' } },
  { id: 119, key: 'al-th', query: { name: 'RTA' } },
  { id: 120, key: 'al-th', query: { name: 'ASBK' } },
  { id: 121, key: 'al-th', query: { name: 'AMM' } },
  { id: 122, key: 'al-th', query: { name: 'APE' } },
  { id: 123, key: 'al-th', query: { name: 'AMC' } },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

export const DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL1' },
  { id: 2, key: 'EL2' },
  { id: 3, key: 'EL3' },
  { id: 4, key: 'EL4' },
  { id: 5, key: 'EL5' },
  { id: 6, key: 'SH1' },
  { id: 7, key: 'SH2' },
  { id: 8, key: 'SH3' },
  { id: 9, key: 'SH4' },
  { id: 10, key: 'SH5' },
  { id: 11, key: 'SH6' },
  { id: 12, key: 'SH7' },
  { id: 13, key: 'SH8' },
  { id: 14, key: 'SH9' },
  { id: 15, key: 'SH10' },
  { id: 16, key: 'SH11' },
  { id: 17, key: 'SH12' },
  { id: 18, key: 'SH13' },
  { id: 19, key: 'SH14' }
]
export const MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-eme-3' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
export const OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' }
]
